### ISSUE TITLE
P9: Duplicate NewTools world menu items

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#10037]
**Bug description**
Pharo 9 clean image contains duplicate (twice) Playground and Spotter world menu items.

![2021-09-24](https://user-images.githubusercontent.com/9571633/134644601-ffee6f1b-897a-42aa-acc2-7e2efba824fe.png)

**Version information:**
 - OS: Windows (probably irrelevant)
 - Version: Pharo 9 build 1551+ (from PR #9974)
 - Originates from NewTools issue https://github.com/pharo-spec/NewTools/issues/296
 - Pharo 9 only (issue not present on Pharo 10)

**Comment by Ducasse** [comment]
Yes I saw that too during my lectures.
@estebanlm

**Comment by maxwills** [comment]
The reason it happens is because the class GTPlayground has been deprecated, however, its method `GTPlayground class>>menuCommandOn: ` has the pragma `<worldMenu>` and still adds the menu entry.

It looks like the new method (which should replace the deprecated one) is `StPlayground class>>menuCommandOn:`, and it is also adding a menu entry.

I'm not sure how to deal with deprecated methods and pragmas. My question is: is this a bug on `<worldMenu>` expected behavior (it should not add deprecated methods/classes)?

**Comment by MarcusDenker** [comment]
this is now mered
