### ISSUE TITLE
Zinc WebSockets tests fail because echo server is not available anymore

### ISSUE THREAD

**Issue by unique75m** [guillep/pharo-core#10691]
**Bug description**
The Zinc WebSoclket tests fail, because echo.websocket.org is offline

**To Reproduce**
1. I looked at smalltalkhub.org and searched for "WebSocket" and found this url "http://smalltalkhub.com/SvenVanCaekenberghe/ZincHTTPComponents/"
2. add the repository into the Monticello browser
3. load the "Zinc-WebSocket-Core" and "Zinc-WebSocket-Tests"
4. open DrTest and run the "Zinc-WebSocket-Tests"
5. you will get timeout errors

**Expected behavior**
My expectation is that everything is working :-)

**Version information:**
 - OS: [macOSX]
 - Version: [Monterey 12.0.1]
 - Pharo Version [10.0 64bit]

**Comment by svenvc** [comment]
That is a *REALLY* old version, please try: https://github.com/svenvc/zinc

<blockquote><img src="https://opengraph.githubassets.com/3544efb6685b9e34bde95600a0e49c8e1d45c48db4bc1b043a0ef06e6577b320/svenvc/zinc" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/svenvc/zinc">GitHub - svenvc/zinc: Zinc HTTP Components is an open-source Smalltalk framework to deal with the HTTP networking protocol.</a></strong></div><div>Zinc HTTP Components is an open-source Smalltalk framework to deal with the HTTP networking protocol. - GitHub - svenvc/zinc: Zinc HTTP Components is an open-source Smalltalk framework to deal with...</div></blockquote>

**Comment by svenvc** [comment]
```
Metacello new
  repository: 'github://svenvc/zinc/repository';
  baseline: 'ZincHTTPComponents';
  load: #( 'WebSocket' ).
```

**Comment by unique75m** [comment]
Thank you.

I am a Pharo newcomer and also new to github. But now i understand how to use such a url to create a repository in IceBerg, that i can browse with UI tools. I am coming from VisualWorks and Store and for me all the multiple repositories, multi-repository-dependents, ConfigurationOf things etc. are just a mess/hell, because loading is often not working or the dependent projects are outdated/offline or i found simply the wrong url with Google in the case of WebSockets.

Can i assume that current projects are now only hosted at github and this should be the root place for searching ? Because Monticello is legacy and i think IceBerg and github is the future right?

I hope that a first-class-package system is used in near future in Pharo, where i can configure the dependent packages in the browser., so that we can remove the ConfigurationOf things. It is a mess for a newcomer to load something and then to find the right script code to load the real things.

I used now the Iceberg UI to load the WebSockets, but i assume it is not loadable when the dependent things would not be in image already. But the tests are now working with this new version. Thanks.

**Comment by unique75m** [comment]
Ahh and thanks for your very very fast response :-)

**Comment by svenvc** [comment]
Actually, BaselineOfXXX takes care of dependencies.

Yes, Pharo moved to GitHub, mostly.

As an open source project, it is not practical to have one single arbiter of truth/quality.

And trust me, the VW world is just as alien and confusing for Pharo people as the other way around.

Good luck and keep asking questions (ML or Discord).

**Comment by Ducasse** [comment]
Welcome

I tell you that there is a life after VisualWorks. I was one VW person but got no future there.
And I was forced by the VW people to move out of VW. So I built Pharo.

I can tell you that the hell you mentioned I got the same in VisualWorks where I could not reload my project because of the hell
with versions of SUNIT and SUnitTwo and bad dependencies and dependencies conflicts. So I could not even run my test.
And the same can happen in many system. 
May be your system is not complex enough but I spent day facing with this in VW.

Of course git is the future and it was already like that since a couple of years.
And Iceberg is not just fileouting the code and invoking a command line. 
Iceberg is a lot of smarter than that because it deals with the fact that your objects also represent the program
so you have code on the disc, code in the git repo and inside the image and iceberg helps you to deal with this 
specific setup that all Smalltalk like system have to face.
I can tell you that git with Smalltalk without iceberg is another magnitude more challenging to grasp that mere git (because of the double working copy problem).

So we can tell you that github, gitlab and git are important and you can read a free book on git and Pharo
http://books.pharo.org <http://books.pharo.org/>

You can also donate to the authors because so far we wrote it for free and basically we do not need because we know how it works :).

-> Configuration are old ConfigMap in Envy dialect.
Now only old project not migrated to git are using them.

Now and since long time we use BaselineOf.
Read here https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Baselines.md <https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Baselines.md>
Again this is free.

You can have a look at the awesome documentation.

You can check https://github.com/pharo-open-documentation/awesome-pharo <https://github.com/pharo-open-documentation/awesome-pharo>


And BTW this is not that we do not want to improve the situation this is just that we do not have enough manpower.
If we would have got a 10 tenth of the money spent is system like visualworks then Pharo would be different.
Now given the ratio money / dev we have I think that we are really excellent. But this is of course a ratio. 

Pharo is not responsible for 
	- people not producing reloading baseline
	- people loading super old versions of a system.

Now in Pharo I always wanted to have a baseline validator and complete distribution validation but no money to build it. 

S

**Comment by Ducasse** [comment]
So I guess that we can close this issue?

**Comment by unique75m** [comment]
Hello Stephane, Hello Sven,

I have trouble in setting a remote Git repository. At first I had authentication problems, but I think they are now solved. I found out that I cannot use my standard Git login, instead I need an access token in Git (developer settings). With that I can now clone a my git repository from command shel via HTTPS. It asks for username/password, where the password is the access token.

When I delete the cloned repository again from disk and try the same in Iceberg it does not work, because I get the message "IceGitHubError: Not found“. I have simply created an empty private repository on the Git website without readme or anything else, maybe there is something missing, I do not know.

Currently it seems I can also setup a SSH key, I added it in the Pharo settings and on GitHub.com. But I reach then the same error as for HTTPS.

How does it work when I select „New Repository“ in Iceberg, it seems it creates a different file structure than a remote one. The „new“ repository has directly a directory „projectName" , but the remote one has „username / projectName“. Is it possible to create a „new“ one and link it later with a remote GitHub.com repository ?

Regards
Jörg

PS: Is this email address the right place for asking general questions? I do not want to add me on a mailing list and I think creating an issue for a general question is also bad

**Comment by Ducasse** [comment]
Github does not allow since more than a year access with your credential in HTTPS. You should use a token. 
This has nothing to do with Pharo.

**Comment by Ducasse** [comment]
No this page is not a way to ask questions.
We nicely replied but the mailing-list is the place.
You have to configure iceberg with your token check the preference
 or you should use ssh and an ssh-agent.
Did you read the Iceberg booklet?

**Comment by Ducasse** [comment]
You should join the discord channel see Pharo.or/community web page
I will not reply to this issue anymore
