### ISSUE TITLE
Breakpoints cannot be installed on variables and pseudovariables

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#10828]
**Bug description**
Breakpoints cannot be installed on variables and pseudovariables. If you place cursor on a temporary, instance variable or pseudovariable in a method and then double click on the left bar for breakpoints installation, nothing happens.

**To Reproduce**
1. create a message like 
```smalltalk
msg 

	| tmp |

	tmp := self yourself.
```
2. move cursor on top of `tmp` or `self`
3. try to install the breakpoint by double clicking on the left bar

**Version information:**
Pharo 10.0.0
Build information: Pharo-10.0.0+build.411.sha.bef28b93639451e950372e8f659d4ce2e6dd3faf (64 Bit)

**Comment by carolahp** [comment]
To fix the case of pseudovariables we must first decide what does it mean to place a breakpoint in ```self```.
Currently, it fails because it tries to insert a VariableBreakpoint on all accesses to self, and it considers the whole system as the environment. 

Should we allow inserting only normal breakpoints in pseudovariables?
If we allow VariableBreakpoints, should we break only when self is accessed in that method? in that line? in all methods of that class?

I mention @StevenCostiou and @MarcusDenker to be aware of this discussion 

(I will continue to check now the problem for temporary variables)

**Comment by dionisiydk** [comment]
I think it is same issue as #10841 : 
- the double click for breakpoint on self or any other variable is to halt on this particular node, not for any read/writes in the image.

Similarly the breakpoint on literals should work.

The restrictions came from #10812 (ClyDebuggingCommand>>canBeExecutedInContext:)

**Comment by MarcusDenker** [comment]
merged #10841
