### ISSUE TITLE
Iceberg loses changes in commits after package renamed

### ISSUE THREAD

**Issue by bouraqadi** [guillep/pharo-core#10928]
**Bug description**
Suppose 
- we have an Iceberg repo where a class C belongs to package P1. 
- userA moves class C from package P1 to package P2, and delets package P1 from the repo.
- that a userB works in parallel and modifies class C in repository P1 is modified by say adding a method.
- Both users make PRs.
- We integrate first PR from user A so package P1 no longer exists in the repo. But class C is still there.

After integrating PR from userB 
- iceberg shows conflicts, but only the incoming version of C is displayed in the diff
- upon merging we lose changes done by userB. Class C is deleted from the image, and the merge commit is empty.

**Comment by tesonep** [comment]
We were able to reproduce it with two images and a common local repository.
Each image (user) works in a different branch, and we have a master branch.
We integrated the changes from userA into master, and then the same with userB.
When the userA iceberg-merge master into her branch, everything works.
But when userB iceberg-merge master into her branch... we lose the class C and the package P1.

We have seen that the issue is that Iceberg does not load new packages that are in the repository but not in the image.
So, it applies the changes in P1 (removing the package and the class) but never loads C as it is in P2 and P2 is not in the image.
