### ISSUE TITLE
Iceberg should use git and stop trying to use libgit to be git.

### ISSUE THREAD

**Issue by johnhwoods** [guillep/pharo-core#11012]
Iceberg tries to do too much work that git should do.
examples
1) git authentication.
there should not be any git authentication methods in iceberg.  it should just call git.
Have spent hours on systems where git works fine and iceberg doesn't, either because it can't contact the ssh-agent, or because it doesn't recognise the .ssh keys etc.  Furthermore, Iceberg stores all those credentials in plain text and, due to issue #11010 these often end up in parts of the user space where the user may not realise they have been stored.

2) git status of directories
One of the problems Iceberg tries to solve is whether or not to share repos between images.  The git workflow that would allow one to maintain separate checkouts for each image without having several copies of a repo is the use of worktrees.  But iceberg doesn't work with worktrees, as it doesn't recognise a directory where .git is a file rather than a directory.  So 'git status' will work in a directory that Iceberg will insist 'doesn't look like a git directory'

**Comment by guillep** [comment]
Hi @johnhwoods .

Yes, using libgit has drawbacks, but using git directly too. It would require to interface via command line, parse command outputs... Iceberg already supports to plug different backends, so a different one could be implemented, but it would be costly.

Using worktrees is something that could be done. It's not a libgit limitation but an iceberg limitation that does not support it. https://libgit2.org/libgit2/#HEAD/search/worktree

Iceberg (not libgit) also solves other problems like making semantic merges of pharo code (instead of pure lines of text).

Libgit is also cross platform and works more easily on windows without having a shell installation, and has a very active community.

I don't think this belongs to an issue, it could be a discussion on the mailing list or the discord server.
