### ISSUE TITLE
Memory leak caused by resizing Pharo window

### ISSUE THREAD

**Issue by uternet** [guillep/pharo-core#11183]
**Bug description**
When I changed Pharo's window size, I noticed that the memory Pharo used went up quickly and never released. If I keep resize its window, the system quickly runs out of memory and crashes.

The same BUG exists in Pharolauncher.

**Version information:**
 - OS: linux mint
 - Version:  20.3
 - Pharo Version 10.0.0

**Comment by uternet** [comment]
The same problem exists with The Mac and Windows versions of Pharo, but it is not as severe as the Linux version. Because in both operating systems, changing the size of the window with the mouse does not redraw the window until the mouse key is released. It seems that Pharo takes up constant memory every time the window is redrawn and never frees it. On Linux, the window is constantly redrawn until the mouse is released.

**Comment by Psy-Kosh** [comment]
I'm on Windows 10. Tried this out on Pharo-10.0.0+build.515.sha.b18847fed2389428342d35b0056824644a1ce5fe (64 Bit) a few times and it seems that it does eventually does release most of the memory.

Just takes it quite a while.

**Comment by uternet** [comment]
I can confirm again that this is a real BUG, I tried to change Pharo's window twice on Linux with the mouse, it increased the amount of memory used from 124MB to over 800MB, I waited for at least 30 minutes and the number didn't change at all.


This BUG needs to be fixed, otherwise it will affect Pharo app distribution and placement (at least for desktop apps).

**Comment by Psy-Kosh** [comment]
I just tested it again, and definitely something odd going on. (again, on windows 10, with pharo 10 build 515)

I wibbled and wobbled the window for a while until usage had gone up to about 530MB. I then left it alone for a bit, an hour later it was down to two hundred and something MB. about an hour after that, it was down to the 160s. So, at least on my system looks like it eventually releases after a couple hours. But that is kind of a weird time scale for it. I figured I should just mention these results in case it helps track down what's really going on.

**Comment by fmqa** [comment]
This bug seems to be caused by SDL2 textures not being released immediately by the `OSSDL2FormRenderer`.

As `SDL_Texture` is marked  `autoRelease` object, the GC does not collect it immediately. This explains why other users e.g. @Psy-Kosh see a reduction in memory usage after a while. At some point, the GC collects the object ... eventually.

So in general, this does seem to be caused by a mix of 1) The VM's GC being conservative and 2) Textures consuming a lot of memory (making this issue noticeable).

At any rate, I would propose releasing the texture manually as a preliminary fix. With larger displays becoming increasingly common these days, the memory usage for uncompressed graphical objects e.g. Textures is rather high. Burning through texture RAM until a collection happens is obviously not a very appealing approach, especially on memory-constrained systems.

**Comment by fmqa** [comment]
Although #11610 is a valid fix, I would be interested in documentation related to the VM's GC to understand when/how a collection cycle happens. This could be a relevant for other types of "heavy" objects where deterministic release of OS resources is also necessary

**Comment by Ducasse** [comment]
Objects that are passed around to FFI calls are usually pinned (not moving).
Now I will let @tesonep or @guillep to reply about the GC interaction with this bug.
In Pharo you have two GC: one incremental that is invoked when objects are created and when the young space is full and an object get to survive multiple young space garbage go to the old space. Second a stop the world full mark and sweep GC.
The GC can kick at preemption point (i.e., message sends and back jump (not sure about this one)).

**Comment by tesonep** [comment]
The peak of memory is produced because the original surface will be released later when GC, but the GC might occur later. I think is a good idea to manually release it.
