### ISSUE TITLE
bytecode and symbolicBytecodes: would be good to be consistent

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11263]
```
(Rectangle >> #width) bytecode
>>> #[1 126 0 126 97 92]
```

```
(Rectangle >> #width) symbolicBytecodes  
	25 <01> pushRcvr: 1 
	26 <7E> send: x 
	27 <00> pushRcvr: 0 
	28 <7E> send: x 
	29 <61> send: - 
	30 <5C> returnTop
```
It would be nice to have bytecodes and symbolicBytecodes. 

In addition it would be nice to have a more verbose verbose 

```
(Rectangle >> #width) symbolicBytecodes  
	25 <01> pushRcvr: 1  (corner)
	26 <7E> send: x 
	27 <00> pushRcvr: 0 (origin)
	28 <7E> send: x 
	29 <61> send: - 
	30 <5C> returnTop
```

**Comment by hogoww** [comment]
About consistency, is it only the missing 's' at bytecode (=> PR is here #11488)?
Or is it also about decimal vs hexa representation?
If so, would you want to show both in hexa, or both in decimal?

Looking at the printing of IV now.

**Comment by MarcusDenker** [comment]
main topic has been done. For printing the temp names: the problem is that mapping offsets to names for temps requires the compiler and AST and all the infrastructure (temps stored in temp vectors vs not, copies temps getting different offsets in different closures...)

This would complexify the whole implementation a lot and would mean that the package that SymbolicBytecode is in now requires the compiler (or even more to make it pluggable).

Consider that every use in practive is done via the inspector:

![bytecode](https://user-images.githubusercontent.com/413057/206734657-1b93f4ff-c883-4b3b-b9c9-daf4f7c6f753.jpg)

Where when you select the temp read bytecode, it will hightlight exactly the variable in the source.
