### ISSUE TITLE
Willow does not load into Pharo 10 64-bit (stable)

### ISSUE THREAD

**Issue by Shaping** [guillep/pharo-core#11300]
Pharo version:  10 64-bit (stable)
OS:  Windows 10 Pro

Metacello new
  baseline: 'WillowPlayground';
  repository: 'github://ba-st/Willow-Playground:v9/source';
  load

The above does not load Willow into Pharo 10.  Should it?

The error is:  'revspec 'v9' not found'.    When I see the revspec constraint, should I conclude that this is the Pharo version needed for willow?  What about Pharo 8 or 7, etc?

I does work in Pharo 9.

Earlier I reported that a related package, Willow-Semantic-UI, did not load into either Pharo 9 or 10.   My assumption, probably wrong, is that transitive dependencies are automatically loaded.   Namely, if Will-Semantic-UI needs WillowPlaygrond, then the latter will be automatically loaded before the former.

**Comment by gcotelli** [comment]
`v9` is not existent as a branch in `Willow-Playground`, so it fails because you're trying to load something that doesn't exist. You can load a specific released version or `release-candidate` branch. Anyways, I don't think this issue belongs here but in the Willow-Playground repo.

I don't have permission to close the issue here, but It should be closed here and in any case, opened in the corresponding repo.

**Comment by Shaping** [comment]
I'll move the discussion to the Willow-Playground repo.
I'm confused by the basic nature of the problem.  I was only following the instructions on the Willow GitHub page.  How can I know which version number in the repository string will work?   The above Metacello evaluable is unchanged from the original.

I think I've wrongly assumed some backward compatibility, namely, if v9 loads into Pharo 9, then v9 will load into Pharo 10.   I would not assume the opposite to be true.

Willow looks very interesting.  I'm just trying to do some basic tests.

**Comment by MarcusDenker** [comment]
I close the issue here
