### ISSUE TITLE
FLSerializer misses some convenience methods

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#11367]
**Bug description**
Older versions of fuel had some convenience methods on FLSerializer and FLMaterializer: 
- `FLSerializer>>serialize:on:`
- `FLSerializer>>serialize:toFileNamed:`
- `FLSerializer>>serializeToByteArray:`
- `FLMaterializer>>materializeFromByteArray:`
- `FLMaterializer>>materializeFromFileNamed:`
- `FLMaterializer>>materializeHeaderFromFileNamed:`

I have to say they were extremely useful and I think is a bug to just remove them like that. 
At least, provide a deprecation and a point to what to look to make the migration.

Also, it is making some tests to fail (`RSMonitorEventsTest>>testWriteToFile`)

**To Reproduce**
1. Try to execute `RSMonitorEventsTest>>testWriteToFile`test

**Expected behavior**
I want to have those methods back, or a way to migrate.

**Comment by theseion** [comment]
I will create a new release with those methods. One thing I'm not sure about is whether to add extensions to`Object`. I already have `Object>>serializeToFileNamed:` and I could add the other two as well. What do you think? It's handy but it also pollutes `Object`...

The test failure should already have been fixed by https://github.com/pharo-project/pharo/issues/11327.

**Comment by theseion** [comment]
@estebanlm https://github.com/pharo-project/pharo/pull/11384
