### ISSUE TITLE
Fix that unticking the Case Sensitive checkbox does not provide case insensitive completions?

### ISSUE THREAD

**Issue by Dima-369** [guillep/pharo-core#11445]
I have this unticked for case insensitive completions:

![image](https://user-images.githubusercontent.com/15002298/177929322-7520e37b-cb15-4a9d-8713-803b908fb352.png)

But in the Playground, the completion popup is still case sensitive?

![image](https://user-images.githubusercontent.com/15002298/177929468-790e8df4-4785-445d-93fd-a9a1b3463527.png)

Here I would expect that `maxFloat` would also be suggested, but it is not? Am I misunderstanding how this setting behaves? I have never seen it change anything so far.

![image](https://user-images.githubusercontent.com/15002298/177929579-032d64db-3077-4bef-8ce9-c8a772b2d5b0.png)

**Version information:**
 - OS: macOS 
 - Version: 10.14.6
 - Pharo Version 11.0

**Expected development cost**
I am a Pharo novice by any means. I tried to fix this myself by patching in `asLowercase` methods in the `RB...Node` classes, but that does not do anything and is highly likely the incorrect place to change this.

```smalltalk
select: [ :each | each beginsWith: ((self completionToken: offset) asLowercase) ]
```

Maybe someone can point me in the right direction where to approach this? 

I found this pull request: https://github.com/pharo-project/pharo/pull/8895 but my code in Pharo 11.0 looks a bit different to that, so I do not know how to approach this.

**Comment by fmqa** [comment]
This is somewhat annoying, but seems to be mainly caused by various parts of the completion engine ignoring the preference. Modifying `CoCompletionContext >> narrowWith` so that 

`self completion replaceFilterWith: (CoCaseSensitiveBeginsWithFilter filterString: aString)` 

becomes 

`self completion replaceFilterWith: (CoBeginsWithFilter caseSensitive: NECPreferences caseSensitive filterString: aString)` 

improves things somewhat.

**Comment by Ducasse** [comment]
May be we should clean the NecPreferences because I thought that all the NEC infrastructure was gone.

**Comment by Ducasse** [comment]
Ok I see that the heuristics model extends the Nec packages. 
Now the preferences do not seem to be used to configuration the heuristics.

**Comment by Ducasse** [comment]
I started to read 

HeuristicCompletion is a code completion engine using generators and heuristics. Instead of query the entire system and generate lots of potentially intermediate collections that we need to concatenate, copy, grow, iterate all those sub-collections in order. Generators provide a stream-like access to those collections (and sequences of collections) without scanning the full system eagerly.

# Architecture
This completion engine is done out of three main components:

- lazy fetchers implemented using generators (cf. `CoFetcher`),
- a completion object that works as a result-set (cf. `CoResultSet`),
- and several completion heuristics that are decided depending on the code being completed by looking at the AST (cf. `CoASTNodeFetcherHeuristic`).

# Plugging different heuristics

This completion engine is meant to be pluggable. New heuristics can be introduced, or the ones in the system can be completely replaced. If you want to implement your own completion you need to subclass CoASTResultSetBuilder or CoResultSetBuilder. CoASTResultSetBuilder provides already common behavior when basic the code completion algorithm on the AST. Then the completion engine can be configured with the required result set builder.

```
CoCompletionEngine new
    complishonBuilder: MyResultSetBuilder new;
    yourself
```

## Subclassing CoResultSetBuilder
The system will provide your builder with a completion context, and will then call `buildComplishon`. You need to redefine `buildComplishon` and return a `CoResultSet`.

## Subclassing CoASTResultSetBuilder
The system will provide your builder with a completion context, and will then call a default version of `buildComplishon`. By default it will parse the source code to get an AST, get the AST node corresponding to the caret position, and make a double dispatch on the node. As a result, the `ASTResultSetBuilder` will be sent a corresponding `visit*` with the corresponding node. You need to redefine `visit*` and return a `CoResultSet` configured depending on the AST node.

## Subclassing CoASTHeuristicsResultSetBuilder
`CoASTHeuristicsResultSetBuilder` is an `CoASTResultSetBuilder` based on heuristics. It has three sets of heuristics: one for messages, one for variables, and one for methods. You can redefine `messageHeuristic`, `methodHeuristic` or `variablesHeuristic` to change one of them.

**Comment by Ducasse** [comment]
And I will check with guille if we have a moment (and if he joins the coding camp).

**Comment by fmqa** [comment]
@Ducasse Thanks, Dr. - I collected my changes into a PR just in case anyone is interested. Not sure if this is idiomatic Pharo code but the changeset solves the problem for me least.

![case-insensitive completion](https://user-images.githubusercontent.com/7354509/185792406-3a10b647-3054-4596-9ace-4f97e056accf.png)
