### ISSUE TITLE
Undo shortcut (ctrl+z) does not mark method as dirty in System browser

### ISSUE THREAD

**Issue by LABSARI** [guillep/pharo-core#11649]
**Bug description**
Restoring method using ctrl+z to last compiled state does not mark the method as dirty, the code browser thinks the method definition has no change.

**To Reproduce**
1. Go to a method definition using the System browser.
2. Add something to the method.
3. Compile the method with ctrl+s.
4. Undo changes (using ctrl+z) on the method until its initial state (step 1).
5. The method can't be recompiled with ctrl+s.

**Expected behavior**
After undo to previous state of the method, it should be possible to recompile it with ctrl+s.

**Version information:**
 - OS: Mac, Linux
 - Pharo Version: 9 and 10

**Comment by fmqa** [comment]
This happens due to this code in `ClyTextEditor>>#undo`:

```st
self editingState undoManager hasPrevious ifFalse: [ 
		self browserTool changesCancelled]
```

I am not sure what the idea behind it is. In my understanding, this logic here goes like "if the undo stack is empty, then remove the change flag from the editor" but this does not make much sense, maybe I miss some non-obvious edge case.

A simple fix would be to remove this code, or just to remove `ClyTextEditor>>#undo` entirely and have the superclass method apply here. I have experienced no negative side-effects from this. But I would prefer to wait for an opinion from the core team before submitting a PR to do this change.
