### ISSUE TITLE
Browser method filter is broken

### ISSUE THREAD

**Issue by demarey** [guillep/pharo-core#11724]
**Bug description**
In the system browser, when a class defines a lot of methods, you can go quickly to a method by starting to type the method name first letters as shown below.
<img width="858" alt="Capture d’écran 2022-09-27 à 16 06 10" src="https://user-images.githubusercontent.com/2494203/192549602-b5897c29-328a-4952-a3c0-a0d4d8a7e12e.png">

**To Reproduce**
1. Open the system browser
2. Select `AI-Algorithms-Graph` package
3. Select `AIBFS` class
4. Select the first method
5. Type `s`=> `start` method is selected
6.  Play a bit with method selection and filtering. After a while, the filter is not available anymore

**Comment by estebanlm** [comment]
update:
working (trying) on it. 
what was there was never a filter but a search. 
I cannot understand why it works in certain scenarios et pas d'autres.

**Comment by estebanlm** [comment]
yeah, holded it as it was harder than expected ;)

**Comment by fmqa** [comment]
@estebanlm Hope you don't mind me trying to fix this. I think this is an annoying regression and it prevents the user from actually finding stuff.

From what I've found, `FTTableMorph>>keyDown:` delegates to `FTTableMorph>>keyDownSearch:`, which itself delegates to `function keyDown: event` where `function` is an instance of `FTSearchFunction`

However, `FTSearchFunction` is missing a specialized implementation of `keyDown:`, which means the default "do nothing" implementation from `FTFunction` is used.

My solution is: Just add `FTSearchFunction>>keyDown:` and have it delegate to `FTSearchFunction>>keyStroke:` 

But why I don't understand it: This problem should affect Pharo 10 too, since `FTSearchFunction>>keyDown:` is also missing on the Pharo10 branch

**Comment by Ducasse** [comment]
Tx fmqa!
