### ISSUE TITLE
SequenceableCollection >> truncateToSize:

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#11946]
Add tests and verify if SequenceableCollection >> truncateTo: is working for all the sequenceable subclasses.

```
SequenceableCollection >> truncateToSize: smallSize
	"return myself or a copy shortened to smallSize."

	^ self size <= smallSize
		ifTrue: [ self ]
		ifFalse: [ self copyFrom: 1 to: smallSize ]
```

**Comment by olekscode** [comment]
With @DanielCamSan , we called it `truncatedToSize:` instead of `truncateToSize:` because it returns a new collection instead of changing the existing one.

We also created a `TSequenceableTruncatedToSize` trait with tests and used it in the following classes:
- `ArrayTest`
- `OrderedCollectionTest`
- `LinkedListTest`
- `IntervalTest`
- `StringTest`
- `ByteArrayTest`
- `RunArrayTest`

**Comment by Ducasse** [comment]
Good idea. After for the trait we would like to have collection core without traits, the trait is ok for tests.
