### ISSUE TITLE
[Debugger] stepping of block with immediate returns

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#12039]
**Bug description**
Stepping through a block with an immediate return causes `CompiledMethod>>valueWithReceiver:arguments:` error

**To Reproduce**
1. create a class 
```smalltalk
Object subclass: #AAA
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'AAA' 
```
2. create a method 
```smalltalk
msg

    #(1 2) detect: [ :v | false ] ifNone: [ ^ true ].
    ^ false
 ```
3. Debug this expression 
```smalltalk
AAA new msg
```
4. step into msg
6. step through until you reach the return expression `^ true`
7. the next step through causes `CompiledMethod>>valueWithReceiver:arguments:` error

**Version information:**
Pharo 11.0.0
Build information: Pharo-11.0.0+build.353.sha.31e5d29d9e098633df8a6bdecd4203d4fdb7fd24 (64 Bit)

**Comment by MarcusDenker** [comment]
I will check, I think I know what causes it

**Comment by pavel-krivanek** [comment]
In my image, I'm also getting sometimes during stepping test cases this Morphic error:

![image](https://user-images.githubusercontent.com/572494/205266198-3b92d64c-0b38-4e6e-bda8-b010b564e416.png)

It has probably the very same root cause. But it is quite interesting that some UI code of the debugger runs in the simulated mode. I'm trying to find a way how to reproduce it in the vanilla image.

**Comment by MarcusDenker** [comment]
The cause is this PR: https://github.com/pharo-project/pharo/pull/11907/files

I will guard that change by a compiler option that is turned off. Then we can re-visit that after we have simplifies hoe the Context stepper implements quick returns: These days it actually generates bytecode to call the quick method prim for every quick method, we could just simulate executing that and remove the overly complex code in the Context (which can not work for blocks as it tags the compiledcode using properties, which do not exist for CompiledBlock)

<blockquote><img src="https://avatars.githubusercontent.com/u/413057?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/11907">CompiledBlocks: compile quick returns by MarcusDenker · Pull Request #11907 · pharo-project/pharo</a></strong></div><div>This PR makes sure to compile Quick returns if a block has just a non-local return, just as we do for methods.</div></blockquote>
