### ISSUE TITLE
CoverageCollector: ignore some methods

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12112]
CoverageCollector should not bother about some methods:

subclassResponsibility

```	
methods := methods reject: [ :method | 
		           method isAbstract ].
```

we should have a way to tag methods to ingnore them

```
methods := methods reject: [ :method | 
		           method hasPragmaNamed: #ignoreForCoverage ].

```

More:

- isAbstract of class side
- isDeprecated

**Comment by privat** [comment]
Ignoring these methods does not really change the coverage mechanism (uncalled methods will be uncalled) and the overhead of metalink for so few cases should be minimal, but it impacts the percentage of covered things, so it could be useful by default (with ways to opt-out).

In fact, as filtered out methods have not real impact, another approach could be to filter them after the coverage run when you process the results (counting percentage or listing "missing" methods for instance), so you can collect raw data with unfiltered results then do what you want with them.

I'm, not sure about the pragma flag, as it gives the watchees the responsibility to known (or suppose) the motivation of the watchers. But it could make sense in a project with an integrated CI/CD and coverage-aware test-suites.

Another thought, since Coverage work on a granularity finer than methods, could it also make sense to ignore some parts of some methods? Maybe not since I cannot find convincing example (but I might lack imagination).
Maybe error default branch in a switch/case, or error statement after an infinite loop?

**Comment by MarcusDenker** [comment]
ah, yes, the is the *client* of CoverageCollector that needs to do the filtering...  I should implement one for TestCoverage

For sub-method: no, I guess it makes not really sense to filter there.

**Comment by MarcusDenker** [comment]
(I close this as it will be part of a test coverage utility)
