### ISSUE TITLE
FastTable inserts two characters when opening the filter

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#12434]
**Bug description**

When pressing a key in a fast table, with filter enabled (e.g., in calypso method lists), the first character is inserted twice in the filter pop up.

**To Reproduce**
1. Go to Calypso, navigate to a class with methods, click on the method list
2. Type a character
3. You will see two times the character in the filter

**Expected behavior**
The character should appear only once.

**Screenshots**
<img width="887" alt="imagen" src="https://user-images.githubusercontent.com/708322/215041945-fd9b05d0-27b9-41ee-a3f7-000189a16f43.png">

**Version information:**

Pharo 11.0.0
Build information: Pharo-11.0.0+build.474.sha.cd8926c428df0badb660702c102c1a320862f5fb (64 Bit)

**Additional context**
I think this is quite recent. The pharo launcher could help in looking for the version where this got introduced, that could lead to the PR and related changes.

**Comment by ValentinBourcier** [comment]
**Updated steps to reproduce the issue:**

1. Go to Calypso, navigate to a class with methods, click on the method list
4. Execute Cmd + F to open the method finder
5. Type anything in it
6. Close the finder
7. Type a character while focusing on the method list.

You will see two times the character in the filter.
Without the extra 4 - 6 steps I was not able to reproduce the issue.

**Comment by hernanmd** [comment]
One issue I have seen is that now the first typed character in the FTTableMorph doesn't receive anymore a SDL_TextInputEvent, but on a **second** typed character. Some related changes were introduced by this commit to add IME support to Pharo: https://github.com/pharo-project/pharo/commit/b3c3f44fb0025c50e2484816798f1193db5ddd32 which added a #visitTextEditingEvent: and corresponding OSWindow event class named TextEditionEvent (this was handled in Pharo 10 by just creating keyStroke events).

So now Morphic includes two additional event handlers: 1) for text input and 2) for text edition. With every keyboard focus change, the IME system in SDL2 requires to start a request for text edition (SDL_StartTextInput). Similarily, when keyboard focus is lost, a request for stop text edition is sent to the SDL2 engine. However, some behaviors are unclear: When an active window is closed, for example, the keyboard focus is lost but #requestStopTextEditing is not sent, but a request for **start** editing text (this is implemented in #requestTextEditingAt:). 

So the problem is that when a first character is typed in the FTTableMorph, the keyboard focus logic request to SDL2 a start editing text, no SDL event is received in Pharo.

From SDL side: I couldn't manage to receive SDL_TextEditingEvent (probably it has something to do with not activating/installing IME input method in my system?). On the second character the "edition mode" is already started and we receive the SDL_TextInputEvent like before. Hitting Esc key and again any key, spit the buffered character and the new one.

From Morphic side: The morph now receive 2 events: One from they KeyDown and another one from the KeyStroke.

I don't know yet what's the solution but a workflow for using IME is described in https://wiki.libsdl.org/SDL2/Tutorials-TextInput

<blockquote><img src="https://wiki.libsdl.org/static_files/logo.png" width="48" align="right"><div><strong><a href="https://wiki.libsdl.org">SDL2/Tutorials-TextInput</a></strong></div><div>The Simple Directmedia Layer Wiki</div></blockquote>
