### ISSUE TITLE
OmFileStoreReadingError Illegal leading byte after DeprecationPerformedNotification

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#12575]
**Bug description**

we see this now often on the CI:

DeprecationPerformedNotification: Automatic deprecation code rewrite: The method Float class>>#epsilon called from RSTransformable>>#updateCurrentShape: has been deprecated. Use machineEpsilon instead

OmFileStoreReadingError: Reading entry from File @ /Users/lse/Workspace/workspace/est_and_branch_Pipeline_PR-12541/Tests-osx-64/pharo-local/ombu-sessions/Pharo11.0-PR-64bit-3f8475b.218301751A20.ombu@11403266: Illegal leading byte for utf-8 encoding

**Comment by svenvc** [comment]
It could be that this is something that we have seen before, maybe it was not fully fixed.

I think this is related to a position in a binary stream that is being moved (probably backward) without regards for utf8 character boundaries, like going back 100 bytes. Next a higher level character decoding stream is used to read. Most of the time this works (ASCII), but sometimes you are unlucky and end up in the middle of a character. That is a likely cause for the above error.

Here is an example:
```
| bytes |
bytes := 'Francais' utf8Encoded.
(ZnCharacterReadStream on: (bytes readStream setToEnd; skip: -4)) next.
```
This gives you $c as you would expect going 4 positions backwards.
However:
```
| bytes |
bytes := 'Français' utf8Encoded.
(ZnCharacterReadStream on: (bytes readStream setToEnd; skip: -4)) next.
```
gives you the error as $ç is encoded using 2 bytes and the stream is positioned between them.

The method ZnUTF8Encoder>>#backOnStream: can do this correctly, but it is not further integrated into streams. It does not have to be used on each step, doing it only as the last step seems OK:
```
| bytes |
bytes := 'Français' utf8Encoded readStream.
bytes readStream setToEnd; skip: -4.
ZnCharacterEncoder utf8 backOnStream: bytes.
(ZnCharacterReadStream on: bytes) next.
```
Which gives $ç

**Comment by jecisc** [comment]
I checked the code of Ombu and it does not seems to skip back. But it does set the position in the stream explicitly in some places. 

(The problem seems to be in one of the senders of #readEntriesWith:)

**Comment by svenvc** [comment]
OK, as far as I can see, there are 3 senders that manipulate the position:

- OmFileStore>>#nextEntryFromPosition:
- OmFileStore>>#refreshEntryPositionsByLocalNameStartingAt:since:
- OmBlockFileStore>>#entryPositionsStartingAt:upTo:

Now, the read stream seems to be a ZnCharacterReadStream(ZnEncodedReadStream,ZnEncodedStream) where position is understood as byte position in the wrapped binary stream.

The encoder used is normally UTF8, but it could be any ZnCharacterEncoder. Some encodings are fixed size (byte encoders, UTF32) others are variable length (UTF8 but also UTF16).

The most correct solution would probably be for ZnEncodedStream>>#position: to act such that it refuses to place itself inside a character and moves to the beginning of an encoded character, if necessary.

For UTF8 this is doable (using the 2 high bits), as for the fixed encodings (using multiples), but I do not know if this is possible for UTF16. I will have to check that first.

Then adding a #ensureBeginOfCharacterOnStream: to the encoder hierarchy and invoking that from #position: could be a solution. And it will need some unit tests as well.

**Comment by svenvc** [comment]
Here is a first attempt: https://github.com/svenvc/zinc/commit/952f5f4a689206736d38cbe9a00a6661628859a0

It could use another pair of eyes.

There are no tests for non-utf8 encoders, but the code is there.

**Comment by svenvc** [comment]
I added a better test: https://github.com/svenvc/zinc/commit/8f1a2554de51fc8c7f9f848b392526d9f066f2bd

**Comment by astares** [comment]
As code is not sent via a PR (commits were done directly in Zinc repo) there can not be a formal GH approval of a PR as with other regular contributions. But I tried to review as good as possible and the commits as well as the additional tests look good now.

**Comment by jecisc** [comment]
I created a PR to try and integrate those changes in Pharo: https://github.com/pharo-project/pharo/pull/12824
