### ISSUE TITLE
Executable comment syntax error leads to CI crash

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12807]
I created a PR that added executable comments. But I did a syntax error in one of those and the CI build ended up crashing with really poor feedback. 

I have the impression that this is caused because there is a problem when launching the RuntimeSyntaxError. 

To see the problem, you can debug PharoDocCommentTest>>#testExpressionSyntaxError and inspect `node expression evaluate` to see the error it raises. 

The error have a bug when trying to print itself: `#errorMessage was sent to nil`

```
UndefinedObject(Object)>>doesNotUnderstand: #errorMessage
UndefinedObject>>doesNotUnderstand: #errorMessage
RuntimeSyntaxError>>errorMessage
RuntimeSyntaxError>>messageText
[ :stream | | mt |
		stream << self class name.
		(mt := self messageText) isEmptyOrNil
			ifFalse: [ stream << ': ' << mt ] ] in RuntimeSyntaxError(Exception)>>defaultDescription in Block: [ :stream | | mt |...
String class(SequenceableCollection class)>>new:streamContents:
String class(SequenceableCollection class)>>streamContents:
RuntimeSyntaxError(Exception)>>defaultDescription
RuntimeSyntaxError(Exception)>>description
RuntimeSyntaxError(Exception)>>printOn:
[:s | self printOn: s] in RuntimeSyntaxError(Object)>>printStringLimitedTo: in Block: [:s | self printOn: s]
String class(SequenceableCollection class)>>streamContents:limitedTo:
RuntimeSyntaxError(Object)>>printStringLimitedTo:using:
RuntimeSyntaxError(Object)>>printStringLimitedTo:
RuntimeSyntaxError(Object)>>printString
MorphicUIManager(UIManager)>>requestDebuggerOpeningFor:
RuntimeSyntaxError(Exception)>>debug
MorphicUIManager>>unhandledErrorDefaultAction:
RuntimeSyntaxError(Exception)>>unhandledErrorAction
UnhandledError>>defaultAction
UndefinedObject>>handleSignal:
Context>>handleSignal:
Context>>handleSignal:
UnhandledError(Exception)>>signal
UnhandledError class>>signalForException:
RuntimeSyntaxError(Exception)>>raiseUnhandledError
RuntimeSyntaxError(Exception)>>defaultAction
UndefinedObject>>handleSignal:
RuntimeSyntaxError(Exception)>>pass
[ :ex |
			ActiveWorld := priorWorld.
			ex pass ] in WorldMorph>>becomeActiveDuring: in Block: [ :ex |...
FullBlockClosure(BlockClosure)>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
RuntimeSyntaxError(Exception)>>pass
[ :e | e pass ] in SpCodeInspectItCommand(SpCodeSelectionCommand)>>evaluate:andDo: in Block: [ :e | e pass ]
[ :e |
		self announcer announce: (SpCodeEvaluationFailedAnnouncement 
			newContent: aString
			error: e).
		errorBlock value: e ] in SpCodePresenter>>evaluate:onCompileError:onError: in Block: [ :e |...
FullBlockClosure(BlockClosure)>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
RuntimeSyntaxError(Exception)>>signal
RuntimeSyntaxError class(Exception class)>>signal
PharoDocCommentExpression>>evaluate
PharoDocCommentTest>>DoIt
OCContextualDoItSemanticScope(OCDoItSemanticScope)>>evaluateDoIt:
```

It seems that the runtime error is missing the faulty node to be able to print itself and this causes the CI test runner to crash without the possibility to print the proper feedback. 

Problem is that I don’t know where it should be set. Anyone has experience with executable comments mechanism? @Ducasse maybe?

**Comment by MarcusDenker** [comment]
I will check

**Comment by MarcusDenker** [comment]
So PharoDocCommentExpression>>#evaluate raises a RuntimeSyntaxError because there is one somewhere in the AST.

But RuntimeSyntaxError is normally just created for *the faulty* node and then uses the node to print the error message.

If we remove the line

```
self isFaulty ifTrue: [ RuntimeSyntaxError signal ].
```

it makes this example work nicely, but then we have three tests failing where the AST is faulty *but* it can be executed without reaching the faulty node, leading to a result and not raising the runtime error....

Two possibilities:

1) we can embrace faulty execution, remove the check and fix the tests
2) we could just add a nil check if the node is nil, this would then raise a genertic error like:

```
errorMessage
	errorNode ifNil: [ ^'runtime syntax error' ].
	^ errorNode errorMessage

```

**Comment by jecisc** [comment]
Would the second case end up with understandable feedback from the CI to locate the problem?

I don’t have a strong opinion here on how it should work, but I think that it is important to keep things explicit in the CI

**Comment by privat** [comment]
This feels strongly related to #12785. A syntax error in a random evaluated string in a random test should not break the CI (could it be caused by a broken runtime comment or a direct call to parse), but should only error or fail the test. So maybe there is something to do in SUnit to make it more robust, there is also the possibility that a bug was introduced somewhere in the image that cause a corruption, freeze or deadlock in case of parse error.

It also seems to be a new thing, maybe bisecting could help to understand the cause.

**Comment by Ducasse** [comment]
I agree with Jean!
