### ISSUE TITLE
Spec: Editable SpStringTableColumn on a SpTablePresenter does not save edits

### ISSUE THREAD

**Issue by colorow** [guillep/pharo-core#12884]
**Bug description**
Setting SpStringTableColumn to beEditable in an SpTablePresenter give the user the opportunity to change values in the table, but the edits are not saved and are not accepted back into the #items in the SpTablePresenter

**To Reproduce**
1.open a Pharo 11 image and bring up a Playground.
2.  Type SpTablePresenter exampleWriteableTable and do it.
3.  The example will bring up a table, and allow the user to edit values in the left column.  Edit one of the values and remember the edit.
4. Resize the window.

**Expected behavior**
After resizing the window, it should be expected that the edited value will remain in the table and the edited value will be stored in the #items collection.

**Screenshots**

**Version information:**
 - OS: Windows 10
 - Version: 10
 - Pharo Version 11

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
In addition, are you willing to help because after all Pharo is yours too?

I am willing to help fix this as it is important to the code I am currently writing.  This may be able 8 hours of work, mostly as research into exactly where the problem lies.

**Additional context**
SpStringTableColumn implements onAcceptEdition:, which accepts a block to evaluate when the edit is accepted.  I haven't seen this code get executed, and I can't see where it would be called from, but I believe this method is intended to be where edits are saved.  I believe this is a problem of unimplemented code rather than existing broken code.  I also think this was based upon the FontChooser class, but not implemented fully.

**Comment by antonello-chessa** [comment]
Don't worry, it's not a bug, it's just that the table and its supporting classes(the columns, etc) are designed to work without a prior knowledge of the structure of the underlying data. Because of this, wherever the table needs to interact with the underlying data for I/O operations you are expected to provide a block that incapsulates the appropriate logic for the task, so that all the table and its supporting classes have to worry about is to feed the block with the proper data(if needed) and to retrieve the result(if the task requires one) knowing how to handle it in the specific context it was provided.

In your specific case, as you already guessed, you need to provide to the `SpStringTableColumn` you want to make editable a block trough the message `SpStringTableColumn>>onAcceptEdition:`, otherwise the only thing that gets updated is the _cell view_ of the cell you wanted to edit, and as soon as an event happens that triggers a redrawing of the table everything goes back to the previous state because the underlying data didn't actually change.

### An Example
Let's say you want to visualize a list of dictionaries and you want to make editable the values at some keys. A minimum working example that you can run in the playground is:

```
|dataModel table valueR1F1 valueR1F2 valueR2F1 valueR2F2|
"valueRiFj with i and j equal to 1 or 2 stands for: value for Row i and Field j"

valueR1F1 := '1' .
valueR1F2 := '2' .
valueR2F1 := '3' .
valueR2F2 := '4' .
dataModel := OrderedCollection new .
dataModel addLast: (Dictionary newFrom:{'Field1'-> valueR1F1. 'Field2'->valueR1F2}) .
dataModel addLast: (Dictionary newFrom:{'Field1'-> valueR2F1. 'Field2'->valueR2F2}) .

table := SpTablePresenter new .
table addColumn:(SpStringTableColumn new title:'Field1'; evaluated:[:item| item at:'Field1']) .
table addColumn:(SpStringTableColumn new title:'Field2'; evaluated:[:item| item at:'Field2']; onAcceptEdition:[:item :editorValue| item at:'Field2' put:editorValue];beEditable) .
table items:dataModel .
table open .
```
A last note: beware of some conflicts that can arise with the selection mechanism. You don't want the table to be always editable, rather you want to trigger the editing when actually needed, in a way that doesn't interfere with the way you select rows. That's why for example the `SpAbstractListPresenter`(an ancestor of `SpTablePresenter`) defines the messages `SpAbstractListPresenter>>activateOnDoubleClick` and `SpAbstractListPresenter>>whenActivatedDo:aBlock` so that you can preserve the single click to select rows and use the double click to activate editing. In addition to that, inside the code of the block provided through `SpAbstractListPresenter>>whenActivatedDo:aBlock` you should also deselect all the already selected items before activating the editing otherwise they will still interfere with each other.

**Comment by estebanlm** [comment]
as @antonello-chessa says, this is not a bug, is working as intended. 
You need to save your data model. And yes, the resize of the window will fire a data refresh, meaning if you did not save it before, it will be restored.

**Comment by colorow** [comment]
Thank you for your detailed comment.  What I ended up doing was making a change to SpMorphicTableCellBuilder>>visitStringColumnEditable: aTableColumn on: content.

visitStringColumnEditable: aTableColumn on: content
	| presenter morph |

	presenter := self dataSource model newTextInput
		addStyle: 'compact';
  		text: content;
		yourself.

	aTableColumn acceptAction ifNotNil: [ :valuable | 
		presenter whenSubmitDo: [ :aString |
			valuable cull: self item cull: aString ] ].
	
	**aTableColumn textChanged ifNotNil: [ :valuable | 
		presenter whenTextChangedDo: [ :aString |
		
			valuable cull: self item cull: aString ] ].**
	
	"add cell"
	morph := presenter build.
	presenter adapter applyStyle.
	self addCellMorph: morph column: aTableColumn


This allows me to add a block to perform work when text is changed in the cell, not just when accepted:

self table
		addColumn: (SpStringTableColumn new title: aName;
		 										beEditable;
												evaluated: tableRowSymbol ;
												onAcceptEdition: [ :aRow :aString |  aRow perform: tableRowSymbolSetter with: aString ];
												**onTextChanged: [ :aRow :aString |  aRow perform: tableRowSymbolSetter with: aString ];**
												yourself)

I have a grid that looks like a spreadsheet, and so users would expect spreadsheet like behavior.  This change gives the cell editing behavior more like what a user familiar with spreadsheets would expect.  I wrote this into a pull request, but I don't know where that is.   Thanks for the reply.
