### ISSUE TITLE
Speed up Symbol finding

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12940]
I heard that the formatting of incomplete selectors was disabled in Pharo because it is too slow.

One thing that is slow is to request the symbols of the system to know if one starts by what the user is typing.

An idea I have in mind is to replace the linear search by a tree search. We could add a method on collections of strings that return a tree of the symbols and doing the search in this tree.

This could also be used in other places of Pharo.

**Comment by privat** [comment]
It was slow and could be improved, another issue was that colors of complete/incomplete are the same red by default. But more importantly, the final reason for the disabling was the design issue, since distinguishing incomplete selectors from bad/mistyped selectors only make sense for the selector currently written, not all other selectors in the text.

I think I should have simply removed the feature instead of just disabling it by default.

See #12475

**Comment by privat** [comment]
Anyway, efficient search in symbols could also be used for completion. A [trie](https://en.wikipedia.org/wiki/Trie) could be nice, and if you think we deserve (almost) unlimited fanciness, a [suffix tree](https://en.wikipedia.org/wiki/Suffix_tree) could be awesome :)

**Comment by jecisc** [comment]
I'm really interested in adding this, but as for many things we need time ahah

For now I'm cleaning Shout and I have to work on other stuff. But if I find some time I'll give it a try (but don't be surprised if I don't have the time :) )
