### ISSUE TITLE
Remove ReUtilityMethodsRule

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12997]
Now Iceberg propose us to check the rules on commit and this is great!
But we have some rules that do not make sens or that have a looooot of false positive. 

Pharo 12 might be a good opportunity to clean that. If we give better critics, then people might have more motivation to fix the critics remaining. 

In that direction I propose to remove ReUtilityMethodsRule because because it is not a bad thing to have utility methods in Pharo! Without them our methods would be much longer and less readable.

**Comment by privat** [comment]
Utility methods is a code smell because it's often symptomatic of a bad assignment of responsibilities: why the method belongs to class Foo if neither `self` nor its instance variables are involved in anything? A fix can be to move the method to the class of argument with the most involvement (with the use of extension methods if required).

The issue to me seems more about the aggressivity level of the rule, as both the following are critiqued as utility.

```st
foo
  ^true
```

```st
commonParents: shape in: aLine
	| current parents |
	current := shape parent.
	parents := OrderedCollection new.
	[ current = aLine parent ] whileFalse: [ 
		current ifNil: [ ^ nil ].
		current parent = current ifTrue: [ ^ nil ].
		parents add: current.
		current := current parent ].
	^ parents
```

**Comment by jecisc** [comment]
I get that it can highlight a bad design, but most of the time when I see this rule been triggered, it's false positive. 

I think that for Pharo 12 we should either find a way to make it less aggressive like you said or disable it because having a rule with a lot of false positive just push people to not care about the rules anymore.

**Comment by privat** [comment]
Agree, a noisy rule is useless. So improve it or remove it.
