### ISSUE TITLE
RubShoutStylerDecorator #styler error when loading Monticello repository from filesystem

### ISSUE THREAD

**Issue by colorow** [guillep/pharo-core#13149]
**Bug description**

**To Reproduce**
1.Open Monticello browser in Pharo 9-12
2. Press repository
3. Repository type = directory
4. Browse and select a directory where an existing .mcz file exists
5. Press open on the Monticello Browser.
6.  See error (Instance of MCFileRepositoryInspector did not understand #selectedClassOrMetaClass)

**Expected behavior**
Browser should open with list of .MCZ files to load

**Screenshots**

**Version information:**
 - OS: [e.g. iOS] Windows 10
 - Version: [e.g. 1.6.1]
 - Pharo Version [e.g 9] 9-12

**Expected development cost**
An hour or so.

**Additional context**

styler
	"The styler responsible for highlighting text in the receiver"

	^ styler ifNil: [
		styler := (self model notNil and: [ ** self model selectedClassOrMetaClass ** notNil ])
			ifTrue: [
				self model selectedClassOrMetaClass syntaxHighlighter
					view: self;
					yourself ]
			ifFalse: [ self defaultStyler ] ]

The method fails at  self model selectedClassOrMetaClass because the model doesn't implement the method #selectedClassOrMetaClass .  In order to get past this I made the follwing change, but I don't know if it is the most correct way:

		styler := (self model notNil and: [  (self model class canUnderstand: #selectedClassOrMetaClass) and: [    self model selectedClassOrMetaClass notNil ]])

**Comment by Ducasse** [comment]
Thanks for this report. 
We should pay attention because the Monticello code is only used to load code and the monticello browser should probably be removed from the system.

**Comment by colorow** [comment]
Thanks for fixing it.  I understand that Monticello is legacy, but I have a
lot of old projects that I occasionally use, and don't intend to put on
GitHub.  I suspect there is AP lot of code out there like that.

**Comment by Ducasse** [comment]
Ok but do not expect that it will endlessly work. We cannot maintain endlessly things because it prevents us to focus on the real added values. You see you can also not be selfish and consider that our time is not endless and that you would prefer that we focus on making Pharo a cool and modern system instead of being drag behind.

**Comment by jecisc** [comment]
May I ask why you do not want to migrate it on GitHub?

Lack of time? You don’t like git? They work on other Smalltalk that do not manage git? Something else?

I would just like to see if this is because of something that we can improve or not. Because as Stephane said, it’s hard to maintain everything and if we can help to reduce even more the usage of Monticello that might be good for everyone in the long run.

**Comment by colorow** [comment]
The reason is just that I have a lot of half finished projects that I wrote
over the years that aren't worth putting on GitHub publicly, but I
occasionally go back and look at code to see how I did certain things.  I
also have been on Smalltalk hub looking at things recently.  I am not
advocating keeping Monticello inside the current release, but if it is
taken out perhaps it could be in a GitHub repo on its own.  That way when
people need to do archeology they have it available.

**Comment by jecisc** [comment]
I see. The problem is that if we remove it from the image, nobody will keep the compatibility.

it will still be possible to use Pharo 11 images to look at the projects even if we are at a further Pharo version. But the Pharo versions without Monticello will probably not keep the code needed only for Monticello
