### ISSUE TITLE
Frequent crashes of Pharo11

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#13156]
Pharo 11 crashes very often to me (on Windows 10 - not tested elsewhere), even multiple times a day. I did not have any similar problem in Pharo 10.

I did not find any reliable way to reproduce yet. Few times it was during saving an image (making it unloadable), few times when running tests.

My last crash, when running tests, did not produce any logs at all (stderr empty and PharoDebug.log not existing at all).

The crash before that was when saving an image and these are my logs from last few seconds:

[stderr](https://github.com/pharo-project/pharo/files/11077849/stderr.txt)
[PharoDebug.log](https://github.com/pharo-project/pharo/files/11077850/PharoDebug.log)

**Comment by guillep** [comment]
Hi @JanBliznicenko, this is a known issue. You're using an old VM with a new image.
Old VMs do corrupt images with ephemerons, so opening any image with ephemerons is subject to memory corruptions.

You should 
 - update your VM in the launcher
 - discard any P11 image from the last two weeks (since you run it with an old VM)

The new VM should be able to run both new and old images (that are not corrupted)

For more info, see: https://pharo.org/news/2023-03-02-ANN-Ephemerons.html

Please open another issue if you see other problems like this after the corresponding updates.

Cheers

<blockquote><img src="/files/favicon.ico" width="48" align="right"><div><strong><a href="https://pharo.org/news/2023-03-02-ANN-Ephemerons.html">Pharo - [ANN] Ephemerons in Pharo11</a></strong></div></blockquote>

**Comment by Rydier** [comment]
I re-downloaded both VM and image through the launcher today, and still had a crash on save which bricked my image.

Other than version numbers, nothing of interest in PharoDebug.log.
Are these too old as well?

VM: Win32 - x86_64 - Win64 - CoInterpreter VMMaker-tonel.1 uuid: 1881e440-eab2-0d00-9966-11ef0c267fe2 Mar 10 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 1881e440-eab2-0d00-9966-11ef0c267fe2 Mar 10 2023
v10.0.1 - Commit: f928dd94 - Date: 2023-03-10 09:51:08 +0100

Image: Pharo11.0.0 [Build information: Pharo-11.0.0+build.651.sha.57e0d4fc75d06817bc6e8f8e04cc5bf2b8082336 (64 Bit)]

**Comment by JanBliznicenko** [comment]
I have the same VM now and everything seems to be working ok. But updating the VM through launcher was not enough for me. I had to completely remove the VM. I did it by hand (in vms directory, by default Documents\Pharo\vms, remove directory 110-x64 and file 110-x64.zip), but removing it though right-click on the VM in launcher should do the same thing.

**Comment by YeesterPlus** [comment]
plz help these people @guillep
