### ISSUE TITLE
Bug in syntax highlight

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#13316]
In some cases the syntax highlight can be off. For example:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/9519971/230355564-6849005a-f1c3-47c1-a383-d446a1db153b.png">

I do not know yet of this is a syntax highlighter but or a parser bug producing a bad AST

**Comment by privat** [comment]
Can be both. Note that values have two intervals: a large `start`-`stop` one (also called `sourceInterval`), and a smaller `startWithoutParentheses` - `stopWithoutParentheses`. Highlighter should use this small one.
In fact, the information on all parentheses are preserved as `parentheses` that is a collection of intervals.

I suspect that the styler don't care about all the existing information and used its own heuristics.
Maybe the parser is also off-by-one in some case.

Anyway, the issue is general

![Capture d’écran du 2023-04-06 07-30-08](https://user-images.githubusercontent.com/135828/230364480-43eca4d1-51dc-4e9b-adf8-8e0b9efdee65.png)
