### ISSUE TITLE
Attempt to release a shared cairo_font_face

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#13526]
**Bug description**
We are getting recently very often this inform box during image saving: `Attempt to release a shared cairo_font_face. Please report this on pharo-dev mailing list`.  Sometimes even a dozen of them.

It comes from: 'CairoFontFaceExecutor>>#finalize' and this PR describes the background of it: https://github.com/pharo-project/pharo/pull/565

> A cairo_font_face could still be referenced from external heap and further used.
> Thus we must NOT release the FT_Face until the external reference count drops to 1.
> 
> Thus the CairoFontFace is not a good place for retaining a strong reference to the FT2Face, because the reference will vanish as soon as the Smalltalk object is garbage collected, while some external cairo_font_face still point on it.
> It's better to have the strong reference in the executor, and avoid garbageCollecting the executor while there are external references to the resource data...
> 
> The solution is to use a specific CairoFontFaceExecutor.
> If the resource is shared, then we have no other choice than regularly polling the ref count in a new Process.
> This process must stop whenever the session change.

It is probably related to changes in ephemerons. So first question is, have you seen it as well? @nicolas-cellier-aka-nice

**Comment by nicolas-cellier-aka-nice** [comment]
This piece of code was not a proper fix, it was an instrumentation of finalization process to detect a case of potential dangling reference to already freed `FT_face`...

In the fogbugz issue, i have illustrated two scenarii of such dangling reference, but for some reason, i can't drag and drop the png here, github tells me:

> Something went really wrong, and we can't process that file

Since the VM schism has driven me away from Pharo, since Pharo is changing too fast, and since github is not willing to help me, I'll stop my assistance here, but I think that you can gather all the pieces.

Please refer to https://pharo.fogbugz.com/f/cases/20776/Potential-dangling-ref-to-freed-FT_Face if you still have an account.

<blockquote><img src="/favicon_fogbugz.ico" width="48" align="right"><div><strong><a href="https://pharo.fogbugz.com/f/cases/20776/Potential-dangling-ref-to-freed-FT_Face">FogBugz</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
Thanks nicolas. Pharo is improving steadily and we are making strong progress and we will continue.

**Comment by MarcusDenker** [comment]
The PR has been merged

**Comment by Ducasse** [comment]
Marcus do we backport it to P11?

**Comment by tesonep** [comment]
> Marcus do we backport it to P11?

The PR has been merged in P11

**Comment by Ducasse** [comment]
COollllll Tx for the answer
