### ISSUE TITLE
Can we have namespaces?

### ISSUE THREAD

**Issue by privat** [guillep/pharo-core#13563]
Namespace are classical approach to deal with names conflicts caused by independent developers.
While the *two-uppercase-prefix* convention on classnames works locally, I'm not sure how it scales.
Namespace can also be used to isolate versions of some classes, might be used to protect experimentation on core classes, or to install packages in a more transactional way.
However, namespaces do not magically solve all problems, they only offers another level of indirection when resolving static binding :)
Message sends, and object references are not concerned by namespaces.

How namespaces are used in other Smalltalk dialects?

* https://www.gnu.org/software/smalltalk/manual/html_node/Namespaces.html
* ?

Problems to solve

* [ ] What syntax for qualified identifiers? `Foo.Bar`? (from a parser point of view, I don't like it because of the obvious ambiguity with statement separators)
* [ ] How namespaces are related to packages, baselines, classes, environments, etc?
* [ ] What about nesting?
* [ ] What to do with undeclared variables? (One `Undeclared` array by namespace?)

**Comment by Ducasse** [comment]
Jean can we have a discussion on what we did in the past. Let me know when you have time.
We do not want Foo.Bar.

**Comment by Ducasse** [comment]
Hi jean

- could you read https://rmod-files.lille.inria.fr/Team/Texts/Papers/Poli17b-IWST-UndefinedClasses.pdf the idea is how could be support that a class is temporarily not bound. For example I import a namespace and that namespace does not contain the superclass of one of my classes (so in other system, a class cannot have an unindefined superclass, then they remove the classes and all its subclasses.
- and https://rmod-files.lille.inria.fr/Team/Texts/Papers/Poli17d-Programming-ScopedExtensions.pdf
Extensions are key but can be painful. A first step would be to support that the unloading of a package restore shadowed extensions. 

And we can discuss but not by forum about what we learned in the process. 

I think that class extensions and supporting live programming is key. 
We had a prototype called Metalo (may it is in a private repo and we can give you access).

S

**Comment by astares** [comment]
Just a few comments:
- Prefixing is so "old school" and outdated  
- Namespaces would be highly appreciated, often a question on Discord appears if Pharo has namespaces
- SmalltalkMT from https://www.objectconnect.com supports a  "Foo::Bar" notation
- Squeak uses "Environments"

**Some experiments:**
- a part of the success of Java is that it provides **collission free namespacing using reverse DNS name** (which is easy to understand and one easily knows also about the origin, like "org.apache", "org.eclipse", "com.oracle", and other)
- similar namespacing with "." notation is supported in mainstream languages: C#, VB.NET, JavaScript,  ....
- having a similar "dot based" scheme as Java, JavaScript, C#, ... in Pharo would be super beneficial to avoid collissions:  "org.pharo.spec.Window", "org.pharo.athens.Window", "org.pharo.sdl.Window", "org.pharo.morphic.Window" 
- it would also be beneficial in exchange with external systems (Java, .NET, ...) as one could generate wrapper classes with same name and same namespace as the external system and then calling appropriate external pair classes
- and yes - Namespace discussion could be _academic_ (condem static Namespace solutions in other languages) or _pragmatic_ (adopt them to get more Pharo adoption - but make them real objects), I would prefer the pragmatic route as it would help Pharo scale and support easy adoption

- if you hack #isValidGlobalName to accept "dots" you can happily have classes like this:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/5980033/236166881-1746002c-6026-4105-b4df-8861a47d268b.png">

But parser would not understand it (yet) and Tonel File format also needs to be adjusted to store them.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/5980033/236168448-d14c7da6-6221-4103-b473-58cbbe97f26c.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/5980033/236169842-ec167f62-2dd6-499e-b994-292401c28fc4.png">

**Comment by astares** [comment]
> Jean can we have a discussion on what we did in the past. Let me know when you have time. We do not want Foo.Bar.

I would like to understand why the "dot" is excluded right in the beginning? Mainstream has adopted it and it helped to avoid worldwide collissions when using reverse DNS names. It was one factor that helped Java to be adopted so widely also in commercial space. Using the dot notation
- one can have a distinction into Organizations and legal entities ("org.apache" vs. "com.microsoft") with an easy recognition of domain where it comes from
- one would avoid collissions even within a company easily like "com.mycompany.myframework. ...") and many other
- would fulfil developer expectation when coming from other languages like Java, C#, VB.NET, TypeScript, .... and align Pharo with mainstream (which would foster easy adoption)

Would the "dot" be a lexical problem due to the use of the dot to separate expresssions? If there is no space I think it could be parsed and distinguished from variables, messages and other:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/5980033/236175582-c9db0eb8-a855-49ec-95a3-43f6fabd0428.png">

**Comment by guillep** [comment]
> El 4 may. 2023, a las 12:11, Astares ***@***.***> escribió:
> 
> 
> Jean can we have a discussion on what we did in the past. Let me know when you have time. We do not want Foo.Bar.
> 
> I would like to understand why the "dot" is excluded right in the beginning? Mainstream has adopted it and it helped to avoid worldwide collissions (one factor that helped Java to be adopted so widely).
> 
> Would this be a lexical problem due to the use of the dot to separate expresssions? If there is no space I think it could be parsed and be distinguished:
> 
Yes, but I’m sure catching bugs related to that will be a mess :)

**Comment by astares** [comment]
>Yes, but I’m sure catching bugs related to that will be a mess :)

@guillep

Which has yet to be seen/proven. Do you already have any specific cases in mind where bugs appear?

Be aware that typically one does not use the namespace directly - it has to be resolved in collission case only. So if you work within a browser you have imported namespaces and use the short name in the code only.

**Comment by Ducasse** [comment]
I do not have the energy to explain it again and again. 
The dot notation does not solve anything. Come on. You cannot use the same namespace than mine. Period. 
So this is exactly the same as a prefix. The only difference is that you do not have to type the prefix. 
We do not want namespace for just that!

**Comment by Ducasse** [comment]
What we would like is the possibility for example you have a package with tests and in this package we have a reference to OrderedCollection. Now can I have a way to inject in two different versions of this package a different implementation of the class OrderedCollection. So we do not want to have inside method Core.System.Collection.OrderedCollection because we will never be able to reuse the code with My.OrderedCollection. 
So this is not because Java has a super complex and multi millions $ development effort that their model is working.

**Comment by Ducasse** [comment]
Then an important question is what do we do with method extensions?
If I extend a class in a namespace and another package use that namespace does it see my extensions?
And this is something else than just having silly periods in ClassBinding.
So if you are real about that just read the paper of camille Teruel on Scoped Method extensions avaible on my publications page.
The PhD of alexandre bergel was about this too and we understood that this is not the semantics we want. 
Camille worked to see if we can have something better. 
So if you really want to understand you can also read the paper on UndefinedClasses because what will happen if you have classes in a namespace that inherit from a class in another namespace and you want to change it but you did not define the class yet. Do we want to just unload the complete hierarchy as it is in VW now. Sorry but we wanted to have a way to have 
classes were we can rebind their superclasses. So if you are serious about namespace and package and modules
you have some homework to do before talking to me with your tone.

Am I clear?

**Comment by Ducasse** [comment]
Finally I will discuss this with this crappy medium.
May be I can go to Montreal to discuss it for a while.

**Comment by devid-rudesheim** [comment]
Do you want to use a short name?
If so, you can use it without changing the language.

```smalltalk
Object
	subclass: #ExampleNode2Node1Root.

Object
	subclass: #Node2Node1Root.
Root class
	compile: 	'Example ^ ExampleNode2Node1Root'
	classified:	'namespace'.

Object
	subclass: #Node1Root.
Root class
	compile: 	'Node2 ^ Node2Node1Root'
	classified:	'namespace'.

Object
	subclass: #Root.
Root class
	compile: 	'Node1 ^ Node1Root'
	classified:	'namespace'.

| space |

Root Node1 Node2 Example. 	"-> ExampleNode2Node1Root"
Root Node1 Node2 Example new. 	"-> an ExampleNode2Node1Root"

space := Root Node1 Node2.
space Example new.		"-> an ExampleNode2Node1Root"
```

**Comment by astares** [comment]
Some links:

- https://arxiv.org/pdf/1708.01679.pdf 
- https://rmod-files.lille.inria.fr/Team/Texts/Papers/Poli17d-Programming-ScopedExtensions.pdf
- https://rmod-files.lille.inria.fr/Team/Seminars/2014-06-IMT-RMOD/camille-teruel.pdf
- https://theses.hal.science/tel-01290364/document

**Comment by astares** [comment]
# FOR EXPERIMENTS:

## Using "::" as separator

If one patches the method String>>#isValidGlobalName

```Smalltalk
isValidGlobalName

    self ifEmpty: [ ^ false ].
   
    "reserverd default names"
    self = #NameOfSubclass ifTrue: [ ^ false ].
    self = #TNameOfTrait ifTrue: [ ^ false ].

 ^ (self splitOn: '::') allSatisfy: [: part |
                Character supportsNonASCII ifTrue: [
            (part first isLetter
                and: [ part first isUppercase])
                and: [ part allSatisfy: [:character |
                    character isAlphaNumeric or: [ character = $_ ]]]
        ]
        ifFalse: [
            (part first between: $A and: $Z) and: [  
                part allSatisfy: [:character |
                    (character between: $a and: $z) or: [
                        (character between: $A and: $Z) or: [
                        (character between: $0 and: $9) or: [
                         character = $_]]]]]
        ] ]
``` 
as suggested in a discussion from 2017 in http://forum.world.st/Separator-in-class-names-td4926162.html
it is possible to have classes like in **"Foo::Bar::User"** when giving a symbol:

```Smalltalk
Object << #'Foo::Bar::User'
	slots: {};
	package: 'Foo'
```

<img width="364" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/90de4904-007d-45f6-bfa3-51456c417284">

Tonel is able to write/read them as new tonel version uses Symbols:

<img width="260" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/d462a397-3252-452a-8a4e-fb0c5170fa5a">

Tonel writes the file as User.st.

## Using "." as separator

If one patches the method String>>#isValidGlobalName to (without the uppercase requirement)

```Smalltalk
isValidGlobalName

    self ifEmpty: [ ^ false ].
   
    "reserverd default names"
    self = #NameOfSubclass ifTrue: [ ^ false ].
    self = #TNameOfTrait ifTrue: [ ^ false ].

  ^(self splitOn: '.') allSatisfy: [: part |
                Character supportsNonASCII ifTrue: [
            (part first isLetter)
                and: [ part allSatisfy: [:character |
                    character isAlphaNumeric or: [ character = $_ ]]]
        ]
        ifFalse: [
              
                part allSatisfy: [:character |
                    (character between: $a and: $z) or: [
                        (character between: $A and: $Z) or: [
                        (character between: $0 and: $9) or: [
                         character = $_]]]]]
          ]
```         

it is possible to have classes as in **"org.pharo.User"** when giving a symbol:

```Smalltalk
Object << #'org.pharo.User'
	slots: {};
	package: 'Foo'
```
<img width="349" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/347185d0-c4a8-44aa-9c10-77e2f4c2fd96">

Tonel is able to write/read them as new tonel version uses Symbols:

<img width="164" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/f67c1f94-4d2a-433e-9a49-e5ce4ec47cfc">

Tonel writes the file as 

<img width="247" alt="image" src="https://github.com/pharo-project/pharo/assets/5980033/c4b6fae1-28f8-4981-a046-41b617a7d9e0">



<blockquote><div><strong><a href="http://forum.world.st/Separator-in-class-names-td4926162.html">Pharo Smalltalk Developers - :: Separator in class names</a></strong></div><div>:: Separator in class names. Hi, due to the absence of a namespace solution we today often prefix classes with one, two or three letters. You all know prefixes like "Zn", "Zdc", "GLM", "Tx", "WA",...</div></blockquote>

**Comment by Ducasse** [comment]
As if we do not know that!
