### ISSUE TITLE
meta+left shortcut used for 2 things, breaking CompletionEngine's "close details"

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#13584]
**Bug description**
`Meta key + left arrow` shortcut (`cmd + <-` or `ctrl + <-`) is used for two actions that could be activated under the same condition, leading to only one actually working.

1) Move cursor next to previous word
2) Hide details of `CompletionEngine`/`NECMenuMorph`

As a result, the cursor move happens, but there is no way to just hide details without moving the cursor.

Also, the "cmd" words in these completion shortuct labels are hardcoded instead of using "ctrl" on non-mac systems: https://github.com/pharo-project/pharo/issues/6169

**To Reproduce**
1. Open Playground
2. Type `Tr` and wait for completion popup to open
3. Notice the "cmd<- close detail" gray text at the bottom of the popup
4. Press `cmd + <-` or `ctrl + <-`
5. Cursor moved, instead of just closing the details

**Expected behavior**
There should be separate keyboard shorcut for opening and closing the detail and for moving cursor.

**Version information:**
 - Probably all OS, tested on Windows, not sure about mac
 - Probably all Pharo versions, tested on 7-12

**Comment by privat** [comment]
#13473 (merged) propose for pharo12 to open the detail windows by default (and see how people react).

We can go further: always have the detail windows and rebind browse to the classic `ctrl+b`. So ctrl-left and right are no more special in the completion menu.

I think it is correct to hijack ctrl-b if a completion menu is open: you browse the current completion entry instead of the current line or selection.

Note: I looked a little, and this change is not trivial because shortcuts (like ctrl-b) are handled a lot earlier than motions (like ctrl-→)

For the naming issue (ctrl vs cmd), code is really weird, and it's not clear where the platform adaptation is made in other tools (or should be made).
* `$b meta printString` shows `Meta + B`.
* `$b meta printOsRepresentation` exists but is unused and broken because require an unimplemented method `menuShortcutModifierString`.
* `$b meta prettyPrintOn:` exists but is also unused, and prints unicode garbage.
* `KMShortcutPrinter` exists, and seems invoked with `$b meta acceptVisitor: OSPlatform current shortcutPrinter` but do not have a lot of clients and feels very low level and fragile.
* Text in rubric menu seems to rely on `ToggleMenuItemShortcut class>>#normalize:` that just looks insane.
