### ISSUE TITLE
Clean Blocks: self is nil on Debugger

### ISSUE THREAD

**Issue by PalumboN** [guillep/pharo-core#13591]
If I stop a debugger inside a Clean Block and evaluate for `self` it is nil :(

<img width="275" alt="image" src="https://user-images.githubusercontent.com/4098184/235176759-5b19610b-d1e4-42cb-b605-9ad7ae70608e.png">

**Comment by MarcusDenker** [comment]
I checked what is happening. What is clear is that in a clean block, the receiver is nil due to them being clean.

But: we should be able to get something better if the home method of the block (where is was defined) is on the stack.

I did some experiments, and the follwoing works:

1) make sure the doit is evaluated with the right receiver. Here the problem is that we set a nil receiver explicitly after setting the context. see SpCodeInteractionModel>>#compiler

```
compiler
	"Provide a compiler set up on the current context/class/receiver"

	^ self doItReceiver class compiler
		  context: self doItContext;
		  receiver: self doItReceiver;
		  requestor: self
```

if we do not set the receiver, it will use OCContextualDoItSemanticScope to evaluate the doit:

```
compiler
	"Provide a compiler set up on the current context/class/receiver"

	^ self doItReceiver class compiler
		  context: self doItContext;
		  requestor: self
```

In OCContextualDoItSemanticScope>>#receiver, we now could detect this case and use #activeHome:

```
receiver

targetContext sourceNode isClean ifTrue: [ ^ targetContext activeHome receiver].
^targetContext receiver
```

For this example it seems to work, reading "self" in a clean block in a debugger returns the receiver, not nil

**Comment by MarcusDenker** [comment]
Of course, this only works of activeHome is found (and we need to guard for it being nil). 

The cases where is fails willl the those of a clean block that was stored somewhere, where what the  receiver would be in a non-clean block would potentially not even exist anymore, in which nil seems to be a good answer.

**Comment by MarcusDenker** [comment]
As a first step, #13812 will make sure that we do a reflective read when accessing 'self'. This means that we can do the detection for blocks not in  OCContextualDoItSemanticScope>>#receiver, but instead in SelfVariable>>readInContext:

This is much better as the targetContext (and receiver) in OCContextualDoItSemanticScope is correct, what is wrong is that the receiver (the self) in the block is the receiver of the home Context.

TODO:
- fix #compiler in SpCodeInteractionModel so we evaluate against the context, not nil
- use receiver of home context with fall back to activeHome in  SelfVariable>>readInContext: for block context
