### ISSUE TITLE
automatic protocol categoriser does weird stuff

### ISSUE THREAD

**Issue by estebanlm** [guillep/pharo-core#13597]
**Bug description**
it autocategorise methods even if I am creating it inside a category)

**To Reproduce**
Calipso, select a protocol (e.g. private)
type a method that would be categorised if not in protocol, e.g. `isATest`.
See how it puts the method in `adding` instead let it in `private`.

**Expected behavior**
If I add a method in an existing category, I want it to stay there

Pharo 11

**Comment by Ducasse** [comment]
I think that they did that on purpose but I agree that this is intrusive.

**Comment by jecisc** [comment]
This was indeed on purpose because we have tests ensuring some methods are in specific protocols and a lot of PR were failing because of that because a lot of people are just adding methods without checking the protocol currently selected.

But we can add a setting for the people that really take cares of the selected protocol

**Comment by estebanlm** [comment]
no, sorry, this is as ugly and breaking as force a format.
you may suggest it, but you can't force it.
and no, default should be "do not mess with my code", not "I will mess with your code, but you can disable me".

please, inverse the setting.
