### ISSUE TITLE
[Clean Blocks] Test failing with clean blocks enabled: Fuel

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#13755]
When turning on the clean block option in the compiler and recompile all, these tests in Fue fail:

- testSerializeContextToFileNamed 
- testSerializeStackFromContext

**Comment by PalumboN** [comment]
I was debugging it, it is hard to find the issue.

### What I found

The clean block is in the method
```st
FLDebuggerStackSerializer >> serializeStackFromContext: aContext toFileNamed: aFileName
	self
		encodeDebugInformation;
		addPostMaterializationAction: [ :materialization | 
			FLDebuggerStackMaterialization new
				interruptedContext: materialization root;
				signal ];
		filePath: aFileName;
		object: aContext copyStack;
		serialize.
		


	^ aFileName
```

The block is serialized and then deserialized and executed. The deserialized Clean Block is broken because the CompiledBlock is not there (so it cannot be executed).

Debugging the method `FLGlobalCompiledBlockCluster >> materializeInstanceWith: aDecoder` during the CleanBlockClosure creation I got `literalIndex = 0`, so the compiled block is going in the place of other literal.

You can put a conditional halt on that method and run `testSerializeContextToFileNamed` test.
The problem may be during the serialization (not saving the index well).
