### ISSUE TITLE
regression: we cannot compile a method in the class pane

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#13884]
I found that quite annoying that changes break the flow of programming. 
In P10 we can define a method in class pane without problem.
Now in P12 we cannot anymore. 
Why do we have to force the user to decide when the system was working and could decide in a clever way the intention of the user. 

We should be able to define a class in a method pane and a method in a class pane!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Ducasse** [comment]
This is not because you do not use a feature that others don't.

**Comment by MarcusDenker** [comment]
Yes, this was a cleanup done in https://github.com/pharo-project/pharo/pull/12981 

What is interesting is that the other way never worked (defining a class in method pane). The way it was supported for the class pane was a hack in the end.

If this is really important, there is nothing else possible than adding a hack back.

But in the long term, this makes things harder:

The class pane set up for editing classes. So supporting both method and class definitions in a nice way (and have all the tools in the menu work correctly) would means to build a code pane that can deal with both at the same time. Maybe we need to get rid of the idea of having specialized panes? 

But if we project that further,  we really need to back the tools with the AST (which is not the case right now). 
Maybe the class pane would even have the ClassParser structure instead of a normal AST...

Then this gets even harder, as we have to support many different ASTs in the same pane.

**Comment by MarcusDenker** [comment]
This is related to https://github.com/pharo-project/pharo/issues/7468, too: 

- should clean compileANewClassFrom: aString notifying: aController startingFrom: aClass

**Comment by MarcusDenker** [comment]
Interestingly, this was not really working before. if I try to define a method with an argument in the class pane in Pharo11, it does not even do syntax highlight correctly:

![WrongHighlight](https://github.com/pharo-project/pharo/assets/413057/a7c8b846-754c-420c-a794-c24c2e45f80f)

This is because the editor is not setup to parse methods, but classes, while typing.

**Comment by MarcusDenker** [comment]
this is fixed
