### ISSUE TITLE
Searching by example launches a `PrimitiveFailed`

### ISSUE THREAD

**Issue by jthulhu** [guillep/pharo-core#14024]
**Bug description**
In the Finder, searching by example with an input containing a block (for instance, [ 3 ]. 3) launches the exception `PrimitiveFailed: primitive #basicNew: in CompiledBlock class failed`

**To Reproduce**
1. Open Finder
2. Select `Examples`
3. Query `[ 3 ]. 3`

**Version information:**
 - OS: NixOS / nixpkgs unstable
 - VM version: 10.0.5 ([2757766f6](https://github.com/pharo-project/pharo-vm/commit/2757766f6aa6ec505df09af4357a5501f33afcaa))
 - Pharo Version: 11.0.0 (latest `stable.zip` from https://files.pharo.org/image/110/

**Comment by MarcusDenker** [comment]
Thanks, the reason is that #deepCopy is not implemented for CompiledCode (and CompiledBlock, the subclass that is used here).

It should not be hard to support that.

For this example then it would work (as this is a constant block, easy to copy).

But another problem is that deepCopy for full blocks in general might not be a good idea (due to recursive copy of the outer context).  So we should step back and maybe not do a deepCopy for blocks at all in the Finder

**Comment by MarcusDenker** [comment]
deepcopy for compiledBlock is harder than you would think: it searches itself in the outerCode by identity to be able to print itself. But copying destroys that identity.

see the issue #11913 for that.

I think we should add an exception and not copy the receiver if it is a block (change local to method finder) for now.

But it shows that #11913 should really be solved

**Comment by jthulhu** [comment]
@MarcusDenker If I understand correctly, currently the Finder makes a deep copy of what is provided in the search bar to launch all methods and check the results, which is required since the methods might modify the objects. Instead of making a deep copy (which seems to be problematic), since the code snippet are expected to be relatively small, one could execute the code that produces the objects instead of running it once and making copies.

**Comment by MarcusDenker** [comment]
yes, that would be an idea

**Comment by MarcusDenker** [comment]
PR merged
