### ISSUE TITLE
The RNG is biased

### ISSUE THREAD

**Issue by jthulhu** [guillep/pharo-core#14198]
**Bug description**
The first sample of the RNG of Pharo (`Random`) is severely biased toward small numbers (<0.1).
The following shows the first number generated by `Random`, instantiated with 10000 different seeds. Note that none of them ever gets over 0.08!
![image](https://github.com/pharo-project/pharo/assets/23179762/cc60fbe8-ccfd-48b0-8f37-94175d2aa26e)
In contrast, the following is the first 10000 numbers generated by a `Random` instance.
![image](https://github.com/pharo-project/pharo/assets/23179762/c6c2aead-be8a-44a9-b230-6607011c20a9)
It's less homogeneous, and the threshold of 0.08 doesn't hold anymore.

**Version information.**
 - Pharo: 12, built on June, 30.

**Comment by svenvc** [comment]
Any code for others to easily replicate this (your test) ?

Apart from that, IIUC, you expect the seeding to deliver a perfect distribution ? Is that a even a requirement ?

There is also the PolyMath project that has tons of RNGs to choose from and much more.

Another option is to read from /dev/urandom on linux and macOS.

**Comment by jthulhu** [comment]
@svenvc 
Code for the first histogram:
```smalltalk
((1 to: 10000) collect: [ :i |
	random := Random seed: i.
	random next ]) rsHistogram
```
Code for the second histogram:
```smalltalk
random := Random seed: 17.
((1 to: 10000) collect: [ :i |
	random next ]) rsHistogram
```

> Apart from that, IIUC, you expect the seeding to deliver a perfect distribution ? Is that a even a requirement ?

What I do expect is that these two samples should be very similar, and I think it's a pretty reasonable requirement. It's the case, for instance, of the RNG of the standard library of Python.

**Comment by svenvc** [comment]
I think your seed is too small, consider the following 2 examples that give the distribution you are looking for:
```
((1 to: 10000) collect: [ :i |
	random := Random new.
	random next ]) rsHistogram

((1 to: 10000) collect: [ :i |
	random := Random seed: i * 1e6.
	random next ]) rsHistogram
```

**Comment by Ducasse** [comment]
The random generator is bad in Pharo and this is well known. 
In the past I proposed to change it to use somes of the ones I collected in PolyMath and I was told that it can break.... so I gave up. But yes we should change this bad random number generator especially since there are better ones that I already packaged.

**Comment by Ducasse** [comment]
So can you pick one from https://github.com/PolyMathOrg/random-numbers/tree/main/src/Math-RandomNumbers and we use it in place of Random. 
I feel bad because I should have pushed my idea further.


<blockquote><img src="https://opengraph.githubassets.com/e9660614db33e22826602e2d39cf75c11cc867516352c37b6f0d2851d9b542df/PolyMathOrg/random-numbers" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PolyMathOrg/random-numbers">random-numbers/src/Math-RandomNumbers at main · PolyMathOrg/random-numbers</a></strong></div><div>Project to provide different random number generators for the Pharo programming language - random-numbers/src/Math-RandomNumbers at main · PolyMathOrg/random-numbers</div></blockquote>

**Comment by Ducasse** [comment]
I planned to use https://github.com/PolyMathOrg/random-numbers/blob/main/src/Math-RandomNumbers/PMMersenneTwisterRandomGenerator.class.st

So can you run your analysis on it?

<blockquote><img src="https://opengraph.githubassets.com/e9660614db33e22826602e2d39cf75c11cc867516352c37b6f0d2851d9b542df/PolyMathOrg/random-numbers" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/PolyMathOrg/random-numbers">random-numbers/src/Math-RandomNumbers/PMMersenneTwisterRandomGenerator.class.st at main · PolyMathOrg/random-numbers</a></strong></div><div>Project to provide different random number generators for the Pharo programming language - random-numbers/src/Math-RandomNumbers/PMMersenneTwisterRandomGenerator.class.st at main · PolyMathOrg/rand...</div></blockquote>

**Comment by jthulhu** [comment]
@svenvc I think it's not an issue of the seed being small, but being close together. In your example, they are spread out, but if you try this instead
```smalltalk
(1e6 to: 1e6+10000) collect: [ :i |
    random := Random seed: i.
    random next ]) rsHistogram
```
you get the following
![image](https://github.com/pharo-project/pharo/assets/23179762/7983ab87-6d12-4ddc-9a0b-c7d9ee5c6074)

Again, the results are all within 0.1 of each other.

@Ducasse with `PMLinearCongruentialRandomGenerator`, there doesn't appear to be this problem:
```smalltalk
((1 to: 10000) collect: [ :i |
	random := PMLinearCongruentialRandomGenerator seed: i.
	random next ]) rsHistogram
```
![image](https://github.com/pharo-project/pharo/assets/23179762/7a98db75-c384-4867-9565-96020a1e081d)

**Comment by jecisc** [comment]
This was fixed by @BastouP411. Thank you!
