### ISSUE TITLE
Collection>>allSatisfy:  when collection is empty should return false?

### ISSUE THREAD

**Issue by liangbing64** [guillep/pharo-core#14340]
allSatisfy: aBlock
	"Evaluate aBlock with the elements of the receiver.
	If aBlock returns false for any element return false.
	Otherwise return true."
	"#(1 2) allSatisfy: [ :each | each even ] >>> false"
	"#(2 4) allSatisfy: [ :each | each even ] >>> true"

 ++++	self ifEmpty: [ ^false ].
 	self do: [:each | (aBlock value: each) ifFalse: [^ false]].
	^ true

**Comment by guillep** [comment]
Hi @liangbing64,

Thanks for the issue, but the current implementation is correct from a logic point of view.
In your case, it is *true* that all elements of the empty collection are even.
Because since there are no elements, none of them is odd.

*allSatisfy:* is in the spirit of known collection/list operations in [Python](https://docs.python.org/3/library/functions.html#all), [haskell](http://zvon.org/other/haskell/Outputprelude/all_f.html) and others.
