### ISSUE TITLE
Extract temporary variable doesn't correctly position temp definition

### ISSUE THREAD

**Issue by balsa-sarenac** [guillep/pharo-core#14611]
**Bug description**
When a class has multiple occurrences of a expression that you're extracting to a temp, new temp definition is added just above the expression you selected to inline, instead of the first occurrence.

**To Reproduce**
1. Go to 'RBRemoveMethodParametrizedTest>>#testModelRecursiveMethodThatIsNotReferencedFromOtherMethods'
2. Select on ''someMethodThatIsNotReferenced' asSymbol' 2nd or 3rd occurrence
3. Invoke Extract temp (I've created temp called `selector`)
4. Rule now complains that `selector` might be read before written

**Expected behavior**
Temp is written before first read.

**Additional information**
This is before:
```smalltalk
testModelRecursiveMethodThatIsNotReferencedFromOtherMethods

	| class otherClass |
	class := model classNamed: #Object.
	class
		compile: 'someMethodThatIsNotReferenced ^2'
		classified: #( #accessing ).
	self assert:
		(class definesMethod: 'someMethodThatIsNotReferenced' asSymbol).
	otherClass := model metaclassNamed: self class superclass name.
	otherClass
		compile:
		'someMethodThatIsNotReferenced ^3 someMethodThatIsNotReferenced'
		classified: #( #accessing ).
	model removeClassNamed: self class name.

	self executeRefactorings:
		(self createRefactoringWithModel: model andArguments: {
				 'someMethodThatIsNotReferenced' asSymbol.
				 #Object }).
	self deny:
		(class definesMethod: 'someMethodThatIsNotReferenced' asSymbol)
```

this is after:

```smalltalk
testModelRecursiveMethodThatIsNotReferencedFromOtherMethods

	| class otherClass selector |
	class := model classNamed: #Object.
	class
		compile: 'someMethodThatIsNotReferenced ^2'
		classified: #( #accessing ).
	self assert: (class definesMethod: selector).
	otherClass := model metaclassNamed: self class superclass name.
	otherClass
		compile:
		'someMethodThatIsNotReferenced ^3 someMethodThatIsNotReferenced'
		classified: #( #accessing ).
	model removeClassNamed: self class name.
	selector := 'someMethodThatIsNotReferenced' asSymbol.

	self executeRefactorings:
		(self createRefactoringWithModel: model andArguments: {
				 selector.
				 #Object }).
	self deny: (class definesMethod: selector)
```

See that `selector` is used on line ~7 and it is initialised on line ~14.

**Comment by daniels220** [comment]
One further complication: What if the first occurrence of the extracted expression is within a child scope?

```
aCollection do: [:each | each doSomethingWith: self foo].
someObject doSomethingWith: self foo
```

If we select the second `self foo` and extract, we can't assign to the temp immediately before the first occurrence. Either it'll get uselessly reassigned every time through the loop, or, the way the code is written, the temp might get declared within the loop, leading to a compile failure at the point we _originally selected_, which is especially egregious.

I...guess it should work in basically all cases to walk up the tree from the first occurrence, finding the statement node that is within the same scope as the originally-selected expression, and assign immediately before _that_ statement, which would produce:

```
|theFoo|
theFoo := self foo.
aCollection do: [:each | each doSomethingWith: theFoo].
anObject doSomethingWith: theFoo.
```

Can you think of a case where this would produce strange behavior? If not, I can implement it when I have time—probably not real soon, because I'm busy, but I know exactly what to do.

**Comment by balsa-sarenac** [comment]
Good point, the proposed solution seems nice. I can't think of any other edge case that this solution will not satisfy.
We should include test for this, since it's a potentially nasty bug.
