### ISSUE TITLE
Accessing beyond valid index of LargeInteger should raise SubscriptOutOfBounds

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#14624]
**Bug description**

When accessing beyond the possible index of a large integer, the access should signal a SubscriptOutOfBounds exception, but currently responds 0.

For this reason, some accesses that should fail may go unnoticed.

**To Reproduce**

Create a LargeInteger and access beyond its byte count as follows:

```smalltalk
43092843028439028430284932843902489320489320532054023 byteAt: 100000000000000000000000000000000000000 "=> 0" 
```

**Expected behavior**

Raise a SubscriptOutOfBounds when accessing beyond valid index elements in a large integer.

**Version information:**

 - Pharo Version: 12 (and possibly all previous ones too)

**Comment by svenvc** [comment]
Well, the answer is correct. All bytes beyond the last one are zero.

BTW, it seems as if size gives you the number of bytes used, if that is what you are looking for.

**Comment by hernanmd** [comment]
> Well, the answer is correct. All bytes beyond the last one are zero.

It seems that isn't, as it is explicitly mentioned in the method comment : "Fail if the argument..."

```smalltalk
byteAt: index
	"Primitive. Answer the value of an indexable field in the receiver.   
LargePositiveInteger uses bytes of base two number, and each is a 'digit' base 256.  
Fail if the argument (the index) is not an Integer or is out of bounds. Essential.  
See Object documentation whatIsAPrimitive."

	<primitive: 60>
	self bytesCount < index
		ifTrue: [^0]
		ifFalse: [^super at: index]
```

And the method is even calling super to a different message.

Also bytesCount refers to the indexable fields:

```smalltalk
bytesCount
	"Primitive. Answer the number of indexable fields in the receiver. This
	value is the same as the largest legal subscript. Essential. See Object
	documentation whatIsAPrimitive."
```

It seems that we cannot safely assume that all bytes beyond the last one should be zero.

**Comment by svenvc** [comment]
I did not see the comment.

Please give an example of an integer where there is a byte beyond the last one that is not zero ;-)

**Comment by hernanmd** [comment]
> I did not see the comment.
> 
> Please give an example of an integer where there is a byte beyond the last one that is not zero ;-)

Let's clarify so we ensure we're talking about the same.

Assuming a little-endian system, the last byte is the rightmost byte (the LSB is on the right), and the MSB is on the left. So a binary representation where the byte beyond the last one is not zero would be 16777216 which is `00000001 00000000 00000000 00000000`

In a big-endian system, the last byte would indeed be the leftmost byte, so the example would be `00000000 00000000 00000000 00000001`. Here the integer is 1, but the byte beyond the last one (the rightmost byte) is not zero; it contains the value 1.

So if we consider an 8-byte (64-bit) little-endian integer 1152921504606846977 in decimal, which is `1000000000000000000000000000000000000000000000000000000000001`, the least significant byte (LSB) is on the right, the byte beyond the last one (the leftmost byte) is not all zero.

Is that what you meant?

**Comment by svenvc** [comment]
I try again to explain myself, but I probably am also not understanding you or your question.

LargeIntegers are stored as bytes, but that and the endianness are an implementation detail that is sometimes important but not really. 

What the byteAt: access offers is equivalent to looking at the number in base 256. In that way, it is not different than other bases.

In decimal notation, 123 = (1 * 10 ^ 2) + (2 * 10 ^ 1) + (3 * 10 ^ 0) and since Smalltalk is 1-based, the first digit (least significant) is 3, the second 2 and the third 1 with their positions being 1, 2 and 3.

https://en.wikipedia.org/wiki/Positional_notation#Exponentiation

Now, asking for the decimal digit at position 4 and further is always 0, since 123 = 0123 = 00123 = 000...0123 all further digits are 0.

Let's look at your number, byte by byte, or in base 256

```
1152921504606846977 in: [ :n |
	(1 to: n bytesCount) collect: [ :i | 
		i -> (n byteAt: i) ] ].

{1->1. 2->0. 3->0. 4->0. 5->0. 6->0. 7->0. 8->16}
```

You can see this in the raw view of the inspector, because the implementation is byte based.

Anything beyond 8 is always 0, let's count 8 more:

```
1152921504606846977 in: [ :n |
	(1 to: n bytesCount + 8) collect: [ :i | 
		i -> (n byteAt: i) ] ].

{1->1. 2->0. 3->0. 4->0. 5->0. 6->0. 7->0. 8->16. 9->0. 10->0. 11->0. 12->0.
```

My original point was that returning zero is in essence correct. At least that is how I understand it.

Negative and zero indexes do give an error. 

What practical thing are you trying to accomplish ? 

When doing IO or FFI, endianness might become important, just reversing the bytes is often enough.

You could also have a look at ZnBufferedReadStream>>#nextIntegerOfSize:signed:bigEndian: and ZnBufferedWriteStream>>#nextIntegerOfSize:signed:bigEndian:put: for some general code in the same domain.

This code uses the fact the issue that you have as a feature: consider how 123 would be written as an 8 byte integer, 0 gets written for all but the first or last byte.


<blockquote><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Positional_notation_glossary-en.svg/640px-Positional_notation_glossary-en.svg.png" width="48" align="right"><div><strong><a href="https://en.wikipedia.org/wiki/Positional_notation#Exponentiation">Positional notation - Wikipedia</a></strong></div></blockquote>

**Comment by hernanmd** [comment]
I understand that your reasoning aligns well with the mathematical positional notation (and so is widely adopted), however, having out-of-bounds accesses return zero might mask issues (zero values may not raise immediate red flags), for example while trying to ensure not accessing memory outside the allocated space, or writing test cases to verify the behavior of code under different conditions, let's say for boundary condition tests (this is my particular case).

For me it is strange as it may not immediately detect or prevent out-of-bounds access, but as you've mentioned, this trade-off is generally acceptable for most programmers, specially if they're not working in domains where precise bounds checking is crucial (e.g., cryptographic applications) to ensure data integrity and security.

So having explicit out-of-bounds exceptions can be nice, because it allows to receive immediate feedback when access goes out of bounds. What I will do is to override it in my use case, to provide custom strict bounds checking so we don't clash with existing behavior in other packages (as this could affect implementation in Zinc packages, or other ones).

**Comment by svenvc** [comment]
OK.

But I really want to understand where and how this is a practical problem for you, as I might be able to help.

I have written many binary protocols reading/writing from/to byte streams or byte arrays. Of course bounds checking is important and failures should be reported.

Once you have an Integer as object, I see no real problem. And there is always bytesCount to know precisely how many byte are present.

**Comment by hernanmd** [comment]
> OK.
> 
> But I really want to understand where and how this is a practical problem for you, as I might be able to help.
> 

Sure, you may have a look to this [PR](https://github.com/pharo-project/pharo/pull/14616), it would be nice to have some feedback
