### ISSUE TITLE
FLEnvironmentProtectingWrapper cause the system to be inconsistent

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#14634]
FLSerializationTest test case hierarchy is updating the environment used for the tests to use a FLEnvironmentProtectingWrapper. 

I guess that the goal of this class is to not impact the global system with the code generated by the tests, but I am not sure since this is not commented.

But this is problematic because the generated code is installed in the global environment, but then not all actions end up impacting this environment and this causes inconsistances. An example is with the class categories. A class has a category and the system organizer keep track of which class is in which category also. The two should always be in sync. The problem is that this is not the case in Fuel tests and this is currently managed by a hack in `Class>>#category`. But we want to go away from categories and this hack cannot be ported like this.

I tried to run the test by removing this wrapper in order to see how things are going, but I see that some tests are now failing. And I guess one part of the problem is that the SystemDictionary evolved and Fuel did not followed the changes, but the tests never went to that code since the wrapper was intercepting the actions.

@theseion do you have any idea of what would be the best course of action to keep fuel tests working and do not have those inconsistances in the system?

**Comment by theseion** [comment]
IMO, tests that create and delete classes and categories should not interact with the system organisation. I've always had issues because of anonymous classes, obsolete classes, left over empty categories, left over globals, etc. That's the reason I wrote `FLEnvironmentProtectingWrapper`. I agree with you that it's not great but there was no other option for me than to subclass and override.

I think the best approach would be to design the API in such a way that tests can opt out of affecting changes. Maybe something similar to `#doSilentlyWhile:`. Maybe this should be part of the test class factory.

`#testLookUpInGlobalsMustBeGlobal` tests that the environment for Fuel is used to lookup globals and this environment can be different from `Smalltalk globals`. This is the only test that fails for me when I replace `FLEnvironmentProtectingWrapper for: Smalltalk globals` with `Smalltalk globals`. This test requires a view on the system globals as it will otherwise try to serialize the entire system. The reason for this is that when the value `Object new` is serialized, Fuel checks to see whether its  class (`Object`) is a global. If it is not, it will be serialized, and this is the case when the environment does not provide a view of the system globals, e.g., when simply using `IdentityDictionary new` as the environment. The reason why the wrapper is a great here is that I don't need to clean up the global. To achieve the same effect, we could add the following as the first line of the test:
```smalltalk
self testingEnvironment: (SystemDictionary newFrom: Smalltalk globals).
```

**Comment by jecisc** [comment]
I am currently working on having independent environments in the image with independent system organizers and independant system announcers for this kind of cases. But all the global stuff is so deeply rooted in the system that it takes time.

But what you are saying is weird because I had at least 7 or 8 failing tests when I did the same change as you

**Comment by theseion** [comment]
You're right, that happens when I run the test Suite multiple times. That's because the first run will change stuff in the system globals, so that the initial state of the tests is no longer correct. I'll prepare a version without the wrapper.

**Comment by jecisc** [comment]
Thank you Max! :)
I was planing to take a look but I have multiple things to finish before and this will be of a great help since it'll allow us to remove a hack in the kernel that prevents me from fixing some bugs.

**Comment by theseion** [comment]
Here you go: https://github.com/theseion/Fuel/commit/f781681378005942dbb6bf146a75452736f66604. This commit is on the `Pharo12` branch.

**Comment by jecisc** [comment]
Fixed. Thanks Max
