### ISSUE TITLE
Package undefined confused calypso

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#14935]
I was defining class when prompted and apparently the package is not correct but 
here we have a problem.

<img width="491" alt="Capture 2023-10-09 at 09 36 37" src="https://github.com/pharo-project/pharo/assets/432549/a4e628ce-044c-4a4c-a888-587bc8387c60">

**Comment by jecisc** [comment]
What was the package given to be able to reproduce?

**Comment by Ducasse** [comment]
I do not know it was when prompted when you compile a method with a reference to an undefined variable.
It is buggy for sure.

**Comment by hernanmd** [comment]
I tried to reproduce the issue but couldn't. 

https://github.com/pharo-project/pharo/assets/4825959/2782b3cf-5aac-4b31-8949-dc6e3340e649

If I leave the package name string empty, I get "Error: Cannot have empty or nil package name." and method is not compiled.

Probably fixed with the new Package classes?

**Comment by Ducasse** [comment]
Yes this is probably fixed.
