### ISSUE TITLE
[CI] random failure: testPackageOfRemovedTrait

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#14958]
**Bug description**
T2TraitWithPackagesTest>>testPackageOfRemovedTrait is failing sometimes, quite randomly

```
Error

Got an UndefinedPackage(_UnpackagedPackage) instead of a RPackage(TestPackage).
Stacktrace

TestFailure
Got an UndefinedPackage(_UnpackagedPackage) instead of a RPackage(TestPackage).
T2TraitWithPackagesTest(TestAsserter)>>assert:description:resumable:
T2TraitWithPackagesTest(TestAsserter)>>assert:description:
T2TraitWithPackagesTest(TestAsserter)>>assert:equals:
T2TraitWithPackagesTest>>testPackageOfRemovedTrait
T2TraitWithPackagesTest(TestCase)>>performTest
```

**Comment by jecisc** [comment]
The origin of the problem comes from some classes that are not well packaged. 

This problem of packaging happens because during the building of a class, it happens that we update the class. Then we are updating a class that is not fully initialized and it messes things up.

This update happens with #addSlot: in PropertySlot>>#installingIn:

I am not really sure how to fix that for now :(
