### ISSUE TITLE
Slow finalization for pinned objects

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15091]
**Bug description**
Starting with the Pharo 12 builds having this PR integrated [1] (I tested builds 720 as pre-integration and 730 as post-integration), we have troubles with the slow GC of our application objects. In the end, it is garbage collected, but it requires 65 GC cycles to do so.

[1] https://github.com/pharo-project/pharo/pull/14068

This is the typical leak structure:

![Pharo_iDeuS8gZgv](https://github.com/pharo-project/pharo/assets/572494/7c0cfe62-5fff-4ea1-9b37-5e39592cfa0f)

I have discovered it is related to objects pinned in memory which ExternalAdresses usually are.

**To Reproduce**
1. Create your own `ValueHolder` subclass

```smalltalk
ValueHolder << #MyValueHolder
	slots: {};
	tag: 'Base';
	package: 'NewValueHolder-Core'
```

2. open Transcript, then open Playground and fill it with this code:
```smalltalk
"part 1"
| col oldO size |
col := OrderedCollection new.
oldO := nil.
4 timesRepeat: [ 
	| o |
	o := MyValueHolder new contents: oldO.
	oldO := o.
	o pinInMemory.
	o finalizationRegistry add: o.
	col add: o.
	 ].
Smalltalk garbageCollect.

"part 2"
5 timesRepeat: [ 
	Smalltalk garbageCollect.
	size := MyValueHolder allInstances size.
	size traceCr.
]
```
3. Do-It part 1, then Do-It part 2 (it cannot be executed as one)
4. In Transcript, you will see: 
```
4
3
2
1
0
```
5. Now, try to comment out the line `o pinInMemory` and run part 1 and part 2 again. The value holders are GCed immediately

You may try to run it (with pinning) in the older builds before 720; there the GC is immediate, too.

**Expected behavior**
Objects are not GCed one by one.

**Comment by guillep** [comment]
hi @pavel-krivanek what vm version are you using?

**Comment by pavel-krivanek** [comment]
it is the latest stable one the launcher gives me for Windows: 
CoInterpreter VMMaker-tonel.1 uuid: 80dee452-c9c4-0d00-8761-a2e50c0e42f2 Oct 23 2023
StackToRegisterMappingCogit VMMaker-tonel.1 uuid: 80dee452-c9c4-0d00-8761-a2e50c0e42f2 Oct 23 2023
v10.0.8 - Commit: b323c5fb - Date: 2023-10-20 16:02:07 -0400

**Comment by guillep** [comment]
Thanks @pavel-krivanek,

We have checked this, and here is a short analysis.
First, this is a known behavior of current implementation: as soon as two ephemerons have related keys (either the same key or different keys but linked), the number of GC cycles they take to collect is not defined (and not stable).

See for example the case you shared. I extracted the registration for finalization on purpose:

```smalltalk
"part 1"
| col oldO size |
col := OrderedCollection new.
oldO := nil.
40 timesRepeat: [ 
    | o |
    o := MyValueHolder new contents: oldO.
    oldO := o.
    o pinInMemory.
    col add: o.
].
col do: [ :o | o finalizationRegistry add: o ].
Smalltalk garbageCollect.

"part 2"
50 timesRepeat: [ 
    Smalltalk garbageCollect.
    size := MyValueHolder allInstances size.
    size traceCr.
]
```

Interestingly, if we add a `reversed` when registering for finalization, it works as you expect!

```smalltalk
"part 1"
| col oldO size |
col := OrderedCollection new.
oldO := nil.
40 timesRepeat: [ 
    | o |
    o := MyValueHolder new contents: oldO.
    oldO := o.
    o pinInMemory.
    col add: o.
].
col reversed do: [ :o | o finalizationRegistry add: o ].
Smalltalk garbageCollect.

"part 2"
50 timesRepeat: [ 
    Smalltalk garbageCollect.
    size := MyValueHolder allInstances size.
    size traceCr.
]
```

Now, what this means is that the order in which objects are allocated, traversed, and tenured has a lot of impact on the order of finalization. Moreover, this behavior happens both in the scavenge and the full GC. The difference is that the scavenge happens more often and is faster (doing a print-it already triggers a scavenge generally so it affects the observed results).

So, I see three different options here, but not a quick patch to do.
1. we can try enhancing the ephemeron detection/firing algorithms in the GC, but this would require a re-writing of lots of the code and a large testing effort.
2. alternatively we can try putting back the identity dictionary as a registry, but it does not mean that this will avoid the issue, it will just make it appear in other scenarios with different graph structure. This can also re-introduce the performance issues that we were seeing in #14068...
3. another complementary alternative(?) is to fix some bad usages of finalization. FFI abuses auto-release, should it?

I believe in the long term we want a compromise between the three of them...

**Comment by pavel-krivanek** [comment]
Thank you!

Can it be that the FFI is actually a victim here? It registers a lot of external addresses but I see no way they may be linked. However, we have this:
```smalltalk
FinalizationRegistry default keys size = FinalizationRegistry default keys asIdentitySet size.
``` 
which returns `false`. The multiple keys are of Breakpoint, ClassAnnotationRegistry, ExecutionCounter, IceSystemEventListener, MCWorkingCopy, ReRuleManager, ChangeSet, ChangeLog, ClyInheritanceAnalysisEnvironmentPlugin, ClyMethodCodeEditorToolMorph, RPackageOrganizer and EpMonitor in my image

**Comment by pavel-krivanek** [comment]
So I did an experiment - during registration of an object to the finalization registry, I check if it is already there and skip the registration if yes. I had to clean the finalization registry before. But it brought no improvement.
Then I realized that we actually do not use only one finalization registry, the `FFIExternalResourceManager` has its own (`FFIExternalResourceManager uniqueInstance instVarNamed: #registry`). So I tried to use this registry for external addresses instead of the default finalization registry. And it IMHO actually shows the issue!

The `FFIExternalResourceManager` finalization registry registers the `TFCallback`s that indirectly link to  `ExternalAddress`s that are also registered for finalization.

![image](https://github.com/pharo-project/pharo/assets/572494/1d882434-7d64-437e-ae49-fba3d003ad67)

So this way, we have two keys linked together.

What I do not understand is, why, before conversion of the registry to the linked list, this was not an issue. Please, can you describe it to us?

**Comment by guillep** [comment]
Actually, the problem does not appear when two ephemerons have the same key, but when two keys depend on each other (as in your example with a linked list).

In your larger example, a callback is registered for finalization, and the callback holds on to MANY objects:

<img width="544" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/268af9b6-cdb5-41f7-ac3d-85e645044e02">

As soon as one of them is also registered for finalization, finalization could be delayed.
Imagine the case A -> B where both A and B are registered for finalization.
- If the ephemeron for A is found first, it will mark A and (transitively) mark B, thus making the ephemeron for B not finalize (in this round).
- If the ephemeron for B is found first, it will mark B but not A, thus it WILL finalize the ephemeron for A in the same round.

I'll try to put some hours into this today. The idea: use a normal linked list with some tweaks.
The main difference between pre- and post- https://github.com/pharo-project/pharo/pull/14068 is that previously ephemerons could be discovered in a single round, while now they are discovered in many rounds (within the same GC). This is:
 - the GC runs in a loop until it converges
 - before, the first memory scan discovered all ephemerons in the registry because it holds strong pointers to all of them
 - after, the first memory scan discovers *only* the ephemerons with a non-marked key from the head of the registry (the first strong pointer)
 - then, it iterates the ephemerons discovered, which in turn may discover new ephemerons
 - loop :)

In ascii art it looks like

Before (e are ephemerons, k are keys, ==> are strong references,  --> are ephemeral references)

```
Registry
   |====>e1---->k1
   |====>e2---->k1
```

After  (e are ephemerons, k are keys, ==> are strong references,  --> are ephemeral references)
```
Registry
   |====>e1---->k1
         |====>e2---->k1
```

So the simple idea that could be implementable now is to change the structure using a normal linked list.
This way the ephemeron could have a backpointer to its link node for O(1) removal, and still we have a strong path to all ephemerons in the registry to find them in a single pass.
(l are links, e are ephemerons, k are keys, ==> are strong references,  --> are ephemeral references)

```
Registry
   |====> l1 <====> e1---->k1
           |====> l2 <====> e2---->k1
```

I'll come back :)

**Comment by guillep** [comment]
> Can it be that the FFI is actually a victim here?

Haha, no, FFI is a very bad citizen :).
We should improve it because it stresses the architecture a lot in cases that should not.

This does not mean we could not improve, but at some point, improving the usage to be responsible is also good :)
