### ISSUE TITLE
[CI] PRs were merged with failing tests

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#15157]
**Bug description**

Yesterday PRs were merged even though they had failing tests

- Update dependencies to Roassal and Array2D #15148
- Deprecate String>>asDate #15152

Honestly, I would revert them. We just should *never ever* merge PRs that have failing tests !

**Comment by MarcusDenker** [comment]
Roassal is fixed, I will open a dedicated issue for the other

**Comment by guillep** [comment]
> Honestly, I would revert them. We just should _never ever_ merge PRs that have failing tests !

I don't understand why so much fuzz on it. This should be a no-brainer. We should revert it + merge the revert immediately, and re-create a PR with the original changes (by re-reverting it but not integrating it).
Otherwise, reverting it in the future is more problematic because of conflicts, and github not letting us do it automatically.

Making mistakes is part of the job, we should acknowledge this, and do our best.
Re-opening the PR gives the original author the time to fix the PR without breaking everything :).

Moreover, there are no hard feelings. And there should not be, because this should just be a policy.
Broken => revert + reopen.
Doing it "case-per-case" is time-consuming and leads to unfruitful discussions like this one.

For example, I see now there should be a dedicated issue but it's not linked. And I'm losing extra time on it.

**Comment by Ducasse** [comment]
I'm not making a fuzz and I did not say that we should not merge with broken tests.
And when I merged I did not see the broken tests :) and it is not a problem :)

BWT "we should be able to merge PRs with BROKEN tests". I do not like dogma. 
My experience is that is not fun to carry a long stream of changes (like the work on refactoring
in a super long branch). Alpha means that we can have instability.

I suggested to revert because **I**  just did not have the time to fix the issue and trying to flush as many changes as possible to get rid of the instability introduced by the category removal effort.

**Comment by jecisc** [comment]
I wanted to revert it but I didn't had the rights for this :( 

Sorry if it could seems like a fuss, it was more giving the information (and they were given multiple times).

In that case, except the failings tests, I think a problem is that often some changes done in the sprint are not well followed up (because people just go back to their work that has the priority) and if work is still needed we either need to wait for the next sprint or nothing happens. And then it's someone who did not had this on his todo list that needs to finish the task. 

That's why for example I asked not to merge a PR of Sebastian deprecating some stuff that is still used directly. Even if the deprecations are not blocking, then it floods the CI and we might miss other issues.

**Comment by Ducasse** [comment]
I thought I checked the tests because I normally check them all and read all the code before integrating.
But there is no stress. I think that we are doing a lot of good changes. And the fact that Pharo is improving is by itself super cool.
