### ISSUE TITLE
Package ReleaseTests shoudl be "Release-Tests"

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#15257]
Test package naming follow the "...-Tests" convention. We should follow it also for the package with the release tests
as this would be consistent and also fix a lint issue displayed

![image](https://github.com/pharo-project/pharo/assets/5980033/8094297a-643c-43a3-b0ac-aa3c1caf0df8)

**Comment by jecisc** [comment]
Multiple tries have already been made about this and it is currently not possible because updating the name change the order of test execution and the release test currently fails if they are not executed first. 

This is the reason I'm trying to get this PR green but it is hard to do: https://github.com/pharo-project/pharo/pull/13349

**Comment by astares** [comment]
@jecisc  Mmmm ... thanks for letting me know. So I will close the PR for now.
