### ISSUE TITLE
Could browsing a mistyped class not show a debugger

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15437]
- type `StartUpUIManager` in a playground or in a calypso pane and press cmd-B
- We get a debugger with a bad message UndeclaredVariableRead...

Solution catch the error. Showing debuggers all the time is not nice.

**Comment by Ducasse** [comment]
```
evaluateDoIt: doItMethod

	^ [ self receiver withArgs: #() executeMethod: doItMethod] 
			on: UndeclaredVariableRead
		 	do: [ self receiver ]
```

**Comment by MarcusDenker** [comment]
This is again the problem that "Browse it" is "Doit and Browse class", while all users think that it means "Browse the Defintion of this".

As it is "DoIt and browse class", what should happen if we evaluate an expression that is a non-existing variable ? 
Browse nil? Raise an Error? Just do nothing?

**Comment by Ducasse** [comment]
At least it should not press a debugger to the USER. 
We should start to grow up and stop this debugger plague and design the system.

**Comment by MarcusDenker** [comment]
Note from the closed PR:

I think an idea can be to have an error handling not in evaluateDoIt:, but in the code that is implementing the "browse it". 

We do not want to silence all errors for evaluation in general, as that would lead to very strange effects.

Senders-of and implementors-of can be much more clever in this case as they do not evaluate code but can statically analyse and provide something that might make sense. (they try to get some usable selector from the selected text).

Browse-it with "eval this, then browse class of result" cannot do that, but we can guard for errors better.
The idea is that the error handling that we want here is different than for general execution of code.

Besides Undeclared, you could select code that is syntactically incorrect and do a "browse it", here we would want to then not raise an error, either. 

We should after then check if we want the same for "do-it" and "inspect-it". Strangely people seem to be much more ok with those raising errors when they ask for  code  to be executed that is wrong. I think this is because "browse it' feels more like "code navigation" than "code execution", but maybe the same improvements are nice here, too.

**Comment by MarcusDenker** [comment]
We could for now do change RubSmalltalkEditor>>#evaluate:andDo:, this is only used for this case (do-it, inspect and browse).

```
evaluate: aStream andDo: aBlock
	"Treat the current selection as an expression; evaluate it and invoke aBlock with the result."
	| result rcvr ctxt |
	(self model respondsTo: #doItReceiver)
		ifTrue: [ rcvr := self model doItReceiver.
				ctxt := self model doItContext]
		ifFalse: [ rcvr := ctxt := nil].
		
	"to improve: we need better reporting of errors, to revisit when unifying with Spec"
	result := rcvr class compiler
			source: aStream;
			requestor: self;
			context: ctxt;
			receiver: rcvr;
			permitFaulty: false;
			evaluate.

	^ aBlock value: result
```


This makes it work more like before: you get the code reparator for Undeclared, syntax errors are shown via an inform: and do nothing.

We should revisit this when unifying with Spec (which shows the code reparator, too, but uses the pop-over style error reporting for syntax errors)

**Comment by Ducasse** [comment]
Agreed!
