### ISSUE TITLE
Named classes built for test purpose reamain in Undeclated dictionary after cleanup

### ISSUE THREAD

**Issue by bouraqadi** [guillep/pharo-core#15552]
**Bug description**
Providing a name for a class built by a  ClassFactoryForTestCase adds an undeclared variable upon cleanup

**To Reproduce**
In a playground under Pharo 12
```
Undeclared keys includes: #A. "Good result -> false"
factory := ClassFactoryForTestCase new.
class := factory make: [ : builder | builder name: #A  ].
factory cleanUp.
Undeclared keys includes: #A. "Wrong result -> true. Should be false"
(Undeclared at: #X) == class "Wrong result -> true. Should be false. The undeclared value should be nil"
```

**Comment by bouraqadi** [comment]
@MarcusDenker

**Comment by MarcusDenker** [comment]
Thanks!

The current principle (this is how it is done since ST80) is that the Undeclared dict is *only* cleaned up when cleaning explicitly using #cleanOutUndeclared .

One problem with  #cleanOutUndeclared is that afterwards, if there is still an Undeclared in a method that is not installed (e.g. still on the stack), the Undeclared repair can never fix it... so we can not do it "just in case". (and it is slow: it iterates over all methods in the system).

For the ClassFactoryForTestCase we can do better: as we know that these binding in Undeclared where added by us and there are no other users than the test methods that are already removed, we can remove just these entries. 

I will do a PR for that.

Another, related problem we have with Undeclared is that we keep the value when we move to Undeclared when deleting a class, I think this is not good. Maybe that is what lead to the probems in your case?

We should nil out the value when a class remove adds an Undeclared, but I will do that as another step.
(For usages of ClassFactoryForTestCase, removing the binding from Undeclared on tearDown solves that problem, too).
