### ISSUE TITLE
Interactive mode should be the default one

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#15576]
Now, the `--interactive` command line argument makes Pharo's startup logic quite confusing. For example:
You run just the VM executable, and the VM adds the image name and `--interactive` as a default.
You run just the VM executable with the image name, and the VM starts the image in non-interactive mode.

IMHO, we should consider the alternative approach where the command line handler that starts the UI should by default, run in the interactive mode, and only if the non-interactive mode is requested, do not do that. It may also consider to run in non-interactive mode by default if another command line handler commands are specified. 

This way, we may skip the interactive/non-interactive logic from the VM and rely only on the image processing.

What do you think?

**Comment by estebanlm** [comment]
there is already a vm that does that... and you have the pharo-ui command line that fixes that for you.

also, I disagree :P

**Comment by guillep** [comment]
The VM can be built in two modes: default interactive and default non interactive.
The only difference between both is whether they send the `--interactive` flag to the image or not at the startup.
Actually, we made the new VM at some point to never set the `--interactive` flag, but we had to add it as backward compatibility because otherwise we would have had to update the launcher (that is --interactive by default) also and make a ripple of releases.

Personally, I would make everything headless, and make a command line handler that starts the UI.

**Comment by pavel-krivanek** [comment]
Thanks! Then, before I close this, how to set the interactive/non-interactive defaults during the VM compilation?

**Comment by guillep** [comment]
Have a look at 

https://github.com/pharo-project/pharo-vm/blob/de760673b5f108d32576b47f4bbdfd3b230520b0/CMakeLists.txt#L30

CMake arguments are set with `-D[ARG]=[VALUE]`

**Comment by pavel-krivanek** [comment]
Super, thank you, closing
