### ISSUE TITLE
Confused iceberg

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15782]
I renamed a class and iceberg showed me two times in two different packages the class renamed and added. 
It renamed SycRenameMessage2Command into SycRenameMessageCommand. 

So this may be due to categories, tags, packages.

**Comment by jecisc** [comment]
There is no confusion in Iceberg.

Some changes are in SystemCommands-MessageCommands because it is the package that contains the class. And some changes are in Calypso-SystemTools-Core because this package adds extension methods. So Iceberg needs to update the name of the class for the extension methods. 

This seems perfectly normal to me. 

<img width="425" alt="image" src="https://github.com/pharo-project/pharo/assets/9519971/79485332-55c1-487f-a222-37bfc430e883">

If you check, the methods in both packages are different.

**Comment by Ducasse** [comment]
Tx cyril. It was too late and in the middle of a lot of RB changes.
