### ISSUE TITLE
Uncategorized methods

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15847]
the following classes have uncategorized methods: an OrderedCollection(SycMockClassForHierarhicalSenderA SycMockClassForHierarhicalSenderB SycMockClassForHierarhicalSenderC)

**Comment by hernanmd** [comment]
That belongs to a previous commit, I checked now and the class had a typo so it is `SycMockClassForHierarchicalSenderA` instead of `SycMockClassForHierarhicalSenderA`:

<img width="804" alt="Screenshot 2023-12-29 at 15 57 57" src="https://github.com/pharo-project/pharo/assets/4825959/4d2875c7-ee03-47cb-84cf-a6d419ab91ed">

<img width="813" alt="Screenshot 2023-12-29 at 15 58 09" src="https://github.com/pharo-project/pharo/assets/4825959/3dd3c9fd-6c60-4f31-8529-5eecc78797bb">

<img width="783" alt="Screenshot 2023-12-29 at 15 58 23" src="https://github.com/pharo-project/pharo/assets/4825959/d81d808b-94fb-4229-b4b3-e0b99f9f4d6a">


So the issue can be safely closed.

**Comment by Ducasse** [comment]
Yes I fixed them.

**Comment by hernanmd** [comment]
> Yes I fixed them.

Thanks!
