### ISSUE TITLE
Performing a reference to Display.... never comes back

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15856]
Performing a reference to Display from the Playground never comes back:(

Probably the best way to make sure that we will not cure it :)

![Capture 2023-12-27 at 15 51 52](https://github.com/pharo-project/pharo/assets/432549/2085b83d-4494-4e11-a341-9ac8483cfd77)

**Comment by Ducasse** [comment]
Performing senders of Display bring a debugger.

![Capture 2023-12-27 at 15 53 45](https://github.com/pharo-project/pharo/assets/432549/3af8eca1-a526-43e5-8fb1-199d378f6dc4)

**Comment by Ducasse** [comment]
Doing implementors neither :)
![Capture 2023-12-27 at 15 54 18](https://github.com/pharo-project/pharo/assets/432549/99db0543-2874-4a02-930c-d13c0fa7d9e5)

**Comment by Ducasse** [comment]
`SystemNavigation new allGlobalRefsOn: #Display` works :)

**Comment by Ducasse** [comment]
Now senders is working from a code pane in the inspector.

**Comment by hernanmd** [comment]
Probably should be closed.
I couldn't reproduce it since Display, DisplayScreen, etc. are not present anymore in the image.
The remaining Display objects have no references.

![Screenshot 2024-01-18 at 18 15 43](https://github.com/pharo-project/pharo/assets/4825959/4aa1d94c-a49a-411d-80c7-a89b2c0585c7)

**Comment by Ducasse** [comment]
I fixed it and we remove Display after :)
