### ISSUE TITLE
MessageListPresenter>>#removeMethods is sending unknown message 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15874]
It is probably due to https://github.com/pharo-project/pharo/pull/15868

**Comment by hernanmd** [comment]
Maybe it was part of UIManager cleaning, because this used a confirm dialog which is also missing now.
I would restore the method but remove the confirmation request from it.

<img width="998" alt="Screenshot 2023-12-31 at 18 18 19" src="https://github.com/pharo-project/pharo/assets/4825959/54318fab-092b-4aef-8f3d-0e17036baf21">

**Comment by Ducasse** [comment]
I do not think. I think it was never finished or broken long time ago and since we do not use it then it got unnoticed.

**Comment by Ducasse** [comment]
In any case SystemNavigation should not have pop up or UI code because it belongs to the low level.

**Comment by hernanmd** [comment]
Closing this because latest image has the UI dependency removed:

![Screenshot 2024-01-18 at 18 12 06](https://github.com/pharo-project/pharo/assets/4825959/2f305546-a2ed-454f-b466-e0a3a4f6584b)
