### ISSUE TITLE
Remove Teachable from SUnit Mooc.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15907]
I made the stupid mistake to think that a single tiny class was making more sense in Pharo while in P12 I remove tons of classes.
But this is ok I will juts remove Teachable and in fact my driver refactoring tests are not even using it.
Having multiple external projects is more manageable but I will let people manage it if they want. I do not want Teachable anymore in Pharo.

**Comment by Ducasse** [comment]
The funny thing is that I spend most of time working on making Pharo more modular but people can still give me lessons. 
Now I would really appreciate to see their modularity in action.

**Comment by Ducasse** [comment]
May be we should learn what is return on investment. A baseline, a project, dependency shit for a single class that is not even a complex and worth data structure. Perfect world but without me.

**Comment by astares** [comment]
Sorry - but this is not rational. The summary of your current response is: "if I'm not allowed to COPY it I will not use it". 
Please stay objective and not emotional. 

Is your decision really depending on the number of classes as a metric ignoring other peoples arguments? 
So what is the current "decision limit" / classes counter for COPYING vs. LOADING? 

Looks like one class is fine to copy.  Two would be acceptable as well? What about three? Do we load or copy them?
What if the teachable project evolves and we have an "UnderstoodWhatHasBeenTeached" announcement class
or a "NotAbleToBeTeached" exception class additionally in the future. Would three classes then count to reextract it again?

Ten classes can be copied but eleven requires loading? Do we have to save the memory of a single additional 
package object (or two with the tests)?

I hope you understand what I'm up to with such examples. Please do not solely think of your own requirements alone:
- when "Teachable" project is copied we fork and disrupt
- what about people who want to use it independent from any SUnitMock?
- one will get a dirty SUnit-Mock package when loading a newer version from orginal repo
- when we declare a clean dependency and load we are able to satisfy YOUR reguirement but also others
- ... 

Please also check what I wrote in: https://github.com/pharo-project/pharo/pull/15873 as this discussion 
is not about Teachable alone but more about how we deal with projects / compose the image.

**Comment by Ducasse** [comment]
I'm not emotional. 
I count: 4 methods -> not worth the pain to have a baseline, dependency to a new package, different project.
Period.

**Comment by astares** [comment]
To be precise it is 5 methods, not 4 (17 overall with tests, see #15873) 

I'm still interested to receive an answer: what is your exact recommendation to be taken as a decision base? 
Where you see the boundary / break even for the mentioned ROI? What number must be satisfied to cross 
the magical border between

A) ripping/copying code 
B) or following the modularized "loading" approach worth spending a dependency/baseline ?

How many classes are worth a dependency/baseline, what is the minimum number of methods required for it? 

You close your response with a period, so I will close mine (again) with points raised as a comparision:

INTEGRATION BY COPYING: 
Ripping and copying external class(es) into a separate existing Pharo package (here "SUnit-Mocks") has 
bad side effects:
- (+) is quick 
- (-) but dirty (you might lower your pain, but have more pain for others)
- (-) doubles maintenance effort (maintain code in Pharo and in external repo) and burns unnecessary cycles
- (-) forks and disrupts (code easily get out of synch over time)
- (-) kills and prevents independent usage ("fat" SUnit will always be required to use Teachable then, even when use case is outside a scope of testing)
- (-) creates dirty packages (when loading the external code)
- (-) does not scale in the large (we shift more responsibility to Pharo development team with additional maintenance of more and more code)
- (-) original maintainer(s) of such an "inhaled" package might have to give up their stewardship
- (-) is neither consistent nor clean 
- (-) is a bad practice and does only satisfy short term goal

INTEGRATION BY LOADING
- (+) allows to satisfy the goal of integration (assembling a standard or custom image) but also standalone usage 
- (+) allows original author(s)/maintainer(s) to continue to maintain
- (+) allows to load and use in other contexts
- (+) provides clearly defined dependencies and fosters modularization 
- (+) is the clean and consistent approach (independent if we speak about one, two or thousand classes)
- (+) enforces to think about proper layering, dependencies, loading order and help with the goal of modularity
- (-)  requires some invest for additional baseline (which for Teachable already existed), dependency management and repo (where the effort can be lowered by better tools)

I think conclusion is that we are only able to agree that we disagree,. So I closed #15913

**Comment by Ducasse** [comment]
Sorry but I cannot handle your fury.  You won. 
I will just define a class with 5 methods when I need it and I will put it deep hidden inside my package. 

And let me repeat it again
I'm not emotional.
I count: 4 methods -> not worth the pain to have a baseline, dependency to a new package, different project.
Period. 
I'm fighting with complex logic with large impact on users: refactoring engine and I do not have more energy. 
Now you can think that I'm an asshole or whatever you want in fact, just give me a break. You are too toxic for my energy
and I should take distance because you repeat often this super-aggressive behavior on the altar of the right thing to do. 
Go continue your sacrifices on justice. But not with me. I pull up the plug find another target.

S.

**Comment by Ducasse** [comment]
You see torsten you would have calmly told us that 
- you want to keep your project
- we can copy the class but rename it 
It was a middle ground that was acceptable and without all these flurry of messages.
But as I said next time I need a mock that is different from MockObject I will do it myself.

**Comment by astares** [comment]
Pharo is a passion for many of us (each with own individual goals and a different perspective) I assume we all want to strive for the better. This here is not about fury, not about anyone winning or any sacrifices on justice. We share the common goal to have a better Pharo with each step - and keep it maintainable despite our still small community.

We both know:

1. The included license is very clear and fully permits to use and integrate the code with enough freedom. 

2. If you (or community) decide(s) that **COPYING** (even **COPYING + RENAME**) the code of Teachable (or any other
   MIT licensed external project) is the way to go for any integration into the Pharo standard image it's totally valid, legal 
   and fine. 

3. MIT License clearly allows to COPY as well as to MODIFY. If integration is done that way anyone (including me) has 
    to accept that.
    
So from that side all would have been said, fixed and final (and fine for your initial goals) already with merge of PR #15873 
of the copied Teachable class + TeachableTest test class.  As a maintainer I've picked the license - so I should live with
the side effects and have shut up already.  

So why bother or still object and try to discuss and comment again? 

Bad side effects of the COPYING mode are mentioned above already. Additionally we also know about the capacity of the community. Basically it will leave 4 options to an external maintainer when his project should find its way into Pharo:

 a)  Ignore the Pharo integrated code and continue solely in the external repo 
         => external and in-image code would diverge and users would feel more trouble over time
               like incompatibilities or loading issues
 
 b) Give up the external project and repo, only maintain the integrated version inside standard Pharo image
          => would be a slap in the face of existing users who load it via dependencies (not getting fixes anymore) 
                and users who would like to continue to use Teachable standalone and independent 
                (outside of any standard Pharo image or SUnit). 
                They would need to do additional work on their own side then if they would require some fixes/enhacements
                leading to further disruption and forks. Also external repo need to be archived to not give the wrong 
                impression of being abondened work.
 
 c) Try to maintain both (external and internal) at the same time
          =>this doubles the work for the maintainer and he has to see that code stays in synch
               when new fixes get applied in standard Pharo image. Also pharo contributor might need to 
               inform or backport to original project. Will keep people busy on two sides.
 
 d) Keep a single (external) spot for maintenance 
         => this allow standard Pharo but also users with custom images and other requirements to load the 
                code as needed. Both parties would profit from enhancements and fixes. Teachable could
                still be used standalone. We would not see any dirty package side effects and prevent double effort

The first two options a) and b) would not be good for users, the maintainer and also not for Pharo itself. I think this 
is obvious due to the impact on user.

Option c) is possible (you see I cared about #15891) and yes, PR was easy, but still effort for this simple project. 
This is what for instance at the moment we also have to do with Zinc: to try to keep things in synch - and it's not a 
good model due to the additional cycles community has to spend.


The Option d) I offered with issue #15912 and PR #15913 you might call a sacrifice on the altar of the right now. Up to you.
But using a **LOADING** is what also Guille asked me to try (see his comment in #15891).
IMHO it allows for modularity and satisfying internal and external interest.

We do the same for Iceberg, Spec, NewTools, ... so why not with Teachable too? If you have concerns that the repo
is still under "github.com/astares" user account we can also organize a community controlled clone repo under
"github.com/pharo-integrations" for Pharo to stay independent but also allowing for easy synchs of fixes/enhancements/versions. 

In the long term maybe only https://git-scm.com/book/en/v2/Git-Tools-Submodules are the answer to all this.

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://git-scm.com/book/en/v2/Git-Tools-Submodules">Git - Submodules</a></strong></div></blockquote>
