### ISSUE TITLE
StRewriterApplyRuleOnSelectedClassesCommand deserves love

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#15927]
```
execute

	| dialogWindow changes |
	dialogWindow := self context scopeSelectorPresenter openDialog.
	dialogWindow okAction: [
		| ruleHolder |
		ruleHolder := StRewriterRuleHolder
			lhs: self context lhs
			rhs: self context rhs
			isForMethod: self context isRuleForMethod.

		changes := StRewriterAbstractApplier defaultEngineApplier
			calculateChangesForClasses: self context scopeSelectorPresenter selectedClasses
			transformationRules: ruleHolder asOrderedCollection.
		(ChangesBrowser changes: changes) open ]
```

Two points should be fixed
-  ruleHolder asOrderedCollection. (OrderedCollection with: ruleHolder).
- ChangesBrowser is deprecated

In the same package
- here we can also change UIManager default in self application....
```
execute

	| changes ruleHolder |
	(UIManager default
		confirm: 'This process can take between 1 and 2 minutes.'
		label: 'Proceed?') ifFalse: [ ^ self ].

	ruleHolder := StRewriterRuleHolder
		lhs: self context lhs
		rhs: self context rhs
		isForMethod: self context isRuleForMethod.

	changes := StRewriterAbstractApplier defaultEngineApplier
		calculateAllChangesForRules: ruleHolder asOrderedCollection.
	^ (ChangesBrowser changes: changes) open
```

**Comment by Ducasse** [comment]
Under delivery :) https://github.com/pharo-spec/NewTools/pull/652

**Comment by Ducasse** [comment]
I did a PR but nobody looked at it so I merged it.

**Comment by jordanmontt** [comment]
Fixed in: https://github.com/pharo-spec/NewTools/pull/652/files

<blockquote><img src="https://avatars.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-spec/NewTools/pull/652">Fix deprecated classes and methods by Ducasse · Pull Request #652 · pharo-spec/NewTools</a></strong></div><div>add links to references
pharo-project/pharo#15927</div></blockquote>
