### ISSUE TITLE
Rule: Rewrite super messages to self messages looks bogus

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16001]
```
selectors: aSelectorsCollection from: aClass

	super selectors: aSelectorsCollection from: aClass.
	self initializeRefactorings 
```

if I would apply it then it would create a loop.

**Comment by Inao0** [comment]
The rule will not appear in this example because the current rule for detecting application cases would not trigger. 
Indeed because it uses `aMethod methodClass withAllSubclasses` (see below) it will detect the implementation of `selectors:from:` in the current class. This would therefore not create a loop

```Smalltalk
ReSuperSendsRule<<shoudCheckMethod: aMethod
	^ aMethod methodClass withAllSubclasses noneSatisfy: [ :class | class includesSelector: aMethod selector ]
```

This rule offers to replace super by self when it would not change anything for the current code.
