### ISSUE TITLE
Can not commit anymore with Iceberg: DNU #workingCopyModel

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16019]
**Bug description**
I want to commit a fix. But I get a DNU #workingCopyModel

![coit](https://github.com/pharo-project/pharo/assets/413057/b7015988-4e9a-4f12-9ca8-9725c75aff62)

**Comment by MarcusDenker** [comment]
It seems this was fixed, see https://github.com/pharo-project/pharo/issues/16013

But I get it in the image I donwloaded just now...

**Comment by guillep** [comment]
Hi @MarcusDenker what is your image build? We need to specify that in all issues otherwise this is very difficult to follow. Maybe we should add that to the template and close issues that do not specify it?

I've just taken:

Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1313.sha.e5b9eb5f13aadcc24a5e4835b5d62d553e4d9e9d (64 Bit)

And I have:

```smalltalk
IceTipRepositoryGroupPanel >> workingCopyModel
	
	^ self selectedItem workingCopyModel
```

I don't have the issue in build 1313

**Comment by MarcusDenker** [comment]
This is 123065a, the one I got this morning with get.pharo.org

I think that in the meantime a new build was done  and so it should be fixed now

(I do not like this aspect of external projects at all...)

**Comment by guillep** [comment]
What information do you have in the About dialog?

<img width="681" alt="imagen" src="https://github.com/pharo-project/pharo/assets/708322/8daa2acc-45f1-4597-9048-74031e469e49">

**Comment by MarcusDenker** [comment]
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1312.sha.123065a569c1d0be754349a706639461efc5de3c (64 Bit)

**Comment by guillep** [comment]
Oh yes, so just a build behind...

**Comment by guillep** [comment]
I think that we can close this issue in that case
