### ISSUE TITLE
‘Close’ icon on tabs in System Browser gets clipped

### ISSUE THREAD

**Issue by Rinzwind** [guillep/pharo-core#16038]
The ‘close’ icon on tabs in the System Browser gets clipped in Pharo 12 build 1258:
<img width="429" src="https://github.com/pharo-project/pharo/assets/1611248/a03eea0f-a9ad-494f-9959-4c72c171a184">

Build 1236 seems to be the last build in which the icons don’t get clipped:
<img width="427" src="https://github.com/pharo-project/pharo/assets/1611248/95ceb10d-6107-4d01-aac6-7c3d8e6bb0c8">

I assume, but didn’t check, this is due to some of the changes in [commit b64e3bc1df1b06f4 in the Spec repository](https://github.com/pharo-spec/Spec/commit/b64e3bc1df1b06f4f80d2700d698432e357b819a).

**Comment by demarey** [comment]
I and @ISayarLu can confirm the problem started in image number 1237.
The close button is still present but has a ridiculous size of `2@18` instead of `16@18`.

It was introduced by the merge of a PR in Spec integration branch: https://github.com/pharo-spec/Spec/pull/1486
The code causing problems lies in `src/Spec2-Adapters-Morphic/SpMorphicBoxLayoutCalculatorLeftToRight.class.st`.
See https://github.com/pharo-spec/Spec/commit/b64e3bc1df1b06f4f80d2700d698432e357b819a#diff-79065f23e35b422864e3fef686ade71d813e234eb22cb1ef8a955e34ba5d42a8L66-R78
reverting the method `SpMorphicBoxLayoutCalculatorLeftToRight>>#doCalculateFor:in:` fixes the problem but I do not think it is the right fix. @estebanlm Could you help?

**Comment by estebanlm** [comment]
it will fix that but it will break other places :)
So I would say yes, is around there but removing is not the solution
