### ISSUE TITLE
Debugit nils selected variable: we cannot debugit from the debugger

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16340]
```
testTwoUrls
	| lk |
	lk := (splitterClass new parse: '[https://advanced-design-mooc.pharo.org](https://advanced-design-mooc.pharo.org)') first.
	
	self assert: lk bodyString equals: 'https://advanced-design-mooc.pharo.org'.
	self assert: lk url equals: 'https://advanced-design-mooc.pharo.org'
```

- select: `(splitterClass new parse: '[https://advanced-design-mooc.pharo.org](https://advanced-design-mooc.pharo.org)')`
- Debugit
- splitterClass is nil :(

So we cannot debug anymore.

**Comment by StevenCostiou** [comment]
I do not understand the problem :/
I tried and it opens a debugger.
And if I step there is an error that "splitterClass" is nil... That is not what is expected?

**Comment by MarcusDenker** [comment]
If you use "DebugIt" from the Browser and select an expression with an ivar or temp, the Debug It has no instance or context to work with.

Actually,"DebugIt" works the same like "DoIt" and uses the class as the receiver in this case, which does not know the var but will read nil (as it is Undeclared)/

If you use  "Debug it" from inside the Debugger, it works better: now it has an object to to work with and can resolve and read the ivar correctly.

Thus: not a bug. A research question is if the "DoIt" when executed in the browser without an instance could not work better, but that is an open question. (e.g. for a test it could create an instance).

 The current behavior is what is there since ever.

**Comment by MarcusDenker** [comment]
Ah, the title says that it was explicitly the second case: "debugit from the debugger ".

I tested it and that works, I can read the variable (both temps and ivars)
