### ISSUE TITLE
Socket>>#waitForSendDoneFor: does not return a boolean (but ZdcSocketStream expects it to)

### ISSUE THREAD

**Issue by jbrichau** [guillep/pharo-core#16373]
**Bug description**
The comment in `Socket>>#waitForSendDoneFor:` says it returns a boolean but it no longer does after changes in https://github.com/pharo-project/pharo/pull/15984/ and https://github.com/pharo-project/pharo/issues/15975

This breaks Zinc, as it still has methods such as `ZdcAbstractSocketStream>>#socketWaitForSendDone` that expect `Socket>>#waitForSendDoneFor:` to still return a boolean.

**To Reproduce**
On a Mac machine only, because it seems Zinc is not using `ZdcSocketStream` on other platforms!
1. Load Seaside (see https://github.com/SeasideSt/Seaside/)
2. Go to `localhost:8080` in a web browser
3. See the error `NonBooleanReceiver` in `ZdcSimpleSocketStream>>#flushBytes:startingAt:count:`
4. Closing the debugger correctly finishes the request, but it pops up on every next request

**Comment by jbrichau** [comment]
The commit that changes the code is https://github.com/pharo-project/pharo/commit/7f99ec49a102f0a60eb8fabbbca7ea9d1cc9d133 
Reverting the change in that commit resolves the error.

Alternatively, `ZdcSimpleSocketStream>>#flushBytes:startingAt:count:` in Zodiac can be changed by removing the `ifFalse:`check since a `ConnectionTimeout` is already signaled by `Socket>>#waitForSendDoneFor:`

**Comment by jbrichau** [comment]
The PR on Zodiac that fixes this issue is https://github.com/svenvc/zodiac/pull/15
However, it is not being merged, probably because it would need to take different Pharo versions into account.

**Comment by daniels220** [comment]
Just in case, @jbrichau did you see my comment on the Zodiac PR?

**Comment by jbrichau** [comment]
@daniels220 Yes, and I think your suggestion is the correct one.

**Comment by estebanlm** [comment]
I just submitted a fix, this is not really a problem to answer  a boolean and it will simplify people's life

**Comment by daniels220** [comment]
@estebanlm I think having two redundant ways to return success information is unnecessary clutter in Pharo core, and ultimately confusing as the only caller, `waitForSendDoneFor:`, will not return _at all_ if the wait fails (since the blocks throw exceptions), which is already a breaking change from Pharo 11, just not one that happens to inconvenience Zodiac. Also, if we did want to go this route, you don't need the `sendDone` temp—if control flow reaches the final return statement, `sendDone` _must_ be true—which really is a sign that a `true` return value is inappropriate, as where then is the `false`?

Realize, too, that for _most_ users of Socket, `waitForSendDone[For:]` is not something they would use directly—applications will generally use `sendData:count:`, `SocketStream`, or indeed Zodiac. It's only other libraries like Zodiac, SSL implementations, etc. that might need this level of access to Socket.

So, I think it's reasonable for libraries like that that are actively developed to make small changes to maintain compatibility—though I do think it's appropriate for contributors to be aware of such, which is why I submitted this PR in conjunction with the breaking change. I didn't realize that Zodiac didn't have another mechanism to maintain backwards compatibility. I've now added the backwards-compatible implementation of `socketWaitForSendDone` that I proposed above.

**Comment by estebanlm** [comment]
Hi, 

I ack your observations, but I still believe that *restore the old behavior* is the right approach here :)  

Take into account that this is how the method behave before, so introducing a change like this is just introducing noise to the system without clear gains.  
Other ways to access the status (the method `sendDone`) were already there, so this restore of functionality will just enhance other's frameworks maintainers life, taking specially into account that we are at 1w of release and while your change landed right before the freeze, it is still putting an unnecessary pressure to Zodiac maintainer (and who knows who else?).

Yes, there is the possibility that `waitForSendDoneFor:` to not return at all, but I am expecting an exception in that case, so this is still fair play :)

Moreover, I am not against semi-redundant functionality ("semi", because using the return value of `waitForSendDoneFor:` saves a message send and in some very corner scenarios that can be a thing), that will allow some more freedom for users to play with their design.

**Comment by daniels220** [comment]
Given the timing, that's fair. I guess we'll have to agree to disagree on the "no clear gains" part...I think making it clear that `waitForDataFor:...` and `waitForSendDoneFor:...` are exact analogues—note `waitForDataFor:...` never had a return value—is useful. But admittedly having the return value is not harmful as such, as long as the reasoning is clear, so I added a comment explaining _why_ it is there, and removed the temp (it _must_ be true at that point as I mentioned) to keep the rest of the method clean—best of both worlds, perhaps?
