### ISSUE TITLE
Creating a Point with @ and values that are the result of an operation isn't working correctly

### ISSUE THREAD

**Issue by Eliott-Guevel** [guillep/pharo-core#16370]
**Bug description**
When creating a point through the use of @, and when the left and right values of it are not a single value but rather a mathematical operation between 2 values (+, -, *, /...), the x value of the Point is the result of both the left and right operations.
This behavior doesn't happen while using Point x: y: .

**To Reproduce**
1. Go to the Playground
2. Create a point with for x and y values the result of an operation
3. Right-click and Print it

**Screenshots**
![point bug](https://github.com/pharo-project/pharo/assets/76944457/2c13c3bd-574e-4f2f-8dcb-cac6c398c2ee)

**Version information:**
 - OS: Windows
 - Version: 22H2
 - Pharo Version 11

**Comment by guillep** [comment]
Hi @Eliott-Guevel,  thanks for the issue.
I don't believe this is an issue, but rather this works like this by design.
It is a matter of precedence.

```smalltalk
-2 * 100 @ -2 * 100
```
is equivalent to
```smalltalk
((-2 * 100) @ -2) * 100
```
=> Which evaluates first the inner parentheses

```smalltalk
(-200 @ -2) * 100
```
=> now multiplication over a point multiplies each coordinate
```smalltalk
(-20000 @ -200)
```

Remember that binary messages are executed from left to right.
And multiplication (nor any other binary message) has never more precedence than `@` (nor any other binary message).
