### ISSUE TITLE
Wrong source for CompiledBlocks due to incorrect bytecode to AST nodes mapping

### ISSUE THREAD

**Issue by chisandrei** [guillep/pharo-core#16495]
In this method all blocks seem to be printed wrongly:

![image](https://github.com/pharo-project/pharo/assets/3534711/21dda81d-ffe6-47ed-b708-ca1e46161c0c)

This code is wrong as the sourceNode for a `CompiledBloc` resolves to a wrong node. We got several methods like the one below in Pharo 11 where the source code of all the blocks is wrong. Recompiling the method fixes the issue, and all blocks have the right source code, but not sure how initially it got in that state.

This was encountered in the latest Pharo 11 + VW on Windows 11.

In the above case this is the bytecode for the method and block:

<img width="1669" alt="Screenshot 2024-04-19 at 20 55 15" src="https://github.com/pharo-project/pharo/assets/3534711/98d1c3b5-505e-4b7f-8ba1-dab2ba3a135a">

Also this is the bytecode to AST nodes mapping:

<img width="1674" alt="Screenshot 2024-04-19 at 21 00 28" src="https://github.com/pharo-project/pharo/assets/3534711/ee775d2e-ed04-4516-979e-4424de9416ec">

This is after recompiling the method:

<img width="1671" alt="Screenshot 2024-04-19 at 21 03 36" src="https://github.com/pharo-project/pharo/assets/3534711/64adfc7a-b411-4289-b0d7-294eb5811a16">

<img width="1671" alt="Screenshot 2024-04-19 at 21 04 55" src="https://github.com/pharo-project/pharo/assets/3534711/7654a178-bf6f-440b-b3a4-d208a878fd22">

<img width="1680" alt="Screenshot 2024-04-19 at 21 05 17" src="https://github.com/pharo-project/pharo/assets/3534711/3485fd93-46c9-4c46-82bb-607976d6966b">

Not sure if related, but we seem to be getting also wrong sources for blocks in Pharo-12.0.0+SNAPSHOT.build.1488.sha.c55c586763b889b5e3b0c2749a987fac5ae1f7a7 (64 Bit) in some cases.
For example executing the first time this code in Pharo 12 returns the wrong result

```
blocks := OrderedCollection  new.
(AbsolutePath>>#asZnUrl) innerCompiledBlocksDo: [ :aBlock | 
		blocks add: aBlock ].
	
blocks first sourceNode sourceCode.
```
<img width="1088" alt="Screenshot 2024-04-19 at 21 11 50" src="https://github.com/pharo-project/pharo/assets/3534711/cd02cd55-dd10-4bfa-9694-94505fb8cdac">

<img width="1088" alt="Screenshot 2024-04-19 at 21 14 23" src="https://github.com/pharo-project/pharo/assets/3534711/002a2726-67ca-4246-a409-233f3e8acb46">

Executing the code the second time returns the correct result:

<img width="1088" alt="Screenshot 2024-04-19 at 21 13 24" src="https://github.com/pharo-project/pharo/assets/3534711/4aa70abe-e289-4c0c-8649-6e4efcee863a">

<img width="1088" alt="Screenshot 2024-04-19 at 21 13 50" src="https://github.com/pharo-project/pharo/assets/3534711/cf16dcc4-d393-4236-ad32-fe5c0d202ebf">

**Comment by carolahp** [comment]
The problem is caused when the method containing the block references a variable that was undeclared at the time of its compilation. The image below shows that `blocks first outerCode` returns an outdated version of the method's code, where the bytecode 67 (`send:runtimeUndeclaredReadInContext:`) is stacked.
<img width="889" alt="image" src="https://github.com/pharo-project/pharo/assets/4822303/b8c9554a-65ea-4db4-b2a8-f9a11e293fe2">

A solution would be to recompile all the methods referencing a given UndeclaredVariable when the variable is no longer Undeclared, and do the same when a Global is deleted and left as Undeclared.

Additionally, we should add some tests to `ReleaseTest` to ensure that a fresh Pharo image does not contain methods with this problem. 

@MarcusDenker do you think this solution is heading in the right direction?
