### ISSUE TITLE
DebugPoint on class side method

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16682]
**Bug description**
add a simple class side method, e.g.

```
tt
	^ 1+2
```

Try to add a breakpoint by double klick on the gutter (or via the menu).

Breakpoint is not added

**Comment by macta** [comment]
Yes I just noticed that now too (and came here to check) - that needs fixing as its a drag to go back to self halt.

**Comment by adri09070** [comment]
Actually, the debug point is installed but it does not break, I found the bug, this is because I send the message `#link:toAST:` that is understood by both classes and objects.

In the case of classes, the method just installs the link on the node.
In the case of objects, it creates the anonymous class of the object and installs the metalink in the anonymous class so that only the object is instrumented.

However, `Metaclass` does NOT inherit from `Class`, so the method installs the link in an anonymous subclass of the metaclass, which is wrong as the node should directly installed on the node.

A simple solution would be to move up the method `#link:toAST:` from `Class` to `ClassDescription`. This API from Reflectivity seems to be used only by me...

**Comment by MarcusDenker** [comment]
The PR has been merged for Pharo13, I re-opened so we do not forget to backport to Pharo12

**Comment by MarcusDenker** [comment]
I added a backport issue https://github.com/pharo-project/pharo/issues/16733
