### ISSUE TITLE
Full content pane is super super slow.

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#16787]
![world](https://github.com/pharo-project/pharo/assets/432549/1af5e2c9-5058-480e-acb5-ac81ee5185ed)

**Comment by Ducasse** [comment]
Try 'world.svg' asFileReference readStream contents
and click on full contents.... go and take a coffee

**Comment by jecisc** [comment]
This is why we have Preview and Full Contents. 

Since the full contents can be huge and to a lot of time to load we show only a subset at the beginning. 

Maybe we could check the size of the String and above a certain size we display a warning to the user asking if he is sure he wants to display the full content?

**Comment by jecisc** [comment]
I have the impression that there might be room for optimization in Rubric but since it's Morphed based, should we invest in that?

**Comment by jecisc** [comment]
One performance problem I'm seing is that, while Rubric Morph is not open, each operation applied will cause a recomposition of the text. So each time Spec Morphic adapter is applying a method such as #beWrapped before opening the morph, it will still recompute all the text. 

An optimization could be to not compute when the Morph is closed and compute only when we open or update. But I have no idea of how long this would take

**Comment by Ducasse** [comment]
Indeed I think that we should not invest now I hope that album is faster.
@plantec
