### ISSUE TITLE
[CI] SystemDependenciesTest is failing

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16826]
**Bug description**
Tests in SystemDependenciesTest started failing e.g. testExternalBasicToolsDependencies

It is not clear which is the reason for the problem, it seems we merged multiple (mininum 3, maybe more) PRs that intruduce many failing tests.

```
Given Collections do not match!
	additions : #('NewTools-CodeCritiques')
	missing: #()

SystemDependenciesTest(TestAsserter)>>assert:description:resumable:
SystemDependenciesTest(TestAsserter)>>assert:description:
SystemDependenciesTest(TestAsserter)>>assertCollection:hasSameElements:
SystemDependenciesTest>>testExternalBasicToolsDependencies
```

**Comment by jecisc** [comment]
This should be fixed by: https://github.com/pharo-spec/NewTools/pull/797

**Comment by MarcusDenker** [comment]
this is fixed

**Comment by jecisc** [comment]
There is still one.

StProtocolChooserPresenter depends on Commander 1 and is in NewTools-Core. 

I think I'll introduce a package NewTools-Calypso. Make this package load before Calypso in Pharo. And then move the StProtocolChooserPresenter there so that the Commander 1 dependency is loaded later and that we remove the dependency

Here is the first step PR: https://github.com/pharo-spec/NewTools/pull/805

**Comment by jecisc** [comment]
Hum.. In fact I see that we do not use NewTools groups for now. So I'm not sure it's the best solution. 

It might be better to add methods referencing Commander1 as extensions for now

**Comment by jecisc** [comment]
I did this PR to fix the problem: https://github.com/pharo-spec/NewTools/pull/806

**Comment by MarcusDenker** [comment]
I merged the PR
