### ISSUE TITLE
[CI] failing test: testNoUnusedInstanceVariablesLeft

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16824]
**Bug description**
testNoUnusedInstanceVariablesLeft is failing:

```
the following classes have unused instance variables:

ReClassForGeneratingEqualAndHash ReClassForGeneratingPrintOn OupsDummyDebuggerSystem ReClassForGeneratingEqualAndHashExistingImplementors
```

**Comment by MarcusDenker** [comment]
Some where introduced by https://github.com/pharo-project/pharo/pull/16786, but we can not revert it anymore as there where too many things merged after.

So we have to fix it.

**Comment by MarcusDenker** [comment]
ReClassForGeneratingEqualAndHash is test data, so we can not just remove the ivar

**Comment by hernanmd** [comment]
Please notice there is a PR that fixes the issue for the Refactoring packages here: https://github.com/pharo-project/pharo/pull/16853/files#diff-78c29fe49f6e8997db820120f064e9b206e666f6281d26f883d491e1d8d926f3

Another PR should address the OupsDummyDebuggerSystem one.

<blockquote><img src="https://avatars.githubusercontent.com/u/4825959?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo/pull/16853">Fix multiple tests with refactoring driver for duplicate class. by hernanmd · Pull Request #16853 · pharo-project/pharo</a></strong></div><div>Fix a couple of tests failing, reported in #16850, due to missing support to pre-configure refactorings for test purposes.
Also configured missing mocks for the preview presenter.
Fix also for #16825</div></blockquote>

**Comment by MarcusDenker** [comment]
Now it fails just due to OupsDummyDebuggerSystem

**Comment by MarcusDenker** [comment]
Fixed !
