### ISSUE TITLE
Pharo standalone for macOS Apple Silicon can't be opened

### ISSUE THREAD

**Issue by gregspurrier** [guillep/pharo-core#17009]
**Bug description**
The Pharo standalone [Pharo stable VM for macOS: Apple Silicon (default)](https://files.pharo.org/get-files/120/pharo-vm-Darwin-arm64-stable.zip) image that is downloadable from [here](https://pharo.org/download) fails to launch, displaying the error message:

> "Pharo" is damaged and can't be opened. You should move it to the Trash.

**To Reproduce**

1. Go to the [Pharo - Download](https://pharo.org/download) page.
2. Under "Pharo standalone", click on [Apple Silicon (default)](https://files.pharo.org/get-files/120/pharo-vm-Darwin-arm64-stable.zip)
3. Once the file has been downloaded, unzip it to get `Pharo.app`
4. Attempt to launch the app either by double clicking its icon in the Finder or using `open Pharo.app` from the command line.
5. Observe the error modal shown below.

**Expected behavior**
I expect the Pharo environment to be successfully launched.

**Screenshots**
<img width="372" alt="Screenshot 2024-08-14 at 11 05 54 AM" src="https://github.com/user-attachments/assets/ca7d8eb2-5c27-4f9d-af21-2a796b3439f6">

**Version information:**
 - OS: Mac OS
 - Version: Sonoma 14.6.1
 - Hardware: MacBook Pro 14-inch, 2021; Apple M1 Max chip
 - Pharo Version: whatever was up for download as of 2024-08-14 18:00:00 UTC

**Expected development cost**
Unknown

**Comment by Ducasse** [comment]
Thanks for the report. We will have a look Monday.

**Comment by guillep** [comment]
Hi!

Usually this happens when the file is put on quarantine. We are on our way  to produce signed and notarised builds.
But on the meantime, there is a workaround you can apply.

Can you try using the `xattr` command to check the file attributes?

```bash
xattr Pharo.app
```

I'd expect `com.apple.quarantine` to be listed.
If that's the case, you can remove the attribute using 

```bash
xattr -d com.apple.quarantine filename.pem
```

If that doesn't work, we will need further debugging.
Also, you can read more about MacOS quarantine by doing an online search "macos quarantine flag"

**Comment by demarey** [comment]
Hi
I was checking the issue and can confirm it is a problem of MacOs quarantine.
To avoid that, you can use the `xattr`command as explained by @guillep or use Pharo Launcher.

**Comment by Ducasse** [comment]
thank you for the explanation. I forgot :) because I always use the launcher :)
