### ISSUE TITLE
Enhance "Implementors tool" with Column names

### ISSUE THREAD

**Issue by NicolasAnquetil** [guillep/pharo-core#17103]
![image](https://github.com/user-attachments/assets/e2fb2aa6-d0ef-477f-bc4b-f8695c982d7e)

The "implementors window" could have titles for the columns, because in the case of long class name as here, it is impossible to know where the class name ends and where the method name starts...

**Comment by Rinzwind** [comment]
Related issue: issue #13802.

**Comment by hernanmd** [comment]
As it happens with many tools in Pharo today: We have a tool that will be discarded (based on Morphic and Calypso), difficult to understand, to modify, etc. And we have a new incomplete one (see screenshot below). 

The old version is mostly implemented using `ClyMessageSendersQuery` and `ClyMessageImplementorsQuery`.
The new version is based on NewTools `StMessageBrowser`, includes collapsible columns, and messages are displayed hierarchically. 

Advantage:

- In this new version it would be much easier to include a button to configure options (such as fixed column widths).
- It would be easier to add other columns such as the protocol column removed in https://github.com/pharo-project/pharo/pull/16096

Disadvantages:

- It seems that there is still a lack of support to complete the scopes drop-down list.
- Requesting/Spawning new senders or implementors from within a senders or implementors window opens a new window, instead of including it as a palette within the same window.

I will push a PR to replace the senders and implementors launched from Calypso, to use the new `StMessageBrowser`.

**Comment by hernanmd** [comment]
In https://github.com/pharo-spec/NewTools/pull/841

**Comment by Rinzwind** [comment]
@hernanmd I’m confused because the first demo in the pull request, in which you open the implementors of `#at:` from a System Browser, seems to show StMessageBrowser being used as the default, but in Pharo 13 build 262 the default is still ClyOldMessageBrowserAdapter and setting StMessageBrowser as the default through `#beDefaultBrowser` causes a MessageNotUnderstood when opening the implementors.
