### ISSUE TITLE
[CI] SystemDependenciesTest failing on CI

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#17163]
These tests started failing on the CI:

- SystemDependenciesTest.testExternalBasicToolsDependencies
- SystemDependenciesTest.testExternalUIDependencies

**Comment by Rinzwind** [comment]
The [Jenkins test report for `#testExternalBasicToolsDependencies` on macOS in build 265](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/265/testReport/MacOSX64.System.Dependencies.Tests/SystemDependenciesTest/osx_64___Tests_osx_64___testExternalBasicToolsDependencies/) indicates it as failing since [build 247](https://ci.inria.fr/pharo-ci-jenkins2/job/Test%20pending%20pull%20request%20and%20branch%20Pipeline/job/Pharo13/247/). The snippet given below lists the following reference commits for the repositories in build 247 and build 246. The commits that differ are the ones for the ‘pharo’ and ‘NewTools’ repositories. So the failure is presumably due to the changes in either [Pharo commit 9b98b9c](https://github.com/pharo-project/pharo/commit/9b98b9c0fd9abf3affa1538de21518267889b0b6), which merged a pull request by @jecisc, or [NewTools commit fe55742](https://github.com/pharo-spec/NewTools/commit/fe55742f2953c525ee50dc8ca629863d894a29e2), which merged a pull request by @hernanmd.

**Build 247 reference commits:**
```
pharo: 9b98b9c0fd9abf3affa1538de21518267889b0b6
Spec2: eca5e009877255dc578457dd324cf12c0ad12f11
NewTools: fe55742f2953c525ee50dc8ca629863d894a29e2
Roassal: 613f15ca24aa4416d86eb7754bb74d78193df1da
DocumentBrowser: 1c2fad2c80a015182431d228d8b3fdf339d0ab31
WelcomeBrowser: 680e4fa2ca52406bfa742a95f401bf530991f367
Microdown: 470ae1ab4cd3be1d93af5d0cf261a3546ffa11f0
tonel: e1dfa3fa6ad7aa69f0393e92929e5c2843919c16
```

**Build 246 reference commits:**
```
pharo: 7dc989c89c2772e5886210bfbfa988771752c379
Spec2: eca5e009877255dc578457dd324cf12c0ad12f11
NewTools: 7dd5048c533b7fe2d593042d159f51876d9e965b
Roassal: 613f15ca24aa4416d86eb7754bb74d78193df1da
DocumentBrowser: 1c2fad2c80a015182431d228d8b3fdf339d0ab31
WelcomeBrowser: 680e4fa2ca52406bfa742a95f401bf530991f367
Microdown: 470ae1ab4cd3be1d93af5d0cf261a3546ffa11f0
tonel: e1dfa3fa6ad7aa69f0393e92929e5c2843919c16
```

**Snippet to list the reference commits:**
```smalltalk
String cr join: (IceRepository registry collect: [ :repository |
	repository name , ': ' , repository workingCopy referenceCommit id ])
```

**Comment by MarcusDenker** [comment]
We really need to stop merging PRs with failing tests. What do we do here? do we revert now weeks later these ?

**Comment by hernanmd** [comment]
> We really need to stop merging PRs with failing tests. What do we do here? do we revert now weeks later these ?

I strongly suggest NOT revert anything. It takes a lot of work to fix the dependency hell we have between Calypso, Morphic, and NewTools that need features from Calypso that do not depend on Morphic.

So the last commits are going in that direction and failures are expected.

If Calypso had been structured in a modular way (instead of simply creating 50 “plugins” packages) we would not have this situation where a change in an external repository causes the whole CI to fail. 

If anything, the constant checking of external dependencies makes no sense while making major structural changes.

**Comment by Ducasse** [comment]
I agree with hernan.

**Comment by MarcusDenker** [comment]
Tests are not failing anymore
