### ISSUE TITLE
Dependency analyzer is broken through Calypso 

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#17423]
To open the dependency analyzer it now uses `self application tools` but the application is a NullApplication that does not know the tools. Thus the browser cannot open.

**Comment by Ducasse** [comment]
How do you open it?

**Comment by Ducasse** [comment]
```
execute

	| packageNames |
	packageNames := packages collect: [ :each | each name ].
	(DAPackageDependenciesPresenter onPackagesNamed: packageNames) open
```

should probably set the application default for now.

**Comment by Ducasse** [comment]
I tried this 

```
execute

	| packageNames depPresenter |
	packageNames := packages collect: [ :each | each name ].
	depPresenter := (DAPackageDependenciesPresenter onPackagesNamed: packageNames).
	depPresenter application: StPharoApplication current.
	depPresenter open
```

but I failed :( because the default application is already pass to other parts. 

I do not like when the architecture is unclear and we are left in the dark fixing consequences instead of the causes.

**Comment by Ducasse** [comment]
@estebanlm how should we pass the application because I do not know how I can use 
newApplication:

**Comment by Ducasse** [comment]
I found a way but I'm pretty sure it is BAD now if I do not get feedback I will push it in Pharo so that we can get the system working.

**Comment by Ducasse** [comment]
```
DACycleDetectionTreePresenter class >> onPackagesNamed: aCollection
	^ (self newApplication: StPharoApplication current) 
		initializeWithPackageName: aCollection;
		yourself
```

```
DADependencyTreePresenter class>> onPackagesNamed: aCollection
	^ (self newApplication: StPharoApplication current) 
		initializeWith: aCollection;
		yourself
```

**Comment by estebanlm** [comment]
if this is considered part of the pharo ide (it is) and part of the spec set of components known as "newtools", then the best way to ensure the application is to make the root presenters (aka the ones that will be opened as top level windows), in this case  `DACycleDetectionTreePresenter` and `DADependencyTreePresenter` to inherit from `StPresenter` instead of `SpPresenter`. 

Of course, `StPresenter` uses the `currentApplication` accessor which is at the end the same you are proposing, but in that case we are concentrating the point of change so when we finally can get rid of that singleton approach we will have just one point to refactor :)

**Comment by Ducasse** [comment]
Good idea. I did not see the sp vs st point.
