### ISSUE TITLE
rename valeur into value should lead to a refactoring error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2137]
- add a method valeur
- rename it to value
-> the message is totally unclear and the system should propose viable alternatives

**Comment by maxbareis** [comment]
I know this is a stale issue but for training purposes I check those old stuff.
@Ducasse Is the warning itself really needed? If I write a value method and save it, there is also no warning. So when overwriting the superclass method while renaming the behaviour should be the same.

**Comment by Ducasse** [comment]
We should report this to evelyn https://github.com/Lin777/Enjoliveur/issues/38

**Comment by sbragagnolo** [comment]
https://github.com/pharo-project/pharo/pull/4988 is meant to solve this small issue. 
The error message now looks more like
" The selector name has changed to #value and ValueExample an/or part of it's hierarchy already understands #value"

Still place for improvement, since all the error messages are generic macros agnostic of the refactor ongoing, most of the messages are kind of irrelevant.

**Comment by guillep** [comment]
We now have an error as follows:

![image](https://user-images.githubusercontent.com/708322/69875996-bfd95900-12be-11ea-9138-91d8113f0d6e.png)

I'll close it, feel free to reopen if necessary :)
