### ISSUE TITLE
Remove homebrew Pharo cask, rename pharo-launcher to pharo

### ISSUE THREAD

**Issue by nreilly** [guillep/pharo-core#2151]
We seem to be encouraging pharo launcher over pharo as a normal means of launching, getting appropriate VMs and images. Please consider this being the default when installing pharo via homebrew.

**Comment by bencoman** [comment]
I've been a user of homebrew a few times, but not familiar with creating packages for it.
Can you provide a few pointers?

**Comment by Ducasse** [comment]
I know that damien pollet did some cask scripts and it would be super nice to have some maintained ones as part of our release process. Thanks for pushing it.

**Comment by estebanlm** [comment]
hi @cdlm, can you take a look at this?
btw... I would not rename Pharo-launcher into pharo (both are different things). But having a recipe for the launcher would be cool too :)

**Comment by Ducasse** [comment]
fully agreed on that.

**Comment by SergeStinckwich** [comment]
There is Cask : https://github.com/Homebrew/homebrew-cask/blob/master/Casks/pharo-launcher.rb

Install with : ```brew cask pharo-launcher```

**Comment by Ducasse** [comment]
This is cool I will try it :)

**Comment by cdlm** [comment]
@estebanlm sure

**Comment by cdlm** [comment]
So, I had a look… I agree that renaming the Pharo Launcher cask is a bad idea.

The Pharo one should probably be removed, it doesn't really make sense because it's too generic, and there isn't even a 7.0 download at https://files.pharo.org/platform/
Alternatively, it seems possible to make it less generic by providing [major versions](https://docs.brew.sh/Versions); but that's for formulae, not sure how that applies to casks.

Now I wonder what we should do with regards to @pharo-project/homebrew-pharo. It's a [homebrew tap](https://docs.brew.sh/Taps), currently unused, but which would allow us to maintain casks and formulae on our terms, instead of relying on the homebrew maintainers. Problem is, we have name clashes with the casks in the official tap…

**Comment by SergeStinckwich** [comment]
There is a discussion here also : #2297

**Comment by vitorgalvao** [comment]
> Now I wonder what we should do with regards to @pharo-project/homebrew-pharo. It's a [homebrew tap](https://docs.brew.sh/Taps), currently unused, but which would allow us to maintain casks and formulae on our terms, instead of relying on the homebrew maintainers. Problem is, we have name clashes with the casks in the official tap…

Homebrew Cask maintainer here. As a pharo developer, what do you prefer? If you’d rather keep your own tap, we can remove all pharo casks from our repos.

**Comment by cdlm** [comment]
@vitorgalvao I think pharo-launcher is the one cask that should definitely stay, and with that name, since it's not installing pharo-the-development-environment itself, but a helper application that downloads and manages multiple versions and instances of it.

It's probably best if we directly maintain our own tap (already existing at https://github.com/pharo-project/homebrew-pharo). I will have a look at how to do the migration, and @chrisfinazzo you're welcome to contribute there of course ;-)

BTW, do casks support multiple versions, like formulae do? (e.g. gcc@6 gcc@7)

**Comment by chrisfinazzo** [comment]
@cdlm, Broadly speaking, I think the answer is yes. You can handle this within a single cask by conditionally checking `MacOS.version`. BBEdit does this (I worked on that PR, so...yeah) and others _should_ be able to do the same.

Helper applications have always seemed a bit wonky to me, so If it's easier to maintain your own tap, go right ahead. People can get it if they want and to be honest, they probably know what to do anyway in order to set up their environment.

**Comment by SergeStinckwich** [comment]
Pharo cask has been removed.
Can we closed this issue @MarcusDenker ?
