### ISSUE TITLE
RBMethod arguments are parameters!

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2209]
Hi 
this is a bit a pity that method parameters are called arguments. 
Parameters are identifiers and arguments are actual values assigned to parameters during message passing. 
Could we change this in the future? Because it would be much nicer.

**Comment by MarcusDenker** [comment]
I would prefer not to do that change.
-> there are #arguments in message sends, too. 
-> now things are the same: it is argument. if we change it so that all *static* entities have parameter but runt-time entities argument, then it will be quite some overhead to think what is which. 
-> does it mean we need to change #numArgs on CompiledMethod, too? What about Symbol?
-> In meta links, would it be arguments or parameters?

**Comment by MarcusDenker** [comment]
It would be a huge change, take weeks to do and in the end we would ask always "is it now parameter or argument"?
