### ISSUE TITLE
Browser, Implementors, Senders shortcuts should work when the text is not selected

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2289]
When we want to browse a class it would be nice to not be forced to select the text so that we can type Point and Cmand+ B without the need to select the text.

**Comment by dionisiydk** [comment]
I see only case when it does not work: when in source code (dirty version
in editor) the class name is compiled as selector (due to error, missing
dot and so on).
Can your confirm it?

I think it is related to ast-based navigation

вт, 22 янв. 2019 г., 10:11 StéphaneDucasse notifications@github.com:
