### ISSUE TITLE
Add #assertEmpty:

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2309]
I would like to introduce an #assertIsEmpty: because when a test fails on the CI because a collection is not empty, it's hard to debug without seeing the collection.

**Comment by estebanlm** [comment]
`assertEmpty:` is not better?

**Comment by jecisc** [comment]
Agree!

**Comment by astares** [comment]
I still do not get why we need this? Will we provide 
 assertNil: 
 assertNotNil:
 ...
and many other variations afterwards too? We will bloat Sunit with that over time.

One can use:
   self assert: coll isEmpty
or 
   self assert: coll isEmpty description: 'Collection needs to be empty'

**Comment by jecisc** [comment]
Because when I have an error on a release test saying that `self assert: violations isEmpty` failed, it does not help me find the problem. And in the case I was looking for I cannot reproduce it locally. 

So if I could have an error saying `OrderedCollection(MyFaultyClass) should have been empty`, at least I know where to look at. 

It's also useful for random failures. If sometimes in the CI I see a failing test, it's better to know what was in the collection to know where to look at.

**Comment by astares** [comment]
I'm still not convinced - because then you should use 

     self assert: violations isEmpty description: 'Tell what was wrong here'

explicitly on the places you require it. 

With your changes you now refactor all tests and also **enforce it on each test**. Dont know if this is wished.

Also in the #assertEmpty: method you include the collection string

       self assert: aCollection isEmpty description: aCollection asString , ' should have been empty'

in the description. While I agree this is helpful in some collection it could be a problem for larger ones. No?

**Comment by jecisc** [comment]
Most of the time you do not need a specific description and a generic one is fine. Also when someone adds a personalized description, maybe he will not think about printing the elements found and once again your trace in the logs will be useless.

Those last few months I lost a lot of time I could have saved by having this assertion.

I don't see the problem with using it for our current tests since it asserts the same thing and just adds a more detailed description that will be displayed only in case of failure instead of just printing "Assertion Failure".

**Comment by macta** [comment]
I would back up that it is useful. We might not need all combinations but there are a number of pragmatic ones that give a consistent useful output and encourage people to do the right thing. It's also a decent refactoring, so that if we get better visualisations - tests using those constructs will get the better visualization.  I do understand the concern that it can get a bit silly adding absolutely everything - but I think SUnit err's on the side that is too lean at the moment. So +1 from me.

**Comment by Ducasse** [comment]
Ok thanks for the discussion. I like it.
