### ISSUE TITLE
Add scanTokens: to RBScanner

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#2372]
Something probably like that

	

[:c| c isSeparator] split: 'Object subclass: #NameOfSubclass
	instanceVariableNames: ''''
	classVariableNames: ''''
	package: ''UndefinedClasses-Experiment'''
>>> an OrderedCollection('Object' 'subclass:' '#NameOfSubclass' '' 'instanceVariableNames:' '''''' '' 'classVariableNames:' '''''' '' 'package:' '''UndefinedClasses-Experiment''')

The following does not work

(RBParser new parseLiterals: ('Object subclass: #NameOfSubclass
	instanceVariableNames: ''''
	classVariableNames: ''''
	package: ''UndefinedClasses-Experiment''' ))

(RBScanner new on: ('Object subclass: #NameOfSubclass
	instanceVariableNames: ''''
	classVariableNames: ''''
	package: ''UndefinedClasses-Experiment''' readStream))

	scanLiteral

**Comment by kasperosterbye** [comment]
It is the kind of thing I can do (I think), but I must admit I am a somewhat unsure what is the expected behaviour you are looking for. The parseLiterals: in RBParser is not using its input for anything, and scanLiteral (I think correctly) returns the first Literal. 

Did you mean you needed a #scanLiterals (plural) on RBScanner? and then have the #parseLiterals: delegate to that method?

**Comment by Ducasse** [comment]
The idea is that scanTokens: in squeak was returning a collection of tokens and it was useful.
