### ISSUE TITLE
Tonel test is failing

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2373]
```
ByteSymbol(Object)>>doesNotUnderstand: #categories
TonelWriter>>obtainPackageDir:
TonelWriter>>writePackage:
TonelWriter>>writeSnapshot:
TonelWriterTest>>testWriteSnapshotWithoutOrganization
TonelWriterTest(TestCase)>>performTest
```

**Comment by jecisc** [comment]
@pavel-krivanek I think it was you who worked on that part.

**Comment by pavel-krivanek** [comment]
It's because this commit is somehow missing in Pharo, so we have the test but not the fix
https://github.com/pharo-vcs/tonel/commit/6c45db9c2f2e24b14b8976f0017ae9dddecd8078

**Comment by pavel-krivanek** [comment]
the fix seems to be present in the latest version
https://github.com/pharo-vcs/tonel/blob/master/MonticelloTonel-Core.package/TonelWriter.class/instance/createDefaultOrganizationFrom..st

We probably just need to update Tonel (which means to update Iceberg...)

**Comment by Ducasse** [comment]
Tx for looking into it.

**Comment by badetitou** [comment]
I tried to fix this bug but I think i did not understand something...

I've clone/pull/checkout etc the pharo repository in a fresh P7 image, then I clone the tonel repository and update the image from the last commit of the tonel repository.

The test is fixed, but, I cannot commit and create a pull request because the package `MonticelloTonel-Core` is not in the pharo repository nor in the iceberg one. 
So, i suppose I did not get a thing about how the image is build...

Some help needed ?

**Comment by jecisc** [comment]
We need to update Iceberg (https://github.com/pharo-vcs/iceberg/blob/master/BaselineOfIceberg.package/BaselineOfIceberg.class/instance/tonel..st) to use the latest version of Tonel, release a new iceberg version and include it on Pharo baseline.

**Comment by Ducasse** [comment]
Esteban can you help on this one because this is super boring to have the tonel tests always red.

**Comment by estebanlm** [comment]
taking this now

**Comment by Ducasse** [comment]
Tx!

**Comment by badetitou** [comment]
Will the patch be backport on Pharo 7?
