### ISSUE TITLE
Rename selection methods of FastTable to remove the "row" in names

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2423]
Because we want to also have cell selection.

**Comment by dionisiydk** [comment]
How public API #selectRowIndexes: depends on ability to select separate cells?
It will be always needed to select full rows instead of concrete cells. So why this rename? (same for highlighting rows).

**Comment by dionisiydk** [comment]
About rename of variable selectedRowIndexes into selectedIndexes. 
The intention is to hold something different than indexes of rows, right? Will it be indexes of cells? 
Then should not it be named selectedCellIndexes? Because the new name is confusing. What is the index in the table? I see rows, cells, columns but don't know the index.

If you are going to implement cells selection iteratively I would suggest to first introduce new variable for this and maintain it together with existing one. Then it will be cleaner how to remove old one and how to name all these things.

From the other side thinking about selection refactoring I have imagine selection object which merges strategy and indexes and grabs all selection behaviour. So it can be RowSelection and CellSelection classes which will provide different API to control table.

**Comment by jecisc** [comment]
Hi,

I am working on cleaning and integrating the work of someone else that was sleeping on another repository.

The idea is to have a selection mode strategy that will manage if the selection act on a row, column or cell. The strategy will manage the content of the selectedIndexes variable. For rows, it will be the indexes of the rows selected (same if I introduce columns selection) and for cells, it will be the position of the cell. 

Maybe later the selection variable can be moved to the strategy, but for now, I wanted to have a clean enough introduction of the features. 

Everything related to the selection mode will be moved in this strategy that will be the equivalent of what you called RowSelection and CellSelection.
