### ISSUE TITLE
Pharo 7 on startup crashes if current folder name contains blanks

### ISSUE THREAD

**Issue by wyattbiker** [guillep/pharo-core#2439]
Rename your pharo folder to something like **`pharo 7`**  then type ./pharo to launch. You will get the errors below. However rename it back to pharo works fine.
tested on Linuxmint 19.1.

```
standing@standing-VirtualBox:~/pharo 7$ ./pharo
ldd: /home/standing
7/pharo-vm/lib/pharo/5.0-201901051900/pharo: No such file or directory
Error. Could not determine platform's libc path for VM. 
Try forcing $PLATFORMLIBDIR in /home/standing/pharo 7/pharo-vm/pharo, based on LIBC_SO.
Please report what works to pharo [vm-dev] mail list.
  LIBC_SO=
cat: /etc/upstream-release: Is a directory
  DISTRIB_ID=LinuxMint
  DISTRIB_RELEASE=19.1
  DISTRIB_CODENAME=tessa
  DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"
  NAME="Linux Mint"
  VERSION="19.1 (Tessa)"
  ID=linuxmint
  ID_LIKE=ubuntu
  PRETTY_NAME="Linux Mint 19.1"
  VERSION_ID="19.1"
  VERSION_CODENAME=tessa
  UBUNTU_CODENAME=bionic
  UNAME=Linux standing-VirtualBox 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
  System seems to be 64 bit. You may need to (re)install the 32-bit libraries.
standing@standing-VirtualBox:~/pharo 7$ ^C

```

**Comment by akgrant43** [comment]
Huh, I'm surprised this hasn't been raised before.

It's actually a VM issue and should be straightforward to resolve.

Should this issue be transferred to https://github.com/OpenSmalltalk/opensmalltalk-vm/issues ?

**Comment by akgrant43** [comment]
I've got a solution, but it will be tonight or tomorrow before I can look at implementing it.

**Comment by akgrant43** [comment]
@wyattbiker Can you try the latest VM:

$ curl get.pharo.org/64/vmLatest80 | bash
$ ./pharo --version | grep Hash
Date: Mon Feb 4 20:37:32 2019 CommitHash: 694dfe3e

And then start the image as normal.

Thanks,
Alistair

PR: https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/369
Commit: https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/694dfe3ed015e16f5b8e9cf17d37e4bdd32bea16

**Comment by guillep** [comment]
Hi @akgrant43 thanks for looking into this.
Wouldn't it make sense to create a Pharo7 branch in the VM repository to apply the patch and then merge the patch into the main cog repository?

I'd like to avoid the fact that pulling a patch makes us pull a ton of new features or half finished things from the development branch...

**Comment by akgrant43** [comment]
Hi Guille,

I know this is a contentious area, so I'm a bit wary of jumping in. :-)

I think there are two things we should keep in mind when thinking about the code management:

1. We should commit to keeping up with the main branch (Cog) over time, i.e. not diverging the code base.
2. We want to be able to ensure stability for released versions.

I generally agree with what you wrote, and would suggest a process something like (using Pharo 8 as an example):

1. We use the Cog branch during development, i.e. the current Pharo 8 VM is head on Cog.
- This may not mean automatically adopting each build as it is built.  We may use the current mechanism (on files.pharo.org) to stay with a particular build for a while
2. Once we reach feature freeze, i.e. release the first RC, we branch Cog for that version, e.g. create a Pharo8 branch.

So far, this is the same as what you wrote (I think).

3. Bug fixes are then made on the main branch (Cog) and cherry-picked across to the Pharo8 branch as desired.

Step 3 is the reverse of what you proposed, but is how most projects I've been involved in have worked.

Pharo 9 development will then go back to using the Cog branch.

For Pharo 7, we could create a branch from the commit of the current Pharo 7 VM.

I realise there's some additional complexity due to the code generation from slang, but presumably we can follow a similar process for it.

What do you think?

Cheers,
Alistair

**Comment by akgrant43** [comment]
Fixed by https://github.com/OpenSmalltalk/opensmalltalk-vm/pull/369

The discussion about code management can be taken elsewhere.

This issue can be closed.
