### ISSUE TITLE
Use NativeFileSystemBrowser instead of just NativeBrowser

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#2523]
As there could be different native browser types (file browser, web browser, ...)  can we please rename the new selectors like  #openInNativeBrowser into  #openInNativeFileSystemBrowser as this would be more clear.

**Comment by dionisiydk** [comment]
What about OSFileBrowser? It is shorter and simpler

13 февр. 2019 г. 4:00 PM пользователь "Astares" <notifications@github.com>
написал:

As there could be different native browser types (file browser, web
browser, ...) can we please rename the new selectors like
#openInNativeBrowser into #openInNativeFileSystemBrowser as this would be
more clear.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pharo-project/pharo/issues/2523>, or mute the thread

**Comment by astares** [comment]
Why so shy on longer names?

It is not a file browser as it displays directories as well. I would prefer meaningful names - so I think "FileSystemBrowser" is more appropriate.

**Comment by dionisiydk** [comment]
Directories are files too (in linux at least).
And we already use this File Browser name for our internal tool (world
menu/tools/)

13 февр. 2019 г. 4:47 PM пользователь "Astares" <notifications@github.com>
написал:

Why so shy on longer names?

It is not a file browser as it displays directories as well. I would prefer
meaningful names - so I think "FileSystemBrowser" is more appropriate.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pharo-project/pharo/issues/2523#issuecomment-463274522>,
or mute the thread

**Comment by astares** [comment]
Still valid

**Comment by hilaire** [comment]
So what is your final say:
openInOSFileBrowser or openInNativeFileSystemBrowser

**Comment by astares** [comment]
Whatever fits best - but native Browser is not enough as there is also a Web browser

**Comment by hilaire** [comment]
go for openInOSFileBrowser then. I will make a PR
