### ISSUE TITLE
Add description to all Pharo packages

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2609]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/20469
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 23 September 2017 10:48:45 pm
	
Description:
	
I think that all Pharo packages should have an explicit comment. 

This case will probably be a meta case for other subcases.

**Comment by SergeStinckwich** [comment]
What could a template for a package comment ?
Do would the template for BaselineOfXXX packages comment?

**Comment by jecisc** [comment]
For packages in general when I comment them I try to:

- First, add a description that will be the same for all packages on the project
- Second, add a description that will be specific to this package inside the project
- Third, if needed, add a description about relations with other packages
- Then, I add a description of the entry points in case there are some simple entry points.

**Comment by guillep** [comment]
I think this issue is too big and requires too many people involved (not everybody knows everything about all packages). I'll close this.

I think the idea of having a better package comment template is a good one, and we can add individual issues for individual non-commented packages. Maybe some new issues can be added for these?
