### ISSUE TITLE
Parenthesis around autocompleted keyword message after a keyword message

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2635]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/19419
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 2 December 2016 3:35:18 pm
	
Description:
	
I am not sure this is wanted in all cases but I think this feature can be cool:

The idea is to check when we auto complete a method if this method come after another keyword. In that case it should be surrounded by parenthesis in most cases. 

For example if I want to add to a collection an element I will call the method #add:. But if I want to add the result of another method, and this method is a keyword it will not be valid. 

self add: aCollection collect: #something

To be valid we need parenthesis 

self add: (aCollection collect: #something)

Maybe Pharo can be smart and directly add those parenthesis. :)

**Comment by macta** [comment]
Thats a cool idea - I had been thinking about ways to select the correct code afterward (like cmd-2) so you could  add the brackets easily - but its tricky that way because its hard to differntiate which nodes to highlight. In this suggestion you can infer that right after completion.

**Comment by macta** [comment]
I’m still very interested in improving this.

It occurs to me however, that sometimes I want to re-autocomplete on a multi-keyword message (eg : #select:thenCollect: if I originally completed on #select: and want to add the second keyword).

I think it’s still possible given the idea above - if the new  completion matches a multi keyword do that second keyword completion, otherwise add the bracket and complete as suggested

**Comment by guillep** [comment]
This is a pretty big "issue", not easily actionable, more like a big feature project.
But if nobody actively works on it, it would be nicer to move it maybe to a wiki page with project ideas.
