### ISSUE TITLE
Check for settings of older version of Pharo 

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2643]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/18226
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 13 May 2016 4:32:38 pm
	
Description:
	
In Intellij when you use a new version of Intellij it ask you "We see that you have settings from a previous version of Intellij, do you want to use this settings in this version?". 

Maybe we could do the same. If we launch Pharo 6 for the first time and there is no 6.0 directory, it could check if there is a 5.0 directory. If there is one it ask to the user if it want to import them.

If the user wants Pharo would import the settings and export them in the 6.0 directory. If the user does not wants it ask if this is a definitive decision or not and on a definitive decision we add a script to the 6.0 directory to not ask again.

What do you think about it?

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 1:19:13 pm
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by jecisc** [comment]
Still relevant.

**Comment by estebanlm** [comment]
why is still relevant? 
I do not think it worths the work: since settings can change quite a bit from version to version, we will need to do a migration of settings. 
Yes, we could just take the ones that match, but still: most of the settings around in fact are programmed actions, AFAIK, so we cannot know if they are good or bad.

**Comment by MarcusDenker** [comment]
I don't think that we will be able to do this. We so many more issues that are more important to fix.

The issue is from 2016. nearly 5 years. I do not think that we will do this in the next 5 years, either.

I was wondering if we should not have some kind of "list of things that would be nice to do" that are not issue tracker entries...
