### ISSUE TITLE
SystemSetting store Settings should only export non default settings

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2646]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/18214
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 12 May 2016 5:44:25 pm
	
Description:
	
It would be cool to not export the default settings when we save our settings. This make the image long to launch when we use settings.

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 13 May 2017 1:28:50 pm
	
Message:
	
This is important

**Comment by jecisc** [comment]
This issue is important because it currently creates a lot of problem. 

Some settings such as the location of the local folder are relative paths, but they are exported as absolute paths. So if we store the settings, all the next images will point to the local folder of the image where we exported the settings, and this creates problems.

**Comment by fuhrmanator** [comment]
Can someone tell me how to work around this? 

I currently have two images (one that I created to report a bug in iceberg) and now the other image is set to the bug-report branch of my repo. I think they're both pointing to the same repo, which is precisely why I created another image to report the bug. Anyway, how can I get my Pharo to stop sharing the repos? **Share repositories between images** is not enabled on either image.

**Comment by fuhrmanator** [comment]
OK -- thanks to @jecisc I learned (again) that it's the **Local directory** setting that is causing the trouble with the shared repos (they're going into the same directory, which was the image of where I likely "stored" the settings, which is the heart of this bug). 

The workaround is NOT to remove the value of **Local directory**, but rather to get rid of the settings file, so that new images don't point to the same local directory. 

On my Linux path it was in my ```~/.config/pharo/7.0/system-settings.ston```

**Comment by jecisc** [comment]
This is important

**Comment by guillep** [comment]
I think this is already solved by 
- https://github.com/pharo-project/pharo/pull/5431
- https://github.com/pharo-project/pharo/pull/5473
