### ISSUE TITLE
Toggle Bytecodes works only in one way.

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2647]
Migrated case from Manuscript.
	
Original case: https://pharo.fogbugz.com/f/cases/17119
Status: Work Needed
Project: Usability
Original Author: CyrilFerlicot
Date: 25 November 2015 1:34:36 pm
	
Description:
	
Use Toggle Bytecodes, then use it again. The code will stay as bytecodes.

**Comment by jecisc** [comment]
Reply:
Author: Henrik Nergaard
Date: 25 November 2015 2:06:05 pm
	
Message:
	
Perhaps toggling of bytecodes could be moved down to the pane bellow the text, and have a button similar to the "[] format as you read" option?

**Comment by jecisc** [comment]
Reply:
Author: CyrilFerlicot
Date: 30 March 2016 3:29:51 pm
	
Message:
	
can wait Pharo 6

**Comment by jecisc** [comment]
Reply:
Author: Pavel Krivanek
Date: 27 January 2017 9:51:28 am
	
Message:
	
Low priority issue. Not for Pharo 6. The milestone "Later" was set automatically.

**Comment by jecisc** [comment]
The Toggle bytecode feature is not in Calypso.

**Comment by dionisiydk** [comment]
Yes.
With calypso you need to inspect method and get all presentations you need.
Maybe it's important to have it just in browser. I don't know

20 февр. 2019 г. 12:23 пользователь "CyrilFerlicot" <
notifications@github.com> написал:

Closed #2647 <https://github.com/pharo-project/pharo/issues/2647>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pharo-project/pharo/issues/2647#event-2151753854>, or mute
the thread
