### ISSUE TITLE
Show slot class definition by default

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2666]
I discussed with some people at RMoD and we are multiple to think it's time to enable by default the show slot definition setting by default in the browser.

If nobody as an argument against it, I'll do a PR.

**Comment by dionisiydk** [comment]
And what the status of idea to have completely new definition based on
cascades?

20 февр. 2019 г. 13:42 пользователь "CyrilFerlicot" <
notifications@github.com> написал:

I discussed with some people at RMoD and we are multiple to think it's time
to enable by default the show slot definition setting by default in the
browser.

If nobody as an argument against it, I'll do a PR.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pharo-project/pharo/issues/2666>, or mute the thread
