### ISSUE TITLE
Rubric has wrong selection interval when selection is empty

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#2676]
Currently, Rubric returns an interval `1 to: 0` when the selection is empty. This is confusing because when I see a selection such as "1 to 0" I expect to get the first character selected from the right to the left. 

To reproduce: 

```Smalltalk
rub := RubTextFieldArea new setTextWith: 'Test'; yourself.

rub selectionInterval.
```

This can cause trouble in some projects such as Spec. When we clear the selection, Spec is saying that the selection should be 0 to: 0 but rubric set once again the selection to 1 to: 0.

**Comment by StevenCostiou** [comment]
After digging a bit:
- `1 to: 0` is empty by definition because it is `1 to: 0 by: 1`, that would not be the case for `1 to: 0 by: -1`. Even if not intuitive, it is correct from a semantic point of view.
- When selection is graphically made from right to left, e.g. `10 to: 0 by: -1`, it is transformed as `0 to: 10 by: 1` by something in rubric (currently under investigation).

So it seems that is not really a bug, but that it lacks comments.

**Comment by plantec** [comment]
This selection interval convention is inherited from PluggableTextMorph. It is like that since years. So not a bug and I don't see how it could be changed. In the future maybe when we will be able to drop Morphic and Rubric...

**Comment by estebanlm** [comment]
yup, I do not think this can be fix (or has sense to do it). 
I think is better to adapt Spec2.
