### ISSUE TITLE
speedup writesSlot: and readsSlot: for the case of Ivar

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#2880]
writesSlot: and readsSlot: are really slow as they are a query on the AST (which might even not be there yet).

For the case of ivars, we can make it much faster by fallen back on writesField: and readsField:

**Comment by dionisiydk** [comment]
Hi @MarcusDenker. 
I commented on closed issue. But let's continue here:
We already have polymorphic methods in slot classes: #isReadIn: and #isWrittenIn: . They delegate logic to method:
- #readsSlot: is used by main Slot class implementation.
- #readsField: is used by InstanceVariableSlot implementation. 

So with current design it is supposed to ask a slot about usage instead of method.
Would be nice to have both ways available. But it would require better names to distinguish primitive API from high level API (readsField: and readsSlot: are now both primitive API)

**Comment by dionisiydk** [comment]
Maybe current #readSlot: code should be inlined into Slot class. Then method #readSlot: can become general by delegation to given slot.

Also readSlot: code with ast analysis deserves love. Too many message chains. We should ask nodes to do the job.

**Comment by MarcusDenker** [comment]
I think if we move the code of readSlot: to isReadIn: it will do the speedup: isReadIn: is overridden for indexed vars to use the fast code.

yes, the queries are ugly.

**Comment by MarcusDenker** [comment]
https://github.com/pharo-project/pharo/pull/2897

**Comment by MarcusDenker** [comment]
I added https://github.com/pharo-project/pharo/issues/2898 for the simplification

**Comment by MarcusDenker** [comment]
I merged this version. More to come in another Issue
