### ISSUE TITLE
Invoking a MenuMorph on mousedown when positioned under the handmorph might trigger a choice on mouseUp (16473)

### ISSUE THREAD

**Issue by StephanEggermont** [guillep/pharo-core#2902]
When a menuMorph is invoked from a mousedown action the next mouseup action might trigger one of the possible choices given the hand position is above one of them.

Test example: 
| blk m |
blk := [ :evt | | menu |
menu := MenuMorph new
add: 'do it (d)' selector: #doIt;
add: 'print it (p)' selector: #printIt;
add: 'inspect it (i)' selector: #inspectIt;
yourself.
menu invokeAt: evt position - (4@4) in: World 
].
m := Morph new.
m on: #mouseDown send: #value: to: blk.
"m on: #mouseUp send: #value: to: blk." "<--- does not have this behaviour"
m openInWindow.

https://pharo.fogbugz.com/f/cases/16473/Invoking-a-MenuMorph-on-mousedown-when-positioned-under-the-handmorph-might-trigger-a-choice-on-mouseUp

**Comment by StephanEggermont** [comment]
still needed

**Comment by guillep** [comment]
Well,
 - in native osx apps, apps make sure that the cursor is outside of the bounds of the menu
 - moreover, material design lite and twitter bootstrap
     - make also menus appear outside the cursor 
     - make buttons work on mouse up
https://getmdl.io/components/index.html#menus-section
https://getbootstrap.com/2.1.1/javascript.html#dropdowns

I think the issue here is not in morphic

<blockquote><img src="../assets/favicon.png" width="48" align="right"><div><strong><a href="https://getmdl.io/components/index.html#menus-section">Material Design Lite</a></strong></div><div>A front-end template that helps you build fast, modern mobile web apps.</div></blockquote>
<blockquote><img src="assets/ico/favicon.ico" width="48" align="right"><div><strong><a href="https://getbootstrap.com/2.1.1/javascript.html#dropdowns">Javascript · Twitter Bootstrap</a></strong></div></blockquote>

**Comment by StephanEggermont** [comment]
Huh? How is that relevant? This definitely is a morphic problem, and came from actually observing it

**Comment by guillep** [comment]
How is that a morphic problem? In the example
- there is a "button" that opens a menu on mouse down
- the menu carelessly (or in purpose) open under the cursor
- and menus are activated on mouse down like in any other application that I know of

To me the outcome is expected, I don't see a bug

**Comment by guillep** [comment]
It's also relevant to say that when dealing with low-level events, it's up to the user to define them properly.
Here we are not talking about a button that activates properly on key up as it should, but a handcrafted morph.
And since the menu opening position is explicitly set, how could morphic fix it?

**Comment by guillep** [comment]
As a side note, what this would mean is that morphic apps (and their widgets) should by default behave correctly:
 - ensure that the cursor does not overlap with menus on opening
 - buttons and related widgets should activate on mouse up events
