### ISSUE TITLE
Process>>#isTerminated is Wrong

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#2978]
A process that is on the bottom context, but whose context has already started but not terminated says that the process is terminated.

The following code (easily translated to a test) shows the problem.
We start a process from a manually made bottom context.
That context will stop in a semaphore.
While that context is suspended there, the process says it is terminated, and this prevents us from resuming it (because resuming asks if the process is terminated).

However, the process is clearly not terminated! We have some code after the semaphore that should be executed.

```smalltalk
masterSemaphore := Semaphore new.

context := [ 
	| semaphore |
	semaphore := Semaphore new.
	masterSemaphore	signal.
	semaphore wait.
	
	"Some more code that should be executed, so this process should not be terminated yet."
	self error: 'Throw exception'
	
] asContext.

p := Process forContext: context priority: 40.
p resume.

masterSemaphore wait.
self deny: p isTerminated.
```

**Comment by StephanEggermont** [comment]
Broken since at least Pharo 2.0? Works in Squeak 5.2

**Comment by guillep** [comment]
Another way to reproduce it. `newProcess` will create a process with a bottom context doing `[self value. Processor activeProcess]`. So in the following

```smalltalk
p := [ 1+2 ] newProcess.
p step.	
p isTerminated
```

The stepping operation will just push `self` to the stack, we are before the message send of `value`, but still the process says it is terminated.

**Comment by aranega** [comment]
@guillep with @Larcheveque we checked a little bit the issue, and we found a strange comparison in the `#isTerminated` method. There is many comparison checking if the suspended context is dead, and the final one checks if the suspended context's `startpc` is smaller than the it's `pc`. This looks weird, because it should be almost always the case, unless the process as not started.

```smalltalk
isTerminated
	self isActiveProcess ifTrue: [ ^ false ].
	
	^ suspendedContext isNil or: [
		"If the suspendedContext is the bottomContext it is the block in Process>>newProcess.
		If so, and the pc is greater than the startpc, the block has already sent and returned
		from value and there is nothing more to do."
		suspendedContext isBottomContext and: [
			suspendedContext isDead 
			"The pc of the suspendedContext is set to nil in #terminate explicitly.
				Leaving this line in for safety."
			or: [suspendedContext pc > suspendedContext startpc ] ] ]   "HERE"
``` 

We tried to remove it, but of course, it breaks many tests because the termination of processes seems not effective and so many processes are still considered alived. We really don't know which correction to apply, because we don't know exactly why this last comparison have been added and is doing the job in the common case.

**Comment by guillep** [comment]
Last week @Marmat21 and @dupriezt were looking into it and had more insights too. Maybe they can share them here?

**Comment by isCzech** [comment]
This should fix the problem. Indeed the condition was weird because it was all wrong and made almost any bottom context terminated. All Process and Extended tests are passing (also fixed comment):
```
isTerminated
	self isActiveProcess ifTrue: [ ^ false ].
	
	^ suspendedContext isNil or: [
		"If the suspendedContext is the bottomContext it is the block in BlockClosure>>#newProcess.
		If so, and the pc is greater than the startpc, the block has already sent and returned
		from value and there is nothing more to do."
		suspendedContext isBottomContext and: [
			suspendedContext isDead or: [
				"The pc of the suspendedContext is set to nil in #terminate explicitly.
				Leaving this line in for safety."
 			suspendedContext closure 
				ifNil: [suspendedContext methodClass == Process 
					and: [suspendedContext selector == #doTerminationFromYourself]]
				ifNotNil: [suspendedContext pc >= suspendedContext endPC]
			] ] ]
```

**Comment by dionisiydk** [comment]
The fix is part of my PR #8567  (I did not see this issue originally)

**Comment by MarcusDenker** [comment]
The code examples above are now all working 

So I guess we can close this issue?

**Comment by isCzech** [comment]
Yes, this issue has been fixed a while ago and can be closed. 
Reminder: There's, however, another PR #10644 pending approval, fixing some remaining termination issues.

**Comment by Ducasse** [comment]
Thanks. 
Yes we know about the issue and it is so central that we are always dropping it.

**Comment by isCzech** [comment]
Thanks, Stephane, for your note; I understand your concern, indeed. I can only suggest the same code was implemented in both Squeak and Cuis more than half a year ago and no issues have surfaced since. Although Pharo is 99% similar in this particular area I of course understand it doesn't guarantee something won't pop up. Let me know if and how I can help.

**Comment by Ducasse** [comment]
Thanks for your nice words and understanding. Sometimes our execution paths can differ. For example this is really the case on ephemerons because we use a lot of announcements so they stressed the system different and we found and fix many bugs there. So we really appreciate your efforts and feel bad that we did not react better. We are just always running after the next urgent things to be fixed. :(

**Comment by isCzech** [comment]
I can't even begin to imagine how much effort it is to maintain and advance a system like Pharo and how busy you all must be :) From my limited viewpoint, I'm just not happy I left #terminate in its current state with known shortcomings, all of which are addressed in the PR. Thanks again.

**Comment by isCzech** [comment]
Last note: my fear is once some code start "using" those shortcomings it'll be more and more difficult to fix them.
