### ISSUE TITLE
Use WeakValueDictionary for Undeclared

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3022]
When deleting a class, we check if the class is still referenced and if yes, add it to the Undeclared dictionary. (see #removeFromSystem:)

Suggestion of Pablo:
- use WeakValueDictionary 
- remove the #isReferenced check in #removeFromSystem:, always add the class to Undeclared and then let the GC remove the unused classes
- we have to keep #cleanOutUndeclared as the GC will not remove a class that e.g. is referenced somewhere even though not from code.

This will help to improve the speed as discussed in https://github.com/pharo-project/pharo/issues/2369

**Comment by jecisc** [comment]
Any news on this? Is it on a roadmap?

**Comment by Ducasse** [comment]
Cyril did you see performance regressions?

**Comment by Ducasse** [comment]
Cyril did you see performance regressions/improvements?

**Comment by jecisc** [comment]
@Ducasse There was a huge performance regression between Pharo 6 and 7. I describe it here:

https://github.com/pharo-project/pharo/issues/2369

With the PR I did we are not yet back to the previous performances, but it's much better. I tried to remove all packages with 'Test' in the name and I went from 160sec to 35sec. Now I wait for the CI to see if it does not have an unwanted impact since the change touch the bootstrap and the kernel.

**Comment by jecisc** [comment]
@tesonep If we get back the previous performances, I woul like to pair program a little with you to add a benchmark test.

**Comment by Ducasse** [comment]
Thanks cyril.

**Comment by MarcusDenker** [comment]
I analysed this again... and found a better solution, see https://github.com/pharo-project/pharo/pull/6816
