### ISSUE TITLE
Inconsistencies in Memory file system 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#3047]
```
FileSystem memory inspect
```
provides a new memory file system 

When asked for the working directory using
```
FileSystem memory workingDirectory  
```
this returns 'memory:///'

```
FileSystem memory workingDirectory inspector
```
would open an inspector on the empty file system.

But when we try it the other way around using

```
  'memory:///' asFileReference inspect
```
this would give you an inspector on the current hard disk working directory.

Will I be the only one who thinks this is not consistent? Or did I miss something?

**Comment by astares** [comment]
Reason is simple

  "FileSystem disk"

is hardcoded in String>>#asFileReference

Should we choose dending on storage prefix like:
  memory://   -> memory (as given in MemoryStore>>forReferencePrintOn:
  zip://           -> zip (as given in ZipStore>>forReferencePrintOn:)

and none by default to choose disk?

**Comment by akgrant43** [comment]
Hi Torsten,

I agree, this is inconsistent, but I don't think modifying #asFileReference is practical:

- Memory and Zip file systems don't have a common root (they're not singletons like the disk file system), so there's no way to get from a string by itself to a particular file system.
- 'memory:' and 'zip:' are both valid file names in linux (and probably MacOS), so it is necessary to know whether to expect them or not.

I'd suggest changing the MemoryStore>>forReferencePrintOn: so it doesn't return something that looks like a URL but isn't.  Maybe 'Memory @ /path/to/file' so that it is consistent with DiskStore.

Cheers,
Alistair

**Comment by astares** [comment]
But zip:// is not valid file name in Linux

**Comment by akgrant43** [comment]
But... :-)

```
$ mkdir 'zip:'

$ touch zip\:/a.txt

$ ls -l 'zip://a.txt'
-rw-rw-r-- 1 alistair alistair 0 Mar 29 12:15 zip://a.txt
```

**Comment by astares** [comment]
You can construct foo:// on Linux but not foo:///  with the additional slash from the root dir.

That's why 
```Smalltalk
FileSystem memory workingDirectory printString
```
gives memory:///

So when it has three slashes it depicts a store (other to disk) - no?

**Comment by akgrant43** [comment]
The format of a URL is \<protocol>://\<path>

So:

memory:///

Is saying the memory protocol (memory://) with the root path (/).

But the linux file system ignore empty paths when traversing the tree, so memory:/// is a valid relative path (replacing 'memory' with 'zip' and continuing my example above):


```
$ ls -l 'zip:///a.txt'
-rw-rw-r-- 1 alistair alistair 0 Mar 29 12:15 zip:///a.txt

$ ls -l 'zip:///'
total 0
-rw-rw-r-- 1 alistair alistair 0 Mar 29 12:15 a.txt
```

We could theoretically have something like (untested):

'memory:///path/to/file.txt' asURL asFileReference

And that could give a valid file reference.  But it won't work at the moment because there is no common root to memory file systems.

The following does work:

'file:///path/to/file.txt' asZnUrl asFileReference

It only seems to accept absolute paths.  But:

'file://file.txt' asZnUrl asFileReference 

should also work (notice that there are only two slashes at the start, making it a relative path).  But that's a separate issue. :-)

**Comment by akgrant43** [comment]
I've just realised that github has swallowed the angle brackets (I guess as html).  The URL format is

protocol://path

where 'protocol' and 'path' were in angle brackets before.
