### ISSUE TITLE
Fix ProperMethodCategorizationTest to not enforce running protocol. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3224]
Subclasses of TestCase should have #setUp methods in category running

I ***HATE*** this protocol. We should not enforce it. This is not because K. Beck once 
categorise such methods in running that it should be. 

I suggest that setUp and tearDown should be in a protocol name setup. 

I will change that and the rule and I really wonder why we have this specific rule. 

ProperMethodCategorizationTest

**Comment by astares** [comment]
Unfortunately there is no reasoning (beside personal preferences and "hate") given for this PR. 
You do not even explain why "setup" is better than "running"?

There was a clear reason why Kent used this name: because methods in this protocol are used to prepare or end "running" of the tests. And that's why I wrote this rule.

Using "setup" as category / protocol name is misleading as methods within the category
 - not only set the test up (which is already depicted by #setUp method name) 
 - but also clean up afterwards like tearDown

We made good progress with Pharo as a whole. But still 
 - if we do not not following accepted standards (like SUnit or known in the ST or IT industry as a whole)
 - and anyone (including @Ducasse) can quickly decide depending on personal taste for other rules

then over time we will clutter the system more and more and any cleaning and
unification effort is useless. We are not better than things we damned in the past then (like Squeak)

If you hate what is seen as industry wide standard then disabling the rule in in your personal settings would have been enough instead of adding this PR to the base image.

There is a clear reasons why in business people use Maven, Java, ... and other. Because not only because they are mainstream but also because there is a common understanding and clear definition on how to use them, And that's why Smalltalk and even Pharo sometimes sucks ... because it gives even more freedom but would require even more discipline.

But as I have my doubt's you will understand my POV (as it was often already in the past) I also doubt that this could / will be rolled back.
