### ISSUE TITLE
Could we have better comment for Slot>>emitStore: 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3300]
Why Object new and not #foo for temp name.
What is the logic?
Needs comments 
Why this code is duplicated in subclasses?

emitStore: aMethodBuilder
	| tempName |
	tempName := Object new.
	aMethodBuilder
		addTemp: tempName;
		storeTemp: tempName;
		popTop;
		pushReceiver;
		pushLiteralVariable: #slot -> self;
		pushTemp: tempName;
		send: #writeSlot:value:

**Comment by MarcusDenker** [comment]
using #foo would override the value of a temp 'foo'... but I think we can use a name that is not a valid temp in these cases.

Why this code is duplicated in subclasses?

The problem is that InstanceVariableSlot overrides both the emit* methods, so this means that the reflective methods are not called (as they are if you subclass Slot or IndexedSlot).

I think we should not allow subclassing InstanceVariableSlot, as it is an optimisation. All clients should subclass IndexedSlot and implement optimisations explicitly. (which then might result again in code some duplication... e.g. if they want to do the same as InstanceVariableSlot for read or write, or optimise reflective queries like #isWrittenIn: to use byte code instead of the AST.

**Comment by MarcusDenker** [comment]
But it is better, as the current scheme to copy emitStore:  from Slot means that #isWrittenIn: will not be correct.

**Comment by MarcusDenker** [comment]
I think this will improve quite a lot when we provide general Slot composition: most subclasses will then be Wrappers or Decorators for slots...

I will fix the temp vars and add some ducumentation for now
