### ISSUE TITLE
Facilitate Pharo 8 FastTable cell extensions load in Pharo 7

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#3306]
I'm working on a project in Pharo 7 that I'd like to do cell operations with FastTable.
With two small cleanups, Pharo 8 FastTable that has been extended wit cell operations can be FiledOut and loaded into Pharo 7 with all tests green. PR incoming.

**Comment by jecisc** [comment]
At some point I was thinking about creating a FastTable-Compitibility project loadable in Pharo7. 
I did not do it because I did not had time. But if you need it, maybe we can do it. It should be pretty easy because I tried to add deprecation transformations for all changes in the API and I think nothing should break old behavior (or not much)

**Comment by bencoman** [comment]
I had a PR to submit but my Pharo 8 Iceberg hit a UI bug for a **remotes** droplist selection.
Here are the only two changes I needed so a Pharo 8 FileOut of the three FastTable packages 
cleanly load and run in Pharo 7...
```
FTSelectionStrategy>>table: aFastTableMorph
	^ self basicNew initialize  "because Pharo 7 complaining 'Use: #table:' [instead of #new]"
		table: aFastTableMorph;
		yourself

FTTableMorph>>selectionModeStrategy 
	selectionModeStrategy ifNil: [ self beRowSelection ].  "to avoid red panes of death"
	^selectionModeStrategy
```
@jecisc Could you apply these?
