### ISSUE TITLE
Harvesting Nicolas's speedup

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3322]
http://smallissimo.blogspot.com/2019/05/accelerating-large-integer-arithmetic.html

**Comment by SergeStinckwich** [comment]
I start to have a look to this. As mentionned by @nicolas-cellier-aka-nice on his blog, I propose to do it in two commits: 
- [ ] add ``Integer>>multiplyByInteger:`` and ``Integer>>divideByInteger:`` hooks so that subclasses can redefine their own. Redefine ``Integer>>*``, ``Integer>>quo:`` and ``Integer>>/`` to use these hooks.
- [ ] Modify/add users of the previous methods for ``LargeInteger`` (``LargePositiveInteger`` in Squeak), add methods ``digitMul22:``, ``digitMul23:``, ``digitMul33:``, ``digitDiv21:``, ``digitDiv32:``, ``digitDivSplit:``,``digitMulSplit:``, ``inplaceAddNonOverlapping:digitShiftBy:``, ``squaredByFourth``, ``sqrtRem``, ``squaredByHalf``, ``squaredByThird`` and ``squaredByFourth``. Add tests.

@nicolas-cellier-aka-nice any comments ?

**Comment by SergeStinckwich** [comment]
@Ducasse Any comments ?

**Comment by Ducasse** [comment]
For me I'm bad with number so go ahead and write some bench to see the gain.

**Comment by guillep** [comment]
This issue looks more like a small project than an actionable issue.
I propose we move it to a wiki with potential projects for people to contribute.
I'm collecting all these.
Could be a great basis for GSOC.
