### ISSUE TITLE
methods and protocols selection needs confusing extra clicks

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#3345]
in Calypso, if you have selected method or protocol, the next click that changes focus to this list removes the selection. That causes the need for extra clicks:

1) you have a selected protocol and a selected method with a focus on the methods pane
2) the next click on the protocol deselects it, a message template for a new method without assigned protocol is displayed
3) click on a protocol selects it, the message template for a method in this protocol is displayed
4) you click on a method name, the method is not correctly displayed because it was in fact deselected so a message template for a method without assigned protocol is displayed
5) the second click on the method selects it

![6hyWBptYJQ](https://user-images.githubusercontent.com/572494/57676279-75470680-7624-11e9-8b20-91af89905f38.gif)

**Comment by bencoman** [comment]
I second that motion :)  
I got used to it but its still annoying.

**Comment by dionisiydk** [comment]
I think I agree with you. I did not feel in used to it after long time. When you deselect protocol the tab with method is still here but not selected. And to select it again the habit wants to select the method instead of tab and here the workflow breaks.  

The story about this feature is to have similar behaviour as with single pane (no tabs) browser and in same time keep "restore selection" behaviour.
So in old browsers deselecting protocol gives you "new unclassified method pane" and resets existing method selection. 
In Calypso when you deselect the protocol the method pane is updated and previous selection is restored. It is general logic to restore selection anytime when content of pane is updated. Specifically it allows to switch between classes and see same selected method where it exists (try with #initialize method for example). 
So when discussed feature was not implemented this behaviour did not allow to create new unclassified method in this scenario because when method is selected the method tab become active. There were complains about it. 

So the question is how to improve it. I think "restore selection" is useful and important feature and we would like to keep it. But managing it in various scenarios is not really easy.

**Comment by pavel-krivanek** [comment]
Maybe it is more Morphic/FastTable related issue. The first click on the selected item going from another focus should be ignored.

**Comment by dionisiydk** [comment]
ср, 15 мая 2019 г., 9:46 Pavel Krivanek <notifications@github.com>:

> Maybe it is more Morphic/FastTable related issue. The first click on the
> selected item going from another focus should be ignored.
>
It will not fix your scenario. If selection will not change then tabs
selection will not change either. And method tab will be not shown.
