### ISSUE TITLE
Emergency evaluator while debugging some code

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3371]
In a playground I tried to debug this code:

```Smalltalk
1 to: 10 do: [ :e | 1halt. e log ]
```

And in the debuggeur I only did step through all the time. After a while (when I go on the halt) I get an emergency evaluator.

It happens in Pharo 8.

**Comment by Ducasse** [comment]
Thanks Cyril.

**Comment by dupriezt** [comment]
Same issue when stepping **over** a halt message.

**Comment by dupriezt** [comment]
I dug a bit (I started from another example, but the issue is the same).
Full report: [SteppingOverASelfHaltOpensAnEmergencyEvaluatorInP8.pdf](https://github.com/pharo-project/pharo/files/3467083/SteppingOverASelfHaltOpensAnEmergencyEvaluatorInP8.pdf)
Basically, the issue is in `GTGenericStackDebugger>>#setDebuggerToFirstNonFilteredContext` when a debugger for the halt that is stepped over is opened. The stack only contains one context: `Object>>#halt`, which is filtered out because the method has the #debuggerCompleteToSender pragma. So the filtered stack is empty, and #setDebuggerToFirstNonFilteredContext sends #first to this empty collection.

The question is why the unfiltered stack for the halt that is stepped over only contains one context and nothing else.

**Comment by MarcusDenker** [comment]
I added a empty check to the setDebuggerToFirstNonFilteredContext method. Now there is no DNU

**Comment by MarcusDenker** [comment]
(was merged as part of another PR)

**Comment by MarcusDenker** [comment]
This now works fine in Pharo9
