### ISSUE TITLE
Ctrl + O + W is not a good idea to open the workspace.

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#3393]
As O and W are quite far on the keyboard and CTRL + W is mapped on the window closing, it may happen that the strokes on O and W keys are not fast enough that will result to the closing of the current window. Which is not a good thing..

I will prefer to have something like CTRL + SHIFT + W (or P as it is call Playground). It will avoid further issues...

Let me now if you share my idea!

**Comment by jecisc** [comment]
CTRL + SHIFT + W would break coherence I think because currently all shortcuts to open the main tools are meta + o + {something}. 

It would make it harder to remember to have on tool in the list without that pattern IMO.

Maybe we can choose another key than W since it's not called the workspace anymore, but not change the meta + o part.

**Comment by Alisu** [comment]
I have to agree with vincent, i often close some windows instead of opening the playground.
Another thing that would be nice is to be able to recover last closed windows with a shortcut.

**Comment by VincentBlondeau** [comment]
still open

**Comment by astares** [comment]
The term Workspace is a thing of the past anway. 

It's "Playground" now since several Pharo iterations - so CTRL + O + P comes to mind which is unfortunately already taken for opening Monticello browser. But we should remap anyway.

I also wonder why these are not visible in WorldMenu -> System -> Keymap Browser

Overall Key handling in Pharo is still a mess - try to use function keys like "F1" which normally opens help on Windows. One would not even get the events into the image last time I tried. I guess hard to fix due to VM issues / events ....

**Comment by Ducasse** [comment]
Totally agree. We should revisit all the key mapping and the tools too. 
I think that we need more people joining the consortium or doing less things.

**Comment by jecisc** [comment]
In Pharo 12 we removed the Monticello Browser. Maybe we could remap the shortcut to cmd + o + p for "open playground" now?
