### ISSUE TITLE
Add test for: Adding an instance class variable remove the traits of a class

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#3437]
If you have a class with traits and use #addClassSlot: on it (or #addSlot: on its instance), it will remove the traits of the class.

**Comment by MarcusDenker** [comment]
I think #fillFor: is missing to set the trait (using #traitComposition: )

**Comment by MarcusDenker** [comment]
here is a failing test (for class T2TraitWithComplexSlots)


testTraitWithComplexSlotAddSlot
	| t1 c1 |
	
	self createSlotClass.
	t1 := self newTrait: #T1 with: { #ivar  }. 
	c1 := self newClass: #C1 with: { #aSlot. } uses: {t1}.

	
	self assert: (c1 traitComposition includesTrait: t1).
	
	c1 addSlot: #ivar2 => InstanceVariableSlot.
	self assert: c1 instVarNames equals: #(aSlot ivar ivar2).
	self assert: (c1 traitComposition includesTrait: t1).


The interesting thing is that the slot from the trait is survives, but the slot from the class is lost

**Comment by carolahp** [comment]
@MarcusDenker 
In the test if we ask for `c1 instVarNames` before the slot addition we only have `#(aSlot)` , `#ivar` is not considered as an instance variable because `instVarNames` only considers local slots and `#ivar` is not considered as such.

After the installation of the `#ivar2` slot, when we ask for `c1 slots` we have all the slots `#(aSlot ivar2 ivar)`.

Should `instVarNames` include the slots got from Traits?

**Comment by MarcusDenker** [comment]
I have test, it it green in Pharo8. So I guess we fixed this.

testTraitWithComplexSlotAddClassSlot
	| t1 c1 |
	self createSlotClass.
	t1 := self newTrait: #T1 with: { #ivar }.
	c1 := self newClass: #C1 with: { #aSlot } uses: { t1 }.
	self assert: (c1 traitComposition includesTrait: t1).
	c1 addClassSlot:  #ivar2 => InstanceVariableSlot.
	self assert: c1 instVarNames equals: #( aSlot ivar ).
	self assert: c1 class instVarNames equals: #( ivar2 ).
	self assert: (c1 traitComposition includesTrait: t1)
