### ISSUE TITLE
Code coverage calculation code is lacking a proper abstraction

### ISSUE THREAD

**Issue by gcotelli** [guillep/pharo-core#3568]
Code coverage is calculated in `TestRunner>>#collectCoverageFor:` which is an User Interface class. IMHO is lacking a proper abstraction so anyone can use it without a test runner.

For example smalltalkCI is using it's own implementation with a different technique and now the coverage reporting is broken for packages containing traits: hpi-swa/smalltalkCI#427 .

`HDTestCoverage` is also implementing some coverage calculations in the spirit of smalltalkCI, so it's probably broken too.

**Comment by Ducasse** [comment]
We are about to throw away all the UI and the TestRunner because it is badly designed. Check DrTests on Spec.
In addition SUnit offers three different ways to do the same and we should clean it. We started to work on the Runner but the core should also be cleaned. Any action in that perspective is welcome.

**Comment by MarcusDenker** [comment]
yes, it would be nice to make a generalised code coverage tool
