### ISSUE TITLE
Regression with drag and drop

### ISSUE THREAD

**Issue by hilaire** [guillep/pharo-core#3679]
PasteUpMorph>>dropFiles:

Looks wrong in P7 and P8.
A Write stream is created while a Read stream is expected.
Result: drag and drop of a sketch file does not work anymore in DrGeo.
Should it be a binary read stream or just a read stream?
With a read stream it works fine for DrGeo, not sure about other.

See https://github.com/pharo-project/pharo/issues/2634 too

[PasteUpMorph-dropFiles.st.txt](https://github.com/pharo-project/pharo/files/3337844/PasteUpMorph-dropFiles.st.txt)

**Comment by svenvc** [comment]
This is indeed not such a simple situation, since it requires insight into the services framework, which is a bit quirky (from what I have seen of it). I certainly don't understand all aspect of it.

I think that the only sensible thing to do is to pass a FileReference object around, not an open stream, since after all, that is what you are dropping, and then leave to opening of the file to the latest possible moment.

**Comment by hilaire** [comment]
In the meantime, could we reverse to a situation equivalent to the previous one? 
=>A read stream is passed on to the drop event handlers

**Comment by svenvc** [comment]
you said it has to respond to #name, which the new streams don't do and never will, hence my suggestion

**Comment by hilaire** [comment]
Ah yes indeed.

**Comment by tomooda** [comment]
+1 for passing a FileReference. I admit I have a same problem to read a dropped stream and hacked the stream object as a nasty workaround.
