### ISSUE TITLE
remove testPerformanceInlined_ifNotNil and testPerformanceInlined_ifTrue

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#3955]
testPerformanceInlined_ifNotNil and testPerformanceInlined_ifTrue: it is not clear what they are testing as the method #timingPriorityHandleEvent does not exist

**Comment by bencoman** [comment]
`#timingPriorityHandleEvent` was unrolled into `#runBackendLoopAtTimingPriority`.
Because the delay scheduler runs frequently at the highest priority, the very original delay scheduler code inherited from Squeak used ugly "highly optimized" code like...
```
suspendSemaphore isNil ifFalse: [ xxxx ].
```
because of the methods it expected to be inlined.  
But Pharo inlines `#ifNotNil:` so its better to use that.  If someone turned off that inlining the system should slow down a lot (probably be interesting to test).  What I was trying to record is this "requirement" to a proper functioning system (performance wise) - but I'm not completely sure that is the right path to take.  @MarcusDenker I'm interested whether your consider that is worthwhile, is-not, or another approach is preferred.

**Comment by MarcusDenker** [comment]
for #ifTrue: it makes not really sense... that would be a huge change with lots of impact anywhere if it would be changed...

For the #ifNil:, one could let the test check the method directly... but I wonder if it is needed:

this test would make sense if it was there to guard a 

(someting == nil) ifTrue:

because in the past people wanted to turn that into #sNil, which is slower. But as it is bow #ifNil: already, we reached the steady state that no-one will want to change due to some coding rules.

That means that a comment might be enough ("we use ifNil: here because it is inlined by the compiler")

**Comment by MarcusDenker** [comment]
A PR: https://github.com/pharo-project/pharo/pull/4086

- comment out debug checks
- use #== instead of notNil
- ban the notNil rule for the class
- remove the two tests that checked for optimzied coed
