### ISSUE TITLE
Pharo contains deprecated methods that are not in a deprecated package

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4140]
I think we should ensure that deprecated methods are in deprecated packages to make their removal easier. 

I propose to correct it for all current deprecated methods and then add a release test. 

We can find them like this:

```Smalltalk
Smalltalk allClasses select: [ :c | c methods anySatisfy: [ :m | m isDeprecated and: [ m package isDeprecated not ] ] ]
```

Note that it might take some time to correct the problem since some of them are in Iceberg.

**Comment by PharoProject** [comment]
I don't think this is a good move, because it complexifies a lot the
dependencies and the baselines.

Removal is also not easier, is just the same in my opinion. We could do a
script as the one you showed removing the methods.

I think this idea of having a deprecated package is a remnant of the old
build system using mutation of images and mc packages.

Le dim. 28 juil. 2019 à 22:09, CyrilFerlicot <notifications@github.com> a
écrit :

> I think we should ensure that deprecated methods are in deprecated
> packages to make their removal easier.
>
> I propose to correct it for all current deprecated methods and then add a
> release test.
>
> We can find them like this:
>
> Smalltalk allClasses select: [ :c | c methods anySatisfy: [ :m | m isDeprecated and: [ m package isDeprecated not ] ] ]
>
> Note that it might take some time to correct the problem since some of
> them are in Iceberg.
>

**Comment by jecisc** [comment]
Well, at least something needs to be done because currently at each release we only remove the DeprecatedX0 package and some methods in Pharo 8 are deprecated since multiple versions and were never removed.

I liked the idea to move them in DeprecatedX0 because since it's the last package loaded it force us to remove the invocations on the deprecated methods.

**Comment by PharoProject** [comment]
let's remove old deprecated methods then :)

Le dim. 28 juil. 2019 à 22:23, CyrilFerlicot <notifications@github.com> a
écrit :

> Well, at least something needs to be done because currently at each
> release we only remove the DeprecatedX0 package and some methods in Pharo 8
> are deprecated since multiple versions and were never removed.
>
> I liked the idea to move them in DeprecatedX0 because since it's the last
> package loaded it force us to remove the invocations on the deprecated
> methods.

**Comment by jecisc** [comment]
I mean that something needs to be done to correct the problem and also to not introduce it again. Adding a release test to ensure deprecated methods are in a deprecated package it's something I can do. But the Pharo releases is not a process I can change myself (I don't even know where the scripts are), so if the release test solution is not acceptable, we will need someone who can change the release process to do the better solution and add post major releases actions.

**Comment by guillep** [comment]
I understand, but from my point of view having a DeprecatedXX package has never really worked like that. What I mean, having the deprecated package or not, we still have the problem ^^. Sure, having the package simplifies the removal as you can remove the entire package in a single click. But you do that once a year, so you bring up a lot of problems with baseline dependencies during the whole year just to optimize something you do once a year...

Just to clarify, what I'm saying is that I think we can achieve what you want without the deprecated package :). For example, we could have a release test that checks deprecated methods without the need for a package:
```
self assert: self deprecatedMethods isEmpty
```
where
```
deprecatedMethods
^ Smalltalk allClasses select: [ :c | c methods anySatisfy: [ :m | m isDeprecated ] ]
```
Wouldn't that be enough? Also, now we can tag deprecations with versions and dates (`deprecated:on:in:`), to filter even further :).

We could even have some method that cleans deprecations
```
self deprecatedMethods do: #removeFromSystem.
```

Something else to take into account: from what I remember, we did not remove deprecations at the beginning of the release because @Ducasse wanted some time to adapt from deprecations before their removal. So if we are going to put such a test, that test will not pass during those period of time. So there are other reasons than the pure technical here.

**Comment by guillep** [comment]
> But the Pharo releases is not a process I can change myself (I don't even know where the scripts are)

https://github.com/pharo-project/pharo/tree/Pharo8.0/bootstrap

;)

<blockquote><img src="https://avatars3.githubusercontent.com/u/1838382?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">pharo-project/pharo</a></strong></div><div>The Sources for Pharo. Contribute to pharo-project/pharo development by creating an account on GitHub.</div></blockquote>

**Comment by gcotelli** [comment]
Having all the deprecated methods/classes in one package has some
advantages, not only that you can easily stop loading them.
For the code already included in Pharo I think that the one guy deprecating
a method/class should be responsible of fixing the senders/references in
the Pharo image, and we should not merge a PR if deprecates a method/class
and not fixes the senders/references in the Pharo image. In this case you
don't have any problem moving this methods to the Deprecated-Vxx package
and loading it last in the baseline while the version is in development.
Once we enter the release candidate phase we can stop loading by default
the deprecation package but I wouldn't delete it in the repository yet.
Since a lot of deprecations includes rewrite rules that automatically fixes
the code, external package maintainers can load the deprecation package for
the corresponding version, and fix his packages. Once a Pharo version is
released we can remove from the repository definitively the deprecation
package for the previous version.

If we remove the deprecated methods in several commits and the external
package maintainers don't have an easy to way to load it while adapting
it's packages this whole deprecation effort will not work.

One can argue that the best way for external package maintainers is to keep
up with the development version, but the reality is that most of the time
the new stuff in the development version is in flux and it's a waste of
time to keep trying to be up to date with the last one all the time. So
usually people will wait until the version stabilizes a little (in my case
I wait until we are close to a release candidate) for fixing the external
packages. So having the possibility of loading the Deprecation package at
this time it's a great help for external package maintainers.

For sure we can discuss on how to improve the deprecation process, so it
helps not only the core Pharo maintainers but also the maintainers of
packages in the whole ecosystem.

**Comment by guillep** [comment]
> For the code already included in Pharo I think that the one guy deprecating a method/class should be responsible of fixing the senders/references in the Pharo image, and we should not merge a PR if deprecates a method/class and not fixes the senders/references in the Pharo image. In this case you don't have any problem moving this methods to the Deprecated-Vxx package and loading it last in the baseline while the version is in development.

Sure! Now, this means that maybe the better release test would be to test that deprecated methods/classes are not used. While this would be more complicated with methods due to the absence of type information, it can be doable with classes. Furthermore, classes are actually the ones introducing the most problems, because a class cannot be loaded without its superclass.

Now, it is not common that people deprecating methods also remove all users ^^. Even myself I do it from time to time.

> For sure we can discuss on how to improve the deprecation process, so it helps not only the core Pharo maintainers but also the maintainers of packages in the whole ecosystem.

Please!

> So usually people will wait until the version stabilizes a little (in my case I wait until we are close to a release candidate) for fixing the external packages. So having the possibility of loading the Deprecation package at this time it's a great help for external package maintainers.

Well, this is an argument in favour of the deprecated package :).
However, I'd argue that we should keep a separate set of repositories with deprecations, otherwise users will need to lookup the history to find the good version of the package.

**Comment by bencoman** [comment]
On Mon, 29 Jul 2019 at 16:55, Guille Polito <notifications@github.com>
wrote:

> For the code already included in Pharo I think that the one guy
> deprecating a method/class should be responsible of fixing the
> senders/references in the Pharo image, and we should not merge a PR if
> deprecates a method/class and not fixes the senders/references in the Pharo
> image. In this case you don't have any problem moving this methods to the
> Deprecated-Vxx package and loading it last in the baseline while the
> version is in development.
>
> Sure! Now, this means that maybe the better release test would be to test
> that deprecated methods/classes are not used. While this would be more
> complicated with methods due to the absence of type information, it can be
> doable with classes.
>
Ideally as part of the Bootstrap the CI would be run before loading
deprecated packages to iron out dependencies,
and then after loading deprecations the CI would run again to check they
don't break anything.
Downside is longer CI run, but maybe worth it to save developer-time.

**Comment by Ducasse** [comment]
Hi guys

I started the migrator project just for this purpose and I need help. 
I went over all the deprecated methods in old Pharo version and package them. 

For me the key aspects is that we should be able to load code easily: I want to load, run the tests and get my code automatically ported. :)

https://github.com/Ducasse/Migrator



<blockquote><img src="https://avatars2.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Ducasse/Migrator">Ducasse/Migrator</a></strong></div><div>A list of extensions with automatic transformations to ease migration. - Ducasse/Migrator</div></blockquote>

**Comment by guillep** [comment]
@Ducasse how do you create those packages? by hand?

**Comment by Ducasse** [comment]
Yes I took an old version of Pharo and I look at the deprecated methods (either the one in deprecated categories or call deprecated) and I harvested them. 
What I would like to do is to take Deprecated80 once it is available and I clean it and create a FromPharo70ToPharo80 package in Migrator.

**Comment by gcotelli** [comment]
Maybe we can start by moving all the deprecated methods/classes to Deprecated80 package, fix the remaining senders/references in the image, and then moving this package under a new name in the Migrator project? 

Certainly we need some note on how to use the Migrator, so external package maintainers can found that it exists and how to apply to its own packages (maybe fork it under `pharo-project` umbrella). And we also need some kind of deprecation guide explaining what to do to deprecate new code, so people will move the deprecated code to the Migrator package and some kind of test so no new deprecated code gets included in the base image.

What do you think? If we get some actionable items here certainly I can help with some of them.

**Comment by gcotelli** [comment]
BTW, the original snippet is missing class methods: 
```smalltalk
Smalltalk allClasses select: [ :c | c class methods anySatisfy: [ :m | m isDeprecated and: [ m package isDeprecated not ] ] ]
```
and whole classes deprecated:
```smalltalk
Smalltalk allClasses select: [ :class | class isDeprecated and: [ class package isDeprecated not ] ]
```

**Comment by gcotelli** [comment]
@Ducasse @jecisc @guillep any opinion on the comments above?

**Comment by jecisc** [comment]
IMO, the fact that we have a DeprecatedXX package is not a problem. It helps with the removal of deprecated stuff and also helps with the creation of the migration package.

I agree than sometimes it might be hard to fix all users of a deprecated class/method (for example for the #name method we had before, or for Ring, or for the old streams...). In that case, we might keep them at their original place. But I don't see the problem about moving things where all users were updated in a DeprecatedXX package. On the contrary, since it's loaded last and might crash the build if its content is still used, we ensure that we do not use once again some deprecated code.

**Comment by astares** [comment]
Agree with @jecisc here.

For now I dont understand what the problem with DeprecatedXXX package is. It is a simple concept that has proven as working in the past. 

Several benefits of the approach:
- simple to understand and use
- we can simple unload it to get rid of the old deprecations and move on to working on the next versions
- Pharo users can easily spot if they reference a method or class from this package
- helps in creation of migration or compatibility packages

**Comment by MarcusDenker** [comment]
This now look much better... some left, but they are from externally managed packages

**Comment by MarcusDenker** [comment]
(we have opened dedicated issues for those not yet fixed)
