### ISSUE TITLE
Pharo freezes when toggle to full screen

### ISSUE THREAD

**Issue by wyattbiker** [guillep/pharo-core#4412]
Pharo both 7 and 8.
Mac OS X Mojave

Pharo is unresponsive when switching to Full Screen mode.

Pharo menu > Windows > Toggle Full Screen mode
![image](https://user-images.githubusercontent.com/930478/63621556-3b41b500-c5c2-11e9-9d3d-f4c8f3deae33.png)

![image](https://user-images.githubusercontent.com/930478/63621318-9f17ae00-c5c1-11e9-8a7d-4e36f7f80417.png)

**Comment by Ducasse** [comment]
Thanks I confirm that I could reproduce it. 
We will have to check with the new headless VM if this behavior stays the same.

**Comment by StephanEggermont** [comment]
Well known vm bug. I triangulated where it was introduced.
https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/380

**Comment by wyattbiker** [comment]
Is it Mac OS only? Just curious.

**Comment by Ducasse** [comment]
Probably and all the code is about to be thrown away.

**Comment by tesonep** [comment]
Hi Stephan,

Thanks for the report, I have fixed the issue in the vm long time ago.
However, we are using a very old stable vm for pharo that does not include
that fix. Basically, there have never been an stable version after the one
we are using. Mostly about the change to use metal and other vm changes
that were never stable.

It is fixed in the headless vm, as it uses sdl and sdl works perfectly fine.

I can try to push those changes in pharo branch, and generate a vm so it
can be tested.

Cheers,
Pablo

**Comment by seandenigris** [comment]
I confirm that the bug is not present in both P8 and P9 headless VMs. Also, if someone is dumb enough (like me) to check for the bug in an image they still need, the image may get "stuck" in headless mode even after force quitting and restarting. The fix is: `/path/to/vm/Pharo /path/to/image/PharoLauncher.image eval 'Display toggleFullscreen'`

**Comment by jumble** [comment]
Ran into this today in Ubuntu 18.04- when entering fullscreen mode, the Pharo window disappears, while its icon on the taskbar seems to rapidly "toggle" between minimized and maximized states for several seconds before settling in an unresponsive state. I have only been able to recover from this state by restarting the image.

**Comment by astares** [comment]
So far it is working and issue is rather old.
