### ISSUE TITLE
Move to class package should be rename Move to the defining class

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4451]
Right now to move a class from an extension to its defining class we should use the refactoring named Move to class package.

**Comment by dionisiydk** [comment]
Hi @Ducasse .

I agree that current name can be better. But proposed name sounds like move to class instead of package.

**Comment by Ducasse** [comment]
Move to defining class.... means move to the class defining the method and not the package so the name I propose is good.

**Comment by dionisiydk** [comment]
But command performs move to package. It does not move the method to any class.

**Comment by dionisiydk** [comment]
@Ducasse Maybe it is intuitively understandable name. Like if the method is anyway belonging to the defining class (it is always true by definition) then when we move it to defining class we fix some other defining properties.

I just wanted to point that "word to word" meaning is a bit misleading. And the comment explaining it can be very important.

**Comment by jecisc** [comment]
Maybe something like "Move to base" or "Classify in base class"?

**Comment by StephanEggermont** [comment]
Move to package defining the class? (It is only easy once we agree on the text to use :) )

**Comment by leonardoce** [comment]
In my humble opinion, the proposal by @StephanEggermont is nice, and it's even better since this command is just after "Move package". Look at this:
  
![renamed_command](https://user-images.githubusercontent.com/1572058/66265227-3011b400-e813-11e9-95f5-96c6890c0a8a.png)

Now I think it's clear that the command is not moving the method to any class, like @dionisiydk was saying.

I have a patch implementing the behavior you see in the screenshot that just change the command description. If you want, I can rename the class too. Now it's named `SycMoveMethodsToClassPackageCommand`, what do you think of `SycMoveMethodsToPackageDefiningClassCommand`? The new name is too long for my tastes, and I'm uncertain about leaving the name as it is or not.

**Comment by Ducasse** [comment]
Ok for me: "Move to package of the defining class. " else in english is should be 
Move to defining class package.

@Cyril there is no concept of base class and in C++ it means superclass.
