### ISSUE TITLE
Integrate MiniBeacon

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#4537]
I cleaned and created a mini beacon version out of Beacon. 
We should integrate it.

**Comment by Ducasse** [comment]
The code of pharo/Beacon contains the latest version. Should learn how to add beacon-core + tests to Pharo

**Comment by jecisc** [comment]
If we integrate a logger to Pharo we should at least have a File logger IMO. Why users want a logger, it's the main one they'll use.

**Comment by Ducasse** [comment]
well if you look at the current transcript usage in the image, they do not need a file. So if people want more then they will load it. So far I never needed a file logger and my objective is at least to offer an alternative to transcript show.

**Comment by jecisc** [comment]
If it's just to log in a transcript, what will beacon bring more? I don't see the value to add a lot of announcements if there is no new feature.

**Comment by Ducasse** [comment]
The same as systemLogger: having real objects instead of strings and this is a game changer.
Logging is not about strings but about objects!!!!

**Comment by akgrant43** [comment]
Hi Cyril,

> If it's just to log in a transcript, what will beacon bring more? I don't see the value to add a lot of announcements if there is no new feature.

Beacon brings much more than logging to the transcript.

Mostly I use in-memory loggers, e.g. CircularMemoryLogger, which means I typically log something like:

```
signal := StringSignal new message: 'got to here'.
signal properties at: #suspectObject put: anObject.
signal emit.
```

Now I can inspect the log, see where this happened in relation to other objects and inspect anObject.

I really suggest you read: http://www.humane-assessment.com/blog/debugging-duplicated-behavior-with-gtinspector/ (I know this is biased because I'm working with Doru now, but I started using this long before I joined).

I've used a file logger a couple of times in the last few years: once when the problem only occurred in headless mode, and once when the problem caused the image to become 100% cpu bound and the UI unresponsive.  So the file logger definitely has a place, but it's fairly infrequent.

<blockquote><div><strong><a href="http://www.humane-assessment.com/blog/debugging-duplicated-behavior-with-gtinspector/">Humane assessment</a></strong></div></blockquote>

**Comment by akgrant43** [comment]
Hi Stef,

I've merged your changes back in to https://github.com/feenkcom/pharo-beacon if you'd like to merge directly from there.

I have some more enhancements planned, e.g. when inspecting a memory log it would be nice to be able to display relative times instead of absolute times so that performance issues are easier to spot.

Thanks for your refactoring!
Alistair


<blockquote><img src="https://avatars2.githubusercontent.com/u/22122366?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/feenkcom/pharo-beacon">feenkcom/pharo-beacon</a></strong></div><div>Beacon is a small event and logging framework for pharo - feenkcom/pharo-beacon</div></blockquote>
