### ISSUE TITLE
Review #asInteger 

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#4701]
As reported by Frank Lesser [LSW] on Discord today in channel #development:

```Smalltalk
(1/2) asInteger = 0
``` 

caused by Number >>#asInteger - not conforming to ANSI

**Comment by nicolas-cellier-aka-nice** [comment]
I just wonder the rationale for answering rounded (nearest int), is it really in the final version?
Which dialect is conforming to this?
Not st80, so not surprisingly not VW/Squeak/Pharo...

**Comment by frank-lesser** [comment]
I dont want to participate on a discussion weather asInteger should truncate or round.
ANSI defines rounded and Stephane Ducasse as the Pharo autority decided to keep the truncated version with
a clear comment in the implementation.
How I myself fixed senders of asInteger is to use either rounded or truncated. In Pharo you have for instance 
BitBlt >>#roundVariables, which IMO gets improved when using rounded instead of truncated.
And yes there exists Smalltalk dialects which conforms to the ANSI standard including my own.

**Comment by Ducasse** [comment]
Hello nicolas 
what do you think? 

@frank-lesser I do not understand your point then. 
we have to balance risk gain ratio when we change something that is in the core. Remember that this definition works since 1998. 
And ANSI is not an objective for us. If we are compatible then it is good else we do not care. Remember Pharo is not Smalltalk. Our objective is not to build Smalltalk. Our objective is to build Pharo :)
Now if you see places that can take advantage of rounded instead of truncated, open bug entries and we will check them. 

About roundVariables, I see that it is used in the primitive so we will have check.

**Comment by frank-lesser** [comment]
my  point was to accept the decision with the clear comment in the implementation, and to review senders of asInteger ( example roundVariables ) in order to improve the quality.
But if you dont care about ANSI, even the comment is unneeded.

**Comment by nicolas-cellier-aka-nice** [comment]
Even if ANSI conformance is not a primary goal, the knowledge of conformance still has a value.
For now, I would say that asInteger behaviour is a legacy from st80, but we have no clue of the driving rationale, neither in ANSI, nor in st80...
ISO/IEC 10967-2 does not seem to have any rule covering a generic convert float->int
§5.4.2 of draft http://www.open-std.org/JTC1/SC22/WG11/docs/iso10967-2_2001_e.pdf only covers explicit rounding direction...
Some other dialects like Dolphin and gst are conformant and use rounded...

I would advise using explicit direction whenever possible.

<blockquote></blockquote>

**Comment by Ducasse** [comment]
Frank Ok I got your point. Thanks for the clarification. We should at least document the difference in a comment. This has a value.
