### ISSUE TITLE
Protocol>>#methods is missleading

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#4878]
Currently, Protocol>>#methods return a collection of selectors. 

This is misleading for me because I expected a collection of compiled methods.

I propose to change this in two steps:
- In Pharo 8 we deprecate #methods in favour of #methodSelectors and we can add a method #compiledMethods 
- In Pharo 9 we deprecate #compiledMethods and we rename it into #methods.

**Comment by kasperosterbye** [comment]
The status of this on is that in P8 `methods` were deprecated and `methodSelectors` added. In P9 `methodSelectors` are still here. The method  `compiledMethods' was never made. I suggest we stick to `methodSelectors` do not add a `compiledMethods` (if it was important/useful I presume someone would have added it since).

I suggest to close this issue.

**Comment by MarcusDenker** [comment]
yes, the main goal of the Issue was to not have #methods returning selectors, and that is fixed
