### ISSUE TITLE
Autocompletion is slow for images with a lot of source code

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#4896]
Especially in the debugger. In attachment is the process tally of a 10 secs profiling of some typing of characters in the debugger code panel
[processTally.txt](https://github.com/pharo-project/pharo/files/3719407/processTally.txt)

The image used is the Lifeware one.

**Comment by jecisc** [comment]
It would be great to push the work of Clément and Sophie on string comparison. 

https://clementbera.wordpress.com/2018/02/17/massive-string-comparison-performance-boost-up-coming-in-the-cog-vm/

Since a lot of time is spent in the sorting, it might help a lot here. 

<blockquote><img src="https://s0.wp.com/i/blank.jpg" width="48" align="right"><div><img src="https://s1.wp.com/i/favicon.ico" height="14"> Clément Béra</div><div><strong><a href="https://clementbera.wordpress.com/2018/02/17/massive-string-comparison-performance-boost-up-coming-in-the-cog-vm/">Massive String Comparison Performance Boost Up-coming in the Cog VM</a></strong></div><div>Hi all, These days my student Sophie Kaleba is working on the optimizations of String operations in the Cog VM and I’m spending a few hours here and there helping her. The main idea is to add…</div></blockquote>

**Comment by VincentBlondeau** [comment]
Yes, I can be an idea I'll look at it. Or maybe just a change of the collection type for the symbol table?

**Comment by jecisc** [comment]
IIRC what Sophie told me, what we are missing to enable the new string comparison is to register the new primitive in the VM side in the primitive table or something like that (I don't really know how the VM works :P) then use it in the image code.

**Comment by VincentBlondeau** [comment]
So it is the easy part!

**Comment by MarcusDenker** [comment]
I looked a bit at the code again and I have some ideas how to speed up... will do a PR of a first (I guess small) speedup soon  and the other one later the week

**Comment by MarcusDenker** [comment]
I merged: 
- Fix to copy the collections less often: https://github.com/pharo-project/pharo/pull/4899
- do not reset for each keystroke but take the intermediate result and narrow it down: https://github.com/pharo-project/pharo/pull/4914

The second one means that we sort only once when starting to type.

**Comment by Ducasse** [comment]
Also methods proposed should be sorted because now local methods are often mixed with method defined in Object and this is not good.

**Comment by MarcusDenker** [comment]
The old code completion just stopped at 100 (or so) methods. That's why it never proposed "OrderedCollection", for example... sop now we show everything, which of course leads to more strange methods shows.

As for speed: we need to check again after I improved it, I have no idea how much better is is. Maybe the problem even is fixed?

I have no image that I can use to check.

**Comment by David5i6** [comment]
Not a solution but...

Most code use semantic variable names, perhaps using a simple autocomplete for messages bassed on the object (if know) or the inferred object (if possible) can help.

For example:
If the variable is called "aCanvas", the methods (messages) proposed should be those defined in Canvas. If Ctrl + Space (or some other key) is pressed then show messages defined in Canvas and its parents, if pressed again the revert to show all know messages.

**Comment by guillep** [comment]
This should have been solved in #5996.

@David5i6 check the readme in https://github.com/guillep/complishon, as it contains an heuristic to cover exactly that case ;)

<blockquote><img src="https://avatars3.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/guillep/complishon">guillep/complishon</a></strong></div><div>Contribute to guillep/complishon development by creating an account on GitHub.</div></blockquote>

**Comment by VincentBlondeau** [comment]
It was a Pharo8 issue. Can the fix be backported so I can try it?

**Comment by guillep** [comment]
I'd like that first we test it in Pharo9.0 and if the behaviour is good enough, we could back-port it. We should discuss the decision of backporting probably with @tesonep.

Take into account also that #5996 depends on #5834, #5698 and #5671 (at least?) as they were all required to plug different completion engines. This means that if we backport #5834, #5698 and #5671, the new completion engine is just loadable https://github.com/guillep/complishon/

<blockquote><img src="https://avatars3.githubusercontent.com/u/708322?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/guillep/complishon">guillep/complishon</a></strong></div><div>Contribute to guillep/complishon development by creating an account on GitHub.</div></blockquote>
