### ISSUE TITLE
[RB] Two methods in the same class with the same implementation 

### ISSUE THREAD

**Issue by hayatou** [guillep/pharo-core#4902]
RBNamespace>>#allBehaviorsDo: and RBNamespace>>#allClassesDo: has same implementation

**Comment by kasperosterbye** [comment]
I suggest to let `#allBehavioursDo:` delegate to `allClassesDo:`. I am not even sure there are any external calls to `RBNamespace>>#allBehaviorsDo:`, and we could remove the method all together.

There is a single call to `RBNamespace>>#allBehaviorsDo:` from within the class itself (in `privateImplementorsOf:`, but since the two methods are the same, it is easy to repair.
