### ISSUE TITLE
Why is there a baselineOfTelePharoSupport in Pharo?

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5084]
In BaselineOfIDE

		spec package: 'BaselineOfPharoBootstrap'.
		spec package: 'BaselineOfMonticello'.
		spec package: 'BaselineOfMetacello'.
		spec package: 'BaselineOfTelePharoSupport'.

**Comment by pavel-krivanek** [comment]
This is a baseline that is not supposed to be loaded in full image because it belongs to a different image building branch. For more details, see the BaselineOfTelePharoSupport class comment.

**Comment by pavel-krivanek** [comment]
(it is possible to do not have it loaded but just present in the repository but then it would look like a dead code)

**Comment by pavel-krivanek** [comment]
Notice that these baselines are loaded only as packages. The first three are not really used during the bootstrapping process (because loading of baselines requires Metacello) but they serve as a source of packages list.

**Comment by Ducasse** [comment]
Hi pavel this is still unclear to me why we have a reference to telepharo.

**Comment by pavel-krivanek** [comment]
Because of poor granularity of our baselines and my bad assumptions about the Metacello :-)

For TelePharo on the Minimal image, we need to load some baselines (SUnit, Display) and several standalone packages (SortFunctions-Core, Tool-Registry). There would not be an issue with loading of baselines (if they have well expressed dependencies). The problem is with the standalone packages.

I was not aware of the way how to load them from the repository (I tried several ways but not the right one). So the only reasonable way how to make it work for me was to create an additional baseline. In fact, to load one particular package, you need to load the baseline that contains it and then specify the direct package name as if it would be the group name. But it has two issues:
- it is not a good practice becaues is a dirty approach that does not work well with dependencies etc. It should be replaced with more baselines or, at least, groups.
- the loading of a single package from a baselines activates the preload/postload actions that expect all packages to be loaded so it causes initialization errors

We have the same issue for the other tasks like loading only Spec to the minimal Pharo

**Comment by Ducasse** [comment]
Ok what if we create a baseline per standalone package? It would be a good experiment.

**Comment by pavel-krivanek** [comment]
then you do not need baselines, just packges with expressed dependencies and actions

**Comment by Ducasse** [comment]
Yes but for now we can only express this with baselines. 
We will start to work on Pakbot and I want it to work :)
