### ISSUE TITLE
#postLoadActions of LibtGit needs to initialize the FFICompilerPlugin

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5129]
After we merged https://github.com/pharo-project/pharo/pull/5120, we need another change that I sadly could not commit (so someone who know how needs to do it):

add to #postLoadActions of LibtGit:

FFICompilerPlugin initialize

**Comment by guillep** [comment]
Is this then broken since the beginning of november?
And it was left broken on purpose?

This is a clear example that the "let's integrate this now, fix it later" does not work.
Because if the original PR author or the merger do not take responsibility for the further action, the "fix it later" means "fix it never".

We should stop integrating half baked issues.
Yes, it seems a nice pattern, but it is only good if the people involved takes responsibility of the further step.

Now the problem is that we have 4-5 months of distance between the original issue, and this, plus a Pharo8 release in the middle. The more time it takes to fix these kind of issues, the more complicated it becomes to fix them.

Can we summarize?

 - Libgit's baseline should have a postload with `FFICompilerPlugin initialize`
 - A Libgit release should be done
 - An iceberg release should be done with the new libgit release
 - The new iceberg should be integrated in pharo

Is it that? 4-5 months have passed since this, and I was not involved in the original issue. Can somebody confirm?

Why don't we have a test for this? :(

**Comment by guillep** [comment]
I don't understand PR #5120. #5120 is only removing the recompilation using ffi pragmas.
That PR seems bad => it breaks stuff without seemingly fixing anything.

Why not just reverting that PR?

I need extra pair of eyes @tesonep @estebanlm

**Comment by estebanlm** [comment]
It was an attempt to fix the memory corruption problem the VM had at the time. The problem that was later found to be a bug while performing the compression.

I guess it may be reverted now, since it was trying to fix a problem that was fixed elsewhere.

**Comment by MarcusDenker** [comment]
Now fixed in Pharo9
