### ISSUE TITLE
Does LibGit really need to add it's own FFI callout selectors? (call:options: and related)

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#5130]
From https://github.com/pharo-project/pharo/pull/5120

> Are you talking about if TLGitCalloutTrait>>call:, call:options:, callUnchecked:options: are required?
> 
> Hopefully I don't make a fool of myself here...
> 
> Jan van de Sandt added these in 2016 to allow a 'safe' callout, i.e. check that a pointer has been initialized non-zero.
> 
> Guille's recent changes to specify the calloutAPIClass should provide an alternative way of hooking in to the FFICalloutAPI, which would remove the need for #call: and friends.
> 
> @guillep ?

**Comment by guillep** [comment]
This is a clear example that the "let's integrate this now, fix it later" does not work.
Because if the original PR author or the merger do not take responsibility for the further action, the "fix it later" means "fix it never".

We should stop integrating half baked issues.
Yes, it seems a nice pattern, but it is only good if the people involved takes responsibility of the further step.

Now the problem is that we have 4-5 months of distance between the original issue, and this, plus a Pharo8 release in the middle. The more time it takes to fix these kind of issues, the more complicated it becomes to fix them.

**Comment by MarcusDenker** [comment]
#call:, call:options: and #callUnchecked:options: have been removed
