### ISSUE TITLE
SpaceTally logic should handle large images

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5188]
In our image we have 200 000 classes, and a GC of 5 seconds. So, we need 11 days to run the following code: SpaceTally  printSpaceAnalysis

The main question is that why do we need the GC in the middle?

**Comment by MarcusDenker** [comment]
I think the idea is that the data would be less correct without it (even with doing a GC right before the instances that are just created for the report do change the result, but not that much).

I think that a correct  version would need to analyse the image "from the outside" to do a report... e.g. just on a dead image or via some VM level code that stops everything while counting.

**Comment by bencoman** [comment]
>  some VM level code that stops everything while counting

IIUC, on Linux the image is stored as mmap'd segments, so maybe `clone` [1] with:
- CLONE_VM unset - so the parent image can continue while the child has a copy-on-write static image to process
- CLONE_FILES set - so that the child can communicate results back to the parent

Half an example here [2]

[1] https://linux.die.net/man/2/clone
[2] https://eli.thegreenplace.net/2018/launching-linux-threads-and-processes-with-clone/

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://linux.die.net/man/2/clone">clone(2): create child process - Linux man page</a></strong></div><div>clone() creates a new process, in a manner similar to fork(2). It is actually a library function layered on top of the underlying clone() system call, ...</div></blockquote>
<blockquote><div><strong><a href="https://eli.thegreenplace.net/2018/launching-linux-threads-and-processes-with-clone/">Launching Linux threads and processes with clone - Eli Bendersky's website</a></strong></div></blockquote>

**Comment by VincentBlondeau** [comment]
Ps: I want to run it under Windows ;)

**Comment by eliotmiranda** [comment]
The Spur VM provides an allObjects primitive which means one can collect all the data in one primitive and then do the analysis on that one collection with no GC necessary.  I’m sure a full space tally of a 1Gb image implemented above the allObjects primitive would take much less than 10 minutes.

**Comment by Ducasse** [comment]
Thanks for the pointer.

**Comment by VincentBlondeau** [comment]
Fixed in #6177 implemented following @eliotmiranda advice and works like a charm!
