### ISSUE TITLE
Finder should give the class of the exact result

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#5189]
Example: 'ababa' .  $a . $z . 'zbzbz' 
![image](https://user-images.githubusercontent.com/4706329/69257273-19ed6680-0bbb-11ea-8d79-85dfec1c70dd.png)

**Comment by VincentBlondeau** [comment]
There is a star missing before the name of the class

**Comment by kasperosterbye** [comment]
Odd. For me this do not even give a result, but fails
<img width="410" alt="image" src="https://user-images.githubusercontent.com/17723745/69974515-b0a81480-1525-11ea-9ee4-a31d40564625.png">

It fails because of the two-argument-keyword. 
Also this example fails: `'abcdef'. 2. 4. 'bcd'`.

If fails also in Pharo 7.

**Comment by MarcusDenker** [comment]
merged PR
