### ISSUE TITLE
Feature request - debugger able to show/set breakpoints

### ISSUE THREAD

**Issue by bencoman** [guillep/pharo-core#5211]
As I am starting to use breakpoints instead of `self halt` I am feeling awkward in the debugger in two aspects:
1. Not being able to see if there is a breakpoint set somewhere in the method being debugged.
2. Not being able to add a breakpoint half way down the method I'm debugging.  

I feel this is a big gap in the breakpoint usability.
How hard would it be to add a left margin similar to the browser to show/set breakpoints?
Who is best to discuss this with further?

**Comment by Ducasse** [comment]
Hi ben
Yes. We agree and to me breakpoints were never integrated. 
Steven is working to have a better management of breakpoints in the debugger. 
May be you can be a beta tester.

S.

**Comment by StevenCostiou** [comment]
Hi Ben,
for point 1, this is going to be available in the new spec debugger :)
for point 2, just to be sure : do you mean putting a new breakpoint directly in the debugger, in any of the methods available in the call stack?

**Comment by bencoman** [comment]
1. cool.
2. Yes.  If there was a breakpoint on line 2, so the debugger opens there, then I <step> a few lines to line 5 and find those are okay, then next time want to break at line 5 rather than line 2, I'd click in the margin to remove line 2 breakpoint and click again in margin to add line 5 breakpoint, then click  <Proceed>.

**Comment by dvtomas** [comment]
Totally agree. Handling breakpoints should IMO feel totally the same in the debugger and the browser - that means the margin should work the same way, the "Source code" menu on popup should be present with the same items, the red highlight of the message send the breakpoint is on should be displayed the same way, etc ..

As for 2., yes, this should be available for all the methods on the stack.

**Comment by StevenCostiou** [comment]
I'll have a look next week, it's been on my todo-list since a while.

**Comment by macta** [comment]
This description doesn't also explicitly mention (but hopefully its obvious) that you should also be able to "clear" breakpoints in the debugger as well as set them (and obviously see them)

**Comment by StevenCostiou** [comment]
Yes all breakpoint features should be available from the debugger.
One problem: currently we can't add a breakpoint (or a halt) without recompiling the method, so for a method already in the stack we can't add breakpoints without restarting it.
Not good.

We have a solution with spec new tools, which we are working on. 
I'll solve this issue for the new spec debugger, there will be a beta soon in the P9 base image.
For the current debugger, I'll need help because I won't have time unfortunately.

**Comment by dvtomas** [comment]
Sure, if there's going to be a new debugger in the foreseeable future, it might make more sense to focus forces on getting it finished and just removing the current one. Do you have an estimate on when could be the new debugger ready?

I'm very curious, how do you plan to solve the "add breakpoint without recompiling" with the new debugger? What is it that makes it impossible to do it with the old debugger, but possible with the new one?

**Comment by StevenCostiou** [comment]
Well in fact there are two parts, it's not really the debugger UI that *cannot*.
- We have now an API to script the debugger, and we can put what we call "virtual breakpoints". Basically we target an expression (like a breakpoint) and we step until we reach that point. In parallel, we add a standard breakpoint so that once the method is popped off the stack, standard breakpoints can work. This API works at the debugging model level, so this can work both with GT and spec debuggers.
- Then there is the UI part, we have to enable/disable breakpoints from the text editor, which is not easy to do (yet) in both cases. I'll focus on doing that for the spec debugger, but any debugger could use the API and implement control from its text editor.

**Comment by dvtomas** [comment]
Hmm, is there some documentation/text/design document on the subject? (virtual breakpoints?) What do you mean by "standard breakpoint", `self halt` or something more sophisticated? 

VisualWorks have this concept of "Probes", they basically insert special code - message sends to the Probe objects - into the compiled method bytecode itself, so it doesn't record as a method change into the VCS, method history etc, but it still act as breakpoints of various kinds - halt, oneshot, condition, display on hit etc. Code browsers (editors) are aware of the Probes in the bytecode, and display/let the user interact with the probes accordingly. There's just single source of truth, the Probes in the bytecode. It all works nicely together, and the concept doesn't seem overly complicated to me, although there'll be a thousand little details to solve.

But I'm not at all an expert on the subject, quite possibly your approach is superior. When do you plan to have some version to present to the public, if there's already an estimate?

**Comment by astares** [comment]
@dvtomas Check one of these http://wiki.astares.com/pharo/115

<blockquote><img src="/schemes/pharo/favicon.ico" width="48" align="right"><div><strong><a href="http://wiki.astares.com/pharo/115">Reflection</a></strong></div></blockquote>

**Comment by StevenCostiou** [comment]
> Hmm, is there some documentation/text/design document on the subject? (virtual breakpoints?) What do you mean by "standard breakpoint", `self halt` or something more sophisticated?

I chose wrong words, in the end a breakpoint is a breakpoint. I meant by "virtual" that to avoid the problem of recompiling a method on the stack, we don't install a real breakpoint but we control the execution until the point we want to break. That "virtual" thing is implementation concern, in the end it's always breakpoints.

To control the execution, we use a debugging API to step the execution. We published a paper about it last year: [Sindarin](https://hal.archives-ouvertes.fr/hal-02280915)

> VisualWorks have this concept of "Probes", they basically insert special code - message sends to the Probe objects - into the compiled method bytecode itself, so it doesn't record as a method change into the VCS, method history etc, but it still act as breakpoints of various kinds - halt, oneshot, condition, display on hit etc. Code browsers (editors) are aware of the Probes in the bytecode, and display/let the user interact with the probes accordingly. There's just single source of truth, the Probes in the bytecode. It all works nicely together, and the concept doesn't seem overly complicated to me, although there'll be a thousand little details to solve.

We implement breakpoints using reflection, we recently published a paper about it: [Reflectivity](https://programming-journal.org/2020/4/5/). The current implementation also involve inserting bytecode a bit similar to what you describe.

> But I'm not at all an expert on the subject, quite possibly your approach is superior. When do you plan to have some version to present to the public, if there's already an estimate?

I do not know, a prototype probably in a month, give or take what may happen or not with that pandemy problem ;)

I've used Visual Works a few years, but not recently. I do not remember, do you know if those probes (which are recent stuff?) can be installed from the debugger? Do you know how they solve the problem of recompiling methods on the stack (with a started loop for example)?

**Comment by dvtomas** [comment]
Thanks for the links to the papers. Scripting the debugger (Sindarin) seems like potentially quite a useful thing to have, if coupled with a decent UI to expose the capabilities in a user-friendly manner.

As for your question on Probes on VW: It has been about a decade since I've used VW intensively the last time. Probes are by no means new (even by Smalltalk measures :-), it is part of the Professional Debug Package by the Crafted Smalltalk company, I've managed to find [this link](http://www.edm2.com/index.php/Crafted_Smalltalk) which states that it's been available since 1995.

Couple of notes on what can the VW debugger do:

 - Breakpoints are visible and can be manipulated the same way both in the browsers and the debugger (you take this for granted and obvious convenience until you try an environment where it doesn't work that way ;-)
 - Recompiling a method during debugging restarts that method from the beginning, of course invalidating all the stack descending from the old method call
 - Adding/removing breakpoints while debugging a method does NOT restart the method (very very useful)
 - Recompiling the method during debugging does NOT remove existing breakpoints. There's probably some heuristics/diffing involved to reinstall the old breakpoints on the new method, but I'm just guessing
 - various kinds of breakpoint - counters, oneshot, action on hit, ...
 - Step into, step through, step over, restart this method
 - Run, Run until cursor (very useful), Run until method return (very useful)

The program AST is also reified in the Professional Debug Package, but I have no idea how similar is the design to your Reflectivity project. You can always download a non-commercial version of VW and look for inspiration, if you are curious.

Personally, I'd say that the little thingies like the ability to view/add/remove breakpoints while debugging a method without restarting it, run until cursor, run until method return, are the bread and butter of the everyday debugging experience. Having a scriptable debugger will be a very nice extra and it is great to have the door open for this kind of wizardry, but the everyday stuff just matters more for .. well .. everyday development. I'm quite looking forward your new debugger!

**Comment by StevenCostiou** [comment]
At last... 
-> https://github.com/pharo-spec/NewTools/pull/920
