### ISSUE TITLE
Remove blueInk to introduce Enlumineur

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5217]
We can now remove the blueInk pretty printer 
And next introduce Enlumineur

**Comment by astares** [comment]
Not remove initially - deprecate is better.

Also lets have better bug descriptions: @Ducasse is talking about: https://github.com/Ducasse/enlumineur


<blockquote><img src="https://avatars2.githubusercontent.com/u/432549?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Ducasse/enlumineur">Ducasse/enlumineur</a></strong></div><div>Enlumineur is a pretty printer replacing the blueInk pharo pretty printer - Ducasse/enlumineur</div></blockquote>

**Comment by Ducasse** [comment]
Sorry but I will not deprecate it. 
We have something else to do that to keep a bogus pretty printer.

**Comment by astares** [comment]
- no initial discussion on the mailinglist, 
- no description what "Enlumineur" is or where to find it in the bug - I had to google it
- PR was neither reviewed nor commented from a second side although it's a bigger change
- an integrator is merging his own PR, no look from a second side

I understand the impatience - but is this the way we want to work? 

We have broken settings now - which was clear when we do not deprecate.

“Look, that's why there's rules, understand? So that you think before you break 'em.”
― Terry Pratchett, Thief of Time

![blueInkSettings](https://user-images.githubusercontent.com/5980033/69615892-f2245580-1035-11ea-8dda-2c9834bea5e5.png)
