### ISSUE TITLE
Cannot format code anymore

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5228]
There is no much BlueInk in the current Pharo 8 image. It would have been cool to deprecate it because now I cannot launch and image with my settings since it was extending BlueInk :(

Also currently, the format command is messing the code. It's hard to work in those conditions.

**Comment by jecisc** [comment]
Worst than formatting! The current formatter is removing the comments. 
Since the formatter is called by refactorings then it means that each refactoring is removing the method comments.

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/pull/5234

I removed BlueInk first and not the inverse to make sure that we could get for real a build
without a formatter. Now we know it. 
About the RBSimpleFormatter eating comments please open another issue and I will have a look to see how we can do something because the basic formatter should not lose comments.

**Comment by Ducasse** [comment]
Cyril the new formatter is available can you check that it is working for you. 
It was working for me. 
Now we may have to register it as default. I have to check how we do that

**Comment by Ducasse** [comment]
I will close this one and open a new one on the SimpleFormatter because it MUST not lose method comment. This is super bad.
