### ISSUE TITLE
Enluminer-UI packages are present but not loaded

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#5253]
There is two packages related to Enlumier-UI in Pharo but they are not loaded.

Two solutions:
- Load them
- Remove them

**Comment by VincentBlondeau** [comment]
Actually there should be 4 package loaded or deleted:

![image](https://user-images.githubusercontent.com/4706329/69716187-d5f1e880-1109-11ea-974a-f83289ef9671.png)

**Comment by Ducasse** [comment]
Can we let them because they should be loaded later?
I do not want to code in my enlumineur repo anymore. So this packages should stay there but someone with Spec2 knowledge should fix the UI else someone else will complain that the code is not working. Now we can also remove the UI package and the UI package tests like that I will not work on them and this is perfect to me.
