### ISSUE TITLE
Refactoring: Extract method 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5269]
name
	| token |
	token := (String new: 100) writeStream.
	[ currentChar isLetter ]
		whileTrue: [ token nextPut: currentChar.
			self consume ].
	^ token contents

Extracting currentChar isLetter is broken.

**Comment by santids** [comment]
I have tried this, and seems to be working correctly... if you remember to save before trying the refactoring. If you don't, it'll fail gracefully with an alert.

However, I found the menu that is opened very anti-intuitive.The submit button is called `Rename` when you are creating a new method which didn't have any previous name, It's quite confusing. I think that something like `Create` would be more accurate. 

Also the menu looks exactly the same than the one that opens when you do the `Rename` refactoring. Therefore, it's difficult to know if you are doing the correct refactoring, or you just miss-clicked.

**Comment by jordanmontt** [comment]
I've been looking at this and I think that the problem is: when the autoformatted button (the `F + L W` checkbox) is selected, the `ClyTextEditor` class is returning the wrong text interval. So, the text to extract is not the same as the selected.

In the previous example, when you select the text `currentChar isLetter` to extract to a method, the text `    [ currentChar isLett` is sent to the refactor classes. Therefore, it gives an error saying "Invalid source to extract" because indeed the source code is invalid.

So, the problem happens before the `extractMethod` method is called, but when you select the text with the mouse when the autoformatted is activated.

**Comment by Ducasse** [comment]
Extract method does not work well when you have multiple times the same expression in a method. You press replaceAll and only one is replaced.
