### ISSUE TITLE
[Cleanup] CharacterTable in Character -- Bootrap change needed

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5275]
No idea...

**Comment by MarcusDenker** [comment]
needs to be fixed on the bootrap

**Comment by guillep** [comment]
There are many things about this. I'll try to make it short :).
- The character table is not used anymore in Spur.
- The character table implemented a flyweight pattern for characters with codepoint <= 255. My understanding is that this was important to avoid creating tons of characters here and there, specially when manipulating bytestrings.
   => However, take into account this was just an optimization. Because Characters with codepoints > 255 should also work (and unicode supports thousands of code points we don't want to store :)), although they were not contemplated in the flyweight pattern (wide strings are less common too).

Moreover, before Spur, the VM needed to know where the character table was to implement primitives like `ByteString>>#at:`. In that primitive, the VM fetched the byte in the bytestring and then looked up the character at that index in the character table.

```smalltalk
"Pseudocode to illustrate, not real vm code :P"
byteStringAtPrimitive
  ^ self classTable at: (self receiver byteAt: self arguments first)
```
Now with Spur, Characters are immediates, so the VM does not need the character table to create character objects anymore :).

**Comment by Ducasse** [comment]
So do we remove it?

**Comment by MarcusDenker** [comment]
If we remove it (via a direct change in git), we see that this needs another change on the level of the bootstrap code in #createInitialObjects

bootstrap fails with

KeyNotFound: key #CharacterTable not found in EPRemoteDictionary
EPRemoteDictionary>>at:
PBImageBuilderSpur5064bit(PBImageBuilder50)>>createInitialObjects
PBImageBuilderSpur5064bit(PBImageBuilder50)>>bootstrap

**Comment by jecisc** [comment]
Not for P11

**Comment by jecisc** [comment]
I did a PR to remove it from Pharo and the bootstrap altogether
