### ISSUE TITLE
CompletionEngine and Monticello saving

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#5364]
![image](https://user-images.githubusercontent.com/5980033/70666528-19526800-1c6f-11ea-974b-ab21c9ae0552.png)

Open Monticello browser and try to save a new version of a package (here a config is used) by giving a comment to the mcz. While typing a version comment you get an error as seen in the screen.

=> System ends up in a problem of completion engine

**Comment by MarcusDenker** [comment]
I think a solution could be to override #textMorph:, do a super call and then change the mode to #beForPlainText

**Comment by marsell** [comment]
This remains a problem in Pharo 8.0. As a new user, one of the main code revision tools not working doesn't exactly inspire confidence. :(

**Comment by Ducasse** [comment]
@marsell 
- Monticello is not the main revision code tool! Since Pharo 70 alpha this is iceberg and git!
- Do you think that we do not eat our own dog food? All Pharo and all the projects that we managed and there are many are managed perfectly with Iceberg.
- I do not open a MC browser since a couple of years. 

I think that we should stop offering the possibility to save in MCZ format. 
This is at least three years now that I did not save any package in MCZ format.

**Comment by marsell** [comment]
I have little skin in the game since I prefer git myself. Whether monticello is fixed or removed is all the same to me. :)

However, I did not find any deprecation notices and timelines for monticello, the app is listed in the main Tools menu, it is mentioned in several books and the MOOC, and in the end: it was shipped broken. A bit more surprising to me is an apparent attitude that because the core devs have not used the app for a mere two years, nobody else does either.

I understand that you don't have many core devs. Some form of official deprecation timeline, and allowing bugfixes to be submitted without a signed license agreement, would prolly help Pharo's future prospects in industry.

I will continue to play with Pharo. Please take the above in the spirit it was given.

**Comment by MarcusDenker** [comment]
Sorry for not fixing this... I wanted to just do the solution that I described but completely forgot to do it.

I will have a look this week

**Comment by MarcusDenker** [comment]
I added a fix, first for Pharo9 for testing, then I will back port it after we merge it there

**Comment by MarcusDenker** [comment]
I merged a version for Pharo8. But this will only be in the default download after we realease 8.0.2
