### ISSUE TITLE
trace and trace: display too many quotes

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5406]
I suggest to changer their definition as follows: 

```
trace
	self trace: self
```
instead of 

```
trace
	self trace: self printString
```

and 

``` 
trace: aString
	"Log the argument. Use self trace: instead of Transcript show: "
	
	Transcript show: aString asString
```
instead of 

```
trace: aString
	"Log the argument. Use self trace: instead of Transcript show: "
	
	Transcript show: aString
```

which in addition is more robust.

**Comment by Ducasse** [comment]
same for crTrace: and crTrace

**Comment by bencoman** [comment]
Looking at the following snapshot from the github comments, I see the first commit #5414 has only one commit and #5415 has the 52 commits, so what was the action between the two?  What were you trying to achieve? Because if its not easy to do, the perhaps others hit the same problem.
![image](https://user-images.githubusercontent.com/1713447/71328069-e8661300-254b-11ea-90bf-4a2b4382596a.png)

**Comment by Ducasse** [comment]
My image was dirty so I captured all the changes I was working on with enlumineur enhancements. I redid it.
