### ISSUE TITLE
Unbound variable nodes should work with messages using bindings

### ISSUE THREAD

**Issue by hogoww** [guillep/pharo-core#5458]
You currently cannot send #isInstance (for isInstanceVariable #3236)
because it's using binding, which is not annotated on them.
I suspect that super does not work either.

@MarcusDenker 
Would you think it'd be okay to redefine #isInstance for self/super to just return false? 
(i'd have done a PR directly, but I want to add tests for this too, so i'll do it later)

**Comment by hogoww** [comment]
same goes for isGlobal

**Comment by MarcusDenker** [comment]
yes!

**Comment by hogoww** [comment]
same goes for isTemp
(i know, anything using binding anyway..)

**Comment by hogoww** [comment]
One way to solve this (at least on compiled ASTs) #6034

**Comment by MarcusDenker** [comment]
The idea is that as soon as you want to talk about semantic meaning of variables, you *have* to do semantic analysis.
asking "isGlobal" has no meaning on a pure AST (in the sense of Syntax Tree), as the question global vs temp (for example) can not be decided by the Syntax.

The subclasses on the AST just add to the confusion: they are created by semantic analysis, so asking the variable (binding) or implementing is* methods on the subclasses of RBVariableNode is in the end the same: the question makes only sense after semantic analysis. Just that *isSomethign methods return false instead of an error in a non-analyses AST does not make it better: it's wrong, too.
