### ISSUE TITLE
LOC should not count line with space or tab only

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5485]
Hi

linesOfCode is bogus
because it could as empty line lines with only cr
a line with a space count. 
lineOfCode should make sure that empty lines are also lines with only space or tab.

**Comment by kasperosterbye** [comment]
You are talking about `CompiledMethod>>linesOfCode` I presume?

**Comment by Ducasse** [comment]
Yes. Sorry. I should check and write some tests. Now writing a proposal so that Pharo gets a stamp as an official platform of the uni. So exciting.

**Comment by kasperosterbye** [comment]
How about using a somewhat *uniforming* measure. Two comes to mind:

- `CompiledMethod>>codeForNoSource` decompiles the bytecode. This produces something without blank lines and no comment - and with a uniform formatting making it possible to compare across most coding styles
- `ast formattedCode` keeps comments etc, but also makes indentation etc uniform.

If one just want *some kind of measure of method size* the byte code size is also an option.

**Comment by olekscode** [comment]
@kasperosterbye we were using `CompiledMethod >> linesOfCode` for this study: https://hal.inria.fr/hal-02440055v1. You are right that LOC is not the best measure, but I still think that it must be fixed. At the moment, it is implemented like this:

```Smalltalk
CompiledMethod >> linesOfCode
	"An approximate measure of lines of code.
	Includes comments, but excludes empty lines."
	| lines |
	lines := 0.
	self sourceCode lineIndicesDo: [:start :endWithoutDelimiters :end |
		endWithoutDelimiters > start ifTrue: [lines := lines+1]].
	^lines
```

In the comment it is declared that the method excludes empty lines. However, if a line contains whitespace characters, it is not considered empty and is not excluded. And since the environment automatically adds tabulations at the beginning of every new line to keep the code aligned and nicely formatted, almost no lines that seem empty will actually be considered empty. Which means that this comment is misleading.

I believe that we should change the implementation in such a way that a line that contains only whitespace characters is also considered empty and gets excluded.

(besides, this method is not tested at all)

<blockquote><div><strong><a href="https://hal.inria.fr/hal-02440055/document">Characterizing Pharo Code: A Technical Report</a></strong></div><div>Pharo (https://pharo.org/) is a modern dynamically-typed reflective pure object-oriented language. It is inspired from Smalltalk. Its unconventional syntax mimics natural language: arguments are not grouped around parentheses at the end but within the message, making expressions looks like sentences. In addition, all control flow operations are expressed as messages and the programmer can freely define new ones and as such define Domain Specific Languages for his task. In this technical report we discuss the statistical properties of source code that people write using Pharo programming language. We present the methodology and tooling for analysing source code selected from the projects of Pharo ecosystem. By analysing 50 projects, consisting of 824 packages, 13,935 classes, and 151,717 methods, we answer questions such as "what is a typical method length?" or "what percent of source code are literals?".</div></blockquote>

**Comment by olekscode** [comment]
Also, comments are excluded, but not the ones that are inside a block closure

**Comment by kasperosterbye** [comment]
@olekscode I can appreciate the argument that it is done as part of a study, and that it should be consistent with said methodology. I will let someone else who know the study propose a solution then.

**Comment by olekscode** [comment]
I'm working on this issue now.
Apparently, comments are not excluded at all

**Comment by kasperosterbye** [comment]
In that case (with the comments) I still believe that `ast formattedCode` gives the most uniform answer as it ignores the original indentation style.

**Comment by olekscode** [comment]
I think this issue can be closed now
Here is the accepted PR: #5608
