### ISSUE TITLE
Error when inspecting a filereference to an image

### ISSUE THREAD

**Issue by badetitou** [guillep/pharo-core#5527]
When we inspect a file reference to an image there is an error signal about mimeTypes.

(I suppose because the mimetypes keywork has been removed but not the GT extension)

**Comment by JanBliznicenko** [comment]
Hello, 
unfortunately, I am unable to reproduce your issue. What Pharo version did you encounter it on? Is that with clean image? Is it for any image or just some specific ones? I tried inspecting several `FileReference`s to images of various types (jpg, png, gif) and all opened just fine.
Code I tried is (for example):
`'C:\Users\Honza\Downloads\exampleImage1.jpg' asFileReference inspect`
Tried the same on latest Pharo 7, 8 and 9 (on Pharo 7 gif is not supported, but otherwise ok).

**Comment by akgrant43** [comment]
This looks very similar to: http://forum.world.st/BaselineOfZincHTTPComponents-gt-gt-baseline-td5109291.html

<blockquote><div><strong><a href="http://forum.world.st/BaselineOfZincHTTPComponents-gt-gt-baseline-td5109291.html">Pharo Smalltalk Developers - BaselineOfZincHTTPComponents>>baseline:</a></strong></div><div>BaselineOfZincHTTPComponents>>baseline:. Hi Sven, Following on from a discussion I started in Discord development... Loading Zinc SSO in Pharo 8 currently causes problems because the...</div></blockquote>

**Comment by badetitou** [comment]
Yes, it looks like the preceding error.
And it is now solved... sorry.
