### ISSUE TITLE
avoid symbols in place of clean blocks

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5553]
avoid symbols in place of clean blocks
This is slower and also hamper future analysers.

**Comment by Ducasse** [comment]
I should try to come with a rule too.

**Comment by jecisc** [comment]
In fact, symbols are faster than blocks for small collections.

There is a benchmark in Clement's thesis. 

I did some bench and with full block closure, blocks become faster only for collections of more than 700+ elements approximatively.
I checked in an image I used and I have 692743 collections and only 1288 are bigger than 700 elements.

So, if we want to optimize the speed this way, we should use symbols instead of blocks.

**Comment by Ducasse** [comment]
then did you check with sista bytecode?

**Comment by jecisc** [comment]
The bench I did was with the sista bytecode.

**Comment by Ducasse** [comment]
At the end of the day, I find this symbol use super lame

themeChanged
	super themeChanged.
	tabs do: #themeChanged.

UITheme current: aUITheme
.... 
(SystemWindow allSubInstances select:[:e | e owner isNil]) do: [:each | each themeChanged].

A lambda is not the same type as a symbol.

**Comment by MarcusDenker** [comment]
Duplicate of https://github.com/pharo-project/pharo/issues/5543
