### ISSUE TITLE
Equals does not work for two "absolute relative" path

### ISSUE THREAD

**Issue by badetitou** [guillep/pharo-core#5720]
In case you have two files references such as

'D:/folder1/folder2/../folder2/'
and
'D:/folder1/folder2/'

They are not equal whereas FileReference comment says 
"Two FileReferences are considered equal if they refer to the same file / directory."
(which is the case in the example)

**Comment by akgrant43** [comment]
This is actually quite a tricky issue to resolve such that it will answer correctly in all cases.  On Linux and Mac the use of symbolic links can mean that a similar expression isn't true since the parent of the symbolic link is not the directory containing the symbolic link, but the directory of the target of the symbolic link.

If you're confident that symbolic links won't be an issue, just `#canonicalize` the file references first:

```
a := '/a/b/c' asFileReference.
b := '/a/b/c/../c' asFileReference.

{
a = b.
a canonicalize = b canonicalize.
}

" #(false true)"
```

**Comment by Ducasse** [comment]
Should we keep this issue open?

**Comment by MarcusDenker** [comment]
fixed by merging the PR
