### ISSUE TITLE
Complete VM Frozens on recompileAll

### ISSUE THREAD

**Issue by David5i6** [guillep/pharo-core#5778]
Sometimes you can change compilerOptions in terms of gainin performance, or sacrificing RAM or simply to experiment.

Let's say that for example you can do this:

```smalltalk
CompilationContext bytecodeBackend: EncoderForV3PlusClosures .
CompilationContext optionOptimizeIR: true.
CompilationContext optionInlineAndOr: true.
CompilationContext optionInlineCase: true.
CompilationContext optionInlineIf: true.
CompilationContext optionInlineIfNil: true.

CompilationContext optionLongIvarAccessBytecodes: false.

OpalCompiler recompileAll .
```

Well that runs well without problem and you can repeat this operation again and again without issues.

But if you do:

```smalltalk
CompilationContext optionInlineNone: true.

OpalCompiler recompileAll .
```

The entire VM becames frozen. I let it for more that two hours without any progress.

Tested on MacOS over Pharo 8 and Pharo 9 from the Pharo Launcher.
Tested on Windows 10 on git Pharo 9.

**Comment by MarcusDenker** [comment]
CompilationContext optionInlineNone: true.

Here the problem is that some code has been written that relies on optimisations, especially
the scheduler. The reason is that interrupt checks (and thus calling the scheduler) happens at message sends. if you make #ifTrue: a messages send, this triggers the scheduler inside the scheduler.

There are  other places like that, we do not even know which they are.

What we added to the compiler is that you can enforce settings *per class*. #optionLongIvarAccessBytecodes is an option that is true in the Context methods as the JIT relies on that. It would be nice if all the places that rely on an optimisation would declare it...

But that is not your problem, what you you should do is to set the CompilationContext not to no optimisation, but to the default. Maybe we should add a method for that to make it easier to find.

**Comment by MarcusDenker** [comment]
What we should do, too, is to enable more optimisations by default.

**Comment by MarcusDenker** [comment]
explanation explained that this is not a bug
