### ISSUE TITLE
Generate accessors on inst var does not work

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6002]
Generating of accessors does not work, both ways, from context menu on the class or from context menu on the intance variable.
It opens confirmation "There is no change produced by this refactoring"

**Comment by pavel-krivanek** [comment]
introduced by build 164, PR: https://github.com/pharo-project/pharo/pull/5760

**Comment by pavel-krivanek** [comment]
@carolahp can you participate? Originally, the environment for this refactoring was the SystemDictionary, now it is an RBEnvironment where the changes are not correctly applied

**Comment by carolahp** [comment]
@pavel-krivanek I'm on it, this was introduced by me when making the automatic refactorings of eliminating classes compatible with Ring

**Comment by Lin777** [comment]
Hi @pavel-krivanek, I was reviewing this issue but I can not replicate it, I did this steps:

- Create a class
```
Object subclass: #SomeClass
	instanceVariableNames: 'a b c'
	classVariableNames: ''
	package: 'Example'
```
- Select an inst variable since differents contexts
     - from context variable 
     - from class' definition context
     - from source code context
- Select "Generate accessors" command (directly or from submenu "Source code")
- And that command generate accessors for inst var successfully.

I would like to know how replicate your problem with this refactoring

**Comment by pavel-krivanek** [comment]
yes, it is fixed. Thank you for the ping.
