### ISSUE TITLE
Click outside of completion pop-up should close it

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#6012]
**To Reproduce**
1. start writing some code that opens completion pop-up with some existing options
2. press arrow down key to move focus to pop-up (for the first item, it will not have any visual effect which we may consider as a bug)
3. click outside of the pop-up window with mouse

**Expected behavior**
The pop-up should be closed

**Comment by pavel-krivanek** [comment]
It is actually much worse....
To prevent closing of the window by mouse click outside it is enough to just move the cursor over the pop-up for a moment.
Moreover, it remembers this state for the same editor window so even if you close it by Esc and then you write some other code that opens the pop-up, the pop-up cannot be closed by clicking outside of it even if you do not enter it with the mouse or press an arrow key

**Comment by pavel-krivanek** [comment]
hmm, it depends if you click on the related editor or not...

**Comment by guillep** [comment]
Just to add more info.
This was working on build 162. Stopped working with my hand changes in 163.

In Build 162, when we click outside the completion menu, the stack that closes the menu looks like:

```
SmallInteger(Object)>>halt
CompletionEngine>>closeMenu
MessageSend>>value
MessageSend>>cull:
MessageSend>>cull:cull:
[action cull: anAnnouncement cull: announcer] in AnnouncementSubscription>>deliver: in Block: [action cull: anAnnouncement cull: announcer]
BlockClosure>>on:do:
BlockClosure>>on:fork:
AnnouncementSubscription>>deliver:
[ subscription deliver: anAnnouncement ] in SubscriptionRegistry>>deliver:to:startingAt: in Block: [ subscription deliver: anAnnouncement ]
BlockClosure>>ifCurtailed:
SubscriptionRegistry>>deliver:to:startingAt:
SubscriptionRegistry>>deliver:to:
SubscriptionRegistry>>deliver:
Announcer>>announce:
RubEditingArea(Morph)>>doAnnounce:
RubEditingArea(Morph)>>announceKeyboardFocusChange:
RubEditingArea(Morph)>>keyboardFocusChange:
RubEditingArea(RubAbstractTextArea)>>keyboardFocusChange:
HandMorph>>newKeyboardFocus:
RubTextScrollPane(Morph)>>takeKeyboardFocus
NECMenuMorph>>mouseDown:
NECMenuMorph(Morph)>>handleMouseDown:
MouseButtonEvent>>sentTo:
NECMenuMorph(Morph)>>handleEvent:
NECMenuMorph(Morph)>>handleFocusEvent:
[
		ActiveHand := self.
		ActiveEvent := anEvent.
		result := focusHolder handleFocusEvent: 
			(anEvent transformedBy: (focusHolder transformedFrom: self)).
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
BlockClosure>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
```

So it is the lost focus event that indeed caused the closing.
Looking at the variables in the stack, the focus before the click was:
``` 
a RubEditingArea(583942144)
```

And the click is requesting focus on

``` 
a RubTextScrollPane(76486144)
```

But going a bit up in the stack, the code that produces the change in the focus is
  =>

```smalltalk
NECMenuMorph >> mouseDown: anEvent
        ...
        self flag: #pharoFixMe "ugly hack".
	engine editor morph owner owner   <--------
		takeKeyboardFocus;
		handleMouseDown: evt.
```

Even more, why does the NECMenuMorph receives the click? If the click was outside itself!!!
That is because the menu morph requests "mouse focus" when it is shown:

```smalltalk
NECMenuMorph >> show
	self resize.
	self activeHand 
		newMouseFocus: self.
	self changed.
```

I'll try to do a similar analysis for build 163 to see why this is broken.

**Comment by guillep** [comment]
A similar analysis in build 163 shows:

1. NECMenuMorph does not receive the mouseDown event
2. The NECMenuMorph never becomes mouseFocus (I added a traceCr on mouse focus change, see below)

![image](https://user-images.githubusercontent.com/708322/77787461-e090a000-705f-11ea-9a12-64a5f983927c.png)

3. The code of `show` was changed (by myself)

```smalltalk
show
	self resize.
	self activeHand ifNotNil: [ :hand | hand newMouseFocus: self ].
	self changed.
```

The problem was that the `NECMenuMorph` was trying to access the hand before being installed in the world! And the current hand depends on the world where we are installed. Otherwise we need global state, which I was trying to minimize :)...

## An alternative solution

So one alternative solution is to call `show` once we are sure the morph is in the world.

```
openInWorld

	super openInWorld.
	self show
```

And avoid calling show before it:

"protocol: #actions"

```smalltalk
narrowCompletion

	self selected: 0.
	firstVisible := 1.
	context narrowWith: context completionToken.
	(context entries size = 1 and: [ context entries first contents = context completionToken ]) ifTrue: [
		self delete.
		^ false ].
	context hasEntries ifTrue: [ self selected: 1 ].
	^ true
```

This would mean that we can inline show in the `openInWorld` method and then remove the conditional. `show` is not morphic vocabulary...

```smalltalk
openInWorld
	super openInWorld.
        self resize.
	self activeHand newMouseFocus: self.
	self changed.
```

Moreover, in more recent images I added hooks `preOpenInWorld` and `postOpenInWorld`.

**Comment by guillep** [comment]
This is another interesting bug analysis for @StevenCostiou and @dupriezt

**Comment by pavel-krivanek** [comment]
cool, thank you for the deep analysis, I supposed that this is some ancient issue...

**Comment by guillep** [comment]
I assume this is working now?

**Comment by pavel-krivanek** [comment]
yes!
