### ISSUE TITLE
MethodNode should offer a nice way to access primitive number

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#6104]
**Describe the problem**
Right now to access the primitive number of a primitive in a method node
we should do 

```
self pragmas first argumentAt: 'primitive:'
```

And this is not really user friendly. 
The solution should be to propose

```
self primitiveNumber 
```

**Comment by MarcusDenker** [comment]
this should actually use #primitiveFromPragma and get the number from the IRPrimitive.

The reason is that primitive parsing is actually much more complex than what you would expect...

**Comment by MarcusDenker** [comment]
The problem is that primitive numbers on the level of the method are not that simple. They do not map to a pragma "primitive:" in the way that you would expect.

For example there are named primitives. They all share the same primitive number, thus if we add #primitiveNumber to RBMethodNode we *have* to return that, as we would else not be in sync with the CompiledMethod. 

But then, people might be tempted to think that there is "<primitive: 117>" in that method, but there is not.

**Comment by MarcusDenker** [comment]
This is not really possible... primitive numbers do not map to pragmas as one would naively thinkg (see the descrition above).

**Comment by dionisiydk** [comment]
What do you think about modeling primitives as pragmas? (on the level of AST). 
Syntactically they looks equal.

**Comment by dionisiydk** [comment]
Hm. I see that primitive methods are modeled with pragmas. For example:
```Smalltalk
(MirrorPrimitives class>>#classOf:) pragmas "==> an Array(<primitive: 111>)"
```
> But then, people might be tempted to think that there is "<primitive: 117>" in that method, but there is not.

So what do you mean by this?

**Comment by dionisiydk** [comment]
Ok. I read PR comments. No questions there
