### ISSUE TITLE
Random enters invalid state when large seed is given

### ISSUE THREAD

**Issue by webwarrior-ws** [guillep/pharo-core#6231]
To reproduce:
`(Random seed: 16rFFFFFFFFFFFFFFFF) next; inspect`

Now its seed is negative and it outputs funky results.

**Comment by Ducasse** [comment]
but when I read the method comment I see

seed: aNumber
	"Refer #privateNextSeed and [1], seed should be positive"
	| newSeed |
	newSeed := aNumber.
	[ newSeed > 0 ] whileFalse: 
		[ newSeed := newSeed + m ].
	seed := newSeed.


So we can add a simple test. 
To me this is not really a bug. 
Now this is an easy task and I think that we should have also a test.

**Comment by Alisu** [comment]
So the problem comes with the Random>>next that will calculate a new seed.
It calls this method Random>>privateNextSeed
```smalltalk
privateNextSeed
	"This method generates random instances of Integer 	in the interval
	0 to 16r7FFFFFFF. This method does NOT update the seed; repeated sends
	answer the same value. The algorithm is described in detail in [1]"

	| lo hi aLoRHi |
	hi := (seed quo: q) asFloat.
	lo := seed - (hi * q).  " = seed rem: q"  
	aLoRHi := (a * lo) - (r * hi).
	^(aLoRHi > 0.0)
		ifTrue:  [aLoRHi]
		ifFalse: [aLoRHi + m].
```
which return a negative value (should not be the case when we look at the comment).
It checks if the result is negative and add m a magic constant to turn negative integer to positive.
But ... the contributor adpated the algorithm to use Floats so the magic constant m is not valid anymore.

Edit: Changing m to 2^127-1 (magic constant adapted to Floats) seems to break the algo.
