### ISSUE TITLE
RubSmalltalkEditor meta-j shortcut not working

### ISSUE THREAD

**Issue by EwanDawson** [guillep/pharo-core#6323]
**Describe the bug**

`RubSmalltalkEditor class >> buildShortcutsOn:` maps `jumpToNextKeywordOfIt: true` to `$j meta`. Pressing `Ctrl-j` doesn't work.

Note that pressing `Ctrl-Shift-j` (`jumpToNextKeywordOfItL false`) *does* work - it jumps to the previous keyword.

**Version information:**
 - OS: Kubuntu 19.10
 - Version: 8.0.0

I've fixed this, patch coming soon!

**Comment by DarinM223** [comment]
Why hasn't this been merged yet?

**Comment by MarcusDenker** [comment]
because the PR is not done in the Pharo project repository and thus was never seen (it has to show up here: https://github.com/pharo-project/pharo/pulls )

<blockquote><img src="https://repository-images.githubusercontent.com/64123480/451beb80-d08b-11e9-9ade-21d166d787d9" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo">Pull requests · pharo-project/pharo</a></strong></div><div>Pharo is a dynamic reflective pure object-oriented language supporting live programming inspired by Smalltalk. - Pull requests · pharo-project/pharo</div></blockquote>

**Comment by MarcusDenker** [comment]
I made the PR in the correct place, it now just needs a review: https://github.com/pharo-project/pharo/pull/11205
