### ISSUE TITLE
Slot definitions with message cascades in them break class definition parser

### ISSUE THREAD

**Issue by webwarrior-ws** [guillep/pharo-core#6410]
And then classes that contain them cannot be edited.

**To Reproduce**
Create slot subclass with `#printOn:` defined as follows:
 ```
printOn: aStream
	aStream 
		nextPutAll: self class name;
		nextPutAll: ' new yourself; yourself'.
```
Add this slot to a class; save; to edit class definition. 

**Version information:**
Pharo 8 and 9

**Additional context**
Now this example is silly, but I have slots with many parameters, that are also optional, and in definition only parameters with non-default values are shown.
And now I cannot edit definitions of classes that use them.

**Comment by astares** [comment]
I guess you have to follow the regular 

  X => SLOT 

definition style syntax I guess to make the class definition parser happy.

I know this problem - had it/ still have it myself. 

See discussion on <https://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2019-September/276248.html> on Mailinglist. 

If I remember correctly I also discussed this also at ESUG with Marcus as it lead to trouble in my usage of slots and other. 

@MarcusDenker wanted to come up with something regarding Composed Slots to possibly solve it or at least align approaches - but I guess this was also not happening due to time until now. Dont know about the current state.

Unfortunately the way it is now is still not working for me and I still have to do bad workarounds 
in my slot usages - as I run in similar problems with the class definition parser. I still would vote for allowing also the object syntax - which is the most natural. 

But as @Ducasse / @guillep argumented on ML current decision allows to more easily parse definition - which seems to be easier for the tools. I can understand this argument as resources are sparse and time is always an issue.... 


<blockquote><div><strong><a href="https://lists.pharo.org/pipermail/pharo-dev_lists.pharo.org/2019-September/276248.html">[Pharo-dev] Slot definition API?</a></strong></div></blockquote>

**Comment by Ducasse** [comment]
Pay attention, we will change the class definition. I got focusing on the markdown support because it has more immediate impact

**Comment by webwarrior-ws** [comment]
@astares Oh, I forgot to include `#slotName =>` part in my examaple.
However, that changes nothing. The bug is triggered by message cascade - `#parseSlotNode:` does not handle it and throws an error.

**Comment by dionisiydk** [comment]
Whatever "definition syntax" we would consider as a legacy one our parser should not fail on incorrect definition string. This needs to be solved anyway and I think it is important to fix it for Pharo 9 or disable parser integration at all.

@webwarrior-ws maybe you can propose the solution for "failing parsing" as you are working with this.

**Comment by dionisiydk** [comment]
We already have faulty parsing of methods (with syntax errors). We need similar logic for class parser.

**Comment by webwarrior-ws** [comment]
> @webwarrior-ws maybe you can propose the solution for "failing parsing" as you are working with this.

I only encountered a bug and glanced at method that raised exception (it states "this is very ugly" in the comments by the way).
I don't know inner workings of that definition parser.
Also I have no clue about Pharo team's vision regarding this whole thing.

If you plan to only handle select cases, I'd suggest handle message cascade as well. 
Like this:
```#slotName => SlotClass new message1: arg1; message2: arg2; message3: arg3```
or this:
```#slotName => SlotClass message1: arg1; message2: arg2; message3: arg3```
or both.

Because that's the idiomatic way of initializing objects with multiple parameters, all or some of which may be optional.
Only alternatives I can think of are:
1. Builder pattern:
```#slotName => SlotClass in: [ :s | s message1: arg1; message2: arg2; message3: arg3 ]```
2. Redefining `#doesNotUnderstand:` in a way to allow any combination of keywords:
```#slotName => SlotClass message1: arg1 message2: arg2 message3: arg3 ]```
```#slotName => SlotClass message1: arg1 message3: arg3 ]```
and so on

Both of which mess with autocomplete and are less obvious.
