### ISSUE TITLE
String>>asSymbol triggers  self error: 'There is no free space in this collection!'

### ISSUE THREAD

**Issue by georgeganea** [guillep/pharo-core#6524]
**Describe the bug**
String>>asSymbol triggers 
```
self error: 'There is no free space in this collection!'
```

**To Reproduce**
Happens rarely and randomly, generally, the method String>>asSymbol works as expected...
We mostly see this errror on our Jenkins but sometimes we do get it on our dev machines.

**Expected behavior**
String>>asSymbol should work 100% of the time. We should not settle for anything less.

**Screenshots**
<img width="2032" alt="Screenshot 2020-06-09 at 08 59 58" src="https://user-images.githubusercontent.com/3874710/84112287-1f17e300-aa31-11ea-851f-63eb5805bca4.png">

**Version information:**
 - OS: MacOS
 - Version: 0.15.5
But this happens also on Ubuntu 16.04

**Expected development cost**
As you know nothing happens magically, so do you have an idea of the development effort required? 
This looks like an algorithm bug. Should not be that hard to fix.

In addition, are you willing to help because after all Pharo is yours too?
Yes.

**Additional context**
Because we work on Glamorous Toolkit, we always have it loaded so I don't know if this bug is triggered because of loading GT or not. Maybe someone out there has also seen this in the wild in another context.

**Comment by j-brant** [comment]
This is likely a race condition with `asSymbol` as the `NewSymbols` set can be read and written at the same time from different threads. `NewSymbols` is a `WeakSet` and can be read from the `Symbol class>>lookup:` where it sends `like:`, and can be added to from the `Symbol class>>intern:` method. 
The `WeakSet>>like:` method uses the `scanFor:` method that iterates over the slots starting at the hash slot. It returns when it either finds the item it is looking for or finds an empty slot. If it reaches the end of the array, it moves to the first element and checks it. If no element is found and we arrive back at our starting position, then it throws an error. The problem can occur when one process adds a new item which resizes the collection after another process executing the `find:` has reset back to position 1. In this case the `find:` process can make it back to the starting position without finding the element or an empty slot.
Here is some code that I've used to show the problem just using a `WeakSet` instead of trying to get something to work with the `NewSymbols` collection:
```
| set p1 p2 |
set := WeakSet new.
set add: 0.0.
set add: 1.0.
set add: 9.0. 
p1 := [ [set like: 14.0] repeat ] forkAt: 38.
p2 := [ | random |
	random := Random new.
	[ (Delay forMilliseconds: (random nextInt: 50)) wait.
	set addAll: #(2.0 3.0 4.0).
	(Delay forMilliseconds: (random nextInt: 50)) wait.
	set removeAll: #(2.0 3.0 4.0); growTo: 5 ] repeat ] forkAt: 39.
(Delay forSeconds: 10) wait.
"p1 terminate."
p2 terminate.
```
I've ran this around 10 times and alway got an error (however, you mileage may vary). 
The easy fix for this would be to add a lock around the references to the class variables in `Symbol`, but that may slow down lookup. Putting a lock around just the `NewSymbols` might work better as the `SymbolTable` is only modified during `shudown:` or when someone explicitly `rehash` or `compactSymbolTable`

**Comment by StephanEggermont** [comment]
Can confirm in Pharo 9 1543, 64 bit, headless

**Comment by MarcusDenker** [comment]
A PR was merged that protect symbol creation: https://github.com/pharo-project/pharo/pull/16565
