### ISSUE TITLE
Syntactically wrong code can be compiled without Error

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6751]
**Describe the bug**
Compilation of syntactically wrong code should raise an error to at least warn the developer that something bad will happens.

**To Reproduce**
Execute (got from real use case):
```
Object subclass: #Test
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'AAA'.
Test compile: 'initialize
	((Lifeware includesKey: #DummyPoolVar) 
		and: [(Lifeware at: #DummyPoolVar) notNil]) 
			ifFalse: 
				[| nameSpace |
				nameSpace := #{NameSpace} value new.
				Lifeware at: #DummyPoolVar put: nameSpace.
				nameSpace
					environment: Lifeware;
					name: #DummyPoolVar.
				nameSpace at: #Var put: 1].
	(self importDefinitions 
		detect: [:e | e path = #(#Lifeware #DummyPoolVar)]
		ifNone: []) isNil 
		ifTrue: 
			[self setImportDefinitions: (Array 
						with: (#{GeneralNameSpaceImport} value path: #(#Lifeware #DummyPoolVar)))]'
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/4706329/86247797-49327000-bbad-11ea-8889-8000cc50a005.png)
As per the Pharo 9.0.0
Build information: Pharo-9.0.0+build.348.sha.9675774d715aa7943f91d1501b073384441bce14 (64 Bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/4706329/86247898-6c5d1f80-bbad-11ea-8e06-d21be59c25ac.png)

**Version information:**
 - OS: Win 10 - V2004
 - Version: 440

**Expected development cost**
5 mins to revert a wrong commit?
20 mins to add a test on this

**Comment by MarcusDenker** [comment]
This is a result of https://github.com/pharo-project/pharo/issues/6674

Maybe that change was too radical?

**Comment by MarcusDenker** [comment]
What we could do:
-> add a Transcript log when it does it
-> inform the user using inform: (but that is a bit easy to overlook)

Would that be enough?

-> Maybe even add some easy to use expression to find browse all methods like that? A bit like the expression
to find all Undeclareds... which is very similar: code loads but raises error at runtime.

**Comment by tesonep** [comment]
We should not add a transcript log, nobody read the logs. 
We should have a setting to disable this feature and have it off by default by now. As it is really a game-changer feature. 
Until we have better tooling and a good way of working, I think we should have it off.

**Comment by MarcusDenker** [comment]
But why is is bad for syntax errors, but for Undefined Variables we are ok with it?

**Comment by MarcusDenker** [comment]
I really want to understand

**Comment by tesonep** [comment]
It is a good question, maybe non should be error or both should be. 
I am not sure, I am just telling that this is a big game-changer. 
At least we need the setting, and then we can discuss what is the more productive way of using it. 
From a point of view of a dynamic late bound language, maybe we want to handle all the errors like that or not. 

When I see your change the other day I thought it was really cool, but I was doubting about the impact of it. And here, Vincent came with a specific scenario where this is not useful. So, now I am thinking that the best should be to have it optionally (or at least that we can disable it)

**Comment by MarcusDenker** [comment]
my fear is that we will never be able to do anything that matters. Everything interesting will be always "to radical"

**Comment by MarcusDenker** [comment]
Is it really not useful? I am sure in this case they have a lot of methods like that to load. Now they can load all the code, then fix the methods. 

If we disable it, he will get for *every* case the "SyntaxErrorDebugger", (which is broken because it is never used). 
But even if we fix it, it is not nice.

Which means that then you have to do the "load, error, fix the text file, load, error"... while with how it is now, you load all the code, then you browse it and the rule tells you there is a syntax error. You accept, it tells you where, you fix...

But yes, discoverability is a problem...

**Comment by Ducasse** [comment]
Thanks vincent this is cool to have such report.

**Comment by Ducasse** [comment]
I think that this is super important that we have a way to control the fact that we loaded broken code. 
Else we are doomed to have broken code forever around. 
I think that basic cheap static checks are super important because they are cheap. 
Why do we have local definition? We could remove them and think that the first use of unknown variable is a temp.
No? Still local variables are nice because they help us not having multiple wrong temps. 
And this is the same here. I think that we should
- get as much as simple checks
- then and this is not exclusive offers a solid infrastructure to have more relaxed situations. 
We should also understand what are the scenario for relaxed situations. 

I want to be able to say 
``` 
Pharo strictModeFor: packageA
```
and get an the possible garantee.

And I want to be to say
```
Pharo relaxModeFor: Package B
```
And get a lot more support for it.
