### ISSUE TITLE
Enhance StHaltCache to be more performant

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#6946]
**Describe the request**
While compiling methods, StHaltCache add some announcements that slow down a lot the compilation process. 
I'd like to understand what is exactly the goal of this and if this can be optimized to have less impact on the performances.

If it is not mandatory for an everyday use, could we add a setting to disable it?
`StHaltCache defaultCache removeSubscriptions.`

**Expected behavior**
Faster compilation

**Expected development cost**
10 mins

**Version information:**
 - OS: win 10
 - Version: Pharo9.0.0
build: 536, commit: d59067f

**Comment by StevenCostiou** [comment]
The halt cache keeps the knowledge of all halts in the image so that we can see them and enamble/disable them in one click in inspectors and in the debugger.

Speeding it up seems complicated as, either you grab them when you install them (so we need to monitor method changes) or you recompute them at once (which checks all methods in the image).

Both solutions are expansive.

_Mandatory_ is relative to the need or the desire to have that debugging tool or not.
I will add a setting to enable/disable it, it seems to be the best solution.

In the end, it would be solved by completely getting rid of `halt` instructions and rely on breakpoints.

**Comment by MarcusDenker** [comment]
I have an idea how to speed up things like that: we could detect it in the compiler (which would be very fast) and then tag the compiledMethod with a property. This then would be quite fast to check: iterate all methods once, quick check of the property (which would be a very fast nil check in most cases)

**Comment by StevenCostiou** [comment]
In any case, I added a setting to (de)activate the halt gathering at will.
It will be in the next merge.
I will notify you when it's done as I'll need confirmation it's better.
