### ISSUE TITLE
FileLocator workingDirectory gives the root directory on Pharo8

### ISSUE THREAD

**Issue by varvello** [guillep/pharo-core#7039]
**Describe the bug**
See the subject

**To Reproduce**
Evaluate: `FileLocator workingDirectory`, it should give the current directory instead it gives the root directory

**Version information:**
Pharo 8 on OsX 10.14.6

**Comment by Ducasse** [comment]
Guille I added you so that we do not forget to discuss tomorrow. 
I have the same result on P8 and P9 and I'm wondering what is the problem. 

In P8 and P9
```
FileSystem workingDirectory
>>>
 File @ /Users/ducasse/Documents/Pharo/images/P8-Indian
FileLocator workingDirectory
>>> File @ .
```

**Comment by guillep** [comment]
Hi all, I don't think this works wrong.
The working directory is the current directory, but this depends on what your definition of "current directory" means.

The working directory is a per-process property, and it usually defaults to the directory from where the process was launched (if launched from the command line).

https://en.wikipedia.org/wiki/Working_directory
https://linux.die.net/man/3/getcwd
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getcwd-wgetcwd?view=vs-2019

So the question is: how was the process open?
- If Pharo was open from the command line (e.g., `./pharo-ui Pharo.image`) then the working directory will be the same as the one of the invoking shell.
- If Pharo was open by doing a double click, this is defining by the operating system. See for example
https://apple.stackexchange.com/questions/345826/double-click-bash-file-pwd-outputs-my-home-directory-instead-of-the-current-d
https://apple.stackexchange.com/questions/179063/wrong-working-directory-if-bash-script-is-opened-via-double-click
https://stackoverflow.com/questions/12622919/within-windows-what-explicitly-happens-when-i-double-click-on-a-file-in-windows
- If Pharo was open by the Pharo launcher or another application, this is usually inherited

The working directory can usually be changed (for example, the Pharo launcher could change it)

If you want to access your home directory or the image directory, you should use `FileLocator home` or `FileLocator imageDirectory` respectively.

<blockquote><img src="/static/favicon/wikipedia.ico" width="48" align="right"><div><strong><a href="https://en.wikipedia.org/wiki/Working_directory">Working directory - Wikipedia</a></strong></div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://linux.die.net/man/3/getcwd">getcwd(3): current working directory - Linux man page</a></strong></div><div>The getcwd() function copies an absolute pathname of the current working directory to the array pointed to by buf, which is of length size.</div></blockquote>
<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/getcwd-wgetcwd">_getcwd, _wgetcwd</a></strong></div><div>C Runtime Library functions _getcwd, _wgetcwd get the current working directory.</div></blockquote>
<blockquote><img src="https://cdn.sstatic.net/Sites/apple/Img/apple-touch-icon@2.png?v=b514451ec60c" width="48" align="right"><div>Ask Different</div><div><strong><a href="https://apple.stackexchange.com/questions/345826/double-click-bash-file-pwd-outputs-my-home-directory-instead-of-the-current-d">Double-click bash file -> pwd outputs my home directory instead of the current directory</a></strong></div><div>In my Downloads directory, I have an executable bash script :

#!/bin/bash
pwd
when I double-click on it, pwd outputs my home directory. But I want my script to run from the current directory from...</div></blockquote>
<blockquote><img src="https://cdn.sstatic.net/Sites/apple/Img/apple-touch-icon@2.png?v=b514451ec60c" width="48" align="right"><div>Ask Different</div><div><strong><a href="https://apple.stackexchange.com/questions/179063/wrong-working-directory-if-bash-script-is-opened-via-double-click">Wrong working directory, if bash script is opened via double-click</a></strong></div><div>I wrote a bash script in order to directly start eclipse from different workplace locations. Each workplace contains the script, after running it, eclipse is started with the respective workspace s...</div></blockquote>
<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/12622919/within-windows-what-explicitly-happens-when-i-double-click-on-a-file-in-windows">Within Windows, what explicitly happens when I double-click on a file in Windows Explorer?</a></strong></div><div>TL;DR

What are the exact, low-level kernel &amp; OS processes that are being executed when a user either double-clicks or selects a file and presses the Enter key from within Windows Explorer?
De...</div></blockquote>

**Comment by guillep** [comment]
Also, in my image 
```smalltalk
FileLocator workingDirectory  = FileSystem workingDirectory
>>> true
```
 `FileLocator` returns abstract file references that need to be resolved.

Maybe I'm not seeing the problem... The issue is not clear.

**Comment by akgrant43** [comment]
> Maybe I'm not seeing the problem... The issue is not clear.

I think the underlying issue is that Mac sets the working directory to the root directory when Pharo is launched by clicking on an icon (I don't have a Mac, so don't have the exact context), and people aren't expecting this.  Launching from the command line gives the expected behaviour.

Quite likely other applications choose to change the working directory automatically if it is the root directory.

**Comment by varvello** [comment]
I drag and drop the image on the Pharo.app. It's is an issue of Pharo8 (and also Pharo7, I downloaded a vm and tested it). Instead the same behavior  on Pharo6 and previous VMs is fine.

**Comment by guillep** [comment]
It's the other way around. The working directory was broken in Pharo < 6 and it was fixed from Pharo 7 on.

If you want the image directory you can use:

`FileLocator imageDirectory`

And if you want your home directory you can use

`FileLocator home`

**Comment by varvello** [comment]
I see. Anyway I don't know how to set the working directory on Mac OSX 

> It's the other way around. The working directory was broken in Pharo < 6 and it was fixed from Pharo 7 on.
> 
> If you want the image directory you can use:
> 
> `FileLocator imageDirectory`
> 
> And if you want your home directory you can use
> 
> `FileLocator home`

**Comment by Ducasse** [comment]
I suggest that we close the issue now because we will not fix it for now. 
Pablo is telling to me that on Mac applications (not laucnhed from the commandline) always open on root.
