### ISSUE TITLE
UFFI: FFITypeArray should not be deprecated

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#7144]
Class is Needed and should not be deprecated. 

@estebanlm confirmed that on Discord too

**Comment by guillep** [comment]
Yes it should. Please read its class comment and the documentation I spent
2 months to write...

The class had a bad name, FFITypeArray suggests it's an array of types and
it is not.

The functionality is not lost, it is still there, in a class with a
different name and documented properly.

**Comment by estebanlm** [comment]
Mmm... yes. 
So people needs to use `FFIArray`. Nevertheless... I think is still a bad name, because it suggests is to map an array, while is used to define a type which is an array (hence the old name, `FFITypeArray` which was maybe wrong, but it was describing its purpose... just it was possible to be interpreted as you say too). Maybe it should have been called `FFIArrayedType` ?
Anyway, a discussion for other moment :)

**Comment by guillep** [comment]
There are two things: Arrays and Array types. Array types are actually modeled as (anonymous) subclasses of the array class. So the type is not the instance, but the anonymous subclass. Just for the record, this is not my design, I just documented it :).

FFIArray/FFITypeArray has and had two distinct responsibilities: create a new array type (by creating a subclass) and it create an array of a given type/size. This still works as before.

```smalltalk
char128Type := FFITypeArray newArrayType: #char size: 128.
array := FFITypeArray newType: #char size: 10.

char128Type := FFIArray newArrayType: #char size: 128.
array := FFIArray newType: #char size: 10.
```

The problem is that the use of an anonymous subclass can be confusing. `FFITypeArray` did both before too. If the class is the type, and the instance is the array, then the name of the class should refer to the instance, right? Otherwise this could be refactored to not use anonymous subclasses and have explicit `FFIArrayType` objects. That would be a further simplification.

**Comment by astares** [comment]
Thanks for the clarification
