### ISSUE TITLE
Playground does not use the font specified by settings

### ISSUE THREAD

**Issue by tomooda** [guillep/pharo-core#7307]
**Describe the bug**
Playground always uses Source Code Pro font and ignores settings / Appeareance / Standard fonts / Code.

**To Reproduce**
1. Go to Settings / Appearances / Standard fonts / Code and set it to "Courier New".
2. Open a Playground from Tools / Playground menu.
3. Type some letters in the Playground.
4. See the text is not in Courier New but always Source Code Pro.

**Expected behavior**
Playground should use the specified font in the text area.

**Screenshots**
<img width="852" alt="Screenshot 2020-09-15 13 17 51" src="https://user-images.githubusercontent.com/836308/93165035-ef762680-f755-11ea-9dce-d838296c3634.png">

**Version information:**
 - OS: macOS Catalina
 - Version: 10.15.6 

**Expected development cost**
Appending "self whenBuiltDo: [ text withWidgetDo: [ :w | w widget textFont: StandardFonts codeFont ] ]" to StPlayground>>initializePresenters apparently fix the issue.
So, this should be initialization problem during the construction of morphic GUI.
Someone who knows the initialization process of StPlayground and RubScrolledTextMorph would know where to fix.

I can help/pair program to dig the issue.

**Additional context**

**Comment by estebanlm** [comment]
This is more complicated than it seems :) 
Thing is... Spec2 does not uses at all those definitions, and probably it does not has sense anymore... but I need to think in a way to include that, or refactor that into something useful.

**Comment by tomooda** [comment]
Ah, I see it's stylesheet. We need a settings UI on StPharoApplication's stylesheet, do we?

**Comment by estebanlm** [comment]
fixed in https://github.com/pharo-spec/Spec/releases/tag/v0.7.5

<blockquote><img src="https://avatars1.githubusercontent.com/u/43748223?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/pharo-spec/Spec/releases/tag/v0.7.5">Release v0.7.5 · pharo-spec/Spec</a></strong></div><div>SpFilterWithListPresenter was renamed to SpFilteringListPresenter.
lists and trees now use displayIcon: to answer an icon instead icons:.
new presenters SpPaginatorPresenter and SpMillerPaginatorPr...</div></blockquote>
