### ISSUE TITLE
Exceptions should be always logged in the console and PharoDebug.log

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#7312]
After the introduction of Oups the exceptions are not logged in the output file in interactive mode.

**Comment by tesonep** [comment]
The methods sending Smalltalk >> #logError:inContext:
like UIManager >> requestDebuggerOpeningForWarning: aWarning
are not logging the error if Ooups is installed. 

Also DebugSession >> #logStackToFileIfNeeded is never sent.
I can fix it logging before rising the OupsRequest but I don't know if it is correct.

**Comment by dupriezt** [comment]
Yeah, DebugSession>>#logStackToFileIfNeeded is not called by Oups, while it used to be called by MorphicUIManager.
I added this method call in Oups with this PR: https://github.com/pharo-project/pharo/pull/7329
This should also solve Smalltalk>>#logError:inContext: not being called, since DebugSession>>#logStackToFileIfNeeded calls it.
