### ISSUE TITLE
[Fluid] Trait composition should be also a trait

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#7545]
```
Morph < #SpPaginatorMorph
    uses: TObservable;
    slots: { };
    tag: 'Paginator';
    package: 'Spec2-Morphic'
```
now I have to do
```
Morph < #SpPaginatorMorph
    uses: { TObservable };
    slots: { };
    tag: 'Paginator';
    package: 'Spec2-Morphic'
```
trait composition needs to be an array or I have an error

**Comment by dionisiydk** [comment]
I wonder why it's important to accept single trait instead of always require an array (slots part does not allow it for example).
Also would not it be better to use a #traits: selector instead of #uses: ? IMHO it's much clear especially when you do not know the actual meaning of #uses in class definition.

**Comment by Ducasse** [comment]
Yes I agree with you. Now I just used what was there and I would prefer to have traits: { } all the time.

**Comment by Ducasse** [comment]
I opened another issue to have 

```
Morph << #SpPaginatorMorph
    trait: TObservable;
    slots: { };
    tag: 'Paginator';
    package: 'Spec2-Morphic'
```

and I should check with Pablo because it broke the bootstrap.
So I close this issue.
