### ISSUE TITLE
Huge debugger/StPharoApplication memory leak

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#7953]
The closed debuggers are never really destroyed. They are kept in the StPharoApplication.

**To Reproduce**
1. eval `RGEnvironment new halt`
2. do garbage collection and check the class instances
```smalltalk
10 timesRepeat: [Smalltalk garbageCollect ].
RGEnvironment someInstance.

ReferenceFinder findPathTo: RGEnvironment someInstance.
```

![Pharo_KOeiQYgtXz](https://user-images.githubusercontent.com/572494/100990865-ab274500-3552-11eb-9135-3f97283db536.png)

**Version information:**
 - OS: Widnows
 - Version: Pharo 9.0.0, 
 - Build information: Pharo-9.0.0+build.922.sha.0f93f71a2e0ee67f6f76a5765315a2620084897c (64 Bit)

**Comment by StevenCostiou** [comment]
I think I found the problem, it possibly fixes https://github.com/pharo-spec/NewTools/issues/136 at the same time.
It will require a fix in Pharo and in NewTools, I will do both so that we don't have to wait for a merge.
`DebugSession` and the action model of the debugger keep a reference to the exception which seems to prevent garbage collection of the whole debugger and the objects it holds. I would like to find why also...
