### ISSUE TITLE
Integer >> take: needs a better method name, better comment, and better variable names

### ISSUE THREAD

**Issue by olekscode** [guillep/pharo-core#7967]
I think that `Integer >> take:` should be given a more meaningful name (e.g. `numberOfCombinationsTaken:` or `binomialCoefficientsWith:`).

Also, the implementation of `Integer >> take:` is a bit unclear:
- comment is hard to read
- names `kk`, `num`, `denom`, `factor` could be better

```Smalltalk
Integer >> take: kk
	"Return the number of combinations of (self) elements taken kk at a time.  
	For 6 take 3, this is 6*5*4 / (1*2*3).  Zero outside of Pascal's triangle.  Use a trick to go faster."
	" 6 take: 3  "

	| num denom |
	kk < 0 ifTrue: [^ 0].
	kk > self ifTrue: [^ 0].
	num := 1.
	self to: (kk max: self-kk) + 1 by: -1 do: [:factor | num := num * factor].
	denom := 1.
	1 to: (kk min: self-kk) do: [:factor | denom := denom * factor].
	^ num // denom
```

**Comment by Ducasse** [comment]
Indeed!

**Comment by Ducasse** [comment]
So where is the code?

**Comment by olekscode** [comment]
I've only created the issue as a side effect of something else
I didn't do a PR.

But I can do it now because it's cheap

**Comment by Ducasse** [comment]
You see I will not share my todo list with you because it is HUGE and even Huger than that. Now if people do not consider doing what is easy and can help their ecosystem they should not expect that it will magically happen. We are super super busy with super boring and tedious/challenging tasks. And we have a super long list of actions that are important to do. So we could do a little and easy one but at the cost of not doing the complex/important ones.
So thanks for doing it.
