### ISSUE TITLE
testNoUnusedInstanceVariablesLeft is skipped

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8189]
The following classes has unused variables: 

CDFluidClassParserTest FT2BitmapSize SptSpotterProcessor RBRefactoringTest SpRubFindReplaceDialog SptCatalogProjectsProcessorTest StDebuggerInspector SpTestWorldPresenter StPlaygroundPagePresenter RBTransformationTest CDClassDefinitionNode DynamicMessageImplementorTest SpTestingPresenterWithAdditionalPresenters WriteBarrierStub TKTTaskExecution RBFooDummyLintRuleTest RGEnvironmentAnnouncer class SpecTableLayoutAddSpacer NECTestClass RubTextEditor RBFooLintRuleTestData StepThroughTest SliderPresenter SpTestingComposablePresenterWithAdditionalPresenters ListPresenter TKTPromise SpDemoMenuButtonPresenter SpMorphicLabelAdapter ClassHierarchyPrinter SpecLayoutFrame MicAbstractAnnotatedBlock FTHeaderColumnCellMorph PRCodeSemanticActionTest MCMockClassB class RSAbstractContainerBuilder Slot class MicMicrodownTextualBuilder StObjectInspectorPresenter class RSAbstractLineLayout WorldState TMockWithComplexSlot IceTipAdoptCommitCommand StDummyTestClassWithHalts MockForCompilation FLDebuggerStackMaterialization MockWithComplexSlot SpRubFindReplaceService CDClassWithFullDefinitionExample class StPlaygroundPagesPresenter RBRefactoryChange UndefinedSlot class StSindarinDebuggerPresenter CDClassDefinitionParser MCMockClassB SpTextPresenter EDEmergencyDebugger MCGitRemoteRepository RSAbstractFlowLayout class LGitReadStream TMockWithUseAndSlot TreePresenter SpCodeNullInteractionModel WriteBarrierAnotherStub FastTablePresenter ExampleForTestWithSharedPool CDClassWithFullDefinitionExample PRInternalLink RSAbstractContext TKTUIProcessTaskRunner StInspector StDebuggerActionModel CodeParser TFExternalAsyncCall HandMorph EFContext RBDummyLintRuleTest ShCBClassWithInstanceVariables StReporter class TKTLocalProcessTaskRunner SpPanedLayout SpTestingPresenterWithAdditionalPresenters class StPlayground SptHelpProcessorTest RBLintRuleTestData SpCodePopoverErrorPresenter SpecPragmaCollector class TKTWorkerPool CDFluidClassDefinitionParser SpMorphicSpinnerAdapter FluidClassBuilder

**Comment by Ducasse** [comment]
I have no idea why this simple change break the build.

**Comment by Ducasse** [comment]
my PR introduces a little helper to know the instance variables

```
Class {
 	#name : #UnusedVariableRemover,
 	#superclass : #Object,
 	#category : #'ReleaseTests-CleanCode'
 }

  { #category : #analysis }
 UnusedVariableRemover >> classesWithUnusedVariables [
 	"self new classesWithUnusedVariables"

  	^ Smalltalk globals allBehaviors 
 		select: [ :each | each instanceVariables anySatisfy: [ :iv | iv isReferenced not] ]
 ]

  { #category : #analysis }
 UnusedVariableRemover >> unusedVariables [
 	"self new unusedVariables"

  	^ self classesWithUnusedVariables collect: [ :each | each -> (self unusedVariablesOf: each )]
 ]

  { #category : #analysis }
 UnusedVariableRemover >> unusedVariablesOf: aClass [
 	"self new unusedVariablesOf: CDClassDefinitionNode"

  	^ aClass instanceVariables select: [ :iv | iv isReferenced not]
 ]
```

**Comment by astares** [comment]
Some are problems in packages from external projects (like Spec2, NewTools, Epicea, Zinc, ...) that get synched in from time to time - so we need to make sure they do not get reintroduced. I'm already working on that.
Also some of them are not easy to remove as they are required by tests but are not referenced. 
Some of them got freshly introduced as still contributors and even the engineering team seem to constantly ignore the lint rules in their new code (like the one in TFExternalAsyncCall)

I wanted to break this puzzle into pieces therefore - even when this requires more patience and time. I already cleaned many of them (merged by Marcus) and this is still ongoing from my side.

Next one: 
https://github.com/pharo-project/pharo/issues/8224 for TaskIt - CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8228 for deprecated TreePresenter - CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8230 for ClassParser packages - CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8231 for DynamicMessageImplementorTest (fixed with getter) CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8234 for Emergency Debugger packages CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8236 Enlumineur CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8237 ExampleForTestWithSharedPool (required also fixing tests) CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8244 Fuel (FLDebuggerStackMaterialization) - which seems to be out of synch with Fuel repo anyway
https://github.com/pharo-project/pharo/pull/8247 Remove unused class FT2BitmapSize CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8248 FastTable code CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8250 HandMorph CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8253 Microdown CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8256 WriteBarrier Stubs in Kernel CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8258 WorldState CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8261 ClassHierarchyPrinter CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8262 FluidClassBuilder CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8264 in MonticelloMocks CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8266 in Pillar and Pillar tests CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8269 in NECTestClass CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8271 in Ring CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8273 Shift-ClassBuilder CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8276 ThreadedFFI  CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8277 StepThroughTest in Debugger-Model-Tests CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8284 Kernel slots CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8287 MockWithComplexSlot (Kernel-Tests) **STILL OPEN**
https://github.com/pharo-project/pharo/issues/8289 MockForCompilation (OpalCompiler) CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8291 RubTextEditor CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8293 Rubric Spec2 dialogs CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8295 TraitsV2-Tests CLOSED/MERGED
https://github.com/pharo-project/pharo/pull/8328 SliderPresenter CLOSED/MERGED
https://github.com/pharo-project/pharo/issues/8355 ListPresenter CLOSED/MERGED

You can help me moving this forward by reviewing / merging them ... step by step it goes.

**Comment by astares** [comment]
External packages: 
- https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/44  (LGitReadStream / LGitExternalObject in LibGit)
- https://github.com/pharo-project/pharo/issues/8354 (SycRemoveMessageArgumentCommand in SystemCommands)
- https://github.com/ObjectProfile/Roassal3/issues/329 (RSAbstractContext, RSAbstractContainerBuilder, RSAbstractFlowLayout, RSAbstractLineLayout in Roassal)

**Comment by astares** [comment]
For iceberg there is https://github.com/pharo-vcs/iceberg/pull/1424

**Comment by MarcusDenker** [comment]
Update TODO (35 classes to go):

- Spec issue: https://github.com/pharo-spec/NewTools/issues/162
- Newtools issue: https://github.com/pharo-spec/NewTools/issues/162
- RBDummyLintRuleTest,  RBFooDummyLintRuleTest
- SpRoassal3InspectorPresenter
- MockWithComplexSlot https://github.com/pharo-project/pharo/issues/8287
- Iceberg  https://github.com/pharo-vcs/iceberg/pull/1424 (merged but not yet in Pharo9)

**Comment by MarcusDenker** [comment]
Update TODO (29 classes to go):

- Spec issue: pharo-spec/NewTools#162
- Newtools issue: pharo-spec/NewTools#162
- RBDummyLintRuleTest, RBFooDummyLintRuleTest
- SpRoassal3InspectorPresenter: https://github.com/ObjectProfile/Roassal3/issues/339
- MockWithComplexSlot #8287
