### ISSUE TITLE
Reorganize World Menu

### ISSUE THREAD

**Issue by gcorriga** [guillep/pharo-core#8198]
Reorganize the WorldMenu to declutter the Tools menu.

Do this by introducing two new menus - Develop and VCS.
The Develop menu contains all tools for developing within the image - System Browser, Playground, etc.
The VCS menu contains all tools for version control and collaborative work - Iceberg, Change tools etc.

The Tools menu can then be used for additional tools that can be loaded in the image - e.g. Roassal3.

Screenshots:
![image](https://user-images.githubusercontent.com/7032660/103236691-703fe380-493d-11eb-898e-d3f4a418c6af.png)
![image](https://user-images.githubusercontent.com/7032660/103236711-8057c300-493d-11eb-9fbc-57fd0c8a0a70.png)
![image](https://user-images.githubusercontent.com/7032660/103242742-48f21200-494f-11eb-874b-04c639a7ed27.png)
![image](https://user-images.githubusercontent.com/7032660/103242759-57402e00-494f-11eb-83a7-4b4111617469.png)
![image](https://user-images.githubusercontent.com/7032660/103242774-6626e080-494f-11eb-917f-601cb689afcf.png)
![image](https://user-images.githubusercontent.com/7032660/103242808-7fc82800-494f-11eb-9f03-614377593b42.png)

**Comment by macta** [comment]
From Discord -

TM:  Pretty much every application avoids 2 word menus - and those that did seemed to get rid of them... VCS is used by IntelliJ - but actually its not just version control stuff in that menu why not "Organise" - for things you use to organise code, and for Tools - its name has had its day as everything is a tool - I vote for "Community" in part because I like the community feel that Pharo pushes - and why Develop? I would push for "Browse" this would give you:

Pharo, Browse, Organise, Debug, System, Community, Windows, Help - which seems to give a nice complimentary feel. 

(I would also move File Browser into Organise - and remove all "Browser" suffixes), also Process Browser might go into Debug
Reading the menu words again,  I might also think of your journey and change to: 

Pharo, Browse, Debug, Organise, Community, System, Windows, Help

GC: the idea is
'Develop' has all the tools to manage code changes in the image
'VCS' has all the tools for collaboration - version control etc.
I don't like 'Community' too much since there aren't any community-related items there. 'Contrib' would be more precise (but I don't particularly like it). We could go for Applications
anyway I think we all agree more or less with splitting the current Tools menu, and we are now debating the details
so in the spirit of small changes, I wouldn't mind getting the PR merged as is, then build on top of that.

TM: Develop is not resonating - I still think its Browse (Explore?) - effectively you expect it to be File, but we don't do files. If Organise doesn't work - then Collaborate? The trouble there is you have Catalog browser ... but Collaborate could still work? for tools, someone said plugins but they aren't quite that, nor applications but possibly Packages or Libraries?
From your comments we could try:

Pharo, Browse, Debug, Collaborate, Libraries, System, Windows, Help
(Alternatives to Collaborate - Share?)

**Comment by bencoman** [comment]
I haven't been working on Pharo for a while, but this issue caught my eye...

>  we are now debating the details, so in the spirit of small changes, I wouldn't mind getting the PR merged as is, then build on top of that.

Should avoid too much churn on highly visible UI changes, so a bit of upfront debate is good, perhaps with a time limit like 10 days.  My thoughts, just to stimulate discussion - I won't fight for them :)

- Library/Application are better than Collaborate/Community/Organise. 

- If not VCS, then perhaps Sources. That would cover Catalog better than "Versioning" would. Also Catalog might work under Library.

- Test Running, Dr Test, Transcript don't seem to match Explore.

- Develop seems okay, or retain Tools with the shorter list.  

- "Undo last refactoring" might be better under Develop.

**Comment by Bajger** [comment]
Hi there! I'll try to summarize:
There was no representative voice from Pharo users on this. Discord has just few replies that wouldn't tell which preference is good enough. See: 
![image](https://user-images.githubusercontent.com/45875448/105571711-8ed5a680-5d52-11eb-9705-f82e6aeb35c2.png)

Anyway: 
There were few others proposals, which seems to be promising and actually quite touchy. I guess next round of changes (if ever) can use one of these:
eftomi => Pharo, View, Manage, Debug, System, Tools, Windows, Help
Tim => Pharo, Browse, Debug, Organise, Community, System, Windows, Help

Some other thoughts, reasoning is mentioned above by Ben, where:
-  Tools can become "Library" or "Application"
- "VCS" -> "Sources"

In the end it could look like (merge of ideas): 
Pharo, Browse, Debug, Organise, Library, System, Windows, Help
or
Pharo, Browse, Debug, Sources, Library, System, Windows, Help

**Comment by gcorriga** [comment]
If we go for Browse, where should we put Transcript and Playground?

**Comment by gcorriga** [comment]
I'm keeping Browse for now, but an alternative could be 'Explore'. Don't like it too much though.

**Comment by macta** [comment]
I think Browse is the safer choice for our existing users (and we should remove the term browser from any items in that list).

For the record - Explore is also an interesting option too (which might resonate with new users).

I think browsing the Transcript makes sense - for us it's like browsing logs in a traditional system - in fact it makes me think our Transcript could do with a rework to make browsing better to filter stuff etc.

Playgrounds are are a bit of an anomaly but you can stretch it to browsing results/experiments - particularly the new ones that save your snippets... so I think it works well enough?

**Comment by macta** [comment]
Tha is for pushing on this one, a tidy up was due

**Comment by MarcusDenker** [comment]
this was merged
