### ISSUE TITLE
Can't close tabs in System Browser when code has been modified

### ISSUE THREAD

**Issue by gcorriga** [guillep/pharo-core#8308]
**Describe the bug**
I am unable to close system browser tabs if they contained modified code.

**To Reproduce**
1. Open a System Browser
2. Select package 'AST-Core', class ASTCache, method 'reset'
3. Type '; yourself' at the end of the method. Do not accept the edit
4. Click on the 'x' button of the current tab
5. Nothing happens

**Expected behavior**
The Browser should try to close the tab, asking if I want to discard the changes

**Version information:**
 On Windows 10, using headless vm
Build information: Pharo-9.0.0+build.1026.sha.93d6505fa6afca97eabb854e832cca5f3b5255b3 (64 Bit)

**Comment by sanjayminni** [comment]
In the current build the tab cannot be closed at all (irrespective of code being modified). i.e. "x" icon on tab right does not work
Windows 10 Pharo 9 64 bit
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1063.sha.776f24a3fd3544392fa9300503407b3de58a570b (64 Bit)

**Comment by hogoww** [comment]
The problem is that there was a replacement in the hierarchy of the tabs.
(Got no idea of why)
Regardless, Only one event is registered to happen as you can see in the class references of : TabLabelMorph.

I do not know how to fix it properly, but A (super) horrible solution is to swap the code of TabSelectorMorph >> #tabClicked:with:.
(which I haven't submitted because this is way too dirty, even for me)

tabClicked: evt with: aMorph 
	"A tab has been clicked."
	| crossMorph |
	[ 
	crossMorph := aMorph submorphs first submorphs second submorphs first.
	(crossMorph containsPoint: evt position)
		ifTrue:[ | clyMorph pageIndex |
			clyMorph := aMorph owner owner owner.
			pageIndex := aMorph owner tabs indexOf: aMorph.
			clyMorph removePage: (clyMorph pages at: pageIndex).
			^ self .].
		] on: Error do: [:e| ].

	self selectedIndex: (self tabs indexOf: aMorph)

The #on:error: is because not all the TabSelectorMorph have the same object graph, and therefore this may fail.
Note that this fix can be applied to clean up a bit and then go back the the proper behavior.

Might interest @estebanlm 

Pierre

**Comment by Alisu** [comment]
To add some more informations, as Pierre stated we now use Spec2 tabs.
Now, the tab is a TabLabelMorph composed of two submorphs:
-the first one is a morph composed of an AlphaImageMorph and a LabelMorph (for the comment tab it is the "!" and the "Comment".
-the second one is the AlphaImageMorph containing our "x" to close the tab. The problem is that this morph never subscribe to any events.
For the class creation tab we found that Calypso add the tab in ClyNoteBookManager>>addTool: and create the TabLabelMorph in ClyClassCreationToolMorph>>addNotebookPageOn:.
Then after the creation, we send the message beCloseable, the morph with the cross should subscribe to a click event here but the one we send the message to is the presenter who don't know the morph.

**Comment by Alisu** [comment]
Update:

So I added in ClyNoteBookPageMorph>>beCloseable
```
labelPresenter closeImage eventHandler whenMouseDownDo: [ :anEvent | owner removePage: self ]
```
and now I try to suppress the page twice.
