### ISSUE TITLE
font get mangled again...

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8323]
I cannot reproduce it but with 
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1029.sha.0eaa422d0d9681484c04883c4c0e1db3c09e5f81 (64 Bit)

on latest VM headless I got 
![Screenshot 2021-01-09 at 20 08 32](https://user-images.githubusercontent.com/432549/104106774-f18d6380-52b7-11eb-91ce-ebf9bc3dea77.png)

**Comment by tesonep** [comment]
Zombie!!!!

**Comment by amtween** [comment]
This happens when two FreeTypeFonts with the same familyName, but different pointSizes, are concurrently rendering a glyph. The fonts share the same underlying FT_Face handle, e.g.
```
(LogicalFont familyName: 'Source Code Pro' pointSize: 10) realFont face handle == (LogicalFont familyName: 'Source Code Pro' pointSize: 20) realFont face handle
```
But "An FT_Face object can only be safely used from one thread at a time" - https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html.

When 2 processes are trying to use the same FT_Face to render a glyph at different point sizes, this race condition can occur...
Process A sets the point size in the FT_Face to 10
Process B sets the point size in the FT_Face to 20
Process A renders the glyph for 'X' and adds it to the cache
process B renders the glyph for 'X' and adds it to the cache

both the 10 point font and the 20 point font now have a cached 20 point glyph.

The test  below reproduces the problem fairly reliably (I sometimes need to run it a few times)...
```
| sem text canvases10Point canvases20Point renderer process10Point process20Point |
30 timesRepeat: [
	sem := Semaphore new.
	text := (String loremIpsum: 20).
	FreeTypeCache current removeAll.
	canvases10Point := OrderedCollection new.
	canvases20Point := OrderedCollection new.
	renderer := [:pointSize :collection | |canvas|
		canvas := FormCanvas extent: 1000@1000.
		collection add: canvas.
		(RubScrolledTextMorph new)
			setText: text;
			font: (LogicalFont familyName: 'Source Code Pro' pointSize: pointSize);
			bounds: (0@0 corner: canvas form extent);
			fullDrawOn: canvas.
		sem signal].
		process10Point := [ renderer value: 10 value: canvases10Point].
		process20Point := [ renderer value: 20 value: canvases20Point].
	2 timesRepeat: [
		process10Point forkAt: 39.
		process20Point forkAt: 39].
	4 timesRepeat:[sem wait].
	self assert: (canvases10Point first form bits = canvases10Point last form bits).
	self assert: (canvases20Point first form bits = canvases20Point last form bits).
]
```

A possible simple fix is change the FreeTypeFont mutex instance variable into a class variable i.e.

```
AbstractFont subclass: #FreeTypeFont
	instanceVariableNames: 'face pointSize simulatedEmphasis pixelSize widthAndKernedWidthCache cachedHeight cachedAscent cachedDescent subPixelPositioned symbolFont '
	classVariableNames: 'mutex'
	poolDictionaries: 'FT2Constants FreeTypeCacheConstants'
	package: 'FreeType-Fonts'
```

This prevents any two FreeTypeFonts (and therefore their FT_Faces) from concurrently rendering a glyph.
The test above then no longer fails.

A better fix would be to remove the mutex inst var from FreeTypeFont; add a mutex inst var to FreeTypeFace; and use it to protect the relevant sections of code in FreeTypeFont & FreeTypeGlyphRenderer. 


<blockquote><img src="images/favico.ico" width="48" align="right"><div><strong><a href="https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html">Base Interface - FreeType-2.10.4 API Reference</a></strong></div><div>API Reference Documentation for FreeType-2.10.4</div></blockquote>

**Comment by MarcusDenker** [comment]
this did not happen anymore since a long time
