### ISSUE TITLE
Shortcuts insert letter keys

### ISSUE THREAD

**Issue by nnoodle** [guillep/pharo-core#8368]
**Describe the bug**
Shortcuts are inserting their letter keys after pressing them, for example Ctrl-a would select everything, then input an 'a', replacing all the selected text with it.

**To Reproduce**
1. Click on any editable text.
2. Press Ctrl-a.

**Video**
https://user-images.githubusercontent.com/28656483/104578495-6207fc00-568d-11eb-9473-f09260a6f18a.mp4

**Version information:**
 - OS: Ubuntu 20.10
 - Version: Pharo9.0-SNAPSHOT.build.1048.sha.cdbcfb1.arch.64bit

**Additional context**
Shortcuts work fine when I tried the stable image.

**Comment by fxgallego** [comment]
It happens also with Ctrl-C Ctrl-V, doit, printit, etc

**Comment by guillep** [comment]
If somebody has time, could you check the fix in #8384 ? I've tested it in a linux virtual box

**Comment by fxgallego** [comment]
Hi Guille, I'm new to Pharo but not Smalltalk.
I'm not sure how to download the image containing this change because I did
it from the launcher and HandMorph still has the old code.
Anyway, I changed it directly on the source with the same code I see in
the GitHub diff, in a Playground any Ctrl combination doesn't work anymore.
With the old code Ctrl-I (inspect) works ok but not Ctrl-D (doit)

**Comment by guillep** [comment]
> Hi Guille, I'm new to Pharo but not Smalltalk. I'm not sure how to download the image containing this change because I did it from the launcher and HandMorph still has the old code. Anyway, I changed it directly on the source

Well, given that the change is two lines, I was expecting this.
I opened the offending method and I overwrote the lines in the PR with:

```smalltalk
"If a modifier key is pressed the keystroke event is handled by #visitMouseDownEvent:"
(type == #keystroke and: [ keyEvent commandKeyPressed
	or: [ keyEvent controlKeyPressed ] ])
		ifTrue: [ ^ #invalid ].
```

I did the paste and accept by doing right click.

> and with the same code I see in the GitHub diff, in a Playground any Ctrl combination doesn't work anymore. With the old code Ctrl-I (inspect) works ok but not Ctrl-D (doit).

This is strange. I did myself the following:
 - I changed the code as in the PR in the latest image (adding the case for ctrl)
 - opened a new playground
 - I typed `asdasd`
 - Ctrl + A => does select all (instead of inserting an `a`)
 - Ctrl + C => does not insert a `c`
 - Ctrl + V many times => correctly pastes the original `asdad` many times

Maybe it's important to close all browsers/text editors (though it shouldn't be...)

**Comment by fxgallego** [comment]
OK the first time I wrote the code by hand so I made a mistake in the `or:`.
Copy and paste the code and it worked ok in the Playground!

There is an additional problem I found when pressing `Supr` in the Playground as in source code editors. Each time I press `Supr` the editor adds a red square with a cross. If I inspect the Character it's `Character delete` so the editor is showing it instead of ignoring it.

**Comment by guillep** [comment]
> There is an additional problem I found when pressing `Supr` in the Playground as in source code editors. Each time I press `Supr` the editor adds a red square with a cross. If I inspect the Character it's `Character delete` so the editor is showing it instead of ignoring it.

Thanks! I'll fix that one before the day finishes

**Comment by fxgallego** [comment]
Additionally, if you have `CapsLock` ON then with the new code nothing happens. In P8, for instance, Ctrl-V with caps lock ON writes the character `$V` instead of pasting the clipboard. Seems Caps Lock affects the modifier behavior. In Windows works ok.

**Comment by fxgallego** [comment]
The `Start` (inicio) key does nothing. `End` key works ok. If you prefer I can create a new issue for each new thing I found about this kind of problems. I don't work in Linux, just doing some compatibility testing and found this.

**Comment by guillep** [comment]
> The `Start` (inicio) key does nothing. `End` key works ok. If you prefer I can create a new issue for each new thing I found about this kind of problems. I don't work in Linux, just doing some compatibility testing and found this.

Oh, that would be awesome! It will indeed help me tracing all this things

**Comment by fxgallego** [comment]
So do you want me create 2 new issues? One for the caps lock and another one for the start key?

**Comment by guillep** [comment]
Yes, please. One per different issue, worst case scenario I can close many at once. But they may not be related.
