### ISSUE TITLE
Fixes new menu organisation

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8412]
Apparently we lost the code browser, and all the menu related to the browser. 
and more in the process. 
Iceberg should not be under Library!!!

I also suggest to have 

just after Pharo

Quick
    System browser
    Iceberg
    TestRunner
    Playground

Because I do not want to have to look for the most frequent tools we use daily.

S.

**Comment by gcorriga** [comment]
@Ducasse

We will need some coordination as this can't be solved in a single PR.

The problem is that the Iceberg menu item is defined in IceTipRepositoriesBrowser class>>#menuCommandOn: which does not belong to the pharo package - it's managed as a separate package.

I can add a temporary workaround to keep the menu item. This will mean some temporary duplication.
