### ISSUE TITLE
unused Ivars in Iceberag: IceTipAdoptCommitCommand , LGitReadStream

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8423]
**Describe the problem**
LGitReadStream and IceTipAdoptCommitCommand have unused instance variables

**Comment by MarcusDenker** [comment]
MCGitRemoteRepository

**Comment by MarcusDenker** [comment]
Fixing this is a step for issue #8189

**Comment by tinchodias** [comment]
**In short**: This will be fixed when https://github.com/pharo-project/pharo/pull/8461 is merged.

**Details**:

 IceTipAdoptCommitCommand was already fixed in Iceberg v2, but the unused ivar in LGitReadStream still was there. 

However, there was a recent PR from @astares that fixes it. I created the [new version 2.1.2](https://github.com/pharo-vcs/libgit2-pharo-bindings/releases/tag/v2.1.2) including such PR. It is now used from Iceberg v2.
