### ISSUE TITLE
"Browse it" evaluates code. Can lead to bad side effects

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8515]
**Describe the bug**
add this line in the playground:

```
Smalltalk snapshot: true andQuit: true
````

The put the cursor anywhere on the line. CMD-B --> image quits

The reason is that "Browse it" evaluates code. This is not a good idea, as this can have all kinds of evil side effects.

**Comment by kasperosterbye** [comment]
How is this different from doit, printit and inspectit? - I mean - why is it more evil that BrowseIt has side effects than InspectIt has?

**Comment by MarcusDenker** [comment]
I think I expect "browse it" to be purely navigation. Like "implementors of" and "senders of". When I execute code I think about possible side effect, when I navigate I do not.

**Comment by kasperosterbye** [comment]
Do you want `Object newAnonymousSubclass browse` to be without side effects?. I would have no idea of how to come up with a solution, but I am looking forward to seeing what you have of ideas.

**Comment by MarcusDenker** [comment]
no, just the interaction: if I put the courser on the "Smalltalk" and do "alt-b", I do not want the image to quit.

```
Smalltalk snapshot: true andQuit: true
```

I expect it to  realise that Smalltalk is a var pointing to an object and thus browse that class.

if the cursor is on #snapshot, I expect it to browse the implementors of #snapshot: andQuit:

**Comment by MarcusDenker** [comment]
To me "browse it" was meant as an intelligent version that merges both "implementors of" and "Class references to" that in addition knows about variable content.

**Comment by MarcusDenker** [comment]
I am not against a "Doit And browse", but that needs to be explicit that this is a "doit" interaction, not a "code navigation" interaction.

**Comment by kasperosterbye** [comment]
I was just too dense to grasp what you were after. If you put the cursor anywhere in something which is a name of a class, alt-b should just read the variable, not the whole line. 
That is a good idea!
I normally double-click the variable before alt-b.

**Comment by fxgallego** [comment]
Anything in in smalltalk can have side effects.

The term Browse it, means evaluate and browse. It's the same as Do it, Debug it, Inspect it, Print it, it is part of the **same family**. In Dolphin it works the same way and it is something completely normal that you evaluate a line or a message send and browse the result, typically in debug sessions. I believe that it's not only hard to implement this in a safer way but also non desirable. I would consider it a bug not working as Inspect it and the others.

**Comment by Ducasse** [comment]
+100%
For me I expect Browse it to be like Execute and browse. 
I neeeeed it that way. 
I want to select 10@30 browse it and get the class point.
I'm always executing browse it that way. 
Else I have to do inspect self browse.... :(

**Comment by Ducasse** [comment]
But there is a catch!

I want browse it 
- to act as implementor if this is the selector. 
- to act as the basicBrowse = open a class definition when the text is a class (I do not want to see the metaclass when I select Point).

Similar senders should 
   - look for senders when I select a symbol 
   - look for a class ref when the text I selected is a class name. 
 
In fact I implemented this navigation in old versions of Pharo and people systematically broke it. I lost it when we got nautilus and I reimplemented and lost it again when denis
implemented calypso. I do not get why people do not listen because 

We should have 

basicShowClassDef
basicShowCLassRef
basicShowMethodDefinition
basicShowMethodUse
basicInspect

and 
Browse it 
- basicInspect when object is not a class or a symbol
- basicShowMethodDefinition when text = selector
- basicShowClassDefinition when text = a class

Implementor
- basicShowMethodDefinition when text is a symbol
- basicShowClassDefinition when text is a class / trait

Sender
- basicShowMethodUse when text is a symbol
- basicClassRef when text is a class
- basicTraitUsers when text is a traits

This way I do not have to do the job that computer can do for me and I'm not trapped in modes.

**Comment by fxgallego** [comment]
Additionally, and maybe I'm wrong here because I recently started working with Pharo tools, when y select some message in a browser and it is a keyword one, I should not be forced to select all parts of the keyword to browse senders or implementors. 

For example `self at: key ifAbsent: aBlock`
in Pharo if I doubleClick `at:` and press `Ctrl-m` the resulting browser contains the implementors of `#at:`, but the message is `#at:ifAbsent:`. In Dolphin this works better and correctly shows the implementors of  `#at:ifAbsent:`.

**Comment by Ducasse** [comment]
We could implement a heuristic like that. Thanks for the suggestion. 
- Did you see that in Pharo  if you place your cursor on the line and press Cmd-M you get the implementors for the selector in the line. You do not have to move your mouse to precisely select something?
- It works also if you have
- 
```
self at: 
33
ifAbsent: [ ]
```
To select the block you can double click before the first or after the last character + Cmd M and get the implementors.
- So to us this is a lot better than forcing people to select the selector in the text.

- For now we want the receiver to be better handled and it will be our next iteration. Because when we double click on Point we should get the class Point. 
- It also means that in certain cases you can have multiple solutions and that the user should be prompted. And we will check if we have some times for this. 

- What if you type at: hkjhkj toto:, I imagine that I only get at:
- what if the code is 
```
at: hjkjhkj
(
ifAbsent: 
```
so it means that we will need to parse or pay attention to junk in the text.
However a simple approach can work to solve 90% of the case.

BTW Can you open a separate bug entry? Named Cooler SelectorExtractor
Did you check the CodeNavigation package? CNSelectorExtractor is the class responsible for all this logic. As you can see with the tests it is not just plain stupid
and we have nice heuristics to disambiguate selector identification. 

Now if you want to help improving Pharo, adding some tests there showing the desired behavior is a good test. Providing code that makes the tests passed is the best way to make sure that this feature will be implemented.

**Comment by MarcusDenker** [comment]
In Pharo12, we improved the UI to make it explicit that "Browse it" is "doit and browse", see https://github.com/pharo-project/pharo/pull/13095
