### ISSUE TITLE
Inspector not showing block contents after opening bracket

### ISSUE THREAD

**Issue by isCzech** [guillep/pharo-core#8592]
![image](https://user-images.githubusercontent.com/73360313/108628073-fe75a900-7458-11eb-9a92-fa8e187124fb.png)

Pharo 9.0.0
Build information: Pharo-9.0.0+build.1093.sha.5a650fec081de6a41678530844647baad6723797 (64 Bit)

**Comment by isCzech** [comment]
even simpler example... It happens whenever a block contains more than one expression.
![image](https://user-images.githubusercontent.com/73360313/108634534-393c0900-747a-11eb-8738-493660b8bae7.png)

**Comment by estebanlm** [comment]
We cannot show the full block source in the list because it can be huge and it will not has sence in a list. 
However, I have added a "source code" tab in BlockClosure inspection, that will point to the right place/code.

Fixed in https://github.com/pharo-spec/NewTools/commit/a321bea7ecc6196e6faa2b59be8825b3c695cab9
