### ISSUE TITLE
Enhance Debugger to show the DNU call in the stack

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#8595]
**Describe the request**
I concede that it is nice that the DNU method is not needed all the time and it can loose beginner in the debugging process. However, I think it should be still nice to have it in the stack. First, one may want to debug the DNU method (a custom one for instance). Or second, access to the instance on which the DNU has been called:
![image](https://user-images.githubusercontent.com/4706329/108635822-cd5d9e80-7481-11eb-827c-cd1bc8e6f9dd.png)
In the above example, Object new cannot be inspected. I do no want to create a new "toto" method but browse the api of the "Object new" to find the existing equivalent.

**Expected behavior**
Either do not trim the stack and point to the current method (not the DNU one), or show the current stack top.

**Expected development cost**
1h for Steven

**Version information:**
Pharo9.0.0
build: 1145, commit: 2990df5

**Comment by StevenCostiou** [comment]
Vincent, your bug report is incorrect.
You actually want to see the receiver of the DNU, it has nothing to do with the stack filtering.

Thanks for highlighting that problem, could you rewrite your issue as something like "we don't see the receiver?".
Thanks.

To help you until then, you have an option to disable stack filtering, see the screenshot below:
![Screenshot 2021-02-26 at 11 39 57](https://user-images.githubusercontent.com/26929529/109290020-5c263e80-7827-11eb-858f-afc8a317f767.png)

Then about stack filtering, filtering it or not is trivial. Now this is a design problem: how to provide something nice, fluid, intuitive and working for all users (possibly with options)?

Some want it all, some want it filtered. It is complicated. 
Would you like to take an hour of your time and propose a solution?
Thank you very much.

**Comment by StevenCostiou** [comment]
@VincentBlondeau please review https://github.com/pharo-project/pharo/pull/8651
I believe it would help for your problem: see the screenshot in the PR.

As a technical note, it seems not possible to use stack top, as it seems when entering a DNU signaler context the stack is emptied (why?), and in the signal context (the DNU itself) the receiver is on the stack, but stack top is not the receiver (it is the exception).

@MarcusDenker @guillep is it something manipulated in the image side, contexts are dropped or something in case of a DNU?

In any case, the PR provide an enhancement, as we have direct inspection capabilities on the exception itself and the explicit receiver of the DNU (instead of obscure stacktop).

**Comment by StevenCostiou** [comment]
Note: this will not work if you get to a DNU while stepping but that is due to another bug https://github.com/pharo-project/pharo/issues/8502 that is yet to be solved.

**Comment by VincentBlondeau** [comment]
Thanks Steven! It will help greatly!
