### ISSUE TITLE
Traits with State: #allInstVarNames not in sync with #allSlots

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#8630]
**Describe the bug**
This should be true:

```
TDebuggerTest class allInstVarNames size = TDebuggerTest class allSlots size
```

This leads to one of the problems shown by issue https://github.com/pharo-project/pharo/issues/7952

**Comment by astares** [comment]
Why "allInstVarNames" instead of "allInstanceVariableNames" ? 

Lets fight abbreviations ...

https://github.com/pharo-project/pharo/issues/8631

**Comment by Alisu** [comment]
```
TDebuggerTest class allInstVarNames
```
goes through the hierarchy (TDebuggerTest then TestCase class then TestAsserter class etc...) to collect all the InstVar.
Except here there is two more slots define in the class side of the trait TDebugger (TDebugger classTrait) used by TDebuggerTest.
Since we don't go through the hierarchy of the trait we never collect them.

**Comment by MarcusDenker** [comment]
Another interesting finding:

```
TDebuggerTest class slots 
```
vs
```
TDebuggerTest class classLayout slots
```

this should answer the same

**Comment by Alisu** [comment]
Hum this one is more difficult the TDebuggerTest class indeed don't define any new slot but for the layout point of view there is two slots that it should contains (aka they don't come from the hierarchy).
It means we need to define a new scope which is a LayoutTraitScope but the layout has and should have no knowledge the class is traited.
