### ISSUE TITLE
Undeclared Variable does not raise error

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8632]
I got a class with a setter that was setting a field that did not exist.

```
setBar: arg
  bar := arg
```

bar was not defined in the class and calypso reported it. 
Nevertheless invoking the method setBar: did not raise any error. 
To me this is a shock because it means that we can invoke bogus code. 

S.

**Comment by MarcusDenker** [comment]
yes, you should get one dialog "unknown var, what should I do?". If you compile it nevertheless, or load it in non-interactive mode, it compiled an Undeclared.

**Comment by MarcusDenker** [comment]
(there is another problem that if you do that in a debugger in an execution started from the playground, it has some bad behaviour of adding a binding to the requesting playground, I will fix that soon)

**Comment by MarcusDenker** [comment]
This is related to https://github.com/pharo-project/pharo/issues/7083

**Comment by MarcusDenker** [comment]
I think we should do what we tried with Steven: in interactive mode, a non-existing variable should, at runtime, raise a dialog with the action that allows you to define that var.

**Comment by astares** [comment]
@MarcusDenker A dialog? Remember that runtime could be headless...

What is really needed is a kind of **overlay icon** on package icons, class icons and method icons for classes and methods to tell you "there are still lint errors"like in Eclipse:

![image](https://user-images.githubusercontent.com/5980033/109205871-7b7d8700-77a7-11eb-9395-2c9fa9245968.png)

So normally in Java you try to solve lint issues (or exclude the lint rules) until this **exclamation mark** is gone from the method, class up to the package so you come into a clean state for each.

Another additional possibility is to put a red stop icon for rules checking such things in the lint pane.

For instance in IDEs like Eclipse lint errors look like:
![image](https://user-images.githubusercontent.com/5980033/109205749-52f58d00-77a7-11eb-87de-be22bba1c004.png)

**Comment by MarcusDenker** [comment]
Yes, we should a) provide the repair as part of the visualised error, no dialog and b) we should change how Undeclareds work.
But that is a big change...  I want to do it nevertheless.

Right now it works as it was working since ST80 was created... 

- in interactive mode you get a dialog
- in non-interactive mode it compiles a reference to Undeclared. 

This happens, too, when you remove an instance variable: the methods are recompiled non-interactively with Undeclareds (which read as nil), as noted in #7083. Which means that this can happen quite easily during normal development.

**Comment by StevenCostiou** [comment]
@Ducasse I checked when I reported that issue (with documentation and a proposition of fix) https://github.com/pharo-project/pharo/issues/7083 : this problem has been there since a long time.

My proposition was implicitly rejected, so it was a standby.

@astares Your proposition is fully static. The problem is when you actually have that code running (i.e., its a bug). I spotted that because at some point, code executing undeclared variable actually executed and stored something into the undeclared, then **much** later some unrelated code with **another** undeclared variable was also executing, but that time using the shared value that was stored into the undeclared.

Then you get a `myObjectOfARandomClassUnrelatedToMyCode did not understand that message`. Good luck finding where that comes from, it is impossible to track the source of that (not *impossible*, but highly impractical).

So the point is not headless or not, if we execute that code we should crash (or open a debugger, which should be available in headless).

**Comment by StevenCostiou** [comment]
> Nevertheless invoking the method setBar: did not raise any error.
> To me this is a shock because it means that we can invoke bogus code.

I explained that in details a while ago (issues + discord + emails), and I insisted. Nobody cared (or read me, for what I know...). 
It is a motivation killer. Please note that.

**Comment by Ducasse** [comment]
Hi marcus

I do not remember if I was in interactive mode. 
Do we get a notice when we load code?

@StevenCostiou 
Why do you say that your proposal was implicitly rejected?
We never implicitly reject things. We always pay attention to contribution.
Now may be you should consider that people are super busy and that they are running out of time. 

We all have different agenda and roadmaps. 
Please note that it is important to add contents to an issue. Not everybody has the time (again) to 
follow discord.

**Comment by Ducasse** [comment]
To me we should think about what is the behaviour we want to have. 
May be we should do something more than having an undeclared. 
I always wanted to have a kind of log about problems in the code (by opposition to have a trace in Transcript).

**Comment by Ducasse** [comment]
I worked on Logger and after pushed Beacon into Pharo so that we can build a simple tool to log the shadowed, and other compilation related errors.

**Comment by StevenCostiou** [comment]
> Why do you say that your proposal was implicitly rejected?
> We never implicitly reject things. We always pay attention to contribution.

This is not good or bad in any way, it is only the factual status: an unfit solution for a problem in standby.

> Now may be you should consider that people are super busy and that they are running out of time.

I am amongst these people :)

> Please note that it is important to add contents to an issue. Not everybody has the time (again) to
> follow discord.

The issue is reported here https://github.com/pharo-project/pharo/issues/7083 and there is a linked PR (that is not suitable) with a discussion too. Maybe this one should be closed, as it is a duplicate. Maybe some details could be added to the original issue?

**Comment by dionisiydk** [comment]
> I explained that in details a while ago (issues + discord + emails), and I insisted. Nobody cared (or read me, for what I know...).
> It is a motivation killer. Please note that.

HI @StevenCostiou . I remember I commented your PR. It is definitely the right thing to do. But it requires additional work to correctly handle the case when undeclared variable is finally declared. It may affect the performance of code loading and therefore it requires extra testing to measure this

**Comment by MarcusDenker** [comment]
I merge this into issue  #7083
