### ISSUE TITLE
Creating a method is not working when receiver is nil

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8636]
```
express foo
```
when express is nil

produces 

<img width="1022" alt="Screenshot 2021-02-25 at 22 15 48" src="https://user-images.githubusercontent.com/432549/109218830-33666080-77b7-11eb-9037-85fefc86a580.png">

```
MessageNotUnderstood(Object)>>doesNotUnderstand: #variableNode
StDebugger>>createMissingClass
StDefineClassCommand>>execute
StDefineMissingEntityCommand>>execute
SpCommand(CmCommandDecorator)>>execute
[ specCommand execute ] in [ :specCommand | 
			aButtonClass new
				label: specCommand name;
				help: specCommand description;
				in: [ :button | 
					specCommand hasIcon
						ifTrue: [ button icon: specCommand icon ] ];
				action: [ specCommand execute ];
				yourself ] in SpCommand>>configureAsButtonOfClass: in Block: [ specCommand execute ]
FullBlockClosure(BlockClosure)>>cull:
SpMorphicToolbarButtonAdapter>>execute
[ :anAdapter | anAdapter execute ] in SpToolbarButtonPresenter>>execute in Block: [ :anAdapter | anAdapter execute ]
FullBlockClosure(BlockClosure)>>cull:
SpMorphicToolbarButtonAdapter(ProtoObject)>>ifNotNil:
SpToolbarButtonPresenter(SpAbstractPresenter)>>withAdapterDo:
SpToolbarButtonPresenter>>execute
SpToolbarButtonMorph(PluggableButtonMorph)>>performAction:
[:m |
		(m containsPoint: evt cursorPoint) ifTrue: [m enabled ifTrue: [ m performAction: evt ]]] in SpToolbarButtonMorph(PluggableButtonMorph)>>mouseUp: in Block: [:m |...
Array(SequenceableCollection)>>do:
SpToolbarButtonMorph(PluggableButtonMorph)>>mouseUp:
SpToolbarButtonMorph(Morph)>>handleMouseUp:
MouseButtonEvent>>sentTo:
SpToolbarButtonMorph(Morph)>>handleEvent:
SpToolbarButtonMorph(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: 
			(anEvent transformedBy: (focusHolder transformedFrom: self)).
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
```

**Comment by MarcusDenker** [comment]
The reason is that it executes the wrong code: create class, but it should do "create method"

This is because StDebuggerErrorContextPredicate>>#isContextMissingClassException explicitly checks for nil:

```
isContextMissingClassException

	^ exception class == VariableNotDeclared or: [ 
		  exception receiver isNil and: [ 
			  exception class == MessageNotUnderstood ] ]
```

and StDebuggerErrorContextPredicate>>#isContextDoesNotUnderstand explicitly does not match for nil:


```
isContextDoesNotUnderstand

	^ exception class = MessageNotUnderstood and: [ 
		  | message |
		  message := exception message.
		  exception receiver notNil and: [ 
			  (exception receiver respondsTo: message selector) not and: [ 
				  exception signalerContext method methodClass == Object ] ] ]
```

**Comment by MarcusDenker** [comment]
It seems to work if we remove the nil check for both. But there are tests that fail because they check exactly the current behavior.

I do not think that the nil check is needed, as the case of sending a message to a  Undefined Variable (which reads as nil) is taken care of by the " exception class == VariableNotDeclared" check

**Comment by StevenCostiou** [comment]
But the method would be created on which class if the receiver is nil?

**Comment by StevenCostiou** [comment]
> I do not think that the nil check is needed, as the case of sending a message to a Undefined Variable (which reads as nil) is taken care of by the " exception class == VariableNotDeclared" check

This nil check was because the system was unable to detect that an MNU with `nil` is due to an undefined variable.
I did not went further, so checking right now.

When a `nil` enters a DNU, there is a computation to tell if it's a simple MNU or an attempt to send a message to an undefined variable.

But it seems that in `UndefinedObject` the method `findUndeclaredVariableIn:` does not work on the proper ast and is not able to detect the undefined variable.

I will investigate a bit more.

**Comment by StevenCostiou** [comment]
After that, I understand the logic. But what is the sense of creating a method on a nil (which will be what happens in the described case)?

**Comment by StevenCostiou** [comment]
So, in `UndefinedVariable`, writing this instead of `thisContext sender` by the following works (all tests work with just the modification you suggested above):
```Smalltalk
doesNotUnderstand: aMessage

	"Handle the fact that there was an attempt to send the given message to an Undeclared variable (nil), hence the receiver does not understand this message (typically #new)."

	"Testing: (nil activeProcess)"

	<debuggerCompleteToSender>
	| exception resumeValue node |
	[ 
	node := self findUndeclaredVariableIn:
		        thisContext sender sender sender sender sourceNodeExecuted ] onErrorDo: [ :ex | 
				"This is ugly, but we have a dependency with Opal compiler and 
				it should be extracted. If there is a failure during the bootstrap, this
				dependency produces an infinite loop"
		 ].
[...]
```
I understand this is because of full blocks that change the call stack.
But this is ugly... how can we do this better?

I doing a first PR to highlight that.

**Comment by StevenCostiou** [comment]
Ok, I can do `thisContext outerContext sender` and now it works. Doing a PR.

**Comment by StevenCostiou** [comment]
Done https://github.com/pharo-project/pharo/pull/8653
