### ISSUE TITLE
Expression leading to error is not highlighted anymore. 

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8659]
I do not know if this is a bug in the debugger, in the code/text mapping or the SpCodePresenter. 
Now when we have an error and the debugger displays the stack, then the expression is not highlighted
anymore.

**Comment by Ducasse** [comment]
I did not check in latest version: 

Pharo 9.0.0
Build information: Pharo-9.0.0+build.1153.sha.37c85c05e2f95ec779d1c2d701df05e3f87a291b (64 Bit)

**Comment by StevenCostiou** [comment]
This is a regression due to last newtools merge I think.

**Comment by Ducasse** [comment]
I thought it was fixed in latest version but this is not the case.
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1168.sha.f29736f3378a5f70dc672165b68136bcb3a11ad4 (64 Bit)
@estebanlm it is probably a regression in new tool.

**Comment by StevenCostiou** [comment]
I will have a look since I am on the debugger today, and it is really bothering.
I took an image this morning and I still have it too.

**Comment by StevenCostiou** [comment]
Looks like it was introduced by https://github.com/pharo-spec/NewTools/commit/7e5265697cb18f7161ab2d04aa0316530aca5036#diff-3c41e7ff08d7861d091f97b0c0103955715d6edd68278ab0429807e862682ac6

**Comment by StevenCostiou** [comment]
Ok it is the changes in `openWithFullView`& `updatePresenter` of `StDebugger` that introduce the problem.
I will fix it.

**Comment by estebanlm** [comment]
mmm... ok, I'll have a look. 
but the change is good... it just probably misses the highlight thingy.

**Comment by StevenCostiou** [comment]
Not only, the toolbar is not correctly updated, for instance do it `1 a` and the toolbar is all available but the `create method`button.
The update method is not called at the correct moment.
What is needed is that when this update code is called when the top context is selected in the stack presenter.
Maybe it is selected silently the first time or something like this, because after opening it correctly refreshes.
