### ISSUE TITLE
Scaled Decimal multiplication loses precision

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#8668]
**Describe the bug**
1.003s3 * 1.006s4.

 => 

1.0090s4

instead of something like:

1.009018

**Expected behavior**

This happens because scaled decimal multiplication is just taking the largest scale between the two scales. One possibility to keep precision is to multiply the scales instead (and taking care of the cases where scale = 0)

**Comment by pablo-s** [comment]
Hello @guillep. I have been thinking about this issue in order to propose a solution. 
As you correctly indicated with one of the tags, the problem is easy: the scale of the result (of a multiplication) is the addition of the scales of multiplicands.

However, after implementing the mentioned change I saw a consequence of it and I am not sure how desirable it is:

    1.003s3 * 1.006s4
    =>
    1.0090180s7

Although the solution from above is right, the trailing zero in 1.006s4 (1.006**0**) has an effect in the result.
In other cases the effect is more evident:

    1.0 asScaledDecimal * 1.0 asScaledDecimal.
    =>
    1.0000000000000000000000000000s28

Should the trailing zeros problem be fixed as part of another GitHub issue? What do you think?

Thanks in advance.
