### ISSUE TITLE
Extract method in the superclass is not fully working

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#8871]
Take pillar 8eec3c949d2b1a61ce1f5b3efa547dfed45f7288 and take an use of Smalltalk os lineEnding.

When we do extract method, we are asked if we want to search in the complete hierarchy. 
This should lead to 
 - check and extract that expression in the top most class (the top most class using `Smalltalk os lineEnding.`. This way we get lineEnding in the class higher in the hierarchy
 - then we should check the full hierarchy below this top most class and extract the method to call the extracted method.

**Comment by Ducasse** [comment]
```
A foo
   ... Smalltalk os lineEnding

A << B

B << B1 
    ... Smalltalk os lineEnding
```

if we extract Smalltalk os lineEnding in B and say to check in superclasses
we should get 
 
```
A>> foo
   ... self lineEnding

A>> lineEnding 
      ^ Smalltalk os lineEnding
A << B

B << B1 
    ... self lineEnding
```

Is is clear?

**Comment by Lin777** [comment]
At the moment extract method refactoring searches its superclasses to see if one of them has a method with a similar body to the extracted code, if it does, it uses that method in the extraction, if it does not have it, it creates a new method, but in the class where it is extracted, not in its superclasses, because it is a bit difficult to know what the limit will be, for example, Object? ProtoObject?
