### ISSUE TITLE
Browsing a Symbol produces an error / browse UndefinedObject

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#8889]
Browse symbol does not work

**Bug description**
The browsing of symbols is not working. 

**To Reproduce**
A) Symbol ending in colon
    On a spec based text editor (eg. in the debugger)
        - select a selector
        - cmd b
        - red popup
    On a non-spec based text editor
        - select a selector
        - cmd b
        - compiler changes your text!

B) Symbol that does not have colon

    On a playground based text editor
        - select a selector
        - cmd b
        - browse UndefinedObject

    On other text editor
        - select a selector
        - cmd b
        - a popup to add a variable appears.

**Expected behavior**
Browse the class or give me a correct error message.

**Comment by MarcusDenker** [comment]
related to: https://github.com/pharo-project/pharo/issues/8515

**Comment by MarcusDenker** [comment]
Lots of interdependent problems

The first one was:

- Code differences. a DNU was happening (and catched by the Error handler) in newtools. This is now fixed with https://github.com/pharo-spec/NewTools/pull/334 

This means now we get the menu for both. Which is broken (see fix https://github.com/pharo-project/pharo/pull/10775)


But all that then does not fix the base problem described: By just naively evaluating code (see #8515), "browse it" on a selected string always evaluates that string, which means that it is interpreted as a variable. We need to be more clever and use the AST (see  #9615)

**Comment by MarcusDenker** [comment]
after merging the fixes, "Browse it" now works just like "print it" or "inspect it": it executes blindly the selection (and browses the class of the result).

To improve this, we have two other issue tracker entries:

- we should not just evaluate ( #8515)
- but use the AST instead (#9615)

**Comment by MarcusDenker** [comment]
as "browse it" is actually "doit and browse", this is what is expected: the selected text is handed to the compiler, it evaluates it (undeclated var is nil) and then the class is browsed.

The issue https://github.com/pharo-project/pharo/issues/8515 discussion shows that this is actually the behavior that is what  is wanted (the idea that "browse it" is "doit and browse").

In Pharo12, the menus in the editor now make that explicit.

**Comment by MarcusDenker** [comment]
I close this as "browse it" now works as defined: when you select code, it executed that code and opens a browser on the class of the result. If the code you select is syntactically wrong, it tells you.
