### ISSUE TITLE
Restart Quick method smashes stack

### ISSUE THREAD

**Issue by guillep** [guillep/pharo-core#8897]
**To Reproduce**
1. Write in a playground `#symbol asSymbol`
2. Debug it using  `Cmd shift d`
3. Step into `asSymbol`
4. Restart

Now the stack is empty

**Comment by maxwills** [comment]
It works if you put the following code (Notice the last line):
``` 
ByteSymbol>>asSymbol 
	"Refer to the comment in String|asSymbol."
	^super asSymbol
```

Here is what I found:

When you step into (as in your step 3), the debugger shows the source code for the ByteSymbol>>asSymbol method. I noticed that there is no code in that method (So I assume there is some sort of "non-explicit lookup" going on). I suspect that the debugger "breaks" somehow when it is stopped in a zero children sequence ast node like that. The change I suggested works, but I also suspect that the "non-explicit lookup" behavior is totally expected, so the issue should be corrected somewhere in StDebugger (the "restart from context behavior"). 
Someone with more experience than me could give a better insight, so it can be properly solved.

**Comment by tesonep** [comment]
Hi Max, 
    in a short version, the problem is with the methods that have a return self quick primitive.

In Long, here we have a couple of things that are done behind the scenes by the compiler:
- By definition, if a method does not have a return statement, the method will return the receiver. So, an empty method is equivalent to a method with just ``` m1 ^ self ```
- These methods are really common so they are compiled using a primitive to optimize it. This set of primitives are called "Quick Primitives". If you inspect the method you will see that the method is compiled with the primitive 256. This primitive is the so-called "quick return self primitive". This is used for different common operations: accessing instance variables, returning self, returning well-known constants (true, false, 0, 1, -1, 2, nil)
 
![image](https://user-images.githubusercontent.com/355455/113305692-95107200-9303-11eb-9361-3d02baee863e.png)
 
- When we execute a primitive (a normal one or a quick) there is not method activation, so there is not context created in the process. 
- And your example is working, because the new method that you create is not a quick primitive. It is a message sent, and a message sent is always compiled and executed creating a context. Also, it is executing the intern of the symbol again; when it can be returned directly. 
- In a previous version of Pharo, it was not possible to step into a quick method. Steven has allowed this, so I don't know how the lack of context is handled.

**Comment by maxwills** [comment]
(Just pinging @StevenCostiou)

**Comment by StevenCostiou** [comment]
Guys I quickly tracked this down: when restarting a quick method context, the pc is reinitialized and put back on the primitive bytecode.

Then `Context>>stepToSendOrReturn` method steps the context until a send or a return, but then it steps the primitive and steps too much time until the stack is emptied.

Possible fix, can someone investigate? 
I am currently unable to do anything unfortunately.

```Smalltalk
Context>>stepToSendOrReturn
	"Simulate the execution of bytecodes until either sending a message or 
	returning a value to the receiver (that is, until switching contexts)."

	| context |
	self method isQuick ifTrue:[
"Here this fixes the problem: I know that the quick primitives are encoded on 3 bytes so I increased the pc by 3 just to check."
     
		pc := pc + 3.
		^self].
	[ self isDead or: [ self willSend or: [  self willReturn or: [ self willStore or: [self willCreateBlock ] ] ] ] ]
		whileFalse: [
			context := self step.
			context == self ifFalse: [
				"Caused by mustBeBoolean handling"
				^context ]]
```

I added a condition at the begginning to check my hypothesis, and it seems to work.
I know that the quick primitives are encoded on 3 bytes so I increased the pc by 3 just to check.

Now, something cleaner should be investigated (*i.e.*, how to properly update the pc?) and add some additionnal tests.

**Comment by guillep** [comment]
For documentation, this PR is related, probably the one introducing the problem: https://github.com/pharo-project/pharo/pull/8763

**Comment by guillep** [comment]
I'd suggest we revert https://github.com/pharo-project/pharo/pull/8763.
I'd like to have the feature, but if nobody is going to push for it, I prefer not having it to having a freezing implementation.

**Comment by StevenCostiou** [comment]
#8763 does introduce the problem in the debugger because it activates a feature that is broken because of what I described above.
I agree with the revert, it will mask the problem that can be addressed later.

It would be nice however that someone does push for it, since I did the analysis it's perfectly doable now so if someone wants to contribute...

**Comment by StevenCostiou** [comment]
Also a revert will possibly mask #8888 and #8892, so that would gave time to fix them.

**Comment by guillep** [comment]
Yes, it would also remove some pressure.
This can be reworked later with time and without running, I don't think there is any pressure.

Is that ok?

**Comment by StevenCostiou** [comment]
Yes, to me we can revert, the issues are logged in the debugger projects so we have tracks of everything.
Will the revert of #8763 automatically reopen the issue it closed?

**Comment by Ducasse** [comment]
I think that this is good that we let us some time to work. So this is good to see that you have the same point of view.
