### ISSUE TITLE
Rename class refactoring does not show preview

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9032]
I renamed a class and I could not see the preview of the changes

**Comment by Lin777** [comment]
I added a preview, and change the way to make the changes of renaming classes. Now you can see the changes like this:
<img width="641" alt="imagen" src="https://user-images.githubusercontent.com/15729309/115181982-1ce9d080-a0a7-11eb-8a2a-3f30cc6f1470.png">

But I continue working on this because it is erroneously tagged with #undeclared category

<img width="486" alt="imagen" src="https://user-images.githubusercontent.com/15729309/115182091-59b5c780-a0a7-11eb-8a4c-40170e85aa4f.png">
This is due to the OCASTSemanticAnalyzer class, I'm not sure how to fix it.

The changes are here: https://github.com/pharo-project/pharo/compare/Pharo9.0...Lin777:AddPreviewRenameClass

**Comment by Ducasse** [comment]
Fixed.
