### ISSUE TITLE
RB - Inline method refactoring doesn't handle well, handling calls to super or overrides 

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9042]
Current version
- does not differentiate between a sender that is called as super or as self
- does not consider those senders that override the method

**Comment by guillep** [comment]
Also, it cannot inline to statically identifiable receivers, such as classes.
For example, I had a class method

```smalltalk
MyClass newWith: xxx
```

with

```smalltalk
MyClass >> newWith: aValue
  ^ self new value: aValue; yourself.
```

I'd expect to be able to inline the `newWith:` method inside my code because the receiver is explicitly `MyClass`, and it should be rewritten as something close to:

```smalltalk
MyClass new value: xxx; yourself
```

That is, all references to self within the inlined method should be replaced by the receiver (the class `MyClass` in this case, and the variables should be replaces by parameters.

Also, if the values are used more than once they should be extracted into temporaries. For example

```MyClass >> newWith: aValue
    ^ self new value: aValue; doSomethingWith: aValue + 1; yourself
```

Then this should be inlined as

```smalltalk
tmp := xxx.
MyClass new value: tmp; doSomethingWith: tmp + 1; yourself
```

Of course, the temporary can be avoided if the argument is a literal value or a variable, but if it is a message send, it could have a side effect and we should guarantee it will be executed only once as in the original code.
