### ISSUE TITLE
SpValueHolder did not untderstand #asTest (in new playground About menu)

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9077]
- open a new playground
- in the window menu at the top right choose "About"
=> Debugger opens with "Instance of SpValueHolder did not untderstand #asTest"

![image](https://user-images.githubusercontent.com/5980033/114925451-6a5c0880-9e2f-11eb-97b1-562da5916362.png)

**Comment by MarcusDenker** [comment]
I think I understand what happens.

In SpAbstractPresenter the variable aboutText is defined to be an SpObservableSlot.

```
 #aboutText => SpObservableSlot .
```

Which means that it is wrapped in a valueholder. The error comes from the fact that the valueholder "escapes", that is, we read the var and get back a valueholder instead of the value. That should never happen.

Where does it happen?

![bugSlot](https://user-images.githubusercontent.com/413057/115866553-1908d600-a43a-11eb-9f43-8459312bfb0c.jpg)\

This means that the definition of Assignment to a SpObservableSlot is wrong, it has the wrong return value. Instead of returning the value, it returns the valueholder.

This means that the bug has to be in SpObservableSlot>>#emitStore:

**Comment by MarcusDenker** [comment]
Fixed with latest spec merge

**Comment by astares** [comment]
Thanks!
