### ISSUE TITLE
Typing a large float hangs the image

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9112]
**Bug description**
Typing a float with a large exponent hangs the image (user interrupt not working)

**To Reproduce**
1. Open playground
2. type number: `1e111111111`
3. image hangs

(I discovered it by trying to type a document name 'S22C-6e19041715540` into the Playground as a note)

Pharo 9.0.0
Build information: Pharo-9.0.0+build.1341.sha.c5160f448a06a72dbe93cf4a53f2ae44bd0b436c (64 Bit)
Windows 10

**Comment by kasperosterbye** [comment]
The problem can easily be reproduced.

One can debug it easily by debugging `'1e111111111' asNumber` (that way the image do not hang).
The problem seems to be bad performance of  the `digitMultiply:neg:` method in Integer.
The following fragment illustrates this:

```smalltalk
res := 1e100000.
(1 to: 5) collect: [:i| Time millisecondsToRun: [ res := res digitMultiply: res neg: false ]].
```

Which gives these runtimes: `(60 238 961 3928 15664)`.

They show that doubling the number to multiply roughly quadruples the execution time. @pavel-krivanek's example is just so big it might take a "really really long time to finish"

The solution seems to be to provide a better multiplication algorithm with better performance characteristic

**Comment by guillep** [comment]
Fun :) I'd say it's not even the problem of the multiplication. The `1e100000` creates *very* large integers.

- 1e1000 occupies ~400 bytes in memory
- 1e10000 occupies 4K
- 1e10000 40K
and @pavel-krivanek was using an 8 digit exponent, so he was in the order of megabytes :smile:
Maybe this requires to use a more compact representation for integers if possible...

**Comment by kasperosterbye** [comment]
Yes, it becomes some rather large numbers. I do not believe this can be solved per se.
There are several ways I can imagine this issue to be solved:
1. Make it possible to interrupt **any** computation with user interrupt
1. Have a flag in Integer which need to be set if one really wants to play with megabyte large numbers. If it is not on (off by default), an error will be thrown when they grow over a certain threshold. 
1. Provide an implementation of sparse integers

The second option is the easiest one (set threshold in size in bytes should be efficient), and error message could point out the problem hand how to handle it. It is also the least elegant of the three ...

**Comment by guillep** [comment]
> * Have a flag in Integer which need to be set if one really wants to play with megabyte large numbers. If it is not on (off by default), an error will be thrown when they grow over a certain threshold.

Well, I like this as a first workaround. We could just limit the number grammar to not parse those strange numbers.
The we would have a syntax error at that point.

> 3\. Provide an implementation of sparse integers

Well, I was looking at it. What the NumberParser does in a couple of places is this, which computes the actual number right away:

```smalltalk
self readExponent
	ifTrue: [^integerPart * (base raisedToInteger: exponent)].
```

Instead of computing the number with the exponent right away at parse time, another solution could be to generate an 
`ExponentialNumber` that is represented in scientific notation (coefficient, base, exponent). And then we should be able to do math with that (similarly to how we do with fractions now)...

Also, we could compute the actual number at parse/compile time if small enough, otherwise use the scientific notation (or fail if disabled?)

**Comment by MarcusDenker** [comment]
This has been fixed
