### ISSUE TITLE
Class tags with the same name as the package are ignored

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#9127]
**Bug description**
If a class has a tag of the same name as the containing package, this class tag is ignored and Calypso does not it any in the packages list.

**To Reproduce**
1. Go to some package without tags, like `Announcements-Help`
2. In the class `AnnouncementsTutorial` change  package from: `Announcements-Help` to 'Announcements-Help-Announcements-Help'
3. `Announcements-Help` still does not have any tags in the packages list

**Comment by hogoww** [comment]
I'm currently investigating this.
First thing to note is that the class is indeed tagged properly.
It is just not displayed.

**Comment by hogoww** [comment]
The problem is three fold.
(1) First, Fluid does not print the tags.
This comes form: FluidClassDefinitionPrinter (shorten for readability).
Which has a guard preventing it from printing.
I'll PR it, I'll see if the CI/people say it's legitimate.
tagOn: s
	| tag |
	(forClass package classTagForClass: forClass) ifNotNil: [ :t | 
		tag := t name.
		tag = forClass package name ifFalse: [ 
			self print: tag On: s ] ]

(2) Kinda hard to find as is all GUI stuff but the problem comes from RPackage >> #tagsForClasses, which removes packages tags if they have the same name. (via #isRoot selector)
Creating a full browser relies on this method.
This means that the arrow does not show.
I haven't investigated further however.

(3) Not yet investigated but the fact that it can be removed for the printing using the old class printing.
My guess is that it's reliying on the (2) problem.

**Comment by Ducasse** [comment]
The problem is that the logic for the tags is a big mess. I will not touch it because I worked a lot to write RPackage without using categories and tag implementation just messed up everything. So I will not touch it until tags implementation get cleaned.

**Comment by pavel-krivanek** [comment]
still valid, you may want to use it on different package like `System-Announcements-Tests` becuase the original one was already unloaded

**Comment by jecisc** [comment]
This one is on my TODO list of things to clean. 

The problem is that currently SystemOrganizer holds a list of all "Categories" (Category = package + tag in the same string). 

To fix the problem we need to totally kill this system of categories. 

To do that, RPackageOragnizer needs to replace SystemOrganizer and then we need to inline the behavior of SystemOrganizer in RPackage. 

I have a PR to use RPackageOrganizer as the default organizer in the system but it fails because the bootstrap is not happy with the change and currently we have a hard time to update the bootstrap. 

Once we can update the bootstrap I'll proceed my work on this and I hope to have this feature for Pharo 12 release

**Comment by MarcusDenker** [comment]
This now works: tag: is now to be given explicitly, and it works
