### ISSUE TITLE
Add Argument Refactoring generates a MNU in RBMessageNode

### ISSUE THREAD

**Issue by tesonep** [guillep/pharo-core#9194]
1. Have a method like 

```
aMethod

	^ 42
```

2.  Have another method 

```
anotherMethod 

	^ self aMethod
```

3. Select "aMethod" and do Cmd+T and select "Add Argument"

![image](https://user-images.githubusercontent.com/355455/116278110-75475f00-a786-11eb-95ad-37af6dbbd38a.png)

Boom:

![image](https://user-images.githubusercontent.com/355455/116278130-7e383080-a786-11eb-8577-9ffc8f7a023c.png)

**Comment by Alisu** [comment]
~~Quickly, changing ```methodName := RBMethodName selector: originalMessage selector, 'arg:' arguments: originalMessage argumentNames, self createValidNameArgument"``` to ```methodName := RBMethodName selector: originalMessage arguments: originalMessage argumentNames``` in ```SycChangeMessageSignatureCommand>>requestMessageIn:``` remove the DNU but the addArgument refactoring is then stuck in the methodEditor pane.~~

In pharo 8, we don't have the presenter problem but the addArgument refactoring hangs (at least when I put nil as default value in the second pane.

**Comment by Alisu** [comment]
Using the refactor from the method selection panel works fine.
```createValidNameArgument```create for us an argument name that is not already in used as argument (for example: if anObject is used then it return anObject1) or used as an instance variable. By the way, it does not check for already existing temporaries witht the same name.
The problem is that when we ask the refactoring from the method editing panel we don't know yet the exact method and cannot do those checks.
