### ISSUE TITLE
Extract method seems broken

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9290]

**Comment by Ducasse** [comment]
I tried to extract `(MicInlineSplitter new parse: children)`
in 

```
closeMe
	super closeMe.
	children := (MicInlineSplitter new parse: children)
```

and I got impossible with invalid preview....

**Comment by Ducasse** [comment]
![Screenshot 2021-05-18 at 16 29 32](https://user-images.githubusercontent.com/432549/118669959-7b18e900-b7f6-11eb-959e-7ec5356f0852.png)

**Comment by Lin777** [comment]
Very strange I did not get any problem when trying to replicate the error.

The preview asks you to enter the name with which the method will be extracted, for that reason it says invalid since a name has not yet been given to the extracted method
<img width="610" alt="imagen" src="https://user-images.githubusercontent.com/15729309/118835534-18c0f680-b891-11eb-97f8-942902ace411.png">

once the name is given to the method, proceed as normal

<img width="940" alt="imagen" src="https://user-images.githubusercontent.com/15729309/118835650-2fffe400-b891-11eb-858b-678c48740402.png">

@Ducasse Maybe you want that the extract method refactoring suggests a method name when extracting

**Comment by Ducasse** [comment]
I do not know I just could not extract method anymore so I did it by hand.

**Comment by Lin777** [comment]
It is very strange, I did not have any problem when trying to replicate this method. Perhaps it is one of those problems that occurs when the image has several days active, I had similar problems in updating methods from traits

**Comment by Ducasse** [comment]
So let us close it for now and we will see.
