### ISSUE TITLE
CodeCritics - Improving Critic Description (Bugs, Coding Idiom Violation)

### ISSUE THREAD

**Issue by Lin777** [guillep/pharo-core#9309]
For example:
<img width="918" alt="imagen" src="https://user-images.githubusercontent.com/15729309/119155896-a59aba00-ba21-11eb-8891-cd6a032a9cb1.png">

**Comment by AleCossioCh** [comment]
I reviewed every critique of Bugs and Coding Idiom Violation rule groups. Not found descriptions or duplicate critiques for improvement.

However, the Critized source code for the rule ReGuardingClauseRule shows all the highlighted code, instead of the conditional. I leave the example of this case:

![Screenshot from 2021-06-13 18-50-42](https://user-images.githubusercontent.com/23039347/121824263-e086bb00-cc78-11eb-98b7-c232c061042b.png)
