### ISSUE TITLE
Launcher: Problem with uploading Pharo 10 image

### ISSUE THREAD

**Issue by astares** [guillep/pharo-core#9601]
WINDOWS 10:
- installed a new Pharo launcher from website and tried to download Pharo 10 64 image:

![image](https://user-images.githubusercontent.com/5980033/125939382-7397eae6-fbdf-4c8f-8854-9e1b69688657.png)

**Comment by astares** [comment]
Names in this folder are different:

![image](https://user-images.githubusercontent.com/5980033/125939654-661e5306-e829-4c1f-9c4a-d4e41f3aa016.png)

I guess it is not ready yet

**Comment by guillep** [comment]
But that is strange. That is the folder for the upcoming pharo 10 development. If you were loading Pharo 9, it should not be loading from the pharo 10 directory :). Also, this looks like a launcher issue, @demarey is this known?

**Comment by astares** [comment]
@guillep sorry - subject was wrong. I was downloading P10

**Comment by demarey** [comment]
Hi
You need to get the latest Pharo Launcher from https://pharo.org/download to have it work with Urls of Pharo 9 and 10.

**Comment by kasperosterbye** [comment]
I had the same issue until I updated the launcher.

I suggest to close this issue here, and to move it to https://github.com/pharo-project/pharo-launcher/issues. It seems like the error should read to "update launcher" rather than "file not found".

<blockquote><img src="https://opengraph.githubassets.com/2453af34f7c0fb7299b91c9983bdb6083ba212dd98a6f748e803f6f0f63788f3/pharo-project/pharo-launcher" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-launcher">Issues · pharo-project/pharo-launcher</a></strong></div><div>Lets you manage your pharo images and download new ones - Issues · pharo-project/pharo-launcher</div></blockquote>

**Comment by astares** [comment]
Yes - URLs had been updated by @tesonep and the latest launcher version from @demarey is required. Just download it freshly from the www.pharo.org website.

My experience on Windows: reinstalling it using the latest setup does not help: one has to really deinstall the old one 
and install it freshly using the freshly downloaded setup file.

We can close this issue.
