### ISSUE TITLE
OpenSUSE Leap support: Missing VM dependencies

### ISSUE THREAD

**Issue by JanBliznicenko** [guillep/pharo-core#9757]
Hello, I am glad things are moving forward regarding various Linux distros like OpenSUSE and Fedora. Unfortunately, I was not able to install Pharo on OpenSUSE as I do not know how to solve missing dependencies.

The main Pharo Launcher Linux installer does not work (TFFI related error) - that was expected, so I tried the OBS version.

What did I try:

1. I fresh installed OpenSUSE Leap 15.2 in VirtualBox (current one is 15.3, but I used older one to be sure).
2. Updated all packages
3. From Pharo download page, I used link "Install Pharo VM (Full)" that claims to install pharo vm, pharo-u script **and all its dependencies**. The link went to https://software.opensuse.org/download.html?project=devel:languages:pharo:latest&package=pharo9-ui where I picked OpenSUSE, then onenSUSE Leap 15.2 (the main button).
4. I opened the file with YaST
5. Agreed with adding repository `https://download.opensuse.org/repositories/devel:/languages:/pharo:/latest/openSUSE_Leap_15.2/ (devel:languages:pharo:latest)` and installing pharo9-ui
6. after few seconds of installation process, following warning shows:
`nothing provides 'libgit2-1' needed by the to be installed pharo9-ui-9.0-lp152.4.1.x86_64`

I went to try to install various libgit packages available in default repositories with zypper and trying the Pharo installation again, but nothing helped. I tried ignoring the problem and proceeding with the installation, but when I run pharo-ui, I get:

`/usr/bin/pharo-ui: line 14: /usr/bin/pharo: No such file or directory`

So I tried installing pharo package first (although I would expect it would be installed as well with the "full Pharo VM that installs all its dependencies", but it fails on missing dependency libuuid in the same way pharo-ui fails on libgit2-1. `libuuid` is not known name to zypper. libuuid1 exists, is installed and up to date.

I also tried directly downloading pharo9-ui-9.0-lp152.4.1.x86_64.rpm and installing it, but I met the same issues (missing the same libraries).

What is the proper way to make Pharo working on OpenSUSE? Thank you.

**Comment by estebanlm** [comment]
this is fixed :)

**Comment by zilti** [comment]
Why is this marked as fixed? This is still the case on the packages on https://software.opensuse.org/download.html?project=devel:languages:pharo:latest&package=pharo9-ui. Which is mindboggling, I mean, how did you get to even build the package on openSUSE Build Service with missing dependencies?
EDIT: Ahh my bad, I thought this is openSUSE in general. It is still broken for Tumbleweed. Because libgit2_1 is missing and libffi7 conflicts the system's libffi library.

**Comment by estebanlm** [comment]
well, when I closed this tumbleweed was working too, but that's the nature of rolling releases ;)

**Comment by estebanlm** [comment]
hey @zilti, a heads up. I updated thumbleweed build to use current libgit version (1.4). 
that means now pharo is installed correctly.
BUT you will need to use Pharo 10 on it (because the libgit2 bindings changed, so we needed to update them internally).
Otherwise you need to update the libgit2 bindings in Pharo 9 to what is now in https://github.com/pharo-vcs/libgit2-pharo-bindings.
