### ISSUE TITLE
Pharo 9 image cannot be launched after Save and Quit

### ISSUE THREAD

**Issue by rmbishop** [guillep/pharo-core#9779]
**Bug description**
Clicking on "Save and quit" multiple times in succession will cause Pharo Launcher to no
longer launch that image.

**To Reproduce**
1. Create an image named "test_image".
2. Click on test_image in the Pharo Launcher, then click on the Launch button.
3. (Without closing the Welcome Window), click on the main menu item named
"Pharo", then click on "Save and quit".
4. Run steps 2 and 3 again in succession multiple times, until Pharo Launcher no longer launches the image.

**Version information:**
Windows 10
Build information: Pharo-9.0.0+build.1543.sha.0934b1e0222778d8f526a526295a97616fc4f18a (64 Bit)
Pharo Launcher version: 2.4

**Comment by Ducasse** [comment]
Thanks for the report. I cannot reproduce it on mac. So may be this a windows problem.
Do you have multiple time the same image open? Because you could have concurrent access.

Can you report the version of the VM that you are using (see System Reporter)?
Did you update to the latest vm?
May be the saving is slow on your machine and the launcher is trying to open the image before it is saved. 
@demarey Christophe do you is is possible that the launcher is trying to open a file while it is saved. 

@rmbishop do you wait that the image is saved and quitted before launching the image again?

S.

**Comment by rmbishop** [comment]
I put the pharo build in my report.
I performed a test where I did the following:
1)Launch image with PharoLauncher
2)Wait for image to start.
3)Wait 15 seconds
3)Click on 'Save and quit'
4)Wait 15 seconds
5)Goto 1.

I found that this also caused the bug to appear.

**Comment by rmbishop** [comment]
I can no longer reproduce this issue using the following build:
Build information: Pharo-9.0.0+build.1544.sha.e9e51d5f5a2ce5dd03c21b70062c2cca56e04e2a (64 Bit)
