### ISSUE TITLE
MemoryFileSystem does not support well the identification of absolute path

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#9899]
Look at the following
```
(FileSystem memory / 'tmp') pathString 
>>> "'/tmp'"
(FileSystem workingDirectory / 'tmp') pathString 
>>>	"'/Users/ducasse/Documents/Pharo/images/P10-Microdown/tmp'"
	
(FileSystem memory / '/tmp') pathString
>>> "'/tmp'"
(FileSystem workingDirectory / '/tmp') pathString 
>>> "'/tmp'" 
```

We cannot see the difference. 
between this  `(FileSystem memory / '/tmp') pathString` and `(FileSystem memory / 'tmp') pathString`

Probably that pathString is not done for that.

**Comment by Ducasse** [comment]
At least the method comment should tell us to pay attention.

**Comment by demarey** [comment]
FileSystem memory / resolves to FileSystem memory root then appending 'tmp' indeed give '/tmp'.
If you do: `(FileSystem memory / 'a' / 'tmp') pathString`, it will return `'/a/tmp'`which is the expected behaviour.
What is strange, but is the expected behaviour as documented in AbstractFileReference>>#/, is that appending an absolute path to a file reference will give you back the absolute file reference, forgetting the file reference.
`/ aString
	"aString is either a file or path.  If aString is relative, it is appended to the receiver, if it is absolute, an instance of the receiver with the path is answered"`
