### ISSUE TITLE
Debug opening error

### ISSUE THREAD

**Issue by vitormcruz** [guillep/pharo-core#9912]
When I try do run a Metacello load with a breakpoint in `MetacelloBaselineConstructor>>calculate:project:` at line 23 or 24 I get the following error:

`Information **Debugger opening error**  Original error: Break. Debugger error: MetacelloStackCacheNotification` 

And all the loading process stops. Oddly, If I put a break point in any other line, the debug prompts correctly.

Logs are attached.

[PharoDebug.log](https://github.com/pharo-project/pharo/files/7116510/PharoDebug.log)

**Version information:**
 - OS: Windows 10
 - Pharo Version: 9

**Comment by vitormcruz** [comment]
If i put a break point before line 23 and step over line 22 the system halts, CMD + . don't help, I had to open Task Manager and kill the process.

**Comment by StevenCostiou** [comment]
In Pharo 9, this is when there is no debugger able to handle your error (usually because there is an error in the debugger).

There is an option (see screenshot below) to unlock this, and if a debugger fails it tries to open another debugger to open your error and make it debuggable (if the error comes from one of your object, for example, a printing, this can lead to a cascade of failure which ends up in the same message of the original issue).

Select `OupsDebuggerSelector` in the debugger selection strategy.
Perhaps this should be by default.
It is also possible to debug failing debuggers by ticking `handle debugger errors`. In that case, if there is a debugger error it tries to open another debugger to debug your failing debugger.

<img width="634" alt="Screenshot 2021-09-08 at 20 33 38" src="https://user-images.githubusercontent.com/26929529/132565583-ff98dfa6-dfe3-4d80-a005-0fa1d101c9ea.png">

**Comment by vitormcruz** [comment]
Doing this configuration prompts a OupsDebuggerFailure in the find method window... It is strange, I am not sure how to proceed from there, but I managed to fuel out the stacktrace: [Debugger-Stack-OupsDebuggerSelector-2021-09-10-213729.zip](https://github.com/pharo-project/pharo/files/7146948/Debugger-Stack-OupsDebuggerSelector-2021-09-10-213729.zip)

Tell me please if I can do more.

**Comment by adri09070** [comment]
I can't reproduce the issue right now. I think it has been fixed
